.include "macro.inc"

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches

.section .bss

.balign 16

/* Generated by spimdisasm 1.9.1 */

# static variable
glabel B_10002BD0
/* 014BD0 10002BD0 */ .space 0x10

glabel B_10002BE0
/* 014BE0 10002BE0 */ .space 0xA0

glabel B_10002C80
/* 014C80 10002C80 */ .space 0x70

glabel B_10002CF0
/* 014CF0 10002CF0 */ .space 0x10

glabel __Argc
/* 014D00 10002D00 */ .space 0x04

glabel __Argv
/* 014D04 10002D04 */ .space 0x04

glabel __rld_obj_head
/* 014D08 10002D08 */ .space 0x04

glabel progname
/* 014D0C 10002D0C */ .space 0x04

glabel cplusplus
/* 014D10 10002D10 */ .space 0x04

glabel max_include_len
/* 014D14 10002D14 */ .space 0x04

glabel deps_prefix
/* 014D18 10002D18 */ .space 0x04

glabel deps_file
/* 014D1C 10002D1C */ .space 0x04

glabel no_line_commands
/* 014D20 10002D20 */ .space 0x04

glabel dump_macros
/* 014D24 10002D24 */ .space 0x04

glabel pedantic
/* 014D28 10002D28 */ .space 0x04

glabel warnings_off
/* 014D2C 10002D2C */ .space 0x04

glabel showdefines
/* 014D30 10002D30 */ .space 0x04

glabel warn_comments
/* 014D34 10002D34 */ .space 0x04

glabel warn_trigraphs
/* 014D38 10002D38 */ .space 0x04

glabel traditional
/* 014D3C 10002D3C */ .space 0x04

glabel no_output
/* 014D40 10002D40 */ .space 0x04

# Automatically generated pad
glabel B_10002D44
/* 014D44 10002D44 */ .space 0x0C

glabel instack
/* 014D50 10002D50 */ .space 0x1C20

glabel outbuf
/* 016970 10004970 */ .space 0x24

# Automatically generated pad
glabel B_10004994
/* 016994 10004994 */ .space 0x0C

glabel hashtab
/* 0169A0 100049A0 */ .space 0x15EC

# Automatically generated pad
glabel B_10005F8C
/* 017F8C 10005F8C */ .space 0x04

glabel is_idchar
/* 017F90 10005F90 */ .space 0x100

glabel is_idstart
/* 018090 10006090 */ .space 0x100

glabel is_hor_space
/* 018190 10006190 */ .space 0x100

glabel is_space
/* 018290 10006290 */ .space 0x100

glabel deps_buffer
/* 018390 10006390 */ .space 0x04

glabel deps_allocated_size
/* 018394 10006394 */ .space 0x04

glabel deps_size
/* 018398 10006398 */ .space 0x04

glabel deps_column
/* 01839C 1000639C */ .space 0x04

glabel ignore_srcdir
/* 0183A0 100063A0 */ .space 0x04

glabel expression_value
/* 0183A4 100063A4 */ .space 0x04

glabel yylval
/* 0183A8 100063A8 */ .space 0x08

glabel yyval
/* 0183B0 100063B0 */ .space 0x08

# Automatically generated pad
glabel B_100063B8
/* 0183B8 100063B8 */ .space 0x08

glabel yy_yys
/* 0183C0 100063C0 */ .space 0x258

# Automatically generated pad
glabel B_10006618
/* 018618 10006618 */ .space 0x08

glabel yy_yyv
/* 018620 10006620 */ .space 0x4B0

glabel yydebug
/* 018AD0 10006AD0 */ .space 0x04

glabel yypv
/* 018AD4 10006AD4 */ .space 0x04

glabel yyps
/* 018AD8 10006AD8 */ .space 0x04

glabel yystate
/* 018ADC 10006ADC */ .space 0x04

glabel yytmp
/* 018AE0 10006AE0 */ .space 0x04

glabel yynerrs
/* 018AE4 10006AE4 */ .space 0x04

glabel yyerrflag
/* 018AE8 10006AE8 */ .space 0x04

glabel yychar
/* 018AEC 10006AEC */ .space 0x04

glabel scratch
/* 018AF0 10006AF0 */ .space 0x50
