/* Generated by spimdisasm 1.9.1 */

glabel __rpop # 27
# _gp_disp: 0x12368
.set noreorder; .cpload $t9; # .set reorder
/* 006144 0F9A6144 8F858150 */  lw          $a1, %got(__sp_)($gp)
/* 006148 0F9A6148 2401FFFF */  addiu       $at, $zero, -0x1
/* 00614C 0F9A614C 8CA20000 */  lw          $v0, 0x0($a1)
/* 006150 0F9A6150 00000000 */  nop
/* 006154 0F9A6154 8C430000 */  lw          $v1, 0x0($v0)
/* 006158 0F9A6158 244EFFFC */  addiu       $t6, $v0, -0x4
/* 00615C 0F9A615C 14610003 */  bne         $v1, $at, .L0F9A616C
/* 006160 0F9A6160 00602025 */   move       $a0, $v1
/* 006164 0F9A6164 03E00008 */  jr          $ra
/* 006168 0F9A6168 00001025 */   move       $v0, $zero
.L0F9A616C:
/* 00616C 0F9A616C ACAE0000 */  sw          $t6, 0x0($a1)
/* 006170 0F9A6170 03E00008 */  jr          $ra
/* 006174 0F9A6174 00801025 */   move       $v0, $a0

