/* Generated by spimdisasm 1.9.1 */

glabel _mkdirp # 11
# _gp_disp: 0x15840
.set noreorder; .cpload $t9; # .set reorder
/* 002C6C 0F9A2C6C 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 002C70 0F9A2C70 8F998014 */  lw          $t9, %got(func_0F9A2E80)($gp)
/* 002C74 0F9A2C74 AFBF0024 */  sw          $ra, 0x24($sp)
/* 002C78 0F9A2C78 AFB2001C */  sw          $s2, 0x1C($sp)
/* 002C7C 0F9A2C7C 27392E80 */  addiu       $t9, $t9, %lo(func_0F9A2E80)
/* 002C80 0F9A2C80 00A09025 */  move        $s2, $a1
/* 002C84 0F9A2C84 AFBC0020 */  sw          $gp, 0x20($sp)
/* 002C88 0F9A2C88 AFB10018 */  sw          $s1, 0x18($sp)
/* 002C8C 0F9A2C8C 0320F809 */  jalr        $t9
/* 002C90 0F9A2C90 AFB00014 */   sw         $s0, 0x14($sp)
/* 002C94 0F9A2C94 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002C98 0F9A2C98 14400003 */  bnez        $v0, .L0F9A2CA8
/* 002C9C 0F9A2C9C 00408025 */   move       $s0, $v0
/* 002CA0 0F9A2CA0 10000071 */  b           .L0F9A2E68
/* 002CA4 0F9A2CA4 2402FFFF */   addiu      $v0, $zero, -0x1
.L0F9A2CA8:
/* 002CA8 0F9A2CA8 8F998084 */  lw          $t9, %call16(_mkdir)($gp)
/* 002CAC 0F9A2CAC 02002025 */  move        $a0, $s0
/* 002CB0 0F9A2CB0 0320F809 */  jalr        $t9
/* 002CB4 0F9A2CB4 02402825 */   move       $a1, $s2
/* 002CB8 0F9A2CB8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002CBC 0F9A2CBC 14400008 */  bnez        $v0, .L0F9A2CE0
/* 002CC0 0F9A2CC0 00000000 */   nop
/* 002CC4 0F9A2CC4 8F9980C0 */  lw          $t9, %call16(free)($gp)
/* 002CC8 0F9A2CC8 02002025 */  move        $a0, $s0
/* 002CCC 0F9A2CCC 0320F809 */  jalr        $t9
/* 002CD0 0F9A2CD0 00000000 */   nop
/* 002CD4 0F9A2CD4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002CD8 0F9A2CD8 10000063 */  b           .L0F9A2E68
/* 002CDC 0F9A2CDC 00001025 */   move       $v0, $zero
.L0F9A2CE0:
/* 002CE0 0F9A2CE0 8F998078 */  lw          $t9, %call16(__oserror)($gp)
/* 002CE4 0F9A2CE4 00000000 */  nop
/* 002CE8 0F9A2CE8 0320F809 */  jalr        $t9
/* 002CEC 0F9A2CEC 00000000 */   nop
/* 002CF0 0F9A2CF0 8C4E0000 */  lw          $t6, 0x0($v0)
/* 002CF4 0F9A2CF4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002CF8 0F9A2CF8 24010002 */  addiu       $at, $zero, 0x2
/* 002CFC 0F9A2CFC 11C10008 */  beq         $t6, $at, .L0F9A2D20
/* 002D00 0F9A2D00 00000000 */   nop
/* 002D04 0F9A2D04 8F9980C0 */  lw          $t9, %call16(free)($gp)
/* 002D08 0F9A2D08 02002025 */  move        $a0, $s0
/* 002D0C 0F9A2D0C 0320F809 */  jalr        $t9
/* 002D10 0F9A2D10 00000000 */   nop
/* 002D14 0F9A2D14 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002D18 0F9A2D18 10000053 */  b           .L0F9A2E68
/* 002D1C 0F9A2D1C 2402FFFF */   addiu      $v0, $zero, -0x1
.L0F9A2D20:
/* 002D20 0F9A2D20 8F998094 */  lw          $t9, %call16(strrchr)($gp)
/* 002D24 0F9A2D24 02002025 */  move        $a0, $s0
/* 002D28 0F9A2D28 0320F809 */  jalr        $t9
/* 002D2C 0F9A2D2C 00002825 */   move       $a1, $zero
/* 002D30 0F9A2D30 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002D34 0F9A2D34 00408825 */  move        $s1, $v0
/* 002D38 0F9A2D38 8F998094 */  lw          $t9, %call16(strrchr)($gp)
/* 002D3C 0F9A2D3C 02002025 */  move        $a0, $s0
/* 002D40 0F9A2D40 0320F809 */  jalr        $t9
/* 002D44 0F9A2D44 2405002F */   addiu      $a1, $zero, 0x2F
/* 002D48 0F9A2D48 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002D4C 0F9A2D4C 10400022 */  beqz        $v0, .L0F9A2DD8
/* 002D50 0F9A2D50 00401825 */   move       $v1, $v0
.L0F9A2D54:
/* 002D54 0F9A2D54 A0600000 */  sb          $zero, 0x0($v1)
/* 002D58 0F9A2D58 8F998090 */  lw          $t9, %call16(_access)($gp)
/* 002D5C 0F9A2D5C 02002025 */  move        $a0, $s0
/* 002D60 0F9A2D60 0320F809 */  jalr        $t9
/* 002D64 0F9A2D64 00002825 */   move       $a1, $zero
/* 002D68 0F9A2D68 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002D6C 0F9A2D6C 1040001A */  beqz        $v0, .L0F9A2DD8
/* 002D70 0F9A2D70 00000000 */   nop
/* 002D74 0F9A2D74 8F998094 */  lw          $t9, %call16(strrchr)($gp)
/* 002D78 0F9A2D78 02002025 */  move        $a0, $s0
/* 002D7C 0F9A2D7C 0320F809 */  jalr        $t9
/* 002D80 0F9A2D80 2405002F */   addiu      $a1, $zero, 0x2F
/* 002D84 0F9A2D84 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002D88 0F9A2D88 10400003 */  beqz        $v0, .L0F9A2D98
/* 002D8C 0F9A2D8C 00401825 */   move       $v1, $v0
/* 002D90 0F9A2D90 1450000F */  bne         $v0, $s0, .L0F9A2DD0
/* 002D94 0F9A2D94 00000000 */   nop
.L0F9A2D98:
/* 002D98 0F9A2D98 8F998084 */  lw          $t9, %call16(_mkdir)($gp)
/* 002D9C 0F9A2D9C 02002025 */  move        $a0, $s0
/* 002DA0 0F9A2DA0 0320F809 */  jalr        $t9
/* 002DA4 0F9A2DA4 02402825 */   move       $a1, $s2
/* 002DA8 0F9A2DA8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002DAC 0F9A2DAC 1040000A */  beqz        $v0, .L0F9A2DD8
/* 002DB0 0F9A2DB0 00000000 */   nop
/* 002DB4 0F9A2DB4 8F9980C0 */  lw          $t9, %call16(free)($gp)
/* 002DB8 0F9A2DB8 02002025 */  move        $a0, $s0
/* 002DBC 0F9A2DBC 0320F809 */  jalr        $t9
/* 002DC0 0F9A2DC0 00000000 */   nop
/* 002DC4 0F9A2DC4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002DC8 0F9A2DC8 10000027 */  b           .L0F9A2E68
/* 002DCC 0F9A2DCC 2402FFFF */   addiu      $v0, $zero, -0x1
.L0F9A2DD0:
/* 002DD0 0F9A2DD0 1460FFE0 */  bnez        $v1, .L0F9A2D54
/* 002DD4 0F9A2DD4 00000000 */   nop
.L0F9A2DD8:
/* 002DD8 0F9A2DD8 8F9980E8 */  lw          $t9, %call16(strchr)($gp)
/* 002DDC 0F9A2DDC 02002025 */  move        $a0, $s0
/* 002DE0 0F9A2DE0 0320F809 */  jalr        $t9
/* 002DE4 0F9A2DE4 00002825 */   move       $a1, $zero
/* 002DE8 0F9A2DE8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002DEC 0F9A2DEC 10510018 */  beq         $v0, $s1, .L0F9A2E50
/* 002DF0 0F9A2DF0 00401825 */   move       $v1, $v0
.L0F9A2DF4:
/* 002DF4 0F9A2DF4 240F002F */  addiu       $t7, $zero, 0x2F
/* 002DF8 0F9A2DF8 A06F0000 */  sb          $t7, 0x0($v1)
/* 002DFC 0F9A2DFC 8F998084 */  lw          $t9, %call16(_mkdir)($gp)
/* 002E00 0F9A2E00 02002025 */  move        $a0, $s0
/* 002E04 0F9A2E04 0320F809 */  jalr        $t9
/* 002E08 0F9A2E08 02402825 */   move       $a1, $s2
/* 002E0C 0F9A2E0C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002E10 0F9A2E10 10400008 */  beqz        $v0, .L0F9A2E34
/* 002E14 0F9A2E14 00000000 */   nop
/* 002E18 0F9A2E18 8F9980C0 */  lw          $t9, %call16(free)($gp)
/* 002E1C 0F9A2E1C 02002025 */  move        $a0, $s0
/* 002E20 0F9A2E20 0320F809 */  jalr        $t9
/* 002E24 0F9A2E24 00000000 */   nop
/* 002E28 0F9A2E28 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002E2C 0F9A2E2C 1000000E */  b           .L0F9A2E68
/* 002E30 0F9A2E30 2402FFFF */   addiu      $v0, $zero, -0x1
.L0F9A2E34:
/* 002E34 0F9A2E34 8F9980E8 */  lw          $t9, %call16(strchr)($gp)
/* 002E38 0F9A2E38 02002025 */  move        $a0, $s0
/* 002E3C 0F9A2E3C 0320F809 */  jalr        $t9
/* 002E40 0F9A2E40 00002825 */   move       $a1, $zero
/* 002E44 0F9A2E44 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002E48 0F9A2E48 1451FFEA */  bne         $v0, $s1, .L0F9A2DF4
/* 002E4C 0F9A2E4C 00401825 */   move       $v1, $v0
.L0F9A2E50:
/* 002E50 0F9A2E50 8F9980C0 */  lw          $t9, %call16(free)($gp)
/* 002E54 0F9A2E54 02002025 */  move        $a0, $s0
/* 002E58 0F9A2E58 0320F809 */  jalr        $t9
/* 002E5C 0F9A2E5C 00000000 */   nop
/* 002E60 0F9A2E60 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002E64 0F9A2E64 00001025 */  move        $v0, $zero
.L0F9A2E68:
/* 002E68 0F9A2E68 8FBF0024 */  lw          $ra, 0x24($sp)
/* 002E6C 0F9A2E6C 8FB00014 */  lw          $s0, 0x14($sp)
/* 002E70 0F9A2E70 8FB10018 */  lw          $s1, 0x18($sp)
/* 002E74 0F9A2E74 8FB2001C */  lw          $s2, 0x1C($sp)
/* 002E78 0F9A2E78 03E00008 */  jr          $ra
/* 002E7C 0F9A2E7C 27BD0028 */   addiu      $sp, $sp, 0x28
