.section .late_rodata
glabel jtbl_0F9B03F0
/* 0093F0 0F9B03F0 FFFEFBA8 */ .gpword .L0F9A8048
/* 0093F4 0F9B03F4 FFFEFC28 */ .gpword .L0F9A80C8
/* 0093F8 0F9B03F8 FFFEFC28 */ .gpword .L0F9A80C8
/* 0093FC 0F9B03FC FFFEFC28 */ .gpword .L0F9A80C8
/* 009400 0F9B0400 FFFEFC28 */ .gpword .L0F9A80C8
/* 009404 0F9B0404 FFFEFB9C */ .gpword .L0F9A803C
/* 009408 0F9B0408 FFFEFB6C */ .gpword .L0F9A800C
/* 00940C 0F9B040C FFFEFC28 */ .gpword .L0F9A80C8
/* 009410 0F9B0410 FFFEFC28 */ .gpword .L0F9A80C8
/* 009414 0F9B0414 FFFEFC28 */ .gpword .L0F9A80C8
/* 009418 0F9B0418 FFFEFB84 */ .gpword .L0F9A8024
/* 00941C 0F9B041C FFFEFC28 */ .gpword .L0F9A80C8
/* 009420 0F9B0420 FFFEFC28 */ .gpword .L0F9A80C8
/* 009424 0F9B0424 FFFEFC28 */ .gpword .L0F9A80C8
/* 009428 0F9B0428 FFFEFC28 */ .gpword .L0F9A80C8
/* 00942C 0F9B042C FFFEFC28 */ .gpword .L0F9A80C8
/* 009430 0F9B0430 FFFEFC28 */ .gpword .L0F9A80C8
/* 009434 0F9B0434 FFFEFC28 */ .gpword .L0F9A80C8
/* 009438 0F9B0438 FFFEFB54 */ .gpword .L0F9A7FF4
/* 00943C 0F9B043C FFFEFC28 */ .gpword .L0F9A80C8
/* 009440 0F9B0440 FFFEFC28 */ .gpword .L0F9A80C8
/* 009444 0F9B0444 FFFEFC28 */ .gpword .L0F9A80C8
/* 009448 0F9B0448 FFFEFB78 */ .gpword .L0F9A8018
/* 00944C 0F9B044C FFFEFC28 */ .gpword .L0F9A80C8
/* 009450 0F9B0450 FFFEFB60 */ .gpword .L0F9A8000
/* 009454 0F9B0454 FFFEFC28 */ .gpword .L0F9A80C8
/* 009458 0F9B0458 FFFEFB90 */ .gpword .L0F9A8030

glabel jtbl_0F9B045C
/* 00945C 0F9B045C FFFEFBB4 */ .gpword .L0F9A8054
/* 009460 0F9B0460 FFFEFBB4 */ .gpword .L0F9A8054
/* 009464 0F9B0464 FFFEFBB4 */ .gpword .L0F9A8054
/* 009468 0F9B0468 FFFEFBB4 */ .gpword .L0F9A8054
/* 00946C 0F9B046C FFFEFBB4 */ .gpword .L0F9A8054
/* 009470 0F9B0470 FFFEFBB4 */ .gpword .L0F9A8054
/* 009474 0F9B0474 FFFEFBB4 */ .gpword .L0F9A8054
/* 009478 0F9B0478 FFFEFBB4 */ .gpword .L0F9A8054
/* 00947C 0F9B047C 00000000 */ .word 0x00000000


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel _strcadd # 41
# _gp_disp: 0x10574
.set noreorder; .cpload $t9; # .set reorder
/* 007F38 0F9A7F38 27BDFFF0 */  addiu       $sp, $sp, -0x10
/* 007F3C 0F9A7F3C AFB2000C */  sw          $s2, 0xC($sp)
/* 007F40 0F9A7F40 AFB10008 */  sw          $s1, 0x8($sp)
/* 007F44 0F9A7F44 AFB00004 */  sw          $s0, 0x4($sp)
/* 007F48 0F9A7F48 90A20000 */  lbu         $v0, 0x0($a1)
/* 007F4C 0F9A7F4C 2412005C */  addiu       $s2, $zero, 0x5C
/* 007F50 0F9A7F50 10400066 */  beqz        $v0, .L0F9A80EC
/* 007F54 0F9A7F54 24A50001 */   addiu      $a1, $a1, 0x1
/* 007F58 0F9A7F58 24110007 */  addiu       $s1, $zero, 0x7
/* 007F5C 0F9A7F5C 24100008 */  addiu       $s0, $zero, 0x8
/* 007F60 0F9A7F60 240D000C */  addiu       $t5, $zero, 0xC
/* 007F64 0F9A7F64 240C000A */  addiu       $t4, $zero, 0xA
/* 007F68 0F9A7F68 240B000D */  addiu       $t3, $zero, 0xD
/* 007F6C 0F9A7F6C 240A0009 */  addiu       $t2, $zero, 0x9
/* 007F70 0F9A7F70 2409000B */  addiu       $t1, $zero, 0xB
/* 007F74 0F9A7F74 2408005C */  addiu       $t0, $zero, 0x5C
.L0F9A7F78:
/* 007F78 0F9A7F78 15020056 */  bne         $t0, $v0, .L0F9A80D4
/* 007F7C 0F9A7F7C 00000000 */   nop
/* 007F80 0F9A7F80 90A20000 */  lbu         $v0, 0x0($a1)
/* 007F84 0F9A7F84 24A50001 */  addiu       $a1, $a1, 0x1
/* 007F88 0F9A7F88 28410038 */  slti        $at, $v0, 0x38
/* 007F8C 0F9A7F8C 1420000D */  bnez        $at, .L0F9A7FC4
/* 007F90 0F9A7F90 00401825 */   move       $v1, $v0
/* 007F94 0F9A7F94 246EFFA4 */  addiu       $t6, $v1, -0x5C
/* 007F98 0F9A7F98 2DC1001B */  sltiu       $at, $t6, 0x1B
/* 007F9C 0F9A7F9C 1020004A */  beqz        $at, .L0F9A80C8
/* 007FA0 0F9A7FA0 00000000 */   nop
/* 007FA4 0F9A7FA4 8F81804C */  lw          $at, %got(jtbl_0F9B03F0)($gp)
/* 007FA8 0F9A7FA8 000E7080 */  sll         $t6, $t6, 2
/* 007FAC 0F9A7FAC 002E0821 */  addu        $at, $at, $t6
/* 007FB0 0F9A7FB0 8C2E03F0 */  lw          $t6, %lo(jtbl_0F9B03F0)($at)
/* 007FB4 0F9A7FB4 00000000 */  nop
/* 007FB8 0F9A7FB8 01DC7021 */  addu        $t6, $t6, $gp
/* 007FBC 0F9A7FBC 01C00008 */  jr          $t6
/* 007FC0 0F9A7FC0 00000000 */   nop
.L0F9A7FC4:
/* 007FC4 0F9A7FC4 246FFFD0 */  addiu       $t7, $v1, -0x30
/* 007FC8 0F9A7FC8 2DE10008 */  sltiu       $at, $t7, 0x8
/* 007FCC 0F9A7FCC 1020003E */  beqz        $at, .L0F9A80C8
/* 007FD0 0F9A7FD0 00000000 */   nop
/* 007FD4 0F9A7FD4 8F81804C */  lw          $at, %got(jtbl_0F9B045C)($gp)
/* 007FD8 0F9A7FD8 000F7880 */  sll         $t7, $t7, 2
/* 007FDC 0F9A7FDC 002F0821 */  addu        $at, $at, $t7
/* 007FE0 0F9A7FE0 8C2F045C */  lw          $t7, %lo(jtbl_0F9B045C)($at)
/* 007FE4 0F9A7FE4 00000000 */  nop
/* 007FE8 0F9A7FE8 01FC7821 */  addu        $t7, $t7, $gp
/* 007FEC 0F9A7FEC 01E00008 */  jr          $t7
/* 007FF0 0F9A7FF0 00000000 */   nop
.L0F9A7FF4:
/* 007FF4 0F9A7FF4 A08C0000 */  sb          $t4, 0x0($a0)
/* 007FF8 0F9A7FF8 10000038 */  b           .L0F9A80DC
/* 007FFC 0F9A7FFC 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A8000:
/* 008000 0F9A8000 A08A0000 */  sb          $t2, 0x0($a0)
/* 008004 0F9A8004 10000035 */  b           .L0F9A80DC
/* 008008 0F9A8008 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A800C:
/* 00800C 0F9A800C A0900000 */  sb          $s0, 0x0($a0)
/* 008010 0F9A8010 10000032 */  b           .L0F9A80DC
/* 008014 0F9A8014 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A8018:
/* 008018 0F9A8018 A08B0000 */  sb          $t3, 0x0($a0)
/* 00801C 0F9A801C 1000002F */  b           .L0F9A80DC
/* 008020 0F9A8020 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A8024:
/* 008024 0F9A8024 A08D0000 */  sb          $t5, 0x0($a0)
/* 008028 0F9A8028 1000002C */  b           .L0F9A80DC
/* 00802C 0F9A802C 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A8030:
/* 008030 0F9A8030 A0890000 */  sb          $t1, 0x0($a0)
/* 008034 0F9A8034 10000029 */  b           .L0F9A80DC
/* 008038 0F9A8038 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A803C:
/* 00803C 0F9A803C A0910000 */  sb          $s1, 0x0($a0)
/* 008040 0F9A8040 10000026 */  b           .L0F9A80DC
/* 008044 0F9A8044 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A8048:
/* 008048 0F9A8048 A0920000 */  sb          $s2, 0x0($a0)
/* 00804C 0F9A804C 10000023 */  b           .L0F9A80DC
/* 008050 0F9A8050 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A8054:
/* 008054 0F9A8054 90A20000 */  lbu         $v0, 0x0($a1)
/* 008058 0F9A8058 2466FFD0 */  addiu       $a2, $v1, -0x30
/* 00805C 0F9A805C 28410030 */  slti        $at, $v0, 0x30
/* 008060 0F9A8060 00003825 */  move        $a3, $zero
/* 008064 0F9A8064 24A50001 */  addiu       $a1, $a1, 0x1
/* 008068 0F9A8068 14200013 */  bnez        $at, .L0F9A80B8
/* 00806C 0F9A806C 00401825 */   move       $v1, $v0
/* 008070 0F9A8070 28410038 */  slti        $at, $v0, 0x38
/* 008074 0F9A8074 10200010 */  beqz        $at, .L0F9A80B8
/* 008078 0F9A8078 24E70001 */   addiu      $a3, $a3, 0x1
.L0F9A807C:
/* 00807C 0F9A807C 0006C0C0 */  sll         $t8, $a2, 3
/* 008080 0F9A8080 2479FFD0 */  addiu       $t9, $v1, -0x30
/* 008084 0F9A8084 28E10002 */  slti        $at, $a3, 0x2
/* 008088 0F9A8088 14200003 */  bnez        $at, .L0F9A8098
/* 00808C 0F9A808C 03193025 */   or         $a2, $t8, $t9
/* 008090 0F9A8090 10000009 */  b           .L0F9A80B8
/* 008094 0F9A8094 24A50001 */   addiu      $a1, $a1, 0x1
.L0F9A8098:
/* 008098 0F9A8098 90A20000 */  lbu         $v0, 0x0($a1)
/* 00809C 0F9A809C 24A50001 */  addiu       $a1, $a1, 0x1
/* 0080A0 0F9A80A0 28410030 */  slti        $at, $v0, 0x30
/* 0080A4 0F9A80A4 14200004 */  bnez        $at, .L0F9A80B8
/* 0080A8 0F9A80A8 00401825 */   move       $v1, $v0
/* 0080AC 0F9A80AC 28410038 */  slti        $at, $v0, 0x38
/* 0080B0 0F9A80B0 1420FFF2 */  bnez        $at, .L0F9A807C
/* 0080B4 0F9A80B4 24E70001 */   addiu      $a3, $a3, 0x1
.L0F9A80B8:
/* 0080B8 0F9A80B8 A0860000 */  sb          $a2, 0x0($a0)
/* 0080BC 0F9A80BC 24840001 */  addiu       $a0, $a0, 0x1
/* 0080C0 0F9A80C0 10000006 */  b           .L0F9A80DC
/* 0080C4 0F9A80C4 24A5FFFF */   addiu      $a1, $a1, -0x1
.L0F9A80C8:
/* 0080C8 0F9A80C8 A0820000 */  sb          $v0, 0x0($a0)
/* 0080CC 0F9A80CC 10000003 */  b           .L0F9A80DC
/* 0080D0 0F9A80D0 24840001 */   addiu      $a0, $a0, 0x1
.L0F9A80D4:
/* 0080D4 0F9A80D4 A0820000 */  sb          $v0, 0x0($a0)
/* 0080D8 0F9A80D8 24840001 */  addiu       $a0, $a0, 0x1
.L0F9A80DC:
/* 0080DC 0F9A80DC 90A20000 */  lbu         $v0, 0x0($a1)
/* 0080E0 0F9A80E0 24A50001 */  addiu       $a1, $a1, 0x1
/* 0080E4 0F9A80E4 1440FFA4 */  bnez        $v0, .L0F9A7F78
/* 0080E8 0F9A80E8 00000000 */   nop
.L0F9A80EC:
/* 0080EC 0F9A80EC A0800000 */  sb          $zero, 0x0($a0)
/* 0080F0 0F9A80F0 8FB2000C */  lw          $s2, 0xC($sp)
/* 0080F4 0F9A80F4 8FB10008 */  lw          $s1, 0x8($sp)
/* 0080F8 0F9A80F8 8FB00004 */  lw          $s0, 0x4($sp)
/* 0080FC 0F9A80FC 27BD0010 */  addiu       $sp, $sp, 0x10
/* 008100 0F9A8100 03E00008 */  jr          $ra
/* 008104 0F9A8104 00801025 */   move       $v0, $a0
/* 008108 0F9A8108 00000000 */  nop
/* 00810C 0F9A810C 00000000 */  nop
/* 008110 0F9A8110 00000000 */  nop
