.section .late_rodata
glabel jtbl_0F9B0190
/* 009190 0F9B0190 FFFEC34C */ .gpword .L0F9A47EC
/* 009194 0F9B0194 FFFECE44 */ .gpword .L0F9A52E4
/* 009198 0F9B0198 FFFEC1EC */ .gpword .L0F9A468C
/* 00919C 0F9B019C FFFECB54 */ .gpword .L0F9A4FF4
/* 0091A0 0F9B01A0 FFFECE44 */ .gpword .L0F9A52E4
/* 0091A4 0F9B01A4 FFFEC4F0 */ .gpword .L0F9A4990
/* 0091A8 0F9B01A8 FFFEC268 */ .gpword .L0F9A4708
/* 0091AC 0F9B01AC FFFECAAC */ .gpword .L0F9A4F4C
/* 0091B0 0F9B01B0 FFFECE44 */ .gpword .L0F9A52E4
/* 0091B4 0F9B01B4 FFFEC5BC */ .gpword .L0F9A4A5C
/* 0091B8 0F9B01B8 FFFEC2C0 */ .gpword .L0F9A4760
/* 0091BC 0F9B01BC FFFECCB8 */ .gpword .L0F9A5158
/* 0091C0 0F9B01C0 FFFECE44 */ .gpword .L0F9A52E4
/* 0091C4 0F9B01C4 FFFEC870 */ .gpword .L0F9A4D10
/* 0091C8 0F9B01C8 FFFECE44 */ .gpword .L0F9A52E4
/* 0091CC 0F9B01CC FFFECE44 */ .gpword .L0F9A52E4
/* 0091D0 0F9B01D0 FFFECE44 */ .gpword .L0F9A52E4
/* 0091D4 0F9B01D4 FFFECE44 */ .gpword .L0F9A52E4
/* 0091D8 0F9B01D8 FFFEC298 */ .gpword .L0F9A4738
/* 0091DC 0F9B01DC FFFECE44 */ .gpword .L0F9A52E4
/* 0091E0 0F9B01E0 FFFEC2B0 */ .gpword .L0F9A4750
/* 0091E4 0F9B01E4 FFFECE44 */ .gpword .L0F9A52E4
/* 0091E8 0F9B01E8 FFFEC364 */ .gpword .L0F9A4804
/* 0091EC 0F9B01EC FFFECE44 */ .gpword .L0F9A52E4
/* 0091F0 0F9B01F0 FFFECE44 */ .gpword .L0F9A52E4
/* 0091F4 0F9B01F4 FFFECE44 */ .gpword .L0F9A52E4
/* 0091F8 0F9B01F8 FFFECE44 */ .gpword .L0F9A52E4
/* 0091FC 0F9B01FC FFFECE44 */ .gpword .L0F9A52E4
/* 009200 0F9B0200 FFFECE44 */ .gpword .L0F9A52E4
/* 009204 0F9B0204 FFFECE44 */ .gpword .L0F9A52E4
/* 009208 0F9B0208 FFFECE44 */ .gpword .L0F9A52E4
/* 00920C 0F9B020C FFFECE44 */ .gpword .L0F9A52E4
/* 009210 0F9B0210 FFFECE44 */ .gpword .L0F9A52E4
/* 009214 0F9B0214 FFFECE44 */ .gpword .L0F9A52E4
/* 009218 0F9B0218 FFFEC988 */ .gpword .L0F9A4E28
/* 00921C 0F9B021C FFFEC9DC */ .gpword .L0F9A4E7C
/* 009220 0F9B0220 FFFECE44 */ .gpword .L0F9A52E4
/* 009224 0F9B0224 FFFECE44 */ .gpword .L0F9A52E4
/* 009228 0F9B0228 FFFEC208 */ .gpword .L0F9A46A8
/* 00922C 0F9B022C FFFECB80 */ .gpword .L0F9A5020
/* 009230 0F9B0230 FFFECE44 */ .gpword .L0F9A52E4
/* 009234 0F9B0234 FFFEC380 */ .gpword .L0F9A4820
/* 009238 0F9B0238 FFFEC308 */ .gpword .L0F9A47A8
/* 00923C 0F9B023C FFFECC3C */ .gpword .L0F9A50DC
/* 009240 0F9B0240 FFFECE44 */ .gpword .L0F9A52E4
/* 009244 0F9B0244 FFFEC6F4 */ .gpword .L0F9A4B94
/* 009248 0F9B0248 FFFEC304 */ .gpword .L0F9A47A4
/* 00924C 0F9B024C FFFECC38 */ .gpword .L0F9A50D8
/* 009250 0F9B0250 FFFECE44 */ .gpword .L0F9A52E4
/* 009254 0F9B0254 FFFEC6F0 */ .gpword .L0F9A4B90
/* 009258 0F9B0258 FFFECCFC */ .gpword .L0F9A519C
/* 00925C 0F9B025C FFFECE44 */ .gpword .L0F9A52E4
/* 009260 0F9B0260 FFFECE44 */ .gpword .L0F9A52E4
/* 009264 0F9B0264 FFFECE44 */ .gpword .L0F9A52E4
/* 009268 0F9B0268 FFFECDD8 */ .gpword .L0F9A5278
/* 00926C 0F9B026C 00000000 */ .word 0x00000000


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel func_0F9A45F4 # 22
# _gp_disp: 0x13EAC
.set noreorder; .cpload $t9; # .set reorder
/* 004600 0F9A4600 27BDFF88 */  addiu       $sp, $sp, -0x78
/* 004604 0F9A4604 AFBE0038 */  sw          $fp, 0x38($sp)
/* 004608 0F9A4608 AFB70030 */  sw          $s7, 0x30($sp)
/* 00460C 0F9A460C AFB30020 */  sw          $s3, 0x20($sp)
/* 004610 0F9A4610 AFB10018 */  sw          $s1, 0x18($sp)
/* 004614 0F9A4614 AFB6002C */  sw          $s6, 0x2C($sp)
/* 004618 0F9A4618 AFB50028 */  sw          $s5, 0x28($sp)
/* 00461C 0F9A461C AFB40024 */  sw          $s4, 0x24($sp)
/* 004620 0F9A4620 AFB2001C */  sw          $s2, 0x1C($sp)
/* 004624 0F9A4624 AFB00014 */  sw          $s0, 0x14($sp)
/* 004628 0F9A4628 8FB1006C */  lw          $s1, 0x6C($sp)
/* 00462C 0F9A462C 8FB30064 */  lw          $s3, 0x64($sp)
/* 004630 0F9A4630 8F978070 */  lw          $s7, %got(D_FB504F0)($gp)
/* 004634 0F9A4634 8F9E8148 */  lw          $fp, %got(_braslist)($gp)
/* 004638 0F9A4638 00808025 */  move        $s0, $a0
/* 00463C 0F9A463C 00A09025 */  move        $s2, $a1
/* 004640 0F9A4640 AFBF003C */  sw          $ra, 0x3C($sp)
/* 004644 0F9A4644 AFBC0034 */  sw          $gp, 0x34($sp)
/* 004648 0F9A4648 0000A025 */  move        $s4, $zero
/* 00464C 0F9A464C 24150001 */  addiu       $s5, $zero, 0x1
/* 004650 0F9A4650 27B60060 */  addiu       $s6, $sp, 0x60
.L0F9A4654:
/* 004654 0F9A4654 92440000 */  lbu         $a0, 0x0($s2)
/* 004658 0F9A4658 26520001 */  addiu       $s2, $s2, 0x1
/* 00465C 0F9A465C 248EFFFE */  addiu       $t6, $a0, -0x2
/* 004660 0F9A4660 2DC10037 */  sltiu       $at, $t6, 0x37
/* 004664 0F9A4664 1020031F */  beqz        $at, .L0F9A52E4
/* 004668 0F9A4668 00000000 */   nop
/* 00466C 0F9A466C 8F81804C */  lw          $at, %got(jtbl_0F9B0190)($gp)
/* 004670 0F9A4670 000E7080 */  sll         $t6, $t6, 2
/* 004674 0F9A4674 002E0821 */  addu        $at, $at, $t6
/* 004678 0F9A4678 8C2E0190 */  lw          $t6, %lo(jtbl_0F9B0190)($at)
/* 00467C 0F9A467C 00000000 */  nop
/* 004680 0F9A4680 01DC7021 */  addu        $t6, $t6, $gp
/* 004684 0F9A4684 01C00008 */  jr          $t6
/* 004688 0F9A4688 00000000 */   nop
.L0F9A468C:
/* 00468C 0F9A468C 924F0000 */  lbu         $t7, 0x0($s2)
/* 004690 0F9A4690 92180000 */  lbu         $t8, 0x0($s0)
/* 004694 0F9A4694 26520001 */  addiu       $s2, $s2, 0x1
/* 004698 0F9A4698 11F8FFEE */  beq         $t7, $t8, .L0F9A4654
/* 00469C 0F9A469C 26100001 */   addiu      $s0, $s0, 0x1
/* 0046A0 0F9A46A0 1000035E */  b           .L0F9A541C
/* 0046A4 0F9A46A4 00001025 */   move       $v0, $zero
.L0F9A46A8:
/* 0046A8 0F9A46A8 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 0046AC 0F9A46AC 02C02025 */  move        $a0, $s6
/* 0046B0 0F9A46B0 02402825 */  move        $a1, $s2
/* 0046B4 0F9A46B4 0320F809 */  jalr        $t9
/* 0046B8 0F9A46B8 24060005 */   addiu      $a2, $zero, 0x5
/* 0046BC 0F9A46BC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 0046C0 0F9A46C0 8FB10060 */  lw          $s1, 0x60($sp)
/* 0046C4 0F9A46C4 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 0046C8 0F9A46C8 02429021 */  addu        $s2, $s2, $v0
/* 0046CC 0F9A46CC 02C02025 */  move        $a0, $s6
/* 0046D0 0F9A46D0 02002825 */  move        $a1, $s0
/* 0046D4 0F9A46D4 0320F809 */  jalr        $t9
/* 0046D8 0F9A46D8 24060005 */   addiu      $a2, $zero, 0x5
/* 0046DC 0F9A46DC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 0046E0 0F9A46E0 18400005 */  blez        $v0, .L0F9A46F8
/* 0046E4 0F9A46E4 00409825 */   move       $s3, $v0
/* 0046E8 0F9A46E8 8FB90060 */  lw          $t9, 0x60($sp)
/* 0046EC 0F9A46EC 00000000 */  nop
/* 0046F0 0F9A46F0 12390003 */  beq         $s1, $t9, .L0F9A4700
/* 0046F4 0F9A46F4 00000000 */   nop
.L0F9A46F8:
/* 0046F8 0F9A46F8 10000348 */  b           .L0F9A541C
/* 0046FC 0F9A46FC 00001025 */   move       $v0, $zero
.L0F9A4700:
/* 004700 0F9A4700 1000FFD4 */  b           .L0F9A4654
/* 004704 0F9A4704 02028021 */   addu       $s0, $s0, $v0
.L0F9A4708:
/* 004708 0F9A4708 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 00470C 0F9A470C 02C02025 */  move        $a0, $s6
/* 004710 0F9A4710 02002825 */  move        $a1, $s0
/* 004714 0F9A4714 0320F809 */  jalr        $t9
/* 004718 0F9A4718 24060005 */   addiu      $a2, $zero, 0x5
/* 00471C 0F9A471C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004720 0F9A4720 18400003 */  blez        $v0, .L0F9A4730
/* 004724 0F9A4724 00409825 */   move       $s3, $v0
/* 004728 0F9A4728 1000FFCA */  b           .L0F9A4654
/* 00472C 0F9A472C 02028021 */   addu       $s0, $s0, $v0
.L0F9A4730:
/* 004730 0F9A4730 1000033A */  b           .L0F9A541C
/* 004734 0F9A4734 00001025 */   move       $v0, $zero
.L0F9A4738:
/* 004738 0F9A4738 92080000 */  lbu         $t0, 0x0($s0)
/* 00473C 0F9A473C 00000000 */  nop
/* 004740 0F9A4740 1100FFC4 */  beqz        $t0, .L0F9A4654
/* 004744 0F9A4744 00000000 */   nop
/* 004748 0F9A4748 10000334 */  b           .L0F9A541C
/* 00474C 0F9A474C 00001025 */   move       $v0, $zero
.L0F9A4750:
/* 004750 0F9A4750 8F818140 */  lw          $at, %got(_loc2)($gp)
/* 004754 0F9A4754 24020001 */  addiu       $v0, $zero, 0x1
/* 004758 0F9A4758 10000330 */  b           .L0F9A541C
/* 00475C 0F9A475C AC300000 */   sw         $s0, 0x0($at)
.L0F9A4760:
/* 004760 0F9A4760 92110000 */  lbu         $s1, 0x0($s0)
/* 004764 0F9A4764 8F8A805C */  lw          $t2, %got(D_F9B0084)($gp)
/* 004768 0F9A4768 32290007 */  andi        $t1, $s1, 0x7
/* 00476C 0F9A476C 001168C3 */  sra         $t5, $s1, 3
/* 004770 0F9A4770 254A0084 */  addiu       $t2, $t2, %lo(D_F9B0084)
/* 004774 0F9A4774 012A5821 */  addu        $t3, $t1, $t2
/* 004778 0F9A4778 024D7021 */  addu        $t6, $s2, $t5
/* 00477C 0F9A477C 91CF0000 */  lbu         $t7, 0x0($t6)
/* 004780 0F9A4780 916C0000 */  lbu         $t4, 0x0($t3)
/* 004784 0F9A4784 26100001 */  addiu       $s0, $s0, 0x1
/* 004788 0F9A4788 018FC024 */  and         $t8, $t4, $t7
/* 00478C 0F9A478C 13000003 */  beqz        $t8, .L0F9A479C
/* 004790 0F9A4790 00000000 */   nop
/* 004794 0F9A4794 1000FFAF */  b           .L0F9A4654
/* 004798 0F9A4798 26520020 */   addiu      $s2, $s2, 0x20
.L0F9A479C:
/* 00479C 0F9A479C 1000031F */  b           .L0F9A541C
/* 0047A0 0F9A47A0 00001025 */   move       $v0, $zero
.L0F9A47A4:
/* 0047A4 0F9A47A4 02A0A025 */  move        $s4, $s5
.L0F9A47A8:
/* 0047A8 0F9A47A8 8F998014 */  lw          $t9, %got(func_0F9A54A4)($gp)
/* 0047AC 0F9A47AC AFB00074 */  sw          $s0, 0x74($sp)
/* 0047B0 0F9A47B0 273954A4 */  addiu       $t9, $t9, %lo(func_0F9A54A4)
/* 0047B4 0F9A47B4 02402025 */  move        $a0, $s2
/* 0047B8 0F9A47B8 27A50074 */  addiu       $a1, $sp, 0x74
/* 0047BC 0F9A47BC 0320F809 */  jalr        $t9
/* 0047C0 0F9A47C0 02803025 */   move       $a2, $s4
/* 0047C4 0F9A47C4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 0047C8 0F9A47C8 10550003 */  beq         $v0, $s5, .L0F9A47D8
/* 0047CC 0F9A47CC 0000A025 */   move       $s4, $zero
/* 0047D0 0F9A47D0 10000312 */  b           .L0F9A541C
/* 0047D4 0F9A47D4 00001025 */   move       $v0, $zero
.L0F9A47D8:
/* 0047D8 0F9A47D8 92590020 */  lbu         $t9, 0x20($s2)
/* 0047DC 0F9A47DC 8FB00074 */  lw          $s0, 0x74($sp)
/* 0047E0 0F9A47E0 02599021 */  addu        $s2, $s2, $t9
/* 0047E4 0F9A47E4 1000FF9B */  b           .L0F9A4654
/* 0047E8 0F9A47E8 26520020 */   addiu      $s2, $s2, 0x20
.L0F9A47EC:
/* 0047EC 0F9A47EC 92480000 */  lbu         $t0, 0x0($s2)
/* 0047F0 0F9A47F0 26520001 */  addiu       $s2, $s2, 0x1
/* 0047F4 0F9A47F4 00084880 */  sll         $t1, $t0, 2
/* 0047F8 0F9A47F8 03C95021 */  addu        $t2, $fp, $t1
/* 0047FC 0F9A47FC 1000FF95 */  b           .L0F9A4654
/* 004800 0F9A4800 AD500000 */   sw         $s0, 0x0($t2)
.L0F9A4804:
/* 004804 0F9A4804 924B0000 */  lbu         $t3, 0x0($s2)
/* 004808 0F9A4808 8F8E814C */  lw          $t6, %got(_braelist)($gp)
/* 00480C 0F9A480C 000B6880 */  sll         $t5, $t3, 2
/* 004810 0F9A4810 01AE6021 */  addu        $t4, $t5, $t6
/* 004814 0F9A4814 AD900000 */  sw          $s0, 0x0($t4)
/* 004818 0F9A4818 1000FF8E */  b           .L0F9A4654
/* 00481C 0F9A481C 26520001 */   addiu      $s2, $s2, 0x1
.L0F9A4820:
/* 004820 0F9A4820 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 004824 0F9A4824 02C02025 */  move        $a0, $s6
/* 004828 0F9A4828 02402825 */  move        $a1, $s2
/* 00482C 0F9A482C 0320F809 */  jalr        $t9
/* 004830 0F9A4830 24060005 */   addiu      $a2, $zero, 0x5
/* 004834 0F9A4834 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004838 0F9A4838 02429021 */  addu        $s2, $s2, $v0
/* 00483C 0F9A483C 8F998014 */  lw          $t9, %got(func_0F9A544C)($gp)
/* 004840 0F9A4840 8FB10060 */  lw          $s1, 0x60($sp)
/* 004844 0F9A4844 2739544C */  addiu       $t9, $t9, %lo(func_0F9A544C)
/* 004848 0F9A4848 0320F809 */  jalr        $t9
/* 00484C 0F9A484C 02402025 */   move       $a0, $s2
/* 004850 0F9A4850 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004854 0F9A4854 00000000 */  nop
/* 004858 0F9A4858 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 00485C 0F9A485C 00000000 */  nop
/* 004860 0F9A4860 24E70F30 */  addiu       $a3, $a3, %lo(B_F9B0F30)
/* 004864 0F9A4864 8CE30000 */  lw          $v1, 0x0($a3)
/* 004868 0F9A4868 00000000 */  nop
/* 00486C 0F9A486C 246FFFFF */  addiu       $t7, $v1, -0x1
/* 004870 0F9A4870 10600016 */  beqz        $v1, .L0F9A48CC
/* 004874 0F9A4874 ACEF0000 */   sw         $t7, 0x0($a3)
.L0F9A4878:
/* 004878 0F9A4878 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 00487C 0F9A487C 02C02025 */  move        $a0, $s6
/* 004880 0F9A4880 02002825 */  move        $a1, $s0
/* 004884 0F9A4884 0320F809 */  jalr        $t9
/* 004888 0F9A4888 24060005 */   addiu      $a2, $zero, 0x5
/* 00488C 0F9A488C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004890 0F9A4890 00409825 */  move        $s3, $v0
/* 004894 0F9A4894 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 004898 0F9A4898 18400005 */  blez        $v0, .L0F9A48B0
/* 00489C 0F9A489C 24E70F30 */   addiu      $a3, $a3, %lo(B_F9B0F30)
/* 0048A0 0F9A48A0 8FB80060 */  lw          $t8, 0x60($sp)
/* 0048A4 0F9A48A4 00000000 */  nop
/* 0048A8 0F9A48A8 13110003 */  beq         $t8, $s1, .L0F9A48B8
/* 0048AC 0F9A48AC 00000000 */   nop
.L0F9A48B0:
/* 0048B0 0F9A48B0 100002DA */  b           .L0F9A541C
/* 0048B4 0F9A48B4 00001025 */   move       $v0, $zero
.L0F9A48B8:
/* 0048B8 0F9A48B8 8CE30000 */  lw          $v1, 0x0($a3)
/* 0048BC 0F9A48BC 02028021 */  addu        $s0, $s0, $v0
/* 0048C0 0F9A48C0 2479FFFF */  addiu       $t9, $v1, -0x1
/* 0048C4 0F9A48C4 1460FFEC */  bnez        $v1, .L0F9A4878
/* 0048C8 0F9A48C8 ACF90000 */   sw         $t9, 0x0($a3)
.L0F9A48CC:
/* 0048CC 0F9A48CC 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 0048D0 0F9A48D0 0200F025 */  move        $fp, $s0
/* 0048D4 0F9A48D4 24E70F34 */  addiu       $a3, $a3, %lo(B_F9B0F34)
/* 0048D8 0F9A48D8 8CE30000 */  lw          $v1, 0x0($a3)
/* 0048DC 0F9A48DC 00000000 */  nop
/* 0048E0 0F9A48E0 2468FFFF */  addiu       $t0, $v1, -0x1
/* 0048E4 0F9A48E4 10600014 */  beqz        $v1, .L0F9A4938
/* 0048E8 0F9A48E8 ACE80000 */   sw         $t0, 0x0($a3)
.L0F9A48EC:
/* 0048EC 0F9A48EC 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 0048F0 0F9A48F0 02C02025 */  move        $a0, $s6
/* 0048F4 0F9A48F4 02002825 */  move        $a1, $s0
/* 0048F8 0F9A48F8 0320F809 */  jalr        $t9
/* 0048FC 0F9A48FC 24060005 */   addiu      $a2, $zero, 0x5
/* 004900 0F9A4900 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004904 0F9A4904 00409825 */  move        $s3, $v0
/* 004908 0F9A4908 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 00490C 0F9A490C 1840000A */  blez        $v0, .L0F9A4938
/* 004910 0F9A4910 24E70F34 */   addiu      $a3, $a3, %lo(B_F9B0F34)
/* 004914 0F9A4914 8FA90060 */  lw          $t1, 0x60($sp)
/* 004918 0F9A4918 00000000 */  nop
/* 00491C 0F9A491C 15310006 */  bne         $t1, $s1, .L0F9A4938
/* 004920 0F9A4920 00000000 */   nop
/* 004924 0F9A4924 8CE30000 */  lw          $v1, 0x0($a3)
/* 004928 0F9A4928 02028021 */  addu        $s0, $s0, $v0
/* 00492C 0F9A492C 246AFFFF */  addiu       $t2, $v1, -0x1
/* 004930 0F9A4930 1460FFEE */  bnez        $v1, .L0F9A48EC
/* 004934 0F9A4934 ACEA0000 */   sw         $t2, 0x0($a3)
.L0F9A4938:
/* 004938 0F9A4938 8CEB0000 */  lw          $t3, 0x0($a3)
/* 00493C 0F9A493C 02C02025 */  move        $a0, $s6
/* 004940 0F9A4940 05610008 */  bgez        $t3, .L0F9A4964
/* 004944 0F9A4944 2414FFFF */   addiu      $s4, $zero, -0x1
/* 004948 0F9A4948 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 00494C 0F9A494C 02002825 */  move        $a1, $s0
/* 004950 0F9A4950 0320F809 */  jalr        $t9
/* 004954 0F9A4954 24060005 */   addiu      $a2, $zero, 0x5
/* 004958 0F9A4958 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00495C 0F9A495C 00409825 */  move        $s3, $v0
/* 004960 0F9A4960 2414FFFF */  addiu       $s4, $zero, -0x1
.L0F9A4964:
/* 004964 0F9A4964 16740003 */  bne         $s3, $s4, .L0F9A4974
/* 004968 0F9A4968 26520002 */   addiu      $s2, $s2, 0x2
/* 00496C 0F9A496C 100002AB */  b           .L0F9A541C
/* 004970 0F9A4970 00001025 */   move       $v0, $zero
.L0F9A4974:
/* 004974 0F9A4974 12600003 */  beqz        $s3, .L0F9A4984
/* 004978 0F9A4978 24040001 */   addiu      $a0, $zero, 0x1
/* 00497C 0F9A497C 10000001 */  b           .L0F9A4984
/* 004980 0F9A4980 02602025 */   move       $a0, $s3
.L0F9A4984:
/* 004984 0F9A4984 92E20208 */  lbu         $v0, 0x208($s7)
/* 004988 0F9A4988 10000258 */  b           .L0F9A52EC
/* 00498C 0F9A498C 02048021 */   addu       $s0, $s0, $a0
.L0F9A4990:
/* 004990 0F9A4990 8F998014 */  lw          $t9, %got(func_0F9A544C)($gp)
/* 004994 0F9A4994 92510000 */  lbu         $s1, 0x0($s2)
/* 004998 0F9A4998 26520001 */  addiu       $s2, $s2, 0x1
/* 00499C 0F9A499C 2739544C */  addiu       $t9, $t9, %lo(func_0F9A544C)
/* 0049A0 0F9A49A0 0320F809 */  jalr        $t9
/* 0049A4 0F9A49A4 02402025 */   move       $a0, $s2
/* 0049A8 0F9A49A8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 0049AC 0F9A49AC 00000000 */  nop
/* 0049B0 0F9A49B0 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 0049B4 0F9A49B4 00000000 */  nop
/* 0049B8 0F9A49B8 24E70F30 */  addiu       $a3, $a3, %lo(B_F9B0F30)
/* 0049BC 0F9A49BC 8CE30000 */  lw          $v1, 0x0($a3)
/* 0049C0 0F9A49C0 00000000 */  nop
/* 0049C4 0F9A49C4 246DFFFF */  addiu       $t5, $v1, -0x1
/* 0049C8 0F9A49C8 1060000C */  beqz        $v1, .L0F9A49FC
/* 0049CC 0F9A49CC ACED0000 */   sw         $t5, 0x0($a3)
.L0F9A49D0:
/* 0049D0 0F9A49D0 920E0000 */  lbu         $t6, 0x0($s0)
/* 0049D4 0F9A49D4 26100001 */  addiu       $s0, $s0, 0x1
/* 0049D8 0F9A49D8 122E0003 */  beq         $s1, $t6, .L0F9A49E8
/* 0049DC 0F9A49DC 00000000 */   nop
/* 0049E0 0F9A49E0 1000028E */  b           .L0F9A541C
/* 0049E4 0F9A49E4 00001025 */   move       $v0, $zero
.L0F9A49E8:
/* 0049E8 0F9A49E8 8CE30000 */  lw          $v1, 0x0($a3)
/* 0049EC 0F9A49EC 00000000 */  nop
/* 0049F0 0F9A49F0 246CFFFF */  addiu       $t4, $v1, -0x1
/* 0049F4 0F9A49F4 1460FFF6 */  bnez        $v1, .L0F9A49D0
/* 0049F8 0F9A49F8 ACEC0000 */   sw         $t4, 0x0($a3)
.L0F9A49FC:
/* 0049FC 0F9A49FC 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 004A00 0F9A4A00 0200F025 */  move        $fp, $s0
/* 004A04 0F9A4A04 24E70F34 */  addiu       $a3, $a3, %lo(B_F9B0F34)
/* 004A08 0F9A4A08 8CE30000 */  lw          $v1, 0x0($a3)
/* 004A0C 0F9A4A0C 00000000 */  nop
/* 004A10 0F9A4A10 246FFFFF */  addiu       $t7, $v1, -0x1
/* 004A14 0F9A4A14 1060000A */  beqz        $v1, .L0F9A4A40
/* 004A18 0F9A4A18 ACEF0000 */   sw         $t7, 0x0($a3)
.L0F9A4A1C:
/* 004A1C 0F9A4A1C 92180000 */  lbu         $t8, 0x0($s0)
/* 004A20 0F9A4A20 26100001 */  addiu       $s0, $s0, 0x1
/* 004A24 0F9A4A24 16380006 */  bne         $s1, $t8, .L0F9A4A40
/* 004A28 0F9A4A28 00000000 */   nop
/* 004A2C 0F9A4A2C 8CE30000 */  lw          $v1, 0x0($a3)
/* 004A30 0F9A4A30 00000000 */  nop
/* 004A34 0F9A4A34 2479FFFF */  addiu       $t9, $v1, -0x1
/* 004A38 0F9A4A38 1460FFF8 */  bnez        $v1, .L0F9A4A1C
/* 004A3C 0F9A4A3C ACF90000 */   sw         $t9, 0x0($a3)
.L0F9A4A40:
/* 004A40 0F9A4A40 8CE80000 */  lw          $t0, 0x0($a3)
/* 004A44 0F9A4A44 00000000 */  nop
/* 004A48 0F9A4A48 05010002 */  bgez        $t0, .L0F9A4A54
/* 004A4C 0F9A4A4C 00000000 */   nop
/* 004A50 0F9A4A50 26100001 */  addiu       $s0, $s0, 0x1
.L0F9A4A54:
/* 004A54 0F9A4A54 10000259 */  b           .L0F9A53BC
/* 004A58 0F9A4A58 26520002 */   addiu      $s2, $s2, 0x2
.L0F9A4A5C:
/* 004A5C 0F9A4A5C 8F998014 */  lw          $t9, %got(func_0F9A544C)($gp)
/* 004A60 0F9A4A60 02402025 */  move        $a0, $s2
/* 004A64 0F9A4A64 2739544C */  addiu       $t9, $t9, %lo(func_0F9A544C)
/* 004A68 0F9A4A68 0320F809 */  jalr        $t9
/* 004A6C 0F9A4A6C 00000000 */   nop
/* 004A70 0F9A4A70 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004A74 0F9A4A74 00000000 */  nop
/* 004A78 0F9A4A78 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 004A7C 0F9A4A7C 00000000 */  nop
/* 004A80 0F9A4A80 24E70F30 */  addiu       $a3, $a3, %lo(B_F9B0F30)
/* 004A84 0F9A4A84 8CE30000 */  lw          $v1, 0x0($a3)
/* 004A88 0F9A4A88 00000000 */  nop
/* 004A8C 0F9A4A8C 2469FFFF */  addiu       $t1, $v1, -0x1
/* 004A90 0F9A4A90 10600012 */  beqz        $v1, .L0F9A4ADC
/* 004A94 0F9A4A94 ACE90000 */   sw         $t1, 0x0($a3)
.L0F9A4A98:
/* 004A98 0F9A4A98 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 004A9C 0F9A4A9C 02C02025 */  move        $a0, $s6
/* 004AA0 0F9A4AA0 02002825 */  move        $a1, $s0
/* 004AA4 0F9A4AA4 0320F809 */  jalr        $t9
/* 004AA8 0F9A4AA8 24060005 */   addiu      $a2, $zero, 0x5
/* 004AAC 0F9A4AAC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004AB0 0F9A4AB0 00409825 */  move        $s3, $v0
/* 004AB4 0F9A4AB4 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 004AB8 0F9A4AB8 1C400003 */  bgtz        $v0, .L0F9A4AC8
/* 004ABC 0F9A4ABC 24E70F30 */   addiu      $a3, $a3, %lo(B_F9B0F30)
/* 004AC0 0F9A4AC0 10000256 */  b           .L0F9A541C
/* 004AC4 0F9A4AC4 00001025 */   move       $v0, $zero
.L0F9A4AC8:
/* 004AC8 0F9A4AC8 8CE30000 */  lw          $v1, 0x0($a3)
/* 004ACC 0F9A4ACC 02028021 */  addu        $s0, $s0, $v0
/* 004AD0 0F9A4AD0 246AFFFF */  addiu       $t2, $v1, -0x1
/* 004AD4 0F9A4AD4 1460FFF0 */  bnez        $v1, .L0F9A4A98
/* 004AD8 0F9A4AD8 ACEA0000 */   sw         $t2, 0x0($a3)
.L0F9A4ADC:
/* 004ADC 0F9A4ADC 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 004AE0 0F9A4AE0 0200F025 */  move        $fp, $s0
/* 004AE4 0F9A4AE4 24E70F34 */  addiu       $a3, $a3, %lo(B_F9B0F34)
/* 004AE8 0F9A4AE8 8CE30000 */  lw          $v1, 0x0($a3)
/* 004AEC 0F9A4AEC 00000000 */  nop
/* 004AF0 0F9A4AF0 246BFFFF */  addiu       $t3, $v1, -0x1
/* 004AF4 0F9A4AF4 10600010 */  beqz        $v1, .L0F9A4B38
/* 004AF8 0F9A4AF8 ACEB0000 */   sw         $t3, 0x0($a3)
.L0F9A4AFC:
/* 004AFC 0F9A4AFC 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 004B00 0F9A4B00 02C02025 */  move        $a0, $s6
/* 004B04 0F9A4B04 02002825 */  move        $a1, $s0
/* 004B08 0F9A4B08 0320F809 */  jalr        $t9
/* 004B0C 0F9A4B0C 24060005 */   addiu      $a2, $zero, 0x5
/* 004B10 0F9A4B10 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004B14 0F9A4B14 00409825 */  move        $s3, $v0
/* 004B18 0F9A4B18 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 004B1C 0F9A4B1C 18400006 */  blez        $v0, .L0F9A4B38
/* 004B20 0F9A4B20 24E70F34 */   addiu      $a3, $a3, %lo(B_F9B0F34)
/* 004B24 0F9A4B24 8CE30000 */  lw          $v1, 0x0($a3)
/* 004B28 0F9A4B28 02028021 */  addu        $s0, $s0, $v0
/* 004B2C 0F9A4B2C 246DFFFF */  addiu       $t5, $v1, -0x1
/* 004B30 0F9A4B30 1460FFF2 */  bnez        $v1, .L0F9A4AFC
/* 004B34 0F9A4B34 ACED0000 */   sw         $t5, 0x0($a3)
.L0F9A4B38:
/* 004B38 0F9A4B38 8CEE0000 */  lw          $t6, 0x0($a3)
/* 004B3C 0F9A4B3C 02C02025 */  move        $a0, $s6
/* 004B40 0F9A4B40 05C10008 */  bgez        $t6, .L0F9A4B64
/* 004B44 0F9A4B44 2414FFFF */   addiu      $s4, $zero, -0x1
/* 004B48 0F9A4B48 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 004B4C 0F9A4B4C 02002825 */  move        $a1, $s0
/* 004B50 0F9A4B50 0320F809 */  jalr        $t9
/* 004B54 0F9A4B54 24060005 */   addiu      $a2, $zero, 0x5
/* 004B58 0F9A4B58 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004B5C 0F9A4B5C 00409825 */  move        $s3, $v0
/* 004B60 0F9A4B60 2414FFFF */  addiu       $s4, $zero, -0x1
.L0F9A4B64:
/* 004B64 0F9A4B64 16740003 */  bne         $s3, $s4, .L0F9A4B74
/* 004B68 0F9A4B68 26520002 */   addiu      $s2, $s2, 0x2
/* 004B6C 0F9A4B6C 1000022B */  b           .L0F9A541C
/* 004B70 0F9A4B70 00001025 */   move       $v0, $zero
.L0F9A4B74:
/* 004B74 0F9A4B74 12600003 */  beqz        $s3, .L0F9A4B84
/* 004B78 0F9A4B78 24040001 */   addiu      $a0, $zero, 0x1
/* 004B7C 0F9A4B7C 10000001 */  b           .L0F9A4B84
/* 004B80 0F9A4B80 02602025 */   move       $a0, $s3
.L0F9A4B84:
/* 004B84 0F9A4B84 92E20208 */  lbu         $v0, 0x208($s7)
/* 004B88 0F9A4B88 100001D8 */  b           .L0F9A52EC
/* 004B8C 0F9A4B8C 02048021 */   addu       $s0, $s0, $a0
.L0F9A4B90:
/* 004B90 0F9A4B90 02A0A025 */  move        $s4, $s5
.L0F9A4B94:
/* 004B94 0F9A4B94 924C0020 */  lbu         $t4, 0x20($s2)
/* 004B98 0F9A4B98 8F998014 */  lw          $t9, %got(func_0F9A544C)($gp)
/* 004B9C 0F9A4B9C 01922021 */  addu        $a0, $t4, $s2
/* 004BA0 0F9A4BA0 2739544C */  addiu       $t9, $t9, %lo(func_0F9A544C)
/* 004BA4 0F9A4BA4 0320F809 */  jalr        $t9
/* 004BA8 0F9A4BA8 24840020 */   addiu      $a0, $a0, 0x20
/* 004BAC 0F9A4BAC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004BB0 0F9A4BB0 AFB00074 */  sw          $s0, 0x74($sp)
/* 004BB4 0F9A4BB4 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 004BB8 0F9A4BB8 00000000 */  nop
/* 004BBC 0F9A4BBC 24E70F30 */  addiu       $a3, $a3, %lo(B_F9B0F30)
/* 004BC0 0F9A4BC0 8CE30000 */  lw          $v1, 0x0($a3)
/* 004BC4 0F9A4BC4 00000000 */  nop
/* 004BC8 0F9A4BC8 246FFFFF */  addiu       $t7, $v1, -0x1
/* 004BCC 0F9A4BCC 10600013 */  beqz        $v1, .L0F9A4C1C
/* 004BD0 0F9A4BD0 ACEF0000 */   sw         $t7, 0x0($a3)
.L0F9A4BD4:
/* 004BD4 0F9A4BD4 8F998014 */  lw          $t9, %got(func_0F9A54A4)($gp)
/* 004BD8 0F9A4BD8 02402025 */  move        $a0, $s2
/* 004BDC 0F9A4BDC 273954A4 */  addiu       $t9, $t9, %lo(func_0F9A54A4)
/* 004BE0 0F9A4BE0 27A50074 */  addiu       $a1, $sp, 0x74
/* 004BE4 0F9A4BE4 0320F809 */  jalr        $t9
/* 004BE8 0F9A4BE8 02803025 */   move       $a2, $s4
/* 004BEC 0F9A4BEC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004BF0 0F9A4BF0 00000000 */  nop
/* 004BF4 0F9A4BF4 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 004BF8 0F9A4BF8 10550003 */  beq         $v0, $s5, .L0F9A4C08
/* 004BFC 0F9A4BFC 24E70F30 */   addiu      $a3, $a3, %lo(B_F9B0F30)
/* 004C00 0F9A4C00 10000206 */  b           .L0F9A541C
/* 004C04 0F9A4C04 00001025 */   move       $v0, $zero
.L0F9A4C08:
/* 004C08 0F9A4C08 8CE30000 */  lw          $v1, 0x0($a3)
/* 004C0C 0F9A4C0C 00000000 */  nop
/* 004C10 0F9A4C10 2478FFFF */  addiu       $t8, $v1, -0x1
/* 004C14 0F9A4C14 1460FFEF */  bnez        $v1, .L0F9A4BD4
/* 004C18 0F9A4C18 ACF80000 */   sw         $t8, 0x0($a3)
.L0F9A4C1C:
/* 004C1C 0F9A4C1C 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 004C20 0F9A4C20 8FBE0074 */  lw          $fp, 0x74($sp)
/* 004C24 0F9A4C24 24E70F34 */  addiu       $a3, $a3, %lo(B_F9B0F34)
/* 004C28 0F9A4C28 8CE30000 */  lw          $v1, 0x0($a3)
/* 004C2C 0F9A4C2C 02402025 */  move        $a0, $s2
/* 004C30 0F9A4C30 2479FFFF */  addiu       $t9, $v1, -0x1
/* 004C34 0F9A4C34 1060001A */  beqz        $v1, .L0F9A4CA0
/* 004C38 0F9A4C38 ACF90000 */   sw         $t9, 0x0($a3)
/* 004C3C 0F9A4C3C 8F998014 */  lw          $t9, %got(func_0F9A54A4)($gp)
/* 004C40 0F9A4C40 27A50074 */  addiu       $a1, $sp, 0x74
/* 004C44 0F9A4C44 273954A4 */  addiu       $t9, $t9, %lo(func_0F9A54A4)
/* 004C48 0F9A4C48 0320F809 */  jalr        $t9
/* 004C4C 0F9A4C4C 02803025 */   move       $a2, $s4
/* 004C50 0F9A4C50 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004C54 0F9A4C54 00408825 */  move        $s1, $v0
/* 004C58 0F9A4C58 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 004C5C 0F9A4C5C 14550010 */  bne         $v0, $s5, .L0F9A4CA0
/* 004C60 0F9A4C60 24E70F34 */   addiu      $a3, $a3, %lo(B_F9B0F34)
.L0F9A4C64:
/* 004C64 0F9A4C64 8CE30000 */  lw          $v1, 0x0($a3)
/* 004C68 0F9A4C68 02402025 */  move        $a0, $s2
/* 004C6C 0F9A4C6C 2468FFFF */  addiu       $t0, $v1, -0x1
/* 004C70 0F9A4C70 1060000B */  beqz        $v1, .L0F9A4CA0
/* 004C74 0F9A4C74 ACE80000 */   sw         $t0, 0x0($a3)
/* 004C78 0F9A4C78 8F998014 */  lw          $t9, %got(func_0F9A54A4)($gp)
/* 004C7C 0F9A4C7C 27A50074 */  addiu       $a1, $sp, 0x74
/* 004C80 0F9A4C80 273954A4 */  addiu       $t9, $t9, %lo(func_0F9A54A4)
/* 004C84 0F9A4C84 0320F809 */  jalr        $t9
/* 004C88 0F9A4C88 02803025 */   move       $a2, $s4
/* 004C8C 0F9A4C8C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004C90 0F9A4C90 00408825 */  move        $s1, $v0
/* 004C94 0F9A4C94 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 004C98 0F9A4C98 1055FFF2 */  beq         $v0, $s5, .L0F9A4C64
/* 004C9C 0F9A4C9C 24E70F34 */   addiu      $a3, $a3, %lo(B_F9B0F34)
.L0F9A4CA0:
/* 004CA0 0F9A4CA0 2414FFFF */  addiu       $s4, $zero, -0x1
/* 004CA4 0F9A4CA4 16340003 */  bne         $s1, $s4, .L0F9A4CB4
/* 004CA8 0F9A4CA8 00000000 */   nop
/* 004CAC 0F9A4CAC 100001DB */  b           .L0F9A541C
/* 004CB0 0F9A4CB0 00001025 */   move       $v0, $zero
.L0F9A4CB4:
/* 004CB4 0F9A4CB4 8CE90000 */  lw          $t1, 0x0($a3)
/* 004CB8 0F9A4CB8 8FB00074 */  lw          $s0, 0x74($sp)
/* 004CBC 0F9A4CBC 0521000F */  bgez        $t1, .L0F9A4CFC
/* 004CC0 0F9A4CC0 02C02025 */   move       $a0, $s6
/* 004CC4 0F9A4CC4 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 004CC8 0F9A4CC8 02002825 */  move        $a1, $s0
/* 004CCC 0F9A4CCC 0320F809 */  jalr        $t9
/* 004CD0 0F9A4CD0 24060005 */   addiu      $a2, $zero, 0x5
/* 004CD4 0F9A4CD4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004CD8 0F9A4CD8 14540003 */  bne         $v0, $s4, .L0F9A4CE8
/* 004CDC 0F9A4CDC 00000000 */   nop
/* 004CE0 0F9A4CE0 100001CE */  b           .L0F9A541C
/* 004CE4 0F9A4CE4 00001025 */   move       $v0, $zero
.L0F9A4CE8:
/* 004CE8 0F9A4CE8 10400003 */  beqz        $v0, .L0F9A4CF8
/* 004CEC 0F9A4CEC 24040001 */   addiu      $a0, $zero, 0x1
/* 004CF0 0F9A4CF0 10000001 */  b           .L0F9A4CF8
/* 004CF4 0F9A4CF4 00402025 */   move       $a0, $v0
.L0F9A4CF8:
/* 004CF8 0F9A4CF8 02048021 */  addu        $s0, $s0, $a0
.L0F9A4CFC:
/* 004CFC 0F9A4CFC 924A0020 */  lbu         $t2, 0x20($s2)
/* 004D00 0F9A4D00 92E20208 */  lbu         $v0, 0x208($s7)
/* 004D04 0F9A4D04 024A9021 */  addu        $s2, $s2, $t2
/* 004D08 0F9A4D08 10000178 */  b           .L0F9A52EC
/* 004D0C 0F9A4D0C 26520022 */   addiu      $s2, $s2, 0x22
.L0F9A4D10:
/* 004D10 0F9A4D10 8F998014 */  lw          $t9, %got(func_0F9A544C)($gp)
/* 004D14 0F9A4D14 26440020 */  addiu       $a0, $s2, 0x20
/* 004D18 0F9A4D18 2739544C */  addiu       $t9, $t9, %lo(func_0F9A544C)
/* 004D1C 0F9A4D1C 0320F809 */  jalr        $t9
/* 004D20 0F9A4D20 00000000 */   nop
/* 004D24 0F9A4D24 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004D28 0F9A4D28 00000000 */  nop
/* 004D2C 0F9A4D2C 8F87805C */  lw          $a3, %got(B_F9B0F30)($gp)
/* 004D30 0F9A4D30 00000000 */  nop
/* 004D34 0F9A4D34 24E70F30 */  addiu       $a3, $a3, %lo(B_F9B0F30)
/* 004D38 0F9A4D38 8CE30000 */  lw          $v1, 0x0($a3)
/* 004D3C 0F9A4D3C 00000000 */  nop
/* 004D40 0F9A4D40 246BFFFF */  addiu       $t3, $v1, -0x1
/* 004D44 0F9A4D44 10600017 */  beqz        $v1, .L0F9A4DA4
/* 004D48 0F9A4D48 ACEB0000 */   sw         $t3, 0x0($a3)
/* 004D4C 0F9A4D4C 8F82805C */  lw          $v0, %got(D_F9B0084)($gp)
/* 004D50 0F9A4D50 00000000 */  nop
/* 004D54 0F9A4D54 24420084 */  addiu       $v0, $v0, %lo(D_F9B0084)
.L0F9A4D58:
/* 004D58 0F9A4D58 92110000 */  lbu         $s1, 0x0($s0)
/* 004D5C 0F9A4D5C 26100001 */  addiu       $s0, $s0, 0x1
/* 004D60 0F9A4D60 322D0007 */  andi        $t5, $s1, 0x7
/* 004D64 0F9A4D64 001178C3 */  sra         $t7, $s1, 3
/* 004D68 0F9A4D68 024FC021 */  addu        $t8, $s2, $t7
/* 004D6C 0F9A4D6C 004D7021 */  addu        $t6, $v0, $t5
/* 004D70 0F9A4D70 91CC0000 */  lbu         $t4, 0x0($t6)
/* 004D74 0F9A4D74 93190000 */  lbu         $t9, 0x0($t8)
/* 004D78 0F9A4D78 00000000 */  nop
/* 004D7C 0F9A4D7C 01994024 */  and         $t0, $t4, $t9
/* 004D80 0F9A4D80 15000003 */  bnez        $t0, .L0F9A4D90
/* 004D84 0F9A4D84 00000000 */   nop
/* 004D88 0F9A4D88 100001A4 */  b           .L0F9A541C
/* 004D8C 0F9A4D8C 00001025 */   move       $v0, $zero
.L0F9A4D90:
/* 004D90 0F9A4D90 8CE30000 */  lw          $v1, 0x0($a3)
/* 004D94 0F9A4D94 00000000 */  nop
/* 004D98 0F9A4D98 2469FFFF */  addiu       $t1, $v1, -0x1
/* 004D9C 0F9A4D9C 1460FFEE */  bnez        $v1, .L0F9A4D58
/* 004DA0 0F9A4DA0 ACE90000 */   sw         $t1, 0x0($a3)
.L0F9A4DA4:
/* 004DA4 0F9A4DA4 8F87805C */  lw          $a3, %got(B_F9B0F34)($gp)
/* 004DA8 0F9A4DA8 8F82805C */  lw          $v0, %got(D_F9B0084)($gp)
/* 004DAC 0F9A4DAC 24E70F34 */  addiu       $a3, $a3, %lo(B_F9B0F34)
/* 004DB0 0F9A4DB0 8CE30000 */  lw          $v1, 0x0($a3)
/* 004DB4 0F9A4DB4 0200F025 */  move        $fp, $s0
/* 004DB8 0F9A4DB8 246AFFFF */  addiu       $t2, $v1, -0x1
/* 004DBC 0F9A4DBC ACEA0000 */  sw          $t2, 0x0($a3)
/* 004DC0 0F9A4DC0 10600012 */  beqz        $v1, .L0F9A4E0C
/* 004DC4 0F9A4DC4 24420084 */   addiu      $v0, $v0, %lo(D_F9B0084)
.L0F9A4DC8:
/* 004DC8 0F9A4DC8 92110000 */  lbu         $s1, 0x0($s0)
/* 004DCC 0F9A4DCC 26100001 */  addiu       $s0, $s0, 0x1
/* 004DD0 0F9A4DD0 322B0007 */  andi        $t3, $s1, 0x7
/* 004DD4 0F9A4DD4 001178C3 */  sra         $t7, $s1, 3
/* 004DD8 0F9A4DD8 024FC021 */  addu        $t8, $s2, $t7
/* 004DDC 0F9A4DDC 004B6821 */  addu        $t5, $v0, $t3
/* 004DE0 0F9A4DE0 91AE0000 */  lbu         $t6, 0x0($t5)
/* 004DE4 0F9A4DE4 930C0000 */  lbu         $t4, 0x0($t8)
/* 004DE8 0F9A4DE8 00000000 */  nop
/* 004DEC 0F9A4DEC 01CCC824 */  and         $t9, $t6, $t4
/* 004DF0 0F9A4DF0 13200006 */  beqz        $t9, .L0F9A4E0C
/* 004DF4 0F9A4DF4 00000000 */   nop
/* 004DF8 0F9A4DF8 8CE30000 */  lw          $v1, 0x0($a3)
/* 004DFC 0F9A4DFC 00000000 */  nop
/* 004E00 0F9A4E00 2468FFFF */  addiu       $t0, $v1, -0x1
/* 004E04 0F9A4E04 1460FFF0 */  bnez        $v1, .L0F9A4DC8
/* 004E08 0F9A4E08 ACE80000 */   sw         $t0, 0x0($a3)
.L0F9A4E0C:
/* 004E0C 0F9A4E0C 8CE90000 */  lw          $t1, 0x0($a3)
/* 004E10 0F9A4E10 00000000 */  nop
/* 004E14 0F9A4E14 05210002 */  bgez        $t1, .L0F9A4E20
/* 004E18 0F9A4E18 00000000 */   nop
/* 004E1C 0F9A4E1C 26100001 */  addiu       $s0, $s0, 0x1
.L0F9A4E20:
/* 004E20 0F9A4E20 10000166 */  b           .L0F9A53BC
/* 004E24 0F9A4E24 26520022 */   addiu      $s2, $s2, 0x22
.L0F9A4E28:
/* 004E28 0F9A4E28 92420000 */  lbu         $v0, 0x0($s2)
/* 004E2C 0F9A4E2C 8F8D814C */  lw          $t5, %got(_braelist)($gp)
/* 004E30 0F9A4E30 00025080 */  sll         $t2, $v0, 2
/* 004E34 0F9A4E34 03CA5821 */  addu        $t3, $fp, $t2
/* 004E38 0F9A4E38 014D7821 */  addu        $t7, $t2, $t5
/* 004E3C 0F9A4E3C 8D640000 */  lw          $a0, 0x0($t3)
/* 004E40 0F9A4E40 8DF80000 */  lw          $t8, 0x0($t7)
/* 004E44 0F9A4E44 8F9980C4 */  lw          $t9, %call16(strncmp)($gp)
/* 004E48 0F9A4E48 03043023 */  subu        $a2, $t8, $a0
/* 004E4C 0F9A4E4C 26520001 */  addiu       $s2, $s2, 0x1
/* 004E50 0F9A4E50 AFA60054 */  sw          $a2, 0x54($sp)
/* 004E54 0F9A4E54 0320F809 */  jalr        $t9
/* 004E58 0F9A4E58 02002825 */   move       $a1, $s0
/* 004E5C 0F9A4E5C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004E60 0F9A4E60 8FA60054 */  lw          $a2, 0x54($sp)
/* 004E64 0F9A4E64 14400003 */  bnez        $v0, .L0F9A4E74
/* 004E68 0F9A4E68 00000000 */   nop
/* 004E6C 0F9A4E6C 1000FDF9 */  b           .L0F9A4654
/* 004E70 0F9A4E70 02068021 */   addu       $s0, $s0, $a2
.L0F9A4E74:
/* 004E74 0F9A4E74 10000169 */  b           .L0F9A541C
/* 004E78 0F9A4E78 00001025 */   move       $v0, $zero
.L0F9A4E7C:
/* 004E7C 0F9A4E7C 92420000 */  lbu         $v0, 0x0($s2)
/* 004E80 0F9A4E80 8F8C8148 */  lw          $t4, %got(_braslist)($gp)
/* 004E84 0F9A4E84 8F88814C */  lw          $t0, %got(_braelist)($gp)
/* 004E88 0F9A4E88 00027080 */  sll         $t6, $v0, 2
/* 004E8C 0F9A4E8C 01CCC821 */  addu        $t9, $t6, $t4
/* 004E90 0F9A4E90 8F240000 */  lw          $a0, 0x0($t9)
/* 004E94 0F9A4E94 01C84821 */  addu        $t1, $t6, $t0
/* 004E98 0F9A4E98 8D2A0000 */  lw          $t2, 0x0($t1)
/* 004E9C 0F9A4E9C 8F9980C4 */  lw          $t9, %call16(strncmp)($gp)
/* 004EA0 0F9A4EA0 01443023 */  subu        $a2, $t2, $a0
/* 004EA4 0F9A4EA4 26520001 */  addiu       $s2, $s2, 0x1
/* 004EA8 0F9A4EA8 0200F025 */  move        $fp, $s0
/* 004EAC 0F9A4EAC AFA60054 */  sw          $a2, 0x54($sp)
/* 004EB0 0F9A4EB0 02002825 */  move        $a1, $s0
/* 004EB4 0F9A4EB4 0320F809 */  jalr        $t9
/* 004EB8 0F9A4EB8 AFA40058 */   sw         $a0, 0x58($sp)
/* 004EBC 0F9A4EBC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004EC0 0F9A4EC0 8FA40058 */  lw          $a0, 0x58($sp)
/* 004EC4 0F9A4EC4 8FA60054 */  lw          $a2, 0x54($sp)
/* 004EC8 0F9A4EC8 1440000D */  bnez        $v0, .L0F9A4F00
/* 004ECC 0F9A4ECC 021E082B */   sltu       $at, $s0, $fp
.L0F9A4ED0:
/* 004ED0 0F9A4ED0 8F9980C4 */  lw          $t9, %call16(strncmp)($gp)
/* 004ED4 0F9A4ED4 02068021 */  addu        $s0, $s0, $a2
/* 004ED8 0F9A4ED8 02002825 */  move        $a1, $s0
/* 004EDC 0F9A4EDC AFA40058 */  sw          $a0, 0x58($sp)
/* 004EE0 0F9A4EE0 0320F809 */  jalr        $t9
/* 004EE4 0F9A4EE4 AFA60054 */   sw         $a2, 0x54($sp)
/* 004EE8 0F9A4EE8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004EEC 0F9A4EEC 8FA40058 */  lw          $a0, 0x58($sp)
/* 004EF0 0F9A4EF0 8FA60054 */  lw          $a2, 0x54($sp)
/* 004EF4 0F9A4EF4 1040FFF6 */  beqz        $v0, .L0F9A4ED0
/* 004EF8 0F9A4EF8 00000000 */   nop
/* 004EFC 0F9A4EFC 021E082B */  sltu        $at, $s0, $fp
.L0F9A4F00:
/* 004F00 0F9A4F00 14200010 */  bnez        $at, .L0F9A4F44
/* 004F04 0F9A4F04 00000000 */   nop
.L0F9A4F08:
/* 004F08 0F9A4F08 8F998014 */  lw          $t9, %got(func_0F9A45F4)($gp)
/* 004F0C 0F9A4F0C 02002025 */  move        $a0, $s0
/* 004F10 0F9A4F10 273945F4 */  addiu       $t9, $t9, %lo(func_0F9A45F4)
/* 004F14 0F9A4F14 02402825 */  move        $a1, $s2
/* 004F18 0F9A4F18 0320F809 */  jalr        $t9
/* 004F1C 0F9A4F1C AFA60054 */   sw         $a2, 0x54($sp)
/* 004F20 0F9A4F20 8FA60054 */  lw          $a2, 0x54($sp)
/* 004F24 0F9A4F24 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004F28 0F9A4F28 10400003 */  beqz        $v0, .L0F9A4F38
/* 004F2C 0F9A4F2C 02068023 */   subu       $s0, $s0, $a2
/* 004F30 0F9A4F30 1000013A */  b           .L0F9A541C
/* 004F34 0F9A4F34 24020001 */   addiu      $v0, $zero, 0x1
.L0F9A4F38:
/* 004F38 0F9A4F38 021E082B */  sltu        $at, $s0, $fp
/* 004F3C 0F9A4F3C 1020FFF2 */  beqz        $at, .L0F9A4F08
/* 004F40 0F9A4F40 00000000 */   nop
.L0F9A4F44:
/* 004F44 0F9A4F44 10000135 */  b           .L0F9A541C
/* 004F48 0F9A4F48 00001025 */   move       $v0, $zero
.L0F9A4F4C:
/* 004F4C 0F9A4F4C 92EB0208 */  lbu         $t3, 0x208($s7)
/* 004F50 0F9A4F50 0200F025 */  move        $fp, $s0
/* 004F54 0F9A4F54 29610002 */  slti        $at, $t3, 0x2
/* 004F58 0F9A4F58 1020000B */  beqz        $at, .L0F9A4F88
/* 004F5C 0F9A4F5C 02C02025 */   move       $a0, $s6
/* 004F60 0F9A4F60 92040000 */  lbu         $a0, 0x0($s0)
/* 004F64 0F9A4F64 26100001 */  addiu       $s0, $s0, 0x1
/* 004F68 0F9A4F68 1080001F */  beqz        $a0, .L0F9A4FE8
/* 004F6C 0F9A4F6C 00000000 */   nop
.L0F9A4F70:
/* 004F70 0F9A4F70 92040000 */  lbu         $a0, 0x0($s0)
/* 004F74 0F9A4F74 26100001 */  addiu       $s0, $s0, 0x1
/* 004F78 0F9A4F78 1480FFFD */  bnez        $a0, .L0F9A4F70
/* 004F7C 0F9A4F7C 00000000 */   nop
/* 004F80 0F9A4F80 1000001A */  b           .L0F9A4FEC
/* 004F84 0F9A4F84 92E20208 */   lbu        $v0, 0x208($s7)
.L0F9A4F88:
/* 004F88 0F9A4F88 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 004F8C 0F9A4F8C 02002825 */  move        $a1, $s0
/* 004F90 0F9A4F90 0320F809 */  jalr        $t9
/* 004F94 0F9A4F94 24060005 */   addiu      $a2, $zero, 0x5
/* 004F98 0F9A4F98 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004F9C 0F9A4F9C 1840000A */  blez        $v0, .L0F9A4FC8
/* 004FA0 0F9A4FA0 00409825 */   move       $s3, $v0
.L0F9A4FA4:
/* 004FA4 0F9A4FA4 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 004FA8 0F9A4FA8 02138021 */  addu        $s0, $s0, $s3
/* 004FAC 0F9A4FAC 02002825 */  move        $a1, $s0
/* 004FB0 0F9A4FB0 02C02025 */  move        $a0, $s6
/* 004FB4 0F9A4FB4 0320F809 */  jalr        $t9
/* 004FB8 0F9A4FB8 24060005 */   addiu      $a2, $zero, 0x5
/* 004FBC 0F9A4FBC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 004FC0 0F9A4FC0 1C40FFF8 */  bgtz        $v0, .L0F9A4FA4
/* 004FC4 0F9A4FC4 00409825 */   move       $s3, $v0
.L0F9A4FC8:
/* 004FC8 0F9A4FC8 2414FFFF */  addiu       $s4, $zero, -0x1
/* 004FCC 0F9A4FCC 14540003 */  bne         $v0, $s4, .L0F9A4FDC
/* 004FD0 0F9A4FD0 00000000 */   nop
/* 004FD4 0F9A4FD4 10000111 */  b           .L0F9A541C
/* 004FD8 0F9A4FD8 00001025 */   move       $v0, $zero
.L0F9A4FDC:
/* 004FDC 0F9A4FDC 14400002 */  bnez        $v0, .L0F9A4FE8
/* 004FE0 0F9A4FE0 00000000 */   nop
/* 004FE4 0F9A4FE4 26100001 */  addiu       $s0, $s0, 0x1
.L0F9A4FE8:
/* 004FE8 0F9A4FE8 92E20208 */  lbu         $v0, 0x208($s7)
.L0F9A4FEC:
/* 004FEC 0F9A4FEC 100000C0 */  b           .L0F9A52F0
/* 004FF0 0F9A4FF0 28410002 */   slti       $at, $v0, 0x2
.L0F9A4FF4:
/* 004FF4 0F9A4FF4 92420000 */  lbu         $v0, 0x0($s2)
/* 004FF8 0F9A4FF8 920D0000 */  lbu         $t5, 0x0($s0)
/* 004FFC 0F9A4FFC 0200F025 */  move        $fp, $s0
/* 005000 0F9A5000 15A20005 */  bne         $t5, $v0, .L0F9A5018
/* 005004 0F9A5004 26100001 */   addiu      $s0, $s0, 0x1
.L0F9A5008:
/* 005008 0F9A5008 920F0000 */  lbu         $t7, 0x0($s0)
/* 00500C 0F9A500C 26100001 */  addiu       $s0, $s0, 0x1
/* 005010 0F9A5010 11E2FFFD */  beq         $t7, $v0, .L0F9A5008
/* 005014 0F9A5014 00000000 */   nop
.L0F9A5018:
/* 005018 0F9A5018 100000E8 */  b           .L0F9A53BC
/* 00501C 0F9A501C 26520001 */   addiu      $s2, $s2, 0x1
.L0F9A5020:
/* 005020 0F9A5020 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005024 0F9A5024 0200F025 */  move        $fp, $s0
/* 005028 0F9A5028 02C02025 */  move        $a0, $s6
/* 00502C 0F9A502C 02402825 */  move        $a1, $s2
/* 005030 0F9A5030 0320F809 */  jalr        $t9
/* 005034 0F9A5034 24060005 */   addiu      $a2, $zero, 0x5
/* 005038 0F9A5038 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00503C 0F9A503C 8FB10060 */  lw          $s1, 0x60($sp)
/* 005040 0F9A5040 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005044 0F9A5044 02429021 */  addu        $s2, $s2, $v0
/* 005048 0F9A5048 02C02025 */  move        $a0, $s6
/* 00504C 0F9A504C 02002825 */  move        $a1, $s0
/* 005050 0F9A5050 0320F809 */  jalr        $t9
/* 005054 0F9A5054 24060005 */   addiu      $a2, $zero, 0x5
/* 005058 0F9A5058 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00505C 0F9A505C 18400012 */  blez        $v0, .L0F9A50A8
/* 005060 0F9A5060 00409825 */   move       $s3, $v0
/* 005064 0F9A5064 8FB80060 */  lw          $t8, 0x60($sp)
/* 005068 0F9A5068 00000000 */  nop
/* 00506C 0F9A506C 1711000F */  bne         $t8, $s1, .L0F9A50AC
/* 005070 0F9A5070 2414FFFF */   addiu      $s4, $zero, -0x1
.L0F9A5074:
/* 005074 0F9A5074 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005078 0F9A5078 02138021 */  addu        $s0, $s0, $s3
/* 00507C 0F9A507C 02002825 */  move        $a1, $s0
/* 005080 0F9A5080 02C02025 */  move        $a0, $s6
/* 005084 0F9A5084 0320F809 */  jalr        $t9
/* 005088 0F9A5088 24060005 */   addiu      $a2, $zero, 0x5
/* 00508C 0F9A508C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005090 0F9A5090 18400005 */  blez        $v0, .L0F9A50A8
/* 005094 0F9A5094 00409825 */   move       $s3, $v0
/* 005098 0F9A5098 8FAE0060 */  lw          $t6, 0x60($sp)
/* 00509C 0F9A509C 00000000 */  nop
/* 0050A0 0F9A50A0 11D1FFF4 */  beq         $t6, $s1, .L0F9A5074
/* 0050A4 0F9A50A4 00000000 */   nop
.L0F9A50A8:
/* 0050A8 0F9A50A8 2414FFFF */  addiu       $s4, $zero, -0x1
.L0F9A50AC:
/* 0050AC 0F9A50AC 14540003 */  bne         $v0, $s4, .L0F9A50BC
/* 0050B0 0F9A50B0 00000000 */   nop
/* 0050B4 0F9A50B4 100000D9 */  b           .L0F9A541C
/* 0050B8 0F9A50B8 00001025 */   move       $v0, $zero
.L0F9A50BC:
/* 0050BC 0F9A50BC 10400003 */  beqz        $v0, .L0F9A50CC
/* 0050C0 0F9A50C0 24040001 */   addiu      $a0, $zero, 0x1
/* 0050C4 0F9A50C4 10000001 */  b           .L0F9A50CC
/* 0050C8 0F9A50C8 00402025 */   move       $a0, $v0
.L0F9A50CC:
/* 0050CC 0F9A50CC 92E20208 */  lbu         $v0, 0x208($s7)
/* 0050D0 0F9A50D0 10000086 */  b           .L0F9A52EC
/* 0050D4 0F9A50D4 02048021 */   addu       $s0, $s0, $a0
.L0F9A50D8:
/* 0050D8 0F9A50D8 02A0A025 */  move        $s4, $s5
.L0F9A50DC:
/* 0050DC 0F9A50DC 8F998014 */  lw          $t9, %got(func_0F9A54A4)($gp)
/* 0050E0 0F9A50E0 AFB00074 */  sw          $s0, 0x74($sp)
/* 0050E4 0F9A50E4 273954A4 */  addiu       $t9, $t9, %lo(func_0F9A54A4)
/* 0050E8 0F9A50E8 0200F025 */  move        $fp, $s0
/* 0050EC 0F9A50EC 02402025 */  move        $a0, $s2
/* 0050F0 0F9A50F0 27A50074 */  addiu       $a1, $sp, 0x74
/* 0050F4 0F9A50F4 0320F809 */  jalr        $t9
/* 0050F8 0F9A50F8 02803025 */   move       $a2, $s4
/* 0050FC 0F9A50FC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005100 0F9A5100 1455000A */  bne         $v0, $s5, .L0F9A512C
/* 005104 0F9A5104 00000000 */   nop
.L0F9A5108:
/* 005108 0F9A5108 8F998014 */  lw          $t9, %got(func_0F9A54A4)($gp)
/* 00510C 0F9A510C 02402025 */  move        $a0, $s2
/* 005110 0F9A5110 273954A4 */  addiu       $t9, $t9, %lo(func_0F9A54A4)
/* 005114 0F9A5114 27A50074 */  addiu       $a1, $sp, 0x74
/* 005118 0F9A5118 0320F809 */  jalr        $t9
/* 00511C 0F9A511C 02803025 */   move       $a2, $s4
/* 005120 0F9A5120 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005124 0F9A5124 1055FFF8 */  beq         $v0, $s5, .L0F9A5108
/* 005128 0F9A5128 00000000 */   nop
.L0F9A512C:
/* 00512C 0F9A512C 2414FFFF */  addiu       $s4, $zero, -0x1
/* 005130 0F9A5130 14540003 */  bne         $v0, $s4, .L0F9A5140
/* 005134 0F9A5134 00000000 */   nop
/* 005138 0F9A5138 100000B8 */  b           .L0F9A541C
/* 00513C 0F9A513C 00001025 */   move       $v0, $zero
.L0F9A5140:
/* 005140 0F9A5140 924C0020 */  lbu         $t4, 0x20($s2)
/* 005144 0F9A5144 8FB00074 */  lw          $s0, 0x74($sp)
/* 005148 0F9A5148 92E20208 */  lbu         $v0, 0x208($s7)
/* 00514C 0F9A514C 024C9021 */  addu        $s2, $s2, $t4
/* 005150 0F9A5150 10000066 */  b           .L0F9A52EC
/* 005154 0F9A5154 26520020 */   addiu      $s2, $s2, 0x20
.L0F9A5158:
/* 005158 0F9A5158 8F82805C */  lw          $v0, %got(D_F9B0084)($gp)
/* 00515C 0F9A515C 0200F025 */  move        $fp, $s0
/* 005160 0F9A5160 24420084 */  addiu       $v0, $v0, %lo(D_F9B0084)
.L0F9A5164:
/* 005164 0F9A5164 92110000 */  lbu         $s1, 0x0($s0)
/* 005168 0F9A5168 26100001 */  addiu       $s0, $s0, 0x1
/* 00516C 0F9A516C 32390007 */  andi        $t9, $s1, 0x7
/* 005170 0F9A5170 001150C3 */  sra         $t2, $s1, 3
/* 005174 0F9A5174 024A5821 */  addu        $t3, $s2, $t2
/* 005178 0F9A5178 00594021 */  addu        $t0, $v0, $t9
/* 00517C 0F9A517C 91090000 */  lbu         $t1, 0x0($t0)
/* 005180 0F9A5180 916D0000 */  lbu         $t5, 0x0($t3)
/* 005184 0F9A5184 00000000 */  nop
/* 005188 0F9A5188 012D7824 */  and         $t7, $t1, $t5
/* 00518C 0F9A518C 15E0FFF5 */  bnez        $t7, .L0F9A5164
/* 005190 0F9A5190 00000000 */   nop
/* 005194 0F9A5194 10000089 */  b           .L0F9A53BC
/* 005198 0F9A5198 26520020 */   addiu      $s2, $s2, 0x20
.L0F9A519C:
/* 00519C 0F9A519C 8F98805C */  lw          $t8, %got(B_F9B0F38)($gp)
/* 0051A0 0F9A51A0 00000000 */  nop
/* 0051A4 0F9A51A4 8F180F38 */  lw          $t8, %lo(B_F9B0F38)($t8)
/* 0051A8 0F9A51A8 00000000 */  nop
/* 0051AC 0F9A51AC 16180007 */  bne         $s0, $t8, .L0F9A51CC
/* 0051B0 0F9A51B0 00000000 */   nop
/* 0051B4 0F9A51B4 8F8E8144 */  lw          $t6, %got(_locs)($gp)
/* 0051B8 0F9A51B8 00000000 */  nop
/* 0051BC 0F9A51BC 8DCE0000 */  lw          $t6, 0x0($t6)
/* 0051C0 0F9A51C0 00000000 */  nop
/* 0051C4 0F9A51C4 11C0FD23 */  beqz        $t6, .L0F9A4654
/* 0051C8 0F9A51C8 00000000 */   nop
.L0F9A51CC:
/* 0051CC 0F9A51CC 92110000 */  lbu         $s1, 0x0($s0)
/* 0051D0 0F9A51D0 9204FFFF */  lbu         $a0, -0x1($s0)
/* 0051D4 0F9A51D4 02F16021 */  addu        $t4, $s7, $s1
/* 0051D8 0F9A51D8 91820001 */  lbu         $v0, 0x1($t4)
/* 0051DC 0F9A51DC 02E41821 */  addu        $v1, $s7, $a0
/* 0051E0 0F9A51E0 30590004 */  andi        $t9, $v0, 0x4
/* 0051E4 0F9A51E4 1720000C */  bnez        $t9, .L0F9A5218
/* 0051E8 0F9A51E8 30480003 */   andi       $t0, $v0, 0x3
/* 0051EC 0F9A51EC 1500000A */  bnez        $t0, .L0F9A5218
/* 0051F0 0F9A51F0 2401005F */   addiu      $at, $zero, 0x5F
/* 0051F4 0F9A51F4 12210008 */  beq         $s1, $at, .L0F9A5218
/* 0051F8 0F9A51F8 2A210080 */   slti       $at, $s1, 0x80
/* 0051FC 0F9A51FC 1420001C */  bnez        $at, .L0F9A5270
/* 005200 0F9A5200 00000000 */   nop
/* 005204 0F9A5204 92EA0208 */  lbu         $t2, 0x208($s7)
/* 005208 0F9A5208 00000000 */  nop
/* 00520C 0F9A520C 29410002 */  slti        $at, $t2, 0x2
/* 005210 0F9A5210 14200017 */  bnez        $at, .L0F9A5270
/* 005214 0F9A5214 00000000 */   nop
.L0F9A5218:
/* 005218 0F9A5218 90620001 */  lbu         $v0, 0x1($v1)
/* 00521C 0F9A521C 00000000 */  nop
/* 005220 0F9A5220 304B0004 */  andi        $t3, $v0, 0x4
/* 005224 0F9A5224 15600012 */  bnez        $t3, .L0F9A5270
/* 005228 0F9A5228 30490003 */   andi       $t1, $v0, 0x3
/* 00522C 0F9A522C 15200010 */  bnez        $t1, .L0F9A5270
/* 005230 0F9A5230 00000000 */   nop
/* 005234 0F9A5234 8F8D8070 */  lw          $t5, %got(D_FB504F0)($gp)
/* 005238 0F9A5238 00000000 */  nop
/* 00523C 0F9A523C 25AD005F */  addiu       $t5, $t5, 0x5F
/* 005240 0F9A5240 106D000B */  beq         $v1, $t5, .L0F9A5270
/* 005244 0F9A5244 00000000 */   nop
/* 005248 0F9A5248 8F8F8070 */  lw          $t7, %got(D_FB504F0)($gp)
/* 00524C 0F9A524C 00000000 */  nop
/* 005250 0F9A5250 25EF0080 */  addiu       $t7, $t7, 0x80
/* 005254 0F9A5254 006F082B */  sltu        $at, $v1, $t7
/* 005258 0F9A5258 1420FCFE */  bnez        $at, .L0F9A4654
/* 00525C 0F9A525C 00000000 */   nop
/* 005260 0F9A5260 92F80208 */  lbu         $t8, 0x208($s7)
/* 005264 0F9A5264 00000000 */  nop
/* 005268 0F9A5268 12B8FCFA */  beq         $s5, $t8, .L0F9A4654
/* 00526C 0F9A526C 00000000 */   nop
.L0F9A5270:
/* 005270 0F9A5270 1000006A */  b           .L0F9A541C
/* 005274 0F9A5274 00001025 */   move       $v0, $zero
.L0F9A5278:
/* 005278 0F9A5278 92040000 */  lbu         $a0, 0x0($s0)
/* 00527C 0F9A527C 00000000 */  nop
/* 005280 0F9A5280 02E41821 */  addu        $v1, $s7, $a0
/* 005284 0F9A5284 90620001 */  lbu         $v0, 0x1($v1)
/* 005288 0F9A5288 00000000 */  nop
/* 00528C 0F9A528C 304E0004 */  andi        $t6, $v0, 0x4
/* 005290 0F9A5290 15C00012 */  bnez        $t6, .L0F9A52DC
/* 005294 0F9A5294 304C0003 */   andi       $t4, $v0, 0x3
/* 005298 0F9A5298 15800010 */  bnez        $t4, .L0F9A52DC
/* 00529C 0F9A529C 00000000 */   nop
/* 0052A0 0F9A52A0 8F998070 */  lw          $t9, %got(D_FB504F0)($gp)
/* 0052A4 0F9A52A4 00000000 */  nop
/* 0052A8 0F9A52A8 2739005F */  addiu       $t9, $t9, 0x5F
/* 0052AC 0F9A52AC 1079000B */  beq         $v1, $t9, .L0F9A52DC
/* 0052B0 0F9A52B0 00000000 */   nop
/* 0052B4 0F9A52B4 8F888070 */  lw          $t0, %got(D_FB504F0)($gp)
/* 0052B8 0F9A52B8 00000000 */  nop
/* 0052BC 0F9A52BC 25080080 */  addiu       $t0, $t0, 0x80
/* 0052C0 0F9A52C0 0068082B */  sltu        $at, $v1, $t0
/* 0052C4 0F9A52C4 1420FCE3 */  bnez        $at, .L0F9A4654
/* 0052C8 0F9A52C8 00000000 */   nop
/* 0052CC 0F9A52CC 92EA0208 */  lbu         $t2, 0x208($s7)
/* 0052D0 0F9A52D0 00000000 */  nop
/* 0052D4 0F9A52D4 12AAFCDF */  beq         $s5, $t2, .L0F9A4654
/* 0052D8 0F9A52D8 00000000 */   nop
.L0F9A52DC:
/* 0052DC 0F9A52DC 1000004F */  b           .L0F9A541C
/* 0052E0 0F9A52E0 00001025 */   move       $v0, $zero
.L0F9A52E4:
/* 0052E4 0F9A52E4 1000004D */  b           .L0F9A541C
/* 0052E8 0F9A52E8 00001025 */   move       $v0, $zero
.L0F9A52EC:
/* 0052EC 0F9A52EC 28410002 */  slti        $at, $v0, 0x2
.L0F9A52F0:
/* 0052F0 0F9A52F0 14200032 */  bnez        $at, .L0F9A53BC
/* 0052F4 0F9A52F4 2413008F */   addiu      $s3, $zero, 0x8F
/* 0052F8 0F9A52F8 2411008E */  addiu       $s1, $zero, 0x8E
.L0F9A52FC:
/* 0052FC 0F9A52FC 8F848144 */  lw          $a0, %got(_locs)($gp)
/* 005300 0F9A5300 920DFFFF */  lbu         $t5, -0x1($s0)
/* 005304 0F9A5304 92EB0203 */  lbu         $t3, 0x203($s7)
/* 005308 0F9A5308 92E90204 */  lbu         $t1, 0x204($s7)
/* 00530C 0F9A530C 2610FFFF */  addiu       $s0, $s0, -0x1
/* 005310 0F9A5310 8C840000 */  lw          $a0, 0x0($a0)
/* 005314 0F9A5314 29A10080 */  slti        $at, $t5, 0x80
/* 005318 0F9A5318 020B1023 */  subu        $v0, $s0, $t3
/* 00531C 0F9A531C 14200017 */  bnez        $at, .L0F9A537C
/* 005320 0F9A5320 02091823 */   subu       $v1, $s0, $t1
/* 005324 0F9A5324 005E082B */  sltu        $at, $v0, $fp
/* 005328 0F9A5328 14200008 */  bnez        $at, .L0F9A534C
/* 00532C 0F9A532C 007E082B */   sltu       $at, $v1, $fp
/* 005330 0F9A5330 904F0000 */  lbu         $t7, 0x0($v0)
/* 005334 0F9A5334 00000000 */  nop
/* 005338 0F9A5338 162F0004 */  bne         $s1, $t7, .L0F9A534C
/* 00533C 0F9A533C 007E082B */   sltu       $at, $v1, $fp
/* 005340 0F9A5340 1000000E */  b           .L0F9A537C
/* 005344 0F9A5344 00408025 */   move       $s0, $v0
/* 005348 0F9A5348 007E082B */  sltu        $at, $v1, $fp
.L0F9A534C:
/* 00534C 0F9A534C 14200007 */  bnez        $at, .L0F9A536C
/* 005350 0F9A5350 00000000 */   nop
/* 005354 0F9A5354 90780000 */  lbu         $t8, 0x0($v1)
/* 005358 0F9A5358 00000000 */  nop
/* 00535C 0F9A535C 16780003 */  bne         $s3, $t8, .L0F9A536C
/* 005360 0F9A5360 00000000 */   nop
/* 005364 0F9A5364 10000005 */  b           .L0F9A537C
/* 005368 0F9A5368 00608025 */   move       $s0, $v1
.L0F9A536C:
/* 00536C 0F9A536C 92EE0202 */  lbu         $t6, 0x202($s7)
/* 005370 0F9A5370 00000000 */  nop
/* 005374 0F9A5374 020E8023 */  subu        $s0, $s0, $t6
/* 005378 0F9A5378 26100001 */  addiu       $s0, $s0, 0x1
.L0F9A537C:
/* 00537C 0F9A537C 1204000D */  beq         $s0, $a0, .L0F9A53B4
/* 005380 0F9A5380 00000000 */   nop
/* 005384 0F9A5384 8F998014 */  lw          $t9, %got(func_0F9A45F4)($gp)
/* 005388 0F9A5388 02002025 */  move        $a0, $s0
/* 00538C 0F9A538C 273945F4 */  addiu       $t9, $t9, %lo(func_0F9A45F4)
/* 005390 0F9A5390 0320F809 */  jalr        $t9
/* 005394 0F9A5394 02402825 */   move       $a1, $s2
/* 005398 0F9A5398 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00539C 0F9A539C 10400003 */  beqz        $v0, .L0F9A53AC
/* 0053A0 0F9A53A0 03D0082B */   sltu       $at, $fp, $s0
/* 0053A4 0F9A53A4 1000001D */  b           .L0F9A541C
/* 0053A8 0F9A53A8 24020001 */   addiu      $v0, $zero, 0x1
.L0F9A53AC:
/* 0053AC 0F9A53AC 1420FFD3 */  bnez        $at, .L0F9A52FC
/* 0053B0 0F9A53B0 00000000 */   nop
.L0F9A53B4:
/* 0053B4 0F9A53B4 10000019 */  b           .L0F9A541C
/* 0053B8 0F9A53B8 00001025 */   move       $v0, $zero
.L0F9A53BC:
/* 0053BC 0F9A53BC 24110016 */  addiu       $s1, $zero, 0x16
.L0F9A53C0:
/* 0053C0 0F9A53C0 8F8C8144 */  lw          $t4, %got(_locs)($gp)
/* 0053C4 0F9A53C4 2610FFFF */  addiu       $s0, $s0, -0x1
/* 0053C8 0F9A53C8 8D8C0000 */  lw          $t4, 0x0($t4)
/* 0053CC 0F9A53CC 00000000 */  nop
/* 0053D0 0F9A53D0 160C0005 */  bne         $s0, $t4, .L0F9A53E8
/* 0053D4 0F9A53D4 00000000 */   nop
/* 0053D8 0F9A53D8 92590000 */  lbu         $t9, 0x0($s2)
/* 0053DC 0F9A53DC 00000000 */  nop
/* 0053E0 0F9A53E0 1239000E */  beq         $s1, $t9, .L0F9A541C
/* 0053E4 0F9A53E4 00001025 */   move       $v0, $zero
.L0F9A53E8:
/* 0053E8 0F9A53E8 8F998014 */  lw          $t9, %got(func_0F9A45F4)($gp)
/* 0053EC 0F9A53EC 02002025 */  move        $a0, $s0
/* 0053F0 0F9A53F0 273945F4 */  addiu       $t9, $t9, %lo(func_0F9A45F4)
/* 0053F4 0F9A53F4 0320F809 */  jalr        $t9
/* 0053F8 0F9A53F8 02402825 */   move       $a1, $s2
/* 0053FC 0F9A53FC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005400 0F9A5400 10400003 */  beqz        $v0, .L0F9A5410
/* 005404 0F9A5404 03D0082B */   sltu       $at, $fp, $s0
/* 005408 0F9A5408 10000004 */  b           .L0F9A541C
/* 00540C 0F9A540C 24020001 */   addiu      $v0, $zero, 0x1
.L0F9A5410:
/* 005410 0F9A5410 1420FFEB */  bnez        $at, .L0F9A53C0
/* 005414 0F9A5414 00000000 */   nop
/* 005418 0F9A5418 00001025 */  move        $v0, $zero
.L0F9A541C:
/* 00541C 0F9A541C 8FBF003C */  lw          $ra, 0x3C($sp)
/* 005420 0F9A5420 8FB00014 */  lw          $s0, 0x14($sp)
/* 005424 0F9A5424 8FB10018 */  lw          $s1, 0x18($sp)
/* 005428 0F9A5428 8FB2001C */  lw          $s2, 0x1C($sp)
/* 00542C 0F9A542C 8FB30020 */  lw          $s3, 0x20($sp)
/* 005430 0F9A5430 8FB40024 */  lw          $s4, 0x24($sp)
/* 005434 0F9A5434 8FB50028 */  lw          $s5, 0x28($sp)
/* 005438 0F9A5438 8FB6002C */  lw          $s6, 0x2C($sp)
/* 00543C 0F9A543C 8FB70030 */  lw          $s7, 0x30($sp)
/* 005440 0F9A5440 8FBE0038 */  lw          $fp, 0x38($sp)
/* 005444 0F9A5444 03E00008 */  jr          $ra
/* 005448 0F9A5448 27BD0078 */   addiu      $sp, $sp, 0x78
