.section .rodata
glabel STR_0F9B00F0
/* 0090F0 0F9B00F0 */ .asciz "/sbin/sh"
                      .balign 4

glabel STR_0F9B00FC
/* 0090FC 0F9B00FC */ .asciz "sh"
                      .balign 4

glabel STR_0F9B0100
/* 009100 0F9B0100 */ .asciz "-c"
                      .balign 4

glabel STR_0F9B0104
/* 009104 0F9B0104 */ .asciz "w"
                      .balign 4

glabel STR_0F9B0108
/* 009108 0F9B0108 */ .asciz "r"
                      .balign 4
/* 00910C 0F9B010C */ .asciz ""
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel p2open # 13
# _gp_disp: 0x15550
.set noreorder; .cpload $t9; # .set reorder
/* 002F5C 0F9A2F5C 27BDFFC0 */  addiu       $sp, $sp, -0x40
/* 002F60 0F9A2F60 8F9980EC */  lw          $t9, %call16(_pipe)($gp)
/* 002F64 0F9A2F64 AFBF0024 */  sw          $ra, 0x24($sp)
/* 002F68 0F9A2F68 AFA40040 */  sw          $a0, 0x40($sp)
/* 002F6C 0F9A2F6C AFBC0020 */  sw          $gp, 0x20($sp)
/* 002F70 0F9A2F70 AFA50044 */  sw          $a1, 0x44($sp)
/* 002F74 0F9A2F74 0320F809 */  jalr        $t9
/* 002F78 0F9A2F78 27A40038 */   addiu      $a0, $sp, 0x38
/* 002F7C 0F9A2F7C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002F80 0F9A2F80 04400008 */  bltz        $v0, .L0F9A2FA4
/* 002F84 0F9A2F84 00000000 */   nop
/* 002F88 0F9A2F88 8F9980EC */  lw          $t9, %call16(_pipe)($gp)
/* 002F8C 0F9A2F8C 27A40030 */  addiu       $a0, $sp, 0x30
/* 002F90 0F9A2F90 0320F809 */  jalr        $t9
/* 002F94 0F9A2F94 00000000 */   nop
/* 002F98 0F9A2F98 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002F9C 0F9A2F9C 04410004 */  bgez        $v0, .L0F9A2FB0
/* 002FA0 0F9A2FA0 8FAE003C */   lw         $t6, 0x3C($sp)
.L0F9A2FA4:
/* 002FA4 0F9A2FA4 10000097 */  b           .L0F9A3204
/* 002FA8 0F9A2FA8 2402FFFF */   addiu      $v0, $zero, -0x1
/* 002FAC 0F9A2FAC 8FAE003C */  lw          $t6, 0x3C($sp)
.L0F9A2FB0:
/* 002FB0 0F9A2FB0 8FAF0030 */  lw          $t7, 0x30($sp)
/* 002FB4 0F9A2FB4 29C10100 */  slti        $at, $t6, 0x100
/* 002FB8 0F9A2FB8 10200003 */  beqz        $at, .L0F9A2FC8
/* 002FBC 0F9A2FBC 29E10100 */   slti       $at, $t7, 0x100
/* 002FC0 0F9A2FC0 1420001A */  bnez        $at, .L0F9A302C
/* 002FC4 0F9A2FC4 00000000 */   nop
.L0F9A2FC8:
/* 002FC8 0F9A2FC8 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 002FCC 0F9A2FCC 8FA40038 */  lw          $a0, 0x38($sp)
/* 002FD0 0F9A2FD0 0320F809 */  jalr        $t9
/* 002FD4 0F9A2FD4 00000000 */   nop
/* 002FD8 0F9A2FD8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002FDC 0F9A2FDC 8FA4003C */  lw          $a0, 0x3C($sp)
/* 002FE0 0F9A2FE0 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 002FE4 0F9A2FE4 00000000 */  nop
/* 002FE8 0F9A2FE8 0320F809 */  jalr        $t9
/* 002FEC 0F9A2FEC 00000000 */   nop
/* 002FF0 0F9A2FF0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 002FF4 0F9A2FF4 8FA40030 */  lw          $a0, 0x30($sp)
/* 002FF8 0F9A2FF8 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 002FFC 0F9A2FFC 00000000 */  nop
/* 003000 0F9A3000 0320F809 */  jalr        $t9
/* 003004 0F9A3004 00000000 */   nop
/* 003008 0F9A3008 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00300C 0F9A300C 8FA40034 */  lw          $a0, 0x34($sp)
/* 003010 0F9A3010 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 003014 0F9A3014 00000000 */  nop
/* 003018 0F9A3018 0320F809 */  jalr        $t9
/* 00301C 0F9A301C 00000000 */   nop
/* 003020 0F9A3020 8FBC0020 */  lw          $gp, 0x20($sp)
/* 003024 0F9A3024 10000077 */  b           .L0F9A3204
/* 003028 0F9A3028 2402FFFF */   addiu      $v0, $zero, -0x1
.L0F9A302C:
/* 00302C 0F9A302C 8F9980F4 */  lw          $t9, %call16(_fork)($gp)
/* 003030 0F9A3030 00000000 */  nop
/* 003034 0F9A3034 0320F809 */  jalr        $t9
/* 003038 0F9A3038 00000000 */   nop
/* 00303C 0F9A303C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 003040 0F9A3040 14400043 */  bnez        $v0, .L0F9A3150
/* 003044 0F9A3044 00401825 */   move       $v1, $v0
/* 003048 0F9A3048 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 00304C 0F9A304C 8FA4003C */  lw          $a0, 0x3C($sp)
/* 003050 0F9A3050 0320F809 */  jalr        $t9
/* 003054 0F9A3054 AFA2002C */   sw         $v0, 0x2C($sp)
/* 003058 0F9A3058 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00305C 0F9A305C 00002025 */  move        $a0, $zero
/* 003060 0F9A3060 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 003064 0F9A3064 00000000 */  nop
/* 003068 0F9A3068 0320F809 */  jalr        $t9
/* 00306C 0F9A306C 00000000 */   nop
/* 003070 0F9A3070 8FBC0020 */  lw          $gp, 0x20($sp)
/* 003074 0F9A3074 8FA40038 */  lw          $a0, 0x38($sp)
/* 003078 0F9A3078 8F9980C8 */  lw          $t9, %call16(_fcntl)($gp)
/* 00307C 0F9A307C 00002825 */  move        $a1, $zero
/* 003080 0F9A3080 0320F809 */  jalr        $t9
/* 003084 0F9A3084 00003025 */   move       $a2, $zero
/* 003088 0F9A3088 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00308C 0F9A308C 8FA40038 */  lw          $a0, 0x38($sp)
/* 003090 0F9A3090 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 003094 0F9A3094 00000000 */  nop
/* 003098 0F9A3098 0320F809 */  jalr        $t9
/* 00309C 0F9A309C 00000000 */   nop
/* 0030A0 0F9A30A0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0030A4 0F9A30A4 8FA40030 */  lw          $a0, 0x30($sp)
/* 0030A8 0F9A30A8 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 0030AC 0F9A30AC 00000000 */  nop
/* 0030B0 0F9A30B0 0320F809 */  jalr        $t9
/* 0030B4 0F9A30B4 00000000 */   nop
/* 0030B8 0F9A30B8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0030BC 0F9A30BC 24040001 */  addiu       $a0, $zero, 0x1
/* 0030C0 0F9A30C0 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 0030C4 0F9A30C4 00000000 */  nop
/* 0030C8 0F9A30C8 0320F809 */  jalr        $t9
/* 0030CC 0F9A30CC 00000000 */   nop
/* 0030D0 0F9A30D0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0030D4 0F9A30D4 8FA40034 */  lw          $a0, 0x34($sp)
/* 0030D8 0F9A30D8 8F9980C8 */  lw          $t9, %call16(_fcntl)($gp)
/* 0030DC 0F9A30DC 00002825 */  move        $a1, $zero
/* 0030E0 0F9A30E0 0320F809 */  jalr        $t9
/* 0030E4 0F9A30E4 24060001 */   addiu      $a2, $zero, 0x1
/* 0030E8 0F9A30E8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0030EC 0F9A30EC 8FA40034 */  lw          $a0, 0x34($sp)
/* 0030F0 0F9A30F0 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 0030F4 0F9A30F4 00000000 */  nop
/* 0030F8 0F9A30F8 0320F809 */  jalr        $t9
/* 0030FC 0F9A30FC 00000000 */   nop
/* 003100 0F9A3100 8FBC0020 */  lw          $gp, 0x20($sp)
/* 003104 0F9A3104 8FA70040 */  lw          $a3, 0x40($sp)
/* 003108 0F9A3108 8F84804C */  lw          $a0, %got(STR_0F9B00F0)($gp)
/* 00310C 0F9A310C 8F85804C */  lw          $a1, %got(STR_0F9B00FC)($gp)
/* 003110 0F9A3110 8F86804C */  lw          $a2, %got(STR_0F9B0100)($gp)
/* 003114 0F9A3114 8F9980CC */  lw          $t9, %call16(_execl)($gp)
/* 003118 0F9A3118 AFA00010 */  sw          $zero, 0x10($sp)
/* 00311C 0F9A311C 248400F0 */  addiu       $a0, $a0, %lo(STR_0F9B00F0)
/* 003120 0F9A3120 24A500FC */  addiu       $a1, $a1, %lo(STR_0F9B00FC)
/* 003124 0F9A3124 0320F809 */  jalr        $t9
/* 003128 0F9A3128 24C60100 */   addiu      $a2, $a2, %lo(STR_0F9B0100)
/* 00312C 0F9A312C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 003130 0F9A3130 24040001 */  addiu       $a0, $zero, 0x1
/* 003134 0F9A3134 8F9980E0 */  lw          $t9, %call16(_exit)($gp)
/* 003138 0F9A3138 00000000 */  nop
/* 00313C 0F9A313C 0320F809 */  jalr        $t9
/* 003140 0F9A3140 00000000 */   nop
/* 003144 0F9A3144 8FBC0020 */  lw          $gp, 0x20($sp)
/* 003148 0F9A3148 8FA3002C */  lw          $v1, 0x2C($sp)
/* 00314C 0F9A314C 00000000 */  nop
.L0F9A3150:
/* 003150 0F9A3150 2401FFFF */  addiu       $at, $zero, -0x1
/* 003154 0F9A3154 14610003 */  bne         $v1, $at, .L0F9A3164
/* 003158 0F9A3158 00000000 */   nop
/* 00315C 0F9A315C 10000029 */  b           .L0F9A3204
/* 003160 0F9A3160 2402FFFF */   addiu      $v0, $zero, -0x1
.L0F9A3164:
/* 003164 0F9A3164 8F82805C */  lw          $v0, %got(B_F9B0730)($gp)
/* 003168 0F9A3168 8FB8003C */  lw          $t8, 0x3C($sp)
/* 00316C 0F9A316C 24420730 */  addiu       $v0, $v0, %lo(B_F9B0730)
/* 003170 0F9A3170 0018C880 */  sll         $t9, $t8, 2
/* 003174 0F9A3174 00594021 */  addu        $t0, $v0, $t9
/* 003178 0F9A3178 AD030000 */  sw          $v1, 0x0($t0)
/* 00317C 0F9A317C 8FA90030 */  lw          $t1, 0x30($sp)
/* 003180 0F9A3180 00000000 */  nop
/* 003184 0F9A3184 00095080 */  sll         $t2, $t1, 2
/* 003188 0F9A3188 004A5821 */  addu        $t3, $v0, $t2
/* 00318C 0F9A318C AD630000 */  sw          $v1, 0x0($t3)
/* 003190 0F9A3190 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 003194 0F9A3194 8FA40038 */  lw          $a0, 0x38($sp)
/* 003198 0F9A3198 0320F809 */  jalr        $t9
/* 00319C 0F9A319C 00000000 */   nop
/* 0031A0 0F9A31A0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0031A4 0F9A31A4 8FA40034 */  lw          $a0, 0x34($sp)
/* 0031A8 0F9A31A8 8F9980F0 */  lw          $t9, %call16(_close)($gp)
/* 0031AC 0F9A31AC 00000000 */  nop
/* 0031B0 0F9A31B0 0320F809 */  jalr        $t9
/* 0031B4 0F9A31B4 00000000 */   nop
/* 0031B8 0F9A31B8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0031BC 0F9A31BC 8FA4003C */  lw          $a0, 0x3C($sp)
/* 0031C0 0F9A31C0 8F85804C */  lw          $a1, %got(STR_0F9B0104)($gp)
/* 0031C4 0F9A31C4 8F9980D0 */  lw          $t9, %call16(_fdopen)($gp)
/* 0031C8 0F9A31C8 24A50104 */  addiu       $a1, $a1, %lo(STR_0F9B0104)
/* 0031CC 0F9A31CC 0320F809 */  jalr        $t9
/* 0031D0 0F9A31D0 00000000 */   nop
/* 0031D4 0F9A31D4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0031D8 0F9A31D8 8FAC0044 */  lw          $t4, 0x44($sp)
/* 0031DC 0F9A31DC 8F85804C */  lw          $a1, %got(STR_0F9B0108)($gp)
/* 0031E0 0F9A31E0 AD820000 */  sw          $v0, 0x0($t4)
/* 0031E4 0F9A31E4 8F9980D0 */  lw          $t9, %call16(_fdopen)($gp)
/* 0031E8 0F9A31E8 8FA40030 */  lw          $a0, 0x30($sp)
/* 0031EC 0F9A31EC 0320F809 */  jalr        $t9
/* 0031F0 0F9A31F0 24A50108 */   addiu      $a1, $a1, %lo(STR_0F9B0108)
/* 0031F4 0F9A31F4 8FAD0044 */  lw          $t5, 0x44($sp)
/* 0031F8 0F9A31F8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 0031FC 0F9A31FC ADA20004 */  sw          $v0, 0x4($t5)
/* 003200 0F9A3200 00001025 */  move        $v0, $zero
.L0F9A3204:
/* 003204 0F9A3204 8FBF0024 */  lw          $ra, 0x24($sp)
/* 003208 0F9A3208 27BD0040 */  addiu       $sp, $sp, 0x40
/* 00320C 0F9A320C 03E00008 */  jr          $ra
/* 003210 0F9A3210 00000000 */   nop
