.section .rodata
glabel STR_0F9B0114
/* 009114 0F9B0114 */ .asciz ":"
                      .balign 4

.section .late_rodata
glabel jtbl_0F9B0118
/* 009118 0F9B0118 FFFEB044 */ .gpword .L0F9A34E4
/* 00911C 0F9B011C FFFEB050 */ .gpword .L0F9A34F0
/* 009120 0F9B0120 FFFEB05C */ .gpword .L0F9A34FC
/* 009124 0F9B0124 FFFEB0AC */ .gpword .L0F9A354C
/* 009128 0F9B0128 FFFEB068 */ .gpword .L0F9A3508
/* 00912C 0F9B012C FFFEB08C */ .gpword .L0F9A352C
/* 009130 0F9B0130 FFFEB0AC */ .gpword .L0F9A354C
/* 009134 0F9B0134 FFFEB0AC */ .gpword .L0F9A354C
/* 009138 0F9B0138 FFFEB0AC */ .gpword .L0F9A354C
/* 00913C 0F9B013C FFFEB098 */ .gpword .L0F9A3538
/* 009140 0F9B0140 FFFEB0AC */ .gpword .L0F9A354C
/* 009144 0F9B0144 FFFEB0AC */ .gpword .L0F9A354C
/* 009148 0F9B0148 FFFEB0AC */ .gpword .L0F9A354C
/* 00914C 0F9B014C FFFEB0AC */ .gpword .L0F9A354C
/* 009150 0F9B0150 FFFEB074 */ .gpword .L0F9A3514
/* 009154 0F9B0154 FFFEB0AC */ .gpword .L0F9A354C
/* 009158 0F9B0158 FFFEB020 */ .gpword .L0F9A34C0
/* 00915C 0F9B015C FFFEB0A4 */ .gpword .L0F9A3544
/* 009160 0F9B0160 FFFEB0AC */ .gpword .L0F9A354C
/* 009164 0F9B0164 FFFEB080 */ .gpword .L0F9A3520
/* 009168 0F9B0168 FFFEB0AC */ .gpword .L0F9A354C
/* 00916C 0F9B016C FFFEB02C */ .gpword .L0F9A34CC
/* 009170 0F9B0170 FFFEB038 */ .gpword .L0F9A34D8
/* 009174 0F9B0174 00000000 */ .word 0x00000000
/* 009178 0F9B0178 00000000 */ .word 0x00000000
/* 00917C 0F9B017C 00000000 */ .word 0x00000000


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel pathfind # 15
# _gp_disp: 0x15080
.set noreorder; .cpload $t9; # .set reorder
/* 00342C 0F9A342C 27BDFFB0 */  addiu       $sp, $sp, -0x50
/* 003430 0F9A3430 AFB6002C */  sw          $s6, 0x2C($sp)
/* 003434 0F9A3434 AFB50028 */  sw          $s5, 0x28($sp)
/* 003438 0F9A3438 AFB10018 */  sw          $s1, 0x18($sp)
/* 00343C 0F9A343C AFB00014 */  sw          $s0, 0x14($sp)
/* 003440 0F9A3440 00808025 */  move        $s0, $a0
/* 003444 0F9A3444 00A0B025 */  move        $s6, $a1
/* 003448 0F9A3448 AFBF0034 */  sw          $ra, 0x34($sp)
/* 00344C 0F9A344C AFBC0030 */  sw          $gp, 0x30($sp)
/* 003450 0F9A3450 AFB40024 */  sw          $s4, 0x24($sp)
/* 003454 0F9A3454 AFB30020 */  sw          $s3, 0x20($sp)
/* 003458 0F9A3458 AFB2001C */  sw          $s2, 0x1C($sp)
/* 00345C 0F9A345C 00C03825 */  move        $a3, $a2
/* 003460 0F9A3460 00008825 */  move        $s1, $zero
/* 003464 0F9A3464 14C00004 */  bnez        $a2, .L0F9A3478
/* 003468 0F9A3468 0000A825 */   move       $s5, $zero
/* 00346C 0F9A346C 8F87804C */  lw          $a3, %got(RO_F9B0110)($gp)
/* 003470 0F9A3470 00000000 */  nop
/* 003474 0F9A3474 24E70110 */  addiu       $a3, $a3, %lo(RO_F9B0110)
.L0F9A3478:
/* 003478 0F9A3478 90EE0000 */  lbu         $t6, 0x0($a3)
/* 00347C 0F9A347C 00E03025 */  move        $a2, $a3
/* 003480 0F9A3480 11C00038 */  beqz        $t6, .L0F9A3564
/* 003484 0F9A3484 00000000 */   nop
/* 003488 0F9A3488 90E20000 */  lbu         $v0, 0x0($a3)
/* 00348C 0F9A348C 00000000 */  nop
/* 003490 0F9A3490 244FFF9E */  addiu       $t7, $v0, -0x62
.L0F9A3494:
/* 003494 0F9A3494 2DE10017 */  sltiu       $at, $t7, 0x17
/* 003498 0F9A3498 1020002C */  beqz        $at, .L0F9A354C
/* 00349C 0F9A349C 00000000 */   nop
/* 0034A0 0F9A34A0 8F81804C */  lw          $at, %got(jtbl_0F9B0118)($gp)
/* 0034A4 0F9A34A4 000F7880 */  sll         $t7, $t7, 2
/* 0034A8 0F9A34A8 002F0821 */  addu        $at, $at, $t7
/* 0034AC 0F9A34AC 8C2F0118 */  lw          $t7, %lo(jtbl_0F9B0118)($at)
/* 0034B0 0F9A34B0 00000000 */  nop
/* 0034B4 0F9A34B4 01FC7821 */  addu        $t7, $t7, $gp
/* 0034B8 0F9A34B8 01E00008 */  jr          $t7
/* 0034BC 0F9A34BC 00000000 */   nop
.L0F9A34C0:
/* 0034C0 0F9A34C0 36380004 */  ori         $t8, $s1, 0x4
/* 0034C4 0F9A34C4 10000023 */  b           .L0F9A3554
/* 0034C8 0F9A34C8 03008825 */   move       $s1, $t8
.L0F9A34CC:
/* 0034CC 0F9A34CC 36390002 */  ori         $t9, $s1, 0x2
/* 0034D0 0F9A34D0 10000020 */  b           .L0F9A3554
/* 0034D4 0F9A34D4 03208825 */   move       $s1, $t9
.L0F9A34D8:
/* 0034D8 0F9A34D8 36280001 */  ori         $t0, $s1, 0x1
/* 0034DC 0F9A34DC 1000001D */  b           .L0F9A3554
/* 0034E0 0F9A34E0 01008825 */   move       $s1, $t0
.L0F9A34E4:
/* 0034E4 0F9A34E4 36296000 */  ori         $t1, $s1, 0x6000
/* 0034E8 0F9A34E8 1000001A */  b           .L0F9A3554
/* 0034EC 0F9A34EC 01208825 */   move       $s1, $t1
.L0F9A34F0:
/* 0034F0 0F9A34F0 362A2000 */  ori         $t2, $s1, 0x2000
/* 0034F4 0F9A34F4 10000017 */  b           .L0F9A3554
/* 0034F8 0F9A34F8 01408825 */   move       $s1, $t2
.L0F9A34FC:
/* 0034FC 0F9A34FC 362B4000 */  ori         $t3, $s1, 0x4000
/* 003500 0F9A3500 10000014 */  b           .L0F9A3554
/* 003504 0F9A3504 01608825 */   move       $s1, $t3
.L0F9A3508:
/* 003508 0F9A3508 362C8000 */  ori         $t4, $s1, 0x8000
/* 00350C 0F9A350C 10000011 */  b           .L0F9A3554
/* 003510 0F9A3510 01808825 */   move       $s1, $t4
.L0F9A3514:
/* 003514 0F9A3514 362D1000 */  ori         $t5, $s1, 0x1000
/* 003518 0F9A3518 1000000E */  b           .L0F9A3554
/* 00351C 0F9A351C 01A08825 */   move       $s1, $t5
.L0F9A3520:
/* 003520 0F9A3520 362E0800 */  ori         $t6, $s1, 0x800
/* 003524 0F9A3524 1000000B */  b           .L0F9A3554
/* 003528 0F9A3528 01C08825 */   move       $s1, $t6
.L0F9A352C:
/* 00352C 0F9A352C 362F0400 */  ori         $t7, $s1, 0x400
/* 003530 0F9A3530 10000008 */  b           .L0F9A3554
/* 003534 0F9A3534 01E08825 */   move       $s1, $t7
.L0F9A3538:
/* 003538 0F9A3538 36380200 */  ori         $t8, $s1, 0x200
/* 00353C 0F9A353C 10000005 */  b           .L0F9A3554
/* 003540 0F9A3540 03008825 */   move       $s1, $t8
.L0F9A3544:
/* 003544 0F9A3544 10000003 */  b           .L0F9A3554
/* 003548 0F9A3548 24150001 */   addiu      $s5, $zero, 0x1
.L0F9A354C:
/* 00354C 0F9A354C 10000058 */  b           .L0F9A36B0
/* 003550 0F9A3550 00001025 */   move       $v0, $zero
.L0F9A3554:
/* 003554 0F9A3554 90C20001 */  lbu         $v0, 0x1($a2)
/* 003558 0F9A3558 24C60001 */  addiu       $a2, $a2, 0x1
/* 00355C 0F9A355C 1440FFCD */  bnez        $v0, .L0F9A3494
/* 003560 0F9A3560 244FFF9E */   addiu      $t7, $v0, -0x62
.L0F9A3564:
/* 003564 0F9A3564 92D90000 */  lbu         $t9, 0x0($s6)
/* 003568 0F9A3568 2401002F */  addiu       $at, $zero, 0x2F
/* 00356C 0F9A356C 13210007 */  beq         $t9, $at, .L0F9A358C
/* 003570 0F9A3570 2413003A */   addiu      $s3, $zero, 0x3A
/* 003574 0F9A3574 12000005 */  beqz        $s0, .L0F9A358C
/* 003578 0F9A3578 00000000 */   nop
/* 00357C 0F9A357C 92030000 */  lbu         $v1, 0x0($s0)
/* 003580 0F9A3580 00000000 */  nop
/* 003584 0F9A3584 14600006 */  bnez        $v1, .L0F9A35A0
/* 003588 0F9A3588 00000000 */   nop
.L0F9A358C:
/* 00358C 0F9A358C 8F88804C */  lw          $t0, %got(STR_0F9B0114)($gp)
/* 003590 0F9A3590 00000000 */  nop
/* 003594 0F9A3594 25100114 */  addiu       $s0, $t0, %lo(STR_0F9B0114)
/* 003598 0F9A3598 92030000 */  lbu         $v1, 0x0($s0)
/* 00359C 0F9A359C 00000000 */  nop
.L0F9A35A0:
/* 0035A0 0F9A35A0 10600043 */  beqz        $v1, .L0F9A36B0
/* 0035A4 0F9A35A4 00001025 */   move       $v0, $zero
/* 0035A8 0F9A35A8 8F94805C */  lw          $s4, %got(B_F9B0B30)($gp)
/* 0035AC 0F9A35AC 8F92805C */  lw          $s2, %got(B_F9B0F30)($gp)
/* 0035B0 0F9A35B0 26940B30 */  addiu       $s4, $s4, %lo(B_F9B0B30)
/* 0035B4 0F9A35B4 26520F30 */  addiu       $s2, $s2, %lo(B_F9B0F30)
.L0F9A35B8:
/* 0035B8 0F9A35B8 8F81805C */  lw          $at, %got(B_F9B0B30)($gp)
/* 0035BC 0F9A35BC 306200FF */  andi        $v0, $v1, 0xFF
/* 0035C0 0F9A35C0 02803025 */  move        $a2, $s4
/* 0035C4 0F9A35C4 1040000D */  beqz        $v0, .L0F9A35FC
/* 0035C8 0F9A35C8 A0220B30 */   sb         $v0, %lo(B_F9B0B30)($at)
.L0F9A35CC:
/* 0035CC 0F9A35CC 90C90000 */  lbu         $t1, 0x0($a2)
/* 0035D0 0F9A35D0 26100001 */  addiu       $s0, $s0, 0x1
/* 0035D4 0F9A35D4 12690009 */  beq         $s3, $t1, .L0F9A35FC
/* 0035D8 0F9A35D8 00000000 */   nop
/* 0035DC 0F9A35DC 24C60001 */  addiu       $a2, $a2, 0x1
/* 0035E0 0F9A35E0 00D2082B */  sltu        $at, $a2, $s2
/* 0035E4 0F9A35E4 10200005 */  beqz        $at, .L0F9A35FC
/* 0035E8 0F9A35E8 00000000 */   nop
/* 0035EC 0F9A35EC 92020000 */  lbu         $v0, 0x0($s0)
/* 0035F0 0F9A35F0 00000000 */  nop
/* 0035F4 0F9A35F4 1440FFF5 */  bnez        $v0, .L0F9A35CC
/* 0035F8 0F9A35F8 A0C20000 */   sb         $v0, 0x0($a2)
.L0F9A35FC:
/* 0035FC 0F9A35FC 8F9980E4 */  lw          $t9, %call16(strlen)($gp)
/* 003600 0F9A3600 02C02025 */  move        $a0, $s6
/* 003604 0F9A3604 0320F809 */  jalr        $t9
/* 003608 0F9A3608 AFA6004C */   sw         $a2, 0x4C($sp)
/* 00360C 0F9A360C 8FA6004C */  lw          $a2, 0x4C($sp)
/* 003610 0F9A3610 8FBC0030 */  lw          $gp, 0x30($sp)
/* 003614 0F9A3614 00465021 */  addu        $t2, $v0, $a2
/* 003618 0F9A3618 254B0002 */  addiu       $t3, $t2, 0x2
/* 00361C 0F9A361C 0172082B */  sltu        $at, $t3, $s2
/* 003620 0F9A3620 1020001E */  beqz        $at, .L0F9A369C
/* 003624 0F9A3624 02C02825 */   move       $a1, $s6
/* 003628 0F9A3628 10D40004 */  beq         $a2, $s4, .L0F9A363C
/* 00362C 0F9A362C 32270007 */   andi       $a3, $s1, 0x7
/* 003630 0F9A3630 240C002F */  addiu       $t4, $zero, 0x2F
/* 003634 0F9A3634 A0CC0000 */  sb          $t4, 0x0($a2)
/* 003638 0F9A3638 24C60001 */  addiu       $a2, $a2, 0x1
.L0F9A363C:
/* 00363C 0F9A363C A0C00000 */  sb          $zero, 0x0($a2)
/* 003640 0F9A3640 8F9980D4 */  lw          $t9, %call16(strcat)($gp)
/* 003644 0F9A3644 AFA7003C */  sw          $a3, 0x3C($sp)
/* 003648 0F9A3648 0320F809 */  jalr        $t9
/* 00364C 0F9A364C 00C02025 */   move       $a0, $a2
/* 003650 0F9A3650 8FBC0030 */  lw          $gp, 0x30($sp)
/* 003654 0F9A3654 8FA5003C */  lw          $a1, 0x3C($sp)
/* 003658 0F9A3658 8F998090 */  lw          $t9, %call16(_access)($gp)
/* 00365C 0F9A365C 02802025 */  move        $a0, $s4
/* 003660 0F9A3660 0320F809 */  jalr        $t9
/* 003664 0F9A3664 00000000 */   nop
/* 003668 0F9A3668 8FBC0030 */  lw          $gp, 0x30($sp)
/* 00366C 0F9A366C 1440000B */  bnez        $v0, .L0F9A369C
/* 003670 0F9A3670 02802025 */   move       $a0, $s4
/* 003674 0F9A3674 8F998014 */  lw          $t9, %got(func_0F9A36D8)($gp)
/* 003678 0F9A3678 02202825 */  move        $a1, $s1
/* 00367C 0F9A367C 273936D8 */  addiu       $t9, $t9, %lo(func_0F9A36D8)
/* 003680 0F9A3680 0320F809 */  jalr        $t9
/* 003684 0F9A3684 02A03025 */   move       $a2, $s5
/* 003688 0F9A3688 8FBC0030 */  lw          $gp, 0x30($sp)
/* 00368C 0F9A368C 10400003 */  beqz        $v0, .L0F9A369C
/* 003690 0F9A3690 00000000 */   nop
/* 003694 0F9A3694 10000006 */  b           .L0F9A36B0
/* 003698 0F9A3698 02801025 */   move       $v0, $s4
.L0F9A369C:
/* 00369C 0F9A369C 92030000 */  lbu         $v1, 0x0($s0)
/* 0036A0 0F9A36A0 00000000 */  nop
/* 0036A4 0F9A36A4 1460FFC4 */  bnez        $v1, .L0F9A35B8
/* 0036A8 0F9A36A8 00000000 */   nop
/* 0036AC 0F9A36AC 00001025 */  move        $v0, $zero
.L0F9A36B0:
/* 0036B0 0F9A36B0 8FBF0034 */  lw          $ra, 0x34($sp)
/* 0036B4 0F9A36B4 8FB00014 */  lw          $s0, 0x14($sp)
/* 0036B8 0F9A36B8 8FB10018 */  lw          $s1, 0x18($sp)
/* 0036BC 0F9A36BC 8FB2001C */  lw          $s2, 0x1C($sp)
/* 0036C0 0F9A36C0 8FB30020 */  lw          $s3, 0x20($sp)
/* 0036C4 0F9A36C4 8FB40024 */  lw          $s4, 0x24($sp)
/* 0036C8 0F9A36C8 8FB50028 */  lw          $s5, 0x28($sp)
/* 0036CC 0F9A36CC 8FB6002C */  lw          $s6, 0x2C($sp)
/* 0036D0 0F9A36D0 03E00008 */  jr          $ra
/* 0036D4 0F9A36D4 27BD0050 */   addiu      $sp, $sp, 0x50
