.section .late_rodata
glabel jtbl_0F9B0270
/* 009270 0F9B0270 FFFED8E4 */ .gpword .L0F9A5D84
/* 009274 0F9B0274 FFFEDBEC */ .gpword .L0F9A608C
/* 009278 0F9B0278 FFFEDBEC */ .gpword .L0F9A608C
/* 00927C 0F9B027C FFFEDBEC */ .gpword .L0F9A608C
/* 009280 0F9B0280 FFFED5B4 */ .gpword .L0F9A5A54
/* 009284 0F9B0284 FFFED5E8 */ .gpword .L0F9A5A88
/* 009288 0F9B0288 FFFED8B0 */ .gpword .L0F9A5D50
/* 00928C 0F9B028C FFFED87C */ .gpword .L0F9A5D1C
/* 009290 0F9B0290 FFFEDBEC */ .gpword .L0F9A608C
/* 009294 0F9B0294 FFFEDBEC */ .gpword .L0F9A608C
/* 009298 0F9B0298 FFFED868 */ .gpword .L0F9A5D08
/* 00929C 0F9B029C 00000000 */ .word 0x00000000


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel regcmp # 26
# _gp_disp: 0x12D34
.set noreorder; .cpload $t9; # .set reorder
/* 005778 0F9A5778 27BDFEA0 */  addiu       $sp, $sp, -0x160
/* 00577C 0F9A577C 8F818150 */  lw          $at, %got(__sp_)($gp)
/* 005780 0F9A5780 27AE005C */  addiu       $t6, $sp, 0x5C
/* 005784 0F9A5784 AFBF003C */  sw          $ra, 0x3C($sp)
/* 005788 0F9A5788 AFBE0038 */  sw          $fp, 0x38($sp)
/* 00578C 0F9A578C AFBC0034 */  sw          $gp, 0x34($sp)
/* 005790 0F9A5790 AFB70030 */  sw          $s7, 0x30($sp)
/* 005794 0F9A5794 AFB6002C */  sw          $s6, 0x2C($sp)
/* 005798 0F9A5798 AFB50028 */  sw          $s5, 0x28($sp)
/* 00579C 0F9A579C AFB40024 */  sw          $s4, 0x24($sp)
/* 0057A0 0F9A57A0 AFB30020 */  sw          $s3, 0x20($sp)
/* 0057A4 0F9A57A4 AFB2001C */  sw          $s2, 0x1C($sp)
/* 0057A8 0F9A57A8 AFB10018 */  sw          $s1, 0x18($sp)
/* 0057AC 0F9A57AC AFB00014 */  sw          $s0, 0x14($sp)
/* 0057B0 0F9A57B0 AFA40160 */  sw          $a0, 0x160($sp)
/* 0057B4 0F9A57B4 AFA50164 */  sw          $a1, 0x164($sp)
/* 0057B8 0F9A57B8 AFA60168 */  sw          $a2, 0x168($sp)
/* 0057BC 0F9A57BC AFA7016C */  sw          $a3, 0x16C($sp)
/* 0057C0 0F9A57C0 AC2E0000 */  sw          $t6, 0x0($at)
/* 0057C4 0F9A57C4 ADC00000 */  sw          $zero, 0x0($t6)
/* 0057C8 0F9A57C8 8F818154 */  lw          $at, %got(__stmax)($gp)
/* 0057CC 0F9A57CC 8FB90160 */  lw          $t9, 0x160($sp)
/* 0057D0 0F9A57D0 27AF0124 */  addiu       $t7, $sp, 0x124
/* 0057D4 0F9A57D4 27B80164 */  addiu       $t8, $sp, 0x164
/* 0057D8 0F9A57D8 AFB80050 */  sw          $t8, 0x50($sp)
/* 0057DC 0F9A57DC AFA00130 */  sw          $zero, 0x130($sp)
/* 0057E0 0F9A57E0 AFA0012C */  sw          $zero, 0x12C($sp)
/* 0057E4 0F9A57E4 00001825 */  move        $v1, $zero
/* 0057E8 0F9A57E8 13200012 */  beqz        $t9, .L0F9A5834
/* 0057EC 0F9A57EC AC2F0000 */   sw         $t7, 0x0($at)
/* 0057F0 0F9A57F0 AFB9014C */  sw          $t9, 0x14C($sp)
/* 0057F4 0F9A57F4 2410FFFC */  addiu       $s0, $zero, -0x4
.L0F9A57F8:
/* 0057F8 0F9A57F8 8F9980E4 */  lw          $t9, %call16(strlen)($gp)
/* 0057FC 0F9A57FC 8FA4014C */  lw          $a0, 0x14C($sp)
/* 005800 0F9A5800 0320F809 */  jalr        $t9
/* 005804 0F9A5804 AFA30144 */   sw         $v1, 0x144($sp)
/* 005808 0F9A5808 8FA50050 */  lw          $a1, 0x50($sp)
/* 00580C 0F9A580C 8FA30144 */  lw          $v1, 0x144($sp)
/* 005810 0F9A5810 24A80003 */  addiu       $t0, $a1, 0x3
/* 005814 0F9A5814 01102824 */  and         $a1, $t0, $s0
/* 005818 0F9A5818 8CA40000 */  lw          $a0, 0x0($a1)
/* 00581C 0F9A581C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005820 0F9A5820 24A50004 */  addiu       $a1, $a1, 0x4
/* 005824 0F9A5824 AFA50050 */  sw          $a1, 0x50($sp)
/* 005828 0F9A5828 00621821 */  addu        $v1, $v1, $v0
/* 00582C 0F9A582C 1480FFF2 */  bnez        $a0, .L0F9A57F8
/* 005830 0F9A5830 AFA4014C */   sw         $a0, 0x14C($sp)
.L0F9A5834:
/* 005834 0F9A5834 2410FFFC */  addiu       $s0, $zero, -0x4
/* 005838 0F9A5838 27A90167 */  addiu       $t1, $sp, 0x167
/* 00583C 0F9A583C 01301024 */  and         $v0, $t1, $s0
/* 005840 0F9A5840 24520004 */  addiu       $s2, $v0, 0x4
/* 005844 0F9A5844 AFB20050 */  sw          $s2, 0x50($sp)
/* 005848 0F9A5848 8C450000 */  lw          $a1, 0x0($v0)
/* 00584C 0F9A584C 8F9980B4 */  lw          $t9, %call16(malloc)($gp)
/* 005850 0F9A5850 8FB10160 */  lw          $s1, 0x160($sp)
/* 005854 0F9A5854 00032040 */  sll         $a0, $v1, 1
/* 005858 0F9A5858 24840005 */  addiu       $a0, $a0, 0x5
/* 00585C 0F9A585C 0320F809 */  jalr        $t9
/* 005860 0F9A5860 AFA5014C */   sw         $a1, 0x14C($sp)
/* 005864 0F9A5864 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005868 0F9A5868 0040A025 */  move        $s4, $v0
/* 00586C 0F9A586C 14400003 */  bnez        $v0, .L0F9A587C
/* 005870 0F9A5870 AFA20138 */   sw         $v0, 0x138($sp)
/* 005874 0F9A5874 10000224 */  b           .L0F9A6108
/* 005878 0F9A5878 00001025 */   move       $v0, $zero
.L0F9A587C:
/* 00587C 0F9A587C 92300000 */  lbu         $s0, 0x0($s1)
/* 005880 0F9A5880 8FA3014C */  lw          $v1, 0x14C($sp)
/* 005884 0F9A5884 1600000A */  bnez        $s0, .L0F9A58B0
/* 005888 0F9A5888 26310001 */   addiu      $s1, $s1, 0x1
/* 00588C 0F9A588C 10600218 */  beqz        $v1, .L0F9A60F0
/* 005890 0F9A5890 264A0003 */   addiu      $t2, $s2, 0x3
/* 005894 0F9A5894 2401FFFC */  addiu       $at, $zero, -0x4
/* 005898 0F9A5898 01415824 */  and         $t3, $t2, $at
/* 00589C 0F9A589C 256C0004 */  addiu       $t4, $t3, 0x4
/* 0058A0 0F9A58A0 AFAC0050 */  sw          $t4, 0x50($sp)
/* 0058A4 0F9A58A4 8D6D0000 */  lw          $t5, 0x0($t3)
/* 0058A8 0F9A58A8 00608825 */  move        $s1, $v1
/* 0058AC 0F9A58AC AFAD014C */  sw          $t5, 0x14C($sp)
.L0F9A58B0:
/* 0058B0 0F9A58B0 2401005E */  addiu       $at, $zero, 0x5E
/* 0058B4 0F9A58B4 16010005 */  bne         $s0, $at, .L0F9A58CC
/* 0058B8 0F9A58B8 240E0020 */   addiu      $t6, $zero, 0x20
/* 0058BC 0F9A58BC 92300000 */  lbu         $s0, 0x0($s1)
/* 0058C0 0F9A58C0 26310001 */  addiu       $s1, $s1, 0x1
/* 0058C4 0F9A58C4 A04E0000 */  sb          $t6, 0x0($v0)
/* 0058C8 0F9A58C8 24540001 */  addiu       $s4, $v0, 0x1
.L0F9A58CC:
/* 0058CC 0F9A58CC 2401002A */  addiu       $at, $zero, 0x2A
/* 0058D0 0F9A58D0 12010207 */  beq         $s0, $at, .L0F9A60F0
/* 0058D4 0F9A58D4 2401002B */   addiu      $at, $zero, 0x2B
/* 0058D8 0F9A58D8 12010205 */  beq         $s0, $at, .L0F9A60F0
/* 0058DC 0F9A58DC 2401007B */   addiu      $at, $zero, 0x7B
/* 0058E0 0F9A58E0 12010203 */  beq         $s0, $at, .L0F9A60F0
/* 0058E4 0F9A58E4 2631FFFF */   addiu      $s1, $s1, -0x1
/* 0058E8 0F9A58E8 8F848070 */  lw          $a0, %got(D_FB504F0)($gp)
/* 0058EC 0F9A58EC 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 0058F0 0F9A58F0 90840208 */  lbu         $a0, 0x208($a0)
/* 0058F4 0F9A58F4 241E000A */  addiu       $fp, $zero, 0xA
/* 0058F8 0F9A58F8 2417002C */  addiu       $s7, $zero, 0x2C
/* 0058FC 0F9A58FC 2416007D */  addiu       $s6, $zero, 0x7D
.L0F9A5900:
/* 005900 0F9A5900 28810002 */  slti        $at, $a0, 0x2
.L0F9A5904:
/* 005904 0F9A5904 1420000D */  bnez        $at, .L0F9A593C
/* 005908 0F9A5908 27A40058 */   addiu      $a0, $sp, 0x58
/* 00590C 0F9A590C 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005910 0F9A5910 02202825 */  move        $a1, $s1
/* 005914 0F9A5914 0320F809 */  jalr        $t9
/* 005918 0F9A5918 24060005 */   addiu      $a2, $zero, 0x5
/* 00591C 0F9A591C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005920 0F9A5920 2401FFFF */  addiu       $at, $zero, -0x1
/* 005924 0F9A5924 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005928 0F9A5928 104101F1 */  beq         $v0, $at, .L0F9A60F0
/* 00592C 0F9A592C 00000000 */   nop
/* 005930 0F9A5930 8FB00058 */  lw          $s0, 0x58($sp)
/* 005934 0F9A5934 10000003 */  b           .L0F9A5944
/* 005938 0F9A5938 02228821 */   addu       $s1, $s1, $v0
.L0F9A593C:
/* 00593C 0F9A593C 92300000 */  lbu         $s0, 0x0($s1)
/* 005940 0F9A5940 26310001 */  addiu       $s1, $s1, 0x1
.L0F9A5944:
/* 005944 0F9A5944 16000020 */  bnez        $s0, .L0F9A59C8
/* 005948 0F9A5948 2401002A */   addiu      $at, $zero, 0x2A
/* 00594C 0F9A594C 8FAF014C */  lw          $t7, 0x14C($sp)
/* 005950 0F9A5950 8FA20050 */  lw          $v0, 0x50($sp)
/* 005954 0F9A5954 11E0000A */  beqz        $t7, .L0F9A5980
/* 005958 0F9A5958 01E08825 */   move       $s1, $t7
/* 00595C 0F9A595C 24420003 */  addiu       $v0, $v0, 0x3
/* 005960 0F9A5960 2401FFFC */  addiu       $at, $zero, -0x4
/* 005964 0F9A5964 0041C024 */  and         $t8, $v0, $at
/* 005968 0F9A5968 27020004 */  addiu       $v0, $t8, 0x4
/* 00596C 0F9A596C 8C59FFFC */  lw          $t9, -0x4($v0)
/* 005970 0F9A5970 90E40208 */  lbu         $a0, 0x208($a3)
/* 005974 0F9A5974 AFA20050 */  sw          $v0, 0x50($sp)
/* 005978 0F9A5978 1000FFE1 */  b           .L0F9A5900
/* 00597C 0F9A597C AFB9014C */   sw         $t9, 0x14C($sp)
.L0F9A5980:
/* 005980 0F9A5980 8FA20130 */  lw          $v0, 0x130($sp)
/* 005984 0F9A5984 24080034 */  addiu       $t0, $zero, 0x34
/* 005988 0F9A5988 2442FFFF */  addiu       $v0, $v0, -0x1
/* 00598C 0F9A598C 2841000B */  slti        $at, $v0, 0xB
/* 005990 0F9A5990 A2880000 */  sb          $t0, 0x0($s4)
/* 005994 0F9A5994 102001D6 */  beqz        $at, .L0F9A60F0
/* 005998 0F9A5998 26940001 */   addiu      $s4, $s4, 0x1
/* 00599C 0F9A599C 8F898150 */  lw          $t1, %got(__sp_)($gp)
/* 0059A0 0F9A59A0 8FA20138 */  lw          $v0, 0x138($sp)
/* 0059A4 0F9A59A4 8D290000 */  lw          $t1, 0x0($t1)
/* 0059A8 0F9A59A8 02825823 */  subu        $t3, $s4, $v0
/* 0059AC 0F9A59AC 8D2A0000 */  lw          $t2, 0x0($t1)
/* 0059B0 0F9A59B0 00000000 */  nop
/* 0059B4 0F9A59B4 154001CE */  bnez        $t2, .L0F9A60F0
/* 0059B8 0F9A59B8 00000000 */   nop
/* 0059BC 0F9A59BC 8F818158 */  lw          $at, %got(__i_size)($gp)
/* 0059C0 0F9A59C0 100001D1 */  b           .L0F9A6108
/* 0059C4 0F9A59C4 AC2B0000 */   sw         $t3, 0x0($at)
.L0F9A59C8:
/* 0059C8 0F9A59C8 12010006 */  beq         $s0, $at, .L0F9A59E4
/* 0059CC 0F9A59CC 2401007B */   addiu      $at, $zero, 0x7B
/* 0059D0 0F9A59D0 12010004 */  beq         $s0, $at, .L0F9A59E4
/* 0059D4 0F9A59D4 2401002B */   addiu      $at, $zero, 0x2B
/* 0059D8 0F9A59D8 12010003 */  beq         $s0, $at, .L0F9A59E8
/* 0059DC 0F9A59DC 2A01005C */   slti       $at, $s0, 0x5C
/* 0059E0 0F9A59E0 AFB4013C */  sw          $s4, 0x13C($sp)
.L0F9A59E4:
/* 0059E4 0F9A59E4 2A01005C */  slti        $at, $s0, 0x5C
.L0F9A59E8:
/* 0059E8 0F9A59E8 14200007 */  bnez        $at, .L0F9A5A08
/* 0059EC 0F9A59EC 2401005C */   addiu      $at, $zero, 0x5C
/* 0059F0 0F9A59F0 12010074 */  beq         $s0, $at, .L0F9A5BC4
/* 0059F4 0F9A59F4 2401007B */   addiu      $at, $zero, 0x7B
/* 0059F8 0F9A59F8 12010086 */  beq         $s0, $at, .L0F9A5C14
/* 0059FC 0F9A59FC 00002025 */   move       $a0, $zero
/* 005A00 0F9A5A00 100001A3 */  b           .L0F9A6090
/* 005A04 0F9A5A04 90E80208 */   lbu        $t0, 0x208($a3)
.L0F9A5A08:
/* 005A08 0F9A5A08 2A01002F */  slti        $at, $s0, 0x2F
/* 005A0C 0F9A5A0C 14200006 */  bnez        $at, .L0F9A5A28
/* 005A10 0F9A5A10 260DFFDC */   addiu      $t5, $s0, -0x24
/* 005A14 0F9A5A14 2401005B */  addiu       $at, $zero, 0x5B
/* 005A18 0F9A5A18 120100E4 */  beq         $s0, $at, .L0F9A5DAC
/* 005A1C 0F9A5A1C 00000000 */   nop
/* 005A20 0F9A5A20 1000019B */  b           .L0F9A6090
/* 005A24 0F9A5A24 90E80208 */   lbu        $t0, 0x208($a3)
.L0F9A5A28:
/* 005A28 0F9A5A28 2DA1000B */  sltiu       $at, $t5, 0xB
/* 005A2C 0F9A5A2C 10200197 */  beqz        $at, .L0F9A608C
/* 005A30 0F9A5A30 00000000 */   nop
/* 005A34 0F9A5A34 8F81804C */  lw          $at, %got(jtbl_0F9B0270)($gp)
/* 005A38 0F9A5A38 000D6880 */  sll         $t5, $t5, 2
/* 005A3C 0F9A5A3C 002D0821 */  addu        $at, $at, $t5
/* 005A40 0F9A5A40 8C2D0270 */  lw          $t5, %lo(jtbl_0F9B0270)($at)
/* 005A44 0F9A5A44 00000000 */  nop
/* 005A48 0F9A5A48 01BC6821 */  addu        $t5, $t5, $gp
/* 005A4C 0F9A5A4C 01A00008 */  jr          $t5
/* 005A50 0F9A5A50 00000000 */   nop
.L0F9A5A54:
/* 005A54 0F9A5A54 8F998104 */  lw          $t9, %call16(__rpush)($gp)
/* 005A58 0F9A5A58 02802025 */  move        $a0, $s4
/* 005A5C 0F9A5A5C 0320F809 */  jalr        $t9
/* 005A60 0F9A5A60 00000000 */   nop
/* 005A64 0F9A5A64 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005A68 0F9A5A68 240E003C */  addiu       $t6, $zero, 0x3C
/* 005A6C 0F9A5A6C 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005A70 0F9A5A70 1040019F */  beqz        $v0, .L0F9A60F0
/* 005A74 0F9A5A74 00000000 */   nop
/* 005A78 0F9A5A78 A28E0000 */  sb          $t6, 0x0($s4)
/* 005A7C 0F9A5A7C 90E40208 */  lbu         $a0, 0x208($a3)
/* 005A80 0F9A5A80 1000FF9F */  b           .L0F9A5900
/* 005A84 0F9A5A84 26940002 */   addiu      $s4, $s4, 0x2
.L0F9A5A88:
/* 005A88 0F9A5A88 8F998100 */  lw          $t9, %call16(__rpop)($gp)
/* 005A8C 0F9A5A8C 00000000 */  nop
/* 005A90 0F9A5A90 0320F809 */  jalr        $t9
/* 005A94 0F9A5A94 00000000 */   nop
/* 005A98 0F9A5A98 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005A9C 0F9A5A9C 8FA3012C */  lw          $v1, 0x12C($sp)
/* 005AA0 0F9A5AA0 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005AA4 0F9A5AA4 10400192 */  beqz        $v0, .L0F9A60F0
/* 005AA8 0F9A5AA8 00000000 */   nop
/* 005AAC 0F9A5AAC 92300000 */  lbu         $s0, 0x0($s1)
/* 005AB0 0F9A5AB0 24010024 */  addiu       $at, $zero, 0x24
/* 005AB4 0F9A5AB4 16010013 */  bne         $s0, $at, .L0F9A5B04
/* 005AB8 0F9A5AB8 240F000C */   addiu      $t7, $zero, 0xC
/* 005ABC 0F9A5ABC 92300001 */  lbu         $s0, 0x1($s1)
/* 005AC0 0F9A5AC0 8FA30130 */  lw          $v1, 0x130($sp)
/* 005AC4 0F9A5AC4 2A010030 */  slti        $at, $s0, 0x30
/* 005AC8 0F9A5AC8 14200189 */  bnez        $at, .L0F9A60F0
/* 005ACC 0F9A5ACC 26310002 */   addiu      $s1, $s1, 0x2
/* 005AD0 0F9A5AD0 2A01003A */  slti        $at, $s0, 0x3A
/* 005AD4 0F9A5AD4 10200186 */  beqz        $at, .L0F9A60F0
/* 005AD8 0F9A5AD8 24450001 */   addiu      $a1, $v0, 0x1
/* 005ADC 0F9A5ADC A28F0000 */  sb          $t7, 0x0($s4)
/* 005AE0 0F9A5AE0 A0A30000 */  sb          $v1, 0x0($a1)
/* 005AE4 0F9A5AE4 A2830001 */  sb          $v1, 0x1($s4)
/* 005AE8 0F9A5AE8 2618FFD0 */  addiu       $t8, $s0, -0x30
/* 005AEC 0F9A5AEC A2980002 */  sb          $t8, 0x2($s4)
/* 005AF0 0F9A5AF0 24630001 */  addiu       $v1, $v1, 0x1
/* 005AF4 0F9A5AF4 90E40208 */  lbu         $a0, 0x208($a3)
/* 005AF8 0F9A5AF8 26940003 */  addiu       $s4, $s4, 0x3
/* 005AFC 0F9A5AFC 1000FF80 */  b           .L0F9A5900
/* 005B00 0F9A5B00 AFA30130 */   sw         $v1, 0x130($sp)
.L0F9A5B04:
/* 005B04 0F9A5B04 2419002C */  addiu       $t9, $zero, 0x2C
/* 005B08 0F9A5B08 A2830001 */  sb          $v1, 0x1($s4)
/* 005B0C 0F9A5B0C A2990000 */  sb          $t9, 0x0($s4)
/* 005B10 0F9A5B10 24630001 */  addiu       $v1, $v1, 0x1
/* 005B14 0F9A5B14 2401002A */  addiu       $at, $zero, 0x2A
/* 005B18 0F9A5B18 26940002 */  addiu       $s4, $s4, 0x2
/* 005B1C 0F9A5B1C 1201000F */  beq         $s0, $at, .L0F9A5B5C
/* 005B20 0F9A5B20 AFA3012C */   sw         $v1, 0x12C($sp)
/* 005B24 0F9A5B24 2401002B */  addiu       $at, $zero, 0x2B
/* 005B28 0F9A5B28 12010009 */  beq         $s0, $at, .L0F9A5B50
/* 005B2C 0F9A5B2C 24090044 */   addiu      $t1, $zero, 0x44
/* 005B30 0F9A5B30 2401007B */  addiu       $at, $zero, 0x7B
/* 005B34 0F9A5B34 1201000D */  beq         $s0, $at, .L0F9A5B6C
/* 005B38 0F9A5B38 240B0030 */   addiu      $t3, $zero, 0x30
/* 005B3C 0F9A5B3C 24080028 */  addiu       $t0, $zero, 0x28
/* 005B40 0F9A5B40 A0480000 */  sb          $t0, 0x0($v0)
/* 005B44 0F9A5B44 90E40208 */  lbu         $a0, 0x208($a3)
/* 005B48 0F9A5B48 1000FF6E */  b           .L0F9A5904
/* 005B4C 0F9A5B4C 28810002 */   slti       $at, $a0, 0x2
.L0F9A5B50:
/* 005B50 0F9A5B50 A0490000 */  sb          $t1, 0x0($v0)
/* 005B54 0F9A5B54 10000007 */  b           .L0F9A5B74
/* 005B58 0F9A5B58 00009825 */   move       $s3, $zero
.L0F9A5B5C:
/* 005B5C 0F9A5B5C 240A0038 */  addiu       $t2, $zero, 0x38
/* 005B60 0F9A5B60 A04A0000 */  sb          $t2, 0x0($v0)
/* 005B64 0F9A5B64 10000003 */  b           .L0F9A5B74
/* 005B68 0F9A5B68 00009825 */   move       $s3, $zero
.L0F9A5B6C:
/* 005B6C 0F9A5B6C A04B0000 */  sb          $t3, 0x0($v0)
/* 005B70 0F9A5B70 00009825 */  move        $s3, $zero
.L0F9A5B74:
/* 005B74 0F9A5B74 02822023 */  subu        $a0, $s4, $v0
/* 005B78 0F9A5B78 2483FFFE */  addiu       $v1, $a0, -0x2
/* 005B7C 0F9A5B7C 28610100 */  slti        $at, $v1, 0x100
/* 005B80 0F9A5B80 14200006 */  bnez        $at, .L0F9A5B9C
/* 005B84 0F9A5B84 2A610004 */   slti       $at, $s3, 0x4
.L0F9A5B88:
/* 005B88 0F9A5B88 2463FF00 */  addiu       $v1, $v1, -0x100
/* 005B8C 0F9A5B8C 28610100 */  slti        $at, $v1, 0x100
/* 005B90 0F9A5B90 1020FFFD */  beqz        $at, .L0F9A5B88
/* 005B94 0F9A5B94 26730001 */   addiu      $s3, $s3, 0x1
/* 005B98 0F9A5B98 2A610004 */  slti        $at, $s3, 0x4
.L0F9A5B9C:
/* 005B9C 0F9A5B9C 10200154 */  beqz        $at, .L0F9A60F0
/* 005BA0 0F9A5BA0 00000000 */   nop
/* 005BA4 0F9A5BA4 904C0000 */  lbu         $t4, 0x0($v0)
/* 005BA8 0F9A5BA8 24450001 */  addiu       $a1, $v0, 0x1
/* 005BAC 0F9A5BAC 01936825 */  or          $t5, $t4, $s3
/* 005BB0 0F9A5BB0 A04D0000 */  sb          $t5, 0x0($v0)
/* 005BB4 0F9A5BB4 A0A30000 */  sb          $v1, 0x0($a1)
/* 005BB8 0F9A5BB8 90E40208 */  lbu         $a0, 0x208($a3)
/* 005BBC 0F9A5BBC 1000FF51 */  b           .L0F9A5904
/* 005BC0 0F9A5BC0 28810002 */   slti       $at, $a0, 0x2
.L0F9A5BC4:
/* 005BC4 0F9A5BC4 90EE0208 */  lbu         $t6, 0x208($a3)
/* 005BC8 0F9A5BC8 27A40058 */  addiu       $a0, $sp, 0x58
/* 005BCC 0F9A5BCC 29C10002 */  slti        $at, $t6, 0x2
/* 005BD0 0F9A5BD0 1420000D */  bnez        $at, .L0F9A5C08
/* 005BD4 0F9A5BD4 00000000 */   nop
/* 005BD8 0F9A5BD8 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005BDC 0F9A5BDC 02202825 */  move        $a1, $s1
/* 005BE0 0F9A5BE0 0320F809 */  jalr        $t9
/* 005BE4 0F9A5BE4 24060005 */   addiu      $a2, $zero, 0x5
/* 005BE8 0F9A5BE8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005BEC 0F9A5BEC 2401FFFF */  addiu       $at, $zero, -0x1
/* 005BF0 0F9A5BF0 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005BF4 0F9A5BF4 1041013E */  beq         $v0, $at, .L0F9A60F0
/* 005BF8 0F9A5BF8 00000000 */   nop
/* 005BFC 0F9A5BFC 8FB00058 */  lw          $s0, 0x58($sp)
/* 005C00 0F9A5C00 10000122 */  b           .L0F9A608C
/* 005C04 0F9A5C04 02228821 */   addu       $s1, $s1, $v0
.L0F9A5C08:
/* 005C08 0F9A5C08 92300000 */  lbu         $s0, 0x0($s1)
/* 005C0C 0F9A5C0C 1000011F */  b           .L0F9A608C
/* 005C10 0F9A5C10 26310001 */   addiu      $s1, $s1, 0x1
.L0F9A5C14:
/* 005C14 0F9A5C14 8FAF013C */  lw          $t7, 0x13C($sp)
/* 005C18 0F9A5C18 2401003C */  addiu       $at, $zero, 0x3C
/* 005C1C 0F9A5C1C 91E20000 */  lbu         $v0, 0x0($t7)
/* 005C20 0F9A5C20 01E0C825 */  move        $t9, $t7
/* 005C24 0F9A5C24 10410132 */  beq         $v0, $at, .L0F9A60F0
/* 005C28 0F9A5C28 34580003 */   ori        $t8, $v0, 0x3
/* 005C2C 0F9A5C2C 2401000C */  addiu       $at, $zero, 0xC
/* 005C30 0F9A5C30 1041012F */  beq         $v0, $at, .L0F9A60F0
/* 005C34 0F9A5C34 00000000 */   nop
/* 005C38 0F9A5C38 A1F80000 */  sb          $t8, 0x0($t7)
.L0F9A5C3C:
/* 005C3C 0F9A5C3C 92300000 */  lbu         $s0, 0x0($s1)
/* 005C40 0F9A5C40 26310001 */  addiu       $s1, $s1, 0x1
/* 005C44 0F9A5C44 1216012A */  beq         $s0, $s6, .L0F9A60F0
/* 005C48 0F9A5C48 00001825 */   move       $v1, $zero
/* 005C4C 0F9A5C4C 2A010030 */  slti        $at, $s0, 0x30
.L0F9A5C50:
/* 005C50 0F9A5C50 14200127 */  bnez        $at, .L0F9A60F0
/* 005C54 0F9A5C54 2A01003A */   slti       $at, $s0, 0x3A
/* 005C58 0F9A5C58 10200125 */  beqz        $at, .L0F9A60F0
/* 005C5C 0F9A5C5C 00000000 */   nop
/* 005C60 0F9A5C60 007E0019 */  multu       $v1, $fp
/* 005C64 0F9A5C64 26310001 */  addiu       $s1, $s1, 0x1
/* 005C68 0F9A5C68 00004012 */  mflo        $t0
/* 005C6C 0F9A5C6C 01101821 */  addu        $v1, $t0, $s0
/* 005C70 0F9A5C70 9230FFFF */  lbu         $s0, -0x1($s1)
/* 005C74 0F9A5C74 2463FFD0 */  addiu       $v1, $v1, -0x30
/* 005C78 0F9A5C78 12160004 */  beq         $s0, $s6, .L0F9A5C8C
/* 005C7C 0F9A5C7C 28610100 */   slti       $at, $v1, 0x100
/* 005C80 0F9A5C80 1617FFF3 */  bne         $s0, $s7, .L0F9A5C50
/* 005C84 0F9A5C84 2A010030 */   slti       $at, $s0, 0x30
/* 005C88 0F9A5C88 28610100 */  slti        $at, $v1, 0x100
.L0F9A5C8C:
/* 005C8C 0F9A5C8C 10200118 */  beqz        $at, .L0F9A60F0
/* 005C90 0F9A5C90 00801025 */   move       $v0, $a0
/* 005C94 0F9A5C94 A2830000 */  sb          $v1, 0x0($s4)
/* 005C98 0F9A5C98 1617000D */  bne         $s0, $s7, .L0F9A5CD0
/* 005C9C 0F9A5C9C 26940001 */   addiu      $s4, $s4, 0x1
/* 005CA0 0F9A5CA0 14800113 */  bnez        $a0, .L0F9A60F0
/* 005CA4 0F9A5CA4 24840001 */   addiu      $a0, $a0, 0x1
/* 005CA8 0F9A5CA8 92300000 */  lbu         $s0, 0x0($s1)
/* 005CAC 0F9A5CAC 26310001 */  addiu       $s1, $s1, 0x1
/* 005CB0 0F9A5CB0 16160005 */  bne         $s0, $s6, .L0F9A5CC8
/* 005CB4 0F9A5CB4 240900FF */   addiu      $t1, $zero, 0xFF
/* 005CB8 0F9A5CB8 A2890000 */  sb          $t1, 0x0($s4)
/* 005CBC 0F9A5CBC 90E40208 */  lbu         $a0, 0x208($a3)
/* 005CC0 0F9A5CC0 1000FF0F */  b           .L0F9A5900
/* 005CC4 0F9A5CC4 26940001 */   addiu      $s4, $s4, 0x1
.L0F9A5CC8:
/* 005CC8 0F9A5CC8 1000FFDC */  b           .L0F9A5C3C
/* 005CCC 0F9A5CCC 2631FFFF */   addiu      $s1, $s1, -0x1
.L0F9A5CD0:
/* 005CD0 0F9A5CD0 14800004 */  bnez        $a0, .L0F9A5CE4
/* 005CD4 0F9A5CD4 00000000 */   nop
/* 005CD8 0F9A5CD8 A2830000 */  sb          $v1, 0x0($s4)
/* 005CDC 0F9A5CDC 10000007 */  b           .L0F9A5CFC
/* 005CE0 0F9A5CE0 26940001 */   addiu      $s4, $s4, 0x1
.L0F9A5CE4:
/* 005CE4 0F9A5CE4 928AFFFF */  lbu         $t2, -0x1($s4)
/* 005CE8 0F9A5CE8 928BFFFE */  lbu         $t3, -0x2($s4)
/* 005CEC 0F9A5CEC 00000000 */  nop
/* 005CF0 0F9A5CF0 014B082A */  slt         $at, $t2, $t3
/* 005CF4 0F9A5CF4 142000FE */  bnez        $at, .L0F9A60F0
/* 005CF8 0F9A5CF8 00000000 */   nop
.L0F9A5CFC:
/* 005CFC 0F9A5CFC 90E40208 */  lbu         $a0, 0x208($a3)
/* 005D00 0F9A5D00 1000FF00 */  b           .L0F9A5904
/* 005D04 0F9A5D04 28810002 */   slti       $at, $a0, 0x2
.L0F9A5D08:
/* 005D08 0F9A5D08 240C0040 */  addiu       $t4, $zero, 0x40
/* 005D0C 0F9A5D0C A28C0000 */  sb          $t4, 0x0($s4)
/* 005D10 0F9A5D10 90E40208 */  lbu         $a0, 0x208($a3)
/* 005D14 0F9A5D14 1000FEFA */  b           .L0F9A5900
/* 005D18 0F9A5D18 26940001 */   addiu      $s4, $s4, 0x1
.L0F9A5D1C:
/* 005D1C 0F9A5D1C 8FAD013C */  lw          $t5, 0x13C($sp)
/* 005D20 0F9A5D20 2401003C */  addiu       $at, $zero, 0x3C
/* 005D24 0F9A5D24 91A20000 */  lbu         $v0, 0x0($t5)
/* 005D28 0F9A5D28 00000000 */  nop
/* 005D2C 0F9A5D2C 104100F0 */  beq         $v0, $at, .L0F9A60F0
/* 005D30 0F9A5D30 344E0002 */   ori        $t6, $v0, 0x2
/* 005D34 0F9A5D34 2401000C */  addiu       $at, $zero, 0xC
/* 005D38 0F9A5D38 104100ED */  beq         $v0, $at, .L0F9A60F0
/* 005D3C 0F9A5D3C 00000000 */   nop
/* 005D40 0F9A5D40 A1AE0000 */  sb          $t6, 0x0($t5)
/* 005D44 0F9A5D44 90E40208 */  lbu         $a0, 0x208($a3)
/* 005D48 0F9A5D48 1000FEEE */  b           .L0F9A5904
/* 005D4C 0F9A5D4C 28810002 */   slti       $at, $a0, 0x2
.L0F9A5D50:
/* 005D50 0F9A5D50 8FB8013C */  lw          $t8, 0x13C($sp)
/* 005D54 0F9A5D54 2401003C */  addiu       $at, $zero, 0x3C
/* 005D58 0F9A5D58 93020000 */  lbu         $v0, 0x0($t8)
/* 005D5C 0F9A5D5C 00000000 */  nop
/* 005D60 0F9A5D60 104100E3 */  beq         $v0, $at, .L0F9A60F0
/* 005D64 0F9A5D64 34590001 */   ori        $t9, $v0, 0x1
/* 005D68 0F9A5D68 2401000C */  addiu       $at, $zero, 0xC
/* 005D6C 0F9A5D6C 104100E0 */  beq         $v0, $at, .L0F9A60F0
/* 005D70 0F9A5D70 00000000 */   nop
/* 005D74 0F9A5D74 A3190000 */  sb          $t9, 0x0($t8)
/* 005D78 0F9A5D78 90E40208 */  lbu         $a0, 0x208($a3)
/* 005D7C 0F9A5D7C 1000FEE1 */  b           .L0F9A5904
/* 005D80 0F9A5D80 28810002 */   slti       $at, $a0, 0x2
.L0F9A5D84:
/* 005D84 0F9A5D84 92290000 */  lbu         $t1, 0x0($s1)
/* 005D88 0F9A5D88 8FAA014C */  lw          $t2, 0x14C($sp)
/* 005D8C 0F9A5D8C 152000BF */  bnez        $t1, .L0F9A608C
/* 005D90 0F9A5D90 00000000 */   nop
/* 005D94 0F9A5D94 154000BD */  bnez        $t2, .L0F9A608C
/* 005D98 0F9A5D98 240B001C */   addiu      $t3, $zero, 0x1C
/* 005D9C 0F9A5D9C A28B0000 */  sb          $t3, 0x0($s4)
/* 005DA0 0F9A5DA0 90E40208 */  lbu         $a0, 0x208($a3)
/* 005DA4 0F9A5DA4 1000FED6 */  b           .L0F9A5900
/* 005DA8 0F9A5DA8 26940001 */   addiu      $s4, $s4, 0x1
.L0F9A5DAC:
/* 005DAC 0F9A5DAC 90E40208 */  lbu         $a0, 0x208($a3)
/* 005DB0 0F9A5DB0 0000A825 */  move        $s5, $zero
/* 005DB4 0F9A5DB4 28810002 */  slti        $at, $a0, 0x2
/* 005DB8 0F9A5DB8 1420000F */  bnez        $at, .L0F9A5DF8
/* 005DBC 0F9A5DBC 00009025 */   move       $s2, $zero
/* 005DC0 0F9A5DC0 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005DC4 0F9A5DC4 27A40058 */  addiu       $a0, $sp, 0x58
/* 005DC8 0F9A5DC8 02202825 */  move        $a1, $s1
/* 005DCC 0F9A5DCC 0320F809 */  jalr        $t9
/* 005DD0 0F9A5DD0 24060005 */   addiu      $a2, $zero, 0x5
/* 005DD4 0F9A5DD4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005DD8 0F9A5DD8 2401FFFF */  addiu       $at, $zero, -0x1
/* 005DDC 0F9A5DDC 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005DE0 0F9A5DE0 104100C3 */  beq         $v0, $at, .L0F9A60F0
/* 005DE4 0F9A5DE4 02228821 */   addu       $s1, $s1, $v0
/* 005DE8 0F9A5DE8 8FB00058 */  lw          $s0, 0x58($sp)
/* 005DEC 0F9A5DEC 90E40208 */  lbu         $a0, 0x208($a3)
/* 005DF0 0F9A5DF0 10000003 */  b           .L0F9A5E00
/* 005DF4 0F9A5DF4 00009025 */   move       $s2, $zero
.L0F9A5DF8:
/* 005DF8 0F9A5DF8 92300000 */  lbu         $s0, 0x0($s1)
/* 005DFC 0F9A5DFC 26310001 */  addiu       $s1, $s1, 0x1
.L0F9A5E00:
/* 005E00 0F9A5E00 2401005E */  addiu       $at, $zero, 0x5E
/* 005E04 0F9A5E04 16010013 */  bne         $s0, $at, .L0F9A5E54
/* 005E08 0F9A5E08 28810002 */   slti       $at, $a0, 0x2
/* 005E0C 0F9A5E0C 1420000F */  bnez        $at, .L0F9A5E4C
/* 005E10 0F9A5E10 24120001 */   addiu      $s2, $zero, 0x1
/* 005E14 0F9A5E14 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005E18 0F9A5E18 27A40058 */  addiu       $a0, $sp, 0x58
/* 005E1C 0F9A5E1C 02202825 */  move        $a1, $s1
/* 005E20 0F9A5E20 0320F809 */  jalr        $t9
/* 005E24 0F9A5E24 24060005 */   addiu      $a2, $zero, 0x5
/* 005E28 0F9A5E28 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005E2C 0F9A5E2C 2401FFFF */  addiu       $at, $zero, -0x1
/* 005E30 0F9A5E30 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005E34 0F9A5E34 104100AE */  beq         $v0, $at, .L0F9A60F0
/* 005E38 0F9A5E38 00000000 */   nop
/* 005E3C 0F9A5E3C 8FB00058 */  lw          $s0, 0x58($sp)
/* 005E40 0F9A5E40 90E40208 */  lbu         $a0, 0x208($a3)
/* 005E44 0F9A5E44 10000003 */  b           .L0F9A5E54
/* 005E48 0F9A5E48 02228821 */   addu       $s1, $s1, $v0
.L0F9A5E4C:
/* 005E4C 0F9A5E4C 92300000 */  lbu         $s0, 0x0($s1)
/* 005E50 0F9A5E50 26310001 */  addiu       $s1, $s1, 0x1
.L0F9A5E54:
/* 005E54 0F9A5E54 28810002 */  slti        $at, $a0, 0x2
/* 005E58 0F9A5E58 1420000A */  bnez        $at, .L0F9A5E84
/* 005E5C 0F9A5E5C 24130001 */   addiu      $s3, $zero, 0x1
/* 005E60 0F9A5E60 12400005 */  beqz        $s2, .L0F9A5E78
/* 005E64 0F9A5E64 240D0048 */   addiu      $t5, $zero, 0x48
/* 005E68 0F9A5E68 240C004C */  addiu       $t4, $zero, 0x4C
/* 005E6C 0F9A5E6C A28C0000 */  sb          $t4, 0x0($s4)
/* 005E70 0F9A5E70 1000000C */  b           .L0F9A5EA4
/* 005E74 0F9A5E74 26940001 */   addiu      $s4, $s4, 0x1
.L0F9A5E78:
/* 005E78 0F9A5E78 A28D0000 */  sb          $t5, 0x0($s4)
/* 005E7C 0F9A5E7C 10000009 */  b           .L0F9A5EA4
/* 005E80 0F9A5E80 26940001 */   addiu      $s4, $s4, 0x1
.L0F9A5E84:
/* 005E84 0F9A5E84 12400005 */  beqz        $s2, .L0F9A5E9C
/* 005E88 0F9A5E88 240F0050 */   addiu      $t7, $zero, 0x50
/* 005E8C 0F9A5E8C 240E0054 */  addiu       $t6, $zero, 0x54
/* 005E90 0F9A5E90 A28E0000 */  sb          $t6, 0x0($s4)
/* 005E94 0F9A5E94 10000003 */  b           .L0F9A5EA4
/* 005E98 0F9A5E98 26940001 */   addiu      $s4, $s4, 0x1
.L0F9A5E9C:
/* 005E9C 0F9A5E9C A28F0000 */  sb          $t7, 0x0($s4)
/* 005EA0 0F9A5EA0 26940001 */  addiu       $s4, $s4, 0x1
.L0F9A5EA4:
/* 005EA4 0F9A5EA4 26940001 */  addiu       $s4, $s4, 0x1
.L0F9A5EA8:
/* 005EA8 0F9A5EA8 12000091 */  beqz        $s0, .L0F9A60F0
/* 005EAC 0F9A5EAC 2401002D */   addiu      $at, $zero, 0x2D
/* 005EB0 0F9A5EB0 16010039 */  bne         $s0, $at, .L0F9A5F98
/* 005EB4 0F9A5EB4 00000000 */   nop
/* 005EB8 0F9A5EB8 12A00037 */  beqz        $s5, .L0F9A5F98
/* 005EBC 0F9A5EBC 00000000 */   nop
/* 005EC0 0F9A5EC0 90F80208 */  lbu         $t8, 0x208($a3)
/* 005EC4 0F9A5EC4 27A40058 */  addiu       $a0, $sp, 0x58
/* 005EC8 0F9A5EC8 2B010002 */  slti        $at, $t8, 0x2
/* 005ECC 0F9A5ECC 1420000D */  bnez        $at, .L0F9A5F04
/* 005ED0 0F9A5ED0 00000000 */   nop
/* 005ED4 0F9A5ED4 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 005ED8 0F9A5ED8 02202825 */  move        $a1, $s1
/* 005EDC 0F9A5EDC 0320F809 */  jalr        $t9
/* 005EE0 0F9A5EE0 24060005 */   addiu      $a2, $zero, 0x5
/* 005EE4 0F9A5EE4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005EE8 0F9A5EE8 2401FFFF */  addiu       $at, $zero, -0x1
/* 005EEC 0F9A5EEC 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005EF0 0F9A5EF0 1041007F */  beq         $v0, $at, .L0F9A60F0
/* 005EF4 0F9A5EF4 00000000 */   nop
/* 005EF8 0F9A5EF8 8FB00058 */  lw          $s0, 0x58($sp)
/* 005EFC 0F9A5EFC 10000003 */  b           .L0F9A5F0C
/* 005F00 0F9A5F00 02228821 */   addu       $s1, $s1, $v0
.L0F9A5F04:
/* 005F04 0F9A5F04 92300000 */  lbu         $s0, 0x0($s1)
/* 005F08 0F9A5F08 26310001 */  addiu       $s1, $s1, 0x1
.L0F9A5F0C:
/* 005F0C 0F9A5F0C 2401005D */  addiu       $at, $zero, 0x5D
/* 005F10 0F9A5F10 16010005 */  bne         $s0, $at, .L0F9A5F28
/* 005F14 0F9A5F14 2419002D */   addiu      $t9, $zero, 0x2D
/* 005F18 0F9A5F18 A2990000 */  sb          $t9, 0x0($s4)
/* 005F1C 0F9A5F1C 26940001 */  addiu       $s4, $s4, 0x1
/* 005F20 0F9A5F20 10000051 */  b           .L0F9A6068
/* 005F24 0F9A5F24 26730001 */   addiu      $s3, $s3, 0x1
.L0F9A5F28:
/* 005F28 0F9A5F28 90E80208 */  lbu         $t0, 0x208($a3)
/* 005F2C 0F9A5F2C 00000000 */  nop
/* 005F30 0F9A5F30 29010002 */  slti        $at, $t0, 0x2
/* 005F34 0F9A5F34 14200002 */  bnez        $at, .L0F9A5F40
/* 005F38 0F9A5F38 2A010080 */   slti       $at, $s0, 0x80
/* 005F3C 0F9A5F3C 10200007 */  beqz        $at, .L0F9A5F5C
.L0F9A5F40:
/* 005F40 0F9A5F40 02B0082A */   slt        $at, $s5, $s0
/* 005F44 0F9A5F44 10200014 */  beqz        $at, .L0F9A5F98
/* 005F48 0F9A5F48 24090010 */   addiu      $t1, $zero, 0x10
/* 005F4C 0F9A5F4C A2890000 */  sb          $t1, 0x0($s4)
/* 005F50 0F9A5F50 26940001 */  addiu       $s4, $s4, 0x1
/* 005F54 0F9A5F54 10000010 */  b           .L0F9A5F98
/* 005F58 0F9A5F58 26730001 */   addiu      $s3, $s3, 0x1
.L0F9A5F5C:
/* 005F5C 0F9A5F5C 8F998014 */  lw          $t9, %got(func_0F9A56C4)($gp)
/* 005F60 0F9A5F60 02A02025 */  move        $a0, $s5
/* 005F64 0F9A5F64 273956C4 */  addiu       $t9, $t9, %lo(func_0F9A56C4)
/* 005F68 0F9A5F68 0320F809 */  jalr        $t9
/* 005F6C 0F9A5F6C 02002825 */   move       $a1, $s0
/* 005F70 0F9A5F70 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005F74 0F9A5F74 02B0082A */  slt         $at, $s5, $s0
/* 005F78 0F9A5F78 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 005F7C 0F9A5F7C 10400006 */  beqz        $v0, .L0F9A5F98
/* 005F80 0F9A5F80 00000000 */   nop
/* 005F84 0F9A5F84 10200004 */  beqz        $at, .L0F9A5F98
/* 005F88 0F9A5F88 240A0010 */   addiu      $t2, $zero, 0x10
/* 005F8C 0F9A5F8C A28A0000 */  sb          $t2, 0x0($s4)
/* 005F90 0F9A5F90 26940001 */  addiu       $s4, $s4, 0x1
/* 005F94 0F9A5F94 26730001 */  addiu       $s3, $s3, 0x1
.L0F9A5F98:
/* 005F98 0F9A5F98 90EB0208 */  lbu         $t3, 0x208($a3)
/* 005F9C 0F9A5F9C 0200A825 */  move        $s5, $s0
/* 005FA0 0F9A5FA0 29610002 */  slti        $at, $t3, 0x2
/* 005FA4 0F9A5FA4 1420000A */  bnez        $at, .L0F9A5FD0
/* 005FA8 0F9A5FA8 2A010080 */   slti       $at, $s0, 0x80
/* 005FAC 0F9A5FAC 14200008 */  bnez        $at, .L0F9A5FD0
/* 005FB0 0F9A5FB0 2A010100 */   slti       $at, $s0, 0x100
/* 005FB4 0F9A5FB4 1020000A */  beqz        $at, .L0F9A5FE0
/* 005FB8 0F9A5FB8 00F06021 */   addu       $t4, $a3, $s0
/* 005FBC 0F9A5FBC 918D0001 */  lbu         $t5, 0x1($t4)
/* 005FC0 0F9A5FC0 00000000 */  nop
/* 005FC4 0F9A5FC4 31AE0020 */  andi        $t6, $t5, 0x20
/* 005FC8 0F9A5FC8 11C00005 */  beqz        $t6, .L0F9A5FE0
/* 005FCC 0F9A5FCC 00000000 */   nop
.L0F9A5FD0:
/* 005FD0 0F9A5FD0 A2900000 */  sb          $s0, 0x0($s4)
/* 005FD4 0F9A5FD4 26940001 */  addiu       $s4, $s4, 0x1
/* 005FD8 0F9A5FD8 1000000D */  b           .L0F9A6010
/* 005FDC 0F9A5FDC 26730001 */   addiu      $s3, $s3, 0x1
.L0F9A5FE0:
/* 005FE0 0F9A5FE0 8F998080 */  lw          $t9, %call16(wctomb)($gp)
/* 005FE4 0F9A5FE4 02809025 */  move        $s2, $s4
/* 005FE8 0F9A5FE8 02802025 */  move        $a0, $s4
/* 005FEC 0F9A5FEC 0320F809 */  jalr        $t9
/* 005FF0 0F9A5FF0 02002825 */   move       $a1, $s0
/* 005FF4 0F9A5FF4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 005FF8 0F9A5FF8 2401FFFF */  addiu       $at, $zero, -0x1
/* 005FFC 0F9A5FFC 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 006000 0F9A6000 1041003B */  beq         $v0, $at, .L0F9A60F0
/* 006004 0F9A6004 0282A021 */   addu       $s4, $s4, $v0
/* 006008 0F9A6008 02927823 */  subu        $t7, $s4, $s2
/* 00600C 0F9A600C 026F9821 */  addu        $s3, $s3, $t7
.L0F9A6010:
/* 006010 0F9A6010 90F80208 */  lbu         $t8, 0x208($a3)
/* 006014 0F9A6014 27A40058 */  addiu       $a0, $sp, 0x58
/* 006018 0F9A6018 2B010002 */  slti        $at, $t8, 0x2
/* 00601C 0F9A601C 1420000D */  bnez        $at, .L0F9A6054
/* 006020 0F9A6020 00000000 */   nop
/* 006024 0F9A6024 8F99807C */  lw          $t9, %call16(mbtowc)($gp)
/* 006028 0F9A6028 02202825 */  move        $a1, $s1
/* 00602C 0F9A602C 0320F809 */  jalr        $t9
/* 006030 0F9A6030 24060005 */   addiu      $a2, $zero, 0x5
/* 006034 0F9A6034 8FBC0034 */  lw          $gp, 0x34($sp)
/* 006038 0F9A6038 2401FFFF */  addiu       $at, $zero, -0x1
/* 00603C 0F9A603C 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 006040 0F9A6040 1041002B */  beq         $v0, $at, .L0F9A60F0
/* 006044 0F9A6044 00000000 */   nop
/* 006048 0F9A6048 8FB00058 */  lw          $s0, 0x58($sp)
/* 00604C 0F9A604C 10000003 */  b           .L0F9A605C
/* 006050 0F9A6050 02228821 */   addu       $s1, $s1, $v0
.L0F9A6054:
/* 006054 0F9A6054 92300000 */  lbu         $s0, 0x0($s1)
/* 006058 0F9A6058 26310001 */  addiu       $s1, $s1, 0x1
.L0F9A605C:
/* 00605C 0F9A605C 2401005D */  addiu       $at, $zero, 0x5D
/* 006060 0F9A6060 1601FF91 */  bne         $s0, $at, .L0F9A5EA8
/* 006064 0F9A6064 00000000 */   nop
.L0F9A6068:
/* 006068 0F9A6068 2A610101 */  slti        $at, $s3, 0x101
/* 00606C 0F9A606C 10200020 */  beqz        $at, .L0F9A60F0
/* 006070 0F9A6070 00000000 */   nop
/* 006074 0F9A6074 8FB9013C */  lw          $t9, 0x13C($sp)
/* 006078 0F9A6078 00000000 */  nop
/* 00607C 0F9A607C A3330001 */  sb          $s3, 0x1($t9)
/* 006080 0F9A6080 90E40208 */  lbu         $a0, 0x208($a3)
/* 006084 0F9A6084 1000FE1F */  b           .L0F9A5904
/* 006088 0F9A6088 28810002 */   slti       $at, $a0, 0x2
.L0F9A608C:
/* 00608C 0F9A608C 90E80208 */  lbu         $t0, 0x208($a3)
.L0F9A6090:
/* 006090 0F9A6090 24090014 */  addiu       $t1, $zero, 0x14
/* 006094 0F9A6094 29010002 */  slti        $at, $t0, 0x2
/* 006098 0F9A6098 14200003 */  bnez        $at, .L0F9A60A8
/* 00609C 0F9A609C 2A010080 */   slti       $at, $s0, 0x80
/* 0060A0 0F9A60A0 10200005 */  beqz        $at, .L0F9A60B8
/* 0060A4 0F9A60A4 240A0024 */   addiu      $t2, $zero, 0x24
.L0F9A60A8:
/* 0060A8 0F9A60A8 A2890000 */  sb          $t1, 0x0($s4)
/* 0060AC 0F9A60AC A2900001 */  sb          $s0, 0x1($s4)
/* 0060B0 0F9A60B0 1000000C */  b           .L0F9A60E4
/* 0060B4 0F9A60B4 26940002 */   addiu      $s4, $s4, 0x2
.L0F9A60B8:
/* 0060B8 0F9A60B8 A28A0000 */  sb          $t2, 0x0($s4)
/* 0060BC 0F9A60BC 8F998080 */  lw          $t9, %call16(wctomb)($gp)
/* 0060C0 0F9A60C0 26940001 */  addiu       $s4, $s4, 0x1
/* 0060C4 0F9A60C4 02802025 */  move        $a0, $s4
/* 0060C8 0F9A60C8 0320F809 */  jalr        $t9
/* 0060CC 0F9A60CC 02002825 */   move       $a1, $s0
/* 0060D0 0F9A60D0 8FBC0034 */  lw          $gp, 0x34($sp)
/* 0060D4 0F9A60D4 2401FFFF */  addiu       $at, $zero, -0x1
/* 0060D8 0F9A60D8 8F878070 */  lw          $a3, %got(D_FB504F0)($gp)
/* 0060DC 0F9A60DC 10410004 */  beq         $v0, $at, .L0F9A60F0
/* 0060E0 0F9A60E0 0282A021 */   addu       $s4, $s4, $v0
.L0F9A60E4:
/* 0060E4 0F9A60E4 90E40208 */  lbu         $a0, 0x208($a3)
/* 0060E8 0F9A60E8 1000FE06 */  b           .L0F9A5904
/* 0060EC 0F9A60EC 28810002 */   slti       $at, $a0, 0x2
.L0F9A60F0:
/* 0060F0 0F9A60F0 8F9980C0 */  lw          $t9, %call16(free)($gp)
/* 0060F4 0F9A60F4 8FA40138 */  lw          $a0, 0x138($sp)
/* 0060F8 0F9A60F8 0320F809 */  jalr        $t9
/* 0060FC 0F9A60FC 00000000 */   nop
/* 006100 0F9A6100 8FBC0034 */  lw          $gp, 0x34($sp)
/* 006104 0F9A6104 00001025 */  move        $v0, $zero
.L0F9A6108:
/* 006108 0F9A6108 8FBF003C */  lw          $ra, 0x3C($sp)
/* 00610C 0F9A610C 8FB00014 */  lw          $s0, 0x14($sp)
/* 006110 0F9A6110 8FB10018 */  lw          $s1, 0x18($sp)
/* 006114 0F9A6114 8FB2001C */  lw          $s2, 0x1C($sp)
/* 006118 0F9A6118 8FB30020 */  lw          $s3, 0x20($sp)
/* 00611C 0F9A611C 8FB40024 */  lw          $s4, 0x24($sp)
/* 006120 0F9A6120 8FB50028 */  lw          $s5, 0x28($sp)
/* 006124 0F9A6124 8FB6002C */  lw          $s6, 0x2C($sp)
/* 006128 0F9A6128 8FB70030 */  lw          $s7, 0x30($sp)
/* 00612C 0F9A612C 8FBE0038 */  lw          $fp, 0x38($sp)
/* 006130 0F9A6130 03E00008 */  jr          $ra
/* 006134 0F9A6134 27BD0160 */   addiu      $sp, $sp, 0x160
