/* Generated by spimdisasm 1.9.1 */

# static variable
glabel _ftext # 0
/* 002A00 00402A00 03E00008 */  jr          $ra
/* 002A04 00402A04 00000000 */   nop
/* 002A08 00402A08 00000000 */  nop
/* 002A0C 00402A0C 00000000 */  nop
