/* Generated by spimdisasm 1.9.1 */

glabel bcopy # 65
/* 00EC4C 0040EC4C 0006102A */  slt         $v0, $zero, $a2
/* 00EC50 0040EC50 10400008 */  beqz        $v0, .L0040EC74
/* 00EC54 0040EC54 24C6FFFF */   addiu      $a2, $a2, -0x1
.L0040EC58:
/* 00EC58 0040EC58 908E0000 */  lbu         $t6, 0x0($a0)
/* 00EC5C 0040EC5C 0006102A */  slt         $v0, $zero, $a2
/* 00EC60 0040EC60 24C6FFFF */  addiu       $a2, $a2, -0x1
/* 00EC64 0040EC64 24A50001 */  addiu       $a1, $a1, 0x1
/* 00EC68 0040EC68 24840001 */  addiu       $a0, $a0, 0x1
/* 00EC6C 0040EC6C 1440FFFA */  bnez        $v0, .L0040EC58
/* 00EC70 0040EC70 A0AEFFFF */   sb         $t6, -0x1($a1)
.L0040EC74:
/* 00EC74 0040EC74 03E00008 */  jr          $ra
/* 00EC78 0040EC78 00000000 */   nop
