.section .rodata
glabel STR_100015B4
/* 0135B4 100015B4 */ .asciz "once"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel do_pragma # 27
# _gp_disp: 0xFC006EC
.set noreorder; .cpload $t9; # .set reorder
/* 00A140 0040A140 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 00A144 0040A144 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00A148 0040A148 AFBC0018 */  sw          $gp, 0x18($sp)
/* 00A14C 0040A14C AFA50024 */  sw          $a1, 0x24($sp)
/* 00A150 0040A150 90820000 */  lbu         $v0, 0x0($a0)
/* 00A154 0040A154 24030020 */  addiu       $v1, $zero, 0x20
/* 00A158 0040A158 10620003 */  beq         $v1, $v0, .L0040A168
/* 00A15C 0040A15C 24050009 */   addiu      $a1, $zero, 0x9
/* 00A160 0040A160 14A20007 */  bne         $a1, $v0, .L0040A180
/* 00A164 0040A164 00000000 */   nop
.L0040A168:
/* 00A168 0040A168 90820001 */  lbu         $v0, 0x1($a0)
/* 00A16C 0040A16C 24050009 */  addiu       $a1, $zero, 0x9
/* 00A170 0040A170 1062FFFD */  beq         $v1, $v0, .L0040A168
/* 00A174 0040A174 24840001 */   addiu      $a0, $a0, 0x1
/* 00A178 0040A178 10A2FFFB */  beq         $a1, $v0, .L0040A168
/* 00A17C 0040A17C 00000000 */   nop
.L0040A180:
/* 00A180 0040A180 8F85804C */  lw          $a1, %got(STR_100015B4)($gp)
/* 00A184 0040A184 8F998090 */  lw          $t9, %call16(strncmp)($gp)
/* 00A188 0040A188 24060004 */  addiu       $a2, $zero, 0x4
/* 00A18C 0040A18C 0320F809 */  jalr        $t9
/* 00A190 0040A190 24A515B4 */   addiu      $a1, $a1, %lo(STR_100015B4)
/* 00A194 0040A194 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A198 0040A198 14400008 */  bnez        $v0, .L0040A1BC
/* 00A19C 0040A19C 8FBF001C */   lw         $ra, 0x1C($sp)
/* 00A1A0 0040A1A0 8F998194 */  lw          $t9, %call16(do_once)($gp)
/* 00A1A4 0040A1A4 00000000 */  nop
/* 00A1A8 0040A1A8 0320F809 */  jalr        $t9
/* 00A1AC 0040A1AC 00000000 */   nop
/* 00A1B0 0040A1B0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A1B4 0040A1B4 00000000 */  nop
/* 00A1B8 0040A1B8 8FBF001C */  lw          $ra, 0x1C($sp)
.L0040A1BC:
/* 00A1BC 0040A1BC 27BD0020 */  addiu       $sp, $sp, 0x20
/* 00A1C0 0040A1C0 03E00008 */  jr          $ra
/* 00A1C4 0040A1C4 00000000 */   nop
