.section .rodata
glabel STR_100015EC
/* 0135EC 100015EC */ .asciz "ANSI C does not allow #sccs"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel do_sccs # 29
# _gp_disp: 0xFC005EC
.set noreorder; .cpload $t9; # .set reorder
/* 00A240 0040A240 8F8E8324 */  lw          $t6, %got(pedantic)($gp)
/* 00A244 0040A244 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 00A248 0040A248 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00A24C 0040A24C AFBF001C */  sw          $ra, 0x1C($sp)
/* 00A250 0040A250 11C00008 */  beqz        $t6, .L0040A274
/* 00A254 0040A254 AFBC0018 */   sw         $gp, 0x18($sp)
/* 00A258 0040A258 8F84804C */  lw          $a0, %got(STR_100015EC)($gp)
/* 00A25C 0040A25C 8F9981E4 */  lw          $t9, %call16(error)($gp)
/* 00A260 0040A260 248415EC */  addiu       $a0, $a0, %lo(STR_100015EC)
/* 00A264 0040A264 0320F809 */  jalr        $t9
/* 00A268 0040A268 00000000 */   nop
/* 00A26C 0040A26C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A270 0040A270 00000000 */  nop
.L0040A274:
/* 00A274 0040A274 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00A278 0040A278 27BD0020 */  addiu       $sp, $sp, 0x20
/* 00A27C 0040A27C 03E00008 */  jr          $ra
/* 00A280 0040A280 00000000 */   nop
