.section .rodata
glabel STR_100019CC
/* 0139CC 100019CC */ .asciz "%s:%d: "
                      .balign 4

glabel STR_100019D4
/* 0139D4 100019D4 */ .asciz "\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel error_with_line # 49
# _gp_disp: 0xFBFCD80
.set noreorder; .cpload $t9; # .set reorder
/* 00DAAC 0040DAAC 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 00DAB0 0040DAB0 8F83829C */  lw          $v1, %got(indepth)($gp)
/* 00DAB4 0040DAB4 AFBF0024 */  sw          $ra, 0x24($sp)
/* 00DAB8 0040DAB8 8C630000 */  lw          $v1, 0x0($v1)
/* 00DABC 0040DABC AFBC0020 */  sw          $gp, 0x20($sp)
/* 00DAC0 0040DAC0 AFA40028 */  sw          $a0, 0x28($sp)
/* 00DAC4 0040DAC4 AFA5002C */  sw          $a1, 0x2C($sp)
/* 00DAC8 0040DAC8 AFA60030 */  sw          $a2, 0x30($sp)
/* 00DACC 0040DACC AFA70034 */  sw          $a3, 0x34($sp)
/* 00DAD0 0040DAD0 04600010 */  bltz        $v1, .L0040DB14
/* 00DAD4 0040DAD4 00004025 */   move       $t0, $zero
/* 00DAD8 0040DAD8 000370C0 */  sll         $t6, $v1, 3
/* 00DADC 0040DADC 01C37021 */  addu        $t6, $t6, $v1
/* 00DAE0 0040DAE0 8F838340 */  lw          $v1, %got(instack)($gp)
/* 00DAE4 0040DAE4 000E7080 */  sll         $t6, $t6, 2
/* 00DAE8 0040DAE8 01C31021 */  addu        $v0, $t6, $v1
.L0040DAEC:
/* 00DAEC 0040DAEC 8C580000 */  lw          $t8, 0x0($v0)
/* 00DAF0 0040DAF0 00000000 */  nop
/* 00DAF4 0040DAF4 13000003 */  beqz        $t8, .L0040DB04
/* 00DAF8 0040DAF8 00000000 */   nop
/* 00DAFC 0040DAFC 10000005 */  b           .L0040DB14
/* 00DB00 0040DB00 00404025 */   move       $t0, $v0
.L0040DB04:
/* 00DB04 0040DB04 2442FFDC */  addiu       $v0, $v0, -0x24
/* 00DB08 0040DB08 0043082B */  sltu        $at, $v0, $v1
/* 00DB0C 0040DB0C 1020FFF7 */  beqz        $at, .L0040DAEC
/* 00DB10 0040DB10 00000000 */   nop
.L0040DB14:
/* 00DB14 0040DB14 1100000C */  beqz        $t0, .L0040DB48
/* 00DB18 0040DB18 8FB90038 */   lw         $t9, 0x38($sp)
/* 00DB1C 0040DB1C 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00DB20 0040DB20 8F85804C */  lw          $a1, %got(STR_100019CC)($gp)
/* 00DB24 0040DB24 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00DB28 0040DB28 8D060000 */  lw          $a2, 0x0($t0)
/* 00DB2C 0040DB2C 8FA70028 */  lw          $a3, 0x28($sp)
/* 00DB30 0040DB30 24840020 */  addiu       $a0, $a0, 0x20
/* 00DB34 0040DB34 0320F809 */  jalr        $t9
/* 00DB38 0040DB38 24A519CC */   addiu      $a1, $a1, %lo(STR_100019CC)
/* 00DB3C 0040DB3C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DB40 0040DB40 00000000 */  nop
/* 00DB44 0040DB44 8FB90038 */  lw          $t9, 0x38($sp)
.L0040DB48:
/* 00DB48 0040DB48 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00DB4C 0040DB4C AFB90010 */  sw          $t9, 0x10($sp)
/* 00DB50 0040DB50 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00DB54 0040DB54 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00DB58 0040DB58 8FA60030 */  lw          $a2, 0x30($sp)
/* 00DB5C 0040DB5C 8FA70034 */  lw          $a3, 0x34($sp)
/* 00DB60 0040DB60 0320F809 */  jalr        $t9
/* 00DB64 0040DB64 24840020 */   addiu      $a0, $a0, 0x20
/* 00DB68 0040DB68 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DB6C 0040DB6C 00000000 */  nop
/* 00DB70 0040DB70 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00DB74 0040DB74 8F85804C */  lw          $a1, %got(STR_100019D4)($gp)
/* 00DB78 0040DB78 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00DB7C 0040DB7C 24840020 */  addiu       $a0, $a0, 0x20
/* 00DB80 0040DB80 0320F809 */  jalr        $t9
/* 00DB84 0040DB84 24A519D4 */   addiu      $a1, $a1, %lo(STR_100019D4)
/* 00DB88 0040DB88 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DB8C 0040DB8C 8FBF0024 */  lw          $ra, 0x24($sp)
/* 00DB90 0040DB90 8F8382C8 */  lw          $v1, %got(errors)($gp)
/* 00DB94 0040DB94 00001025 */  move        $v0, $zero
/* 00DB98 0040DB98 8C690000 */  lw          $t1, 0x0($v1)
/* 00DB9C 0040DB9C 27BD0028 */  addiu       $sp, $sp, 0x28
/* 00DBA0 0040DBA0 252A0001 */  addiu       $t2, $t1, 0x1
/* 00DBA4 0040DBA4 03E00008 */  jr          $ra
/* 00DBA8 0040DBA8 AC6A0000 */   sw         $t2, 0x0($v1)
