.section .rodata
glabel STR_10001A9C
/* 013A9C 10001A9C */ .asciz "%s: "
                      .balign 4

glabel STR_10001AA4
/* 013AA4 10001AA4 */ .asciz "\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel fatal # 67
# _gp_disp: 0xFBFBB64
.set noreorder; .cpload $t9; # .set reorder
/* 00ECC8 0040ECC8 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 00ECCC 0040ECCC 8F868308 */  lw          $a2, %got(progname)($gp)
/* 00ECD0 0040ECD0 AFA40020 */  sw          $a0, 0x20($sp)
/* 00ECD4 0040ECD4 AFA50024 */  sw          $a1, 0x24($sp)
/* 00ECD8 0040ECD8 8F85804C */  lw          $a1, %got(STR_10001A9C)($gp)
/* 00ECDC 0040ECDC 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00ECE0 0040ECE0 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00ECE4 0040ECE4 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00ECE8 0040ECE8 8CC60000 */  lw          $a2, 0x0($a2)
/* 00ECEC 0040ECEC AFBC0018 */  sw          $gp, 0x18($sp)
/* 00ECF0 0040ECF0 24A51A9C */  addiu       $a1, $a1, %lo(STR_10001A9C)
/* 00ECF4 0040ECF4 0320F809 */  jalr        $t9
/* 00ECF8 0040ECF8 24840020 */   addiu      $a0, $a0, 0x20
/* 00ECFC 0040ECFC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00ED00 0040ED00 8FA50020 */  lw          $a1, 0x20($sp)
/* 00ED04 0040ED04 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00ED08 0040ED08 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00ED0C 0040ED0C 8FA60024 */  lw          $a2, 0x24($sp)
/* 00ED10 0040ED10 0320F809 */  jalr        $t9
/* 00ED14 0040ED14 24840020 */   addiu      $a0, $a0, 0x20
/* 00ED18 0040ED18 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00ED1C 0040ED1C 00000000 */  nop
/* 00ED20 0040ED20 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00ED24 0040ED24 8F85804C */  lw          $a1, %got(STR_10001AA4)($gp)
/* 00ED28 0040ED28 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00ED2C 0040ED2C 24840020 */  addiu       $a0, $a0, 0x20
/* 00ED30 0040ED30 0320F809 */  jalr        $t9
/* 00ED34 0040ED34 24A51AA4 */   addiu      $a1, $a1, %lo(STR_10001AA4)
/* 00ED38 0040ED38 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00ED3C 0040ED3C 24040021 */  addiu       $a0, $zero, 0x21
/* 00ED40 0040ED40 8F998108 */  lw          $t9, %call16(exit)($gp)
/* 00ED44 0040ED44 00000000 */  nop
/* 00ED48 0040ED48 0320F809 */  jalr        $t9
/* 00ED4C 0040ED4C 00000000 */   nop
/* 00ED50 0040ED50 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00ED54 0040ED54 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00ED58 0040ED58 03E00008 */  jr          $ra
/* 00ED5C 0040ED5C 27BD0020 */   addiu      $sp, $sp, 0x20
