/* Generated by spimdisasm 1.9.1 */

glabel initialize_char_syntax # 59
# _gp_disp: 0xFBFC1CC
.set noreorder; .cpload $t9; # .set reorder
/* 00E660 0040E660 8F83834C */  lw          $v1, %got(is_idchar)($gp)
/* 00E664 0040E664 8F848350 */  lw          $a0, %got(is_idstart)($gp)
/* 00E668 0040E668 8F828350 */  lw          $v0, %got(is_idstart)($gp)
/* 00E66C 0040E66C 24050001 */  addiu       $a1, $zero, 0x1
/* 00E670 0040E670 24630061 */  addiu       $v1, $v1, 0x61
/* 00E674 0040E674 24840061 */  addiu       $a0, $a0, 0x61
/* 00E678 0040E678 2442007B */  addiu       $v0, $v0, 0x7B
.L0040E67C:
/* 00E67C 0040E67C 24840001 */  addiu       $a0, $a0, 0x1
/* 00E680 0040E680 0082082B */  sltu        $at, $a0, $v0
/* 00E684 0040E684 24630001 */  addiu       $v1, $v1, 0x1
/* 00E688 0040E688 A065FFDF */  sb          $a1, -0x21($v1)
/* 00E68C 0040E68C A065FFFF */  sb          $a1, -0x1($v1)
/* 00E690 0040E690 A085FFDF */  sb          $a1, -0x21($a0)
/* 00E694 0040E694 1420FFF9 */  bnez        $at, .L0040E67C
/* 00E698 0040E698 A085FFFF */   sb         $a1, -0x1($a0)
/* 00E69C 0040E69C 8F81834C */  lw          $at, %got(is_idchar)($gp)
/* 00E6A0 0040E6A0 8F83834C */  lw          $v1, %got(is_idchar)($gp)
/* 00E6A4 0040E6A4 A0250030 */  sb          $a1, 0x30($at)
/* 00E6A8 0040E6A8 8F81834C */  lw          $at, %got(is_idchar)($gp)
/* 00E6AC 0040E6AC 8F82834C */  lw          $v0, %got(is_idchar)($gp)
/* 00E6B0 0040E6B0 24630032 */  addiu       $v1, $v1, 0x32
/* 00E6B4 0040E6B4 A0250031 */  sb          $a1, 0x31($at)
/* 00E6B8 0040E6B8 2442003A */  addiu       $v0, $v0, 0x3A
.L0040E6BC:
/* 00E6BC 0040E6BC 24630004 */  addiu       $v1, $v1, 0x4
/* 00E6C0 0040E6C0 A065FFFD */  sb          $a1, -0x3($v1)
/* 00E6C4 0040E6C4 A065FFFE */  sb          $a1, -0x2($v1)
/* 00E6C8 0040E6C8 A065FFFF */  sb          $a1, -0x1($v1)
/* 00E6CC 0040E6CC 1462FFFB */  bne         $v1, $v0, .L0040E6BC
/* 00E6D0 0040E6D0 A065FFFC */   sb         $a1, -0x4($v1)
/* 00E6D4 0040E6D4 8F83834C */  lw          $v1, %got(is_idchar)($gp)
/* 00E6D8 0040E6D8 8F848350 */  lw          $a0, %got(is_idstart)($gp)
/* 00E6DC 0040E6DC 8F8282CC */  lw          $v0, %got(dollars_in_ident)($gp)
/* 00E6E0 0040E6E0 A065005F */  sb          $a1, 0x5F($v1)
/* 00E6E4 0040E6E4 A085005F */  sb          $a1, 0x5F($a0)
/* 00E6E8 0040E6E8 8C420000 */  lw          $v0, 0x0($v0)
/* 00E6EC 0040E6EC 8F878358 */  lw          $a3, %got(is_space)($gp)
/* 00E6F0 0040E6F0 8F868354 */  lw          $a2, %got(is_hor_space)($gp)
/* 00E6F4 0040E6F4 A0620024 */  sb          $v0, 0x24($v1)
/* 00E6F8 0040E6F8 A0820024 */  sb          $v0, 0x24($a0)
/* 00E6FC 0040E6FC A0E50020 */  sb          $a1, 0x20($a3)
/* 00E700 0040E700 A0E50009 */  sb          $a1, 0x9($a3)
/* 00E704 0040E704 A0E5000B */  sb          $a1, 0xB($a3)
/* 00E708 0040E708 A0E5000C */  sb          $a1, 0xC($a3)
/* 00E70C 0040E70C A0E5000A */  sb          $a1, 0xA($a3)
/* 00E710 0040E710 A0C50020 */  sb          $a1, 0x20($a2)
/* 00E714 0040E714 A0C50009 */  sb          $a1, 0x9($a2)
/* 00E718 0040E718 A0C5000B */  sb          $a1, 0xB($a2)
/* 00E71C 0040E71C 03E00008 */  jr          $ra
/* 00E720 0040E720 A0C5000C */   sb         $a1, 0xC($a2)
