.section .rodata
glabel STR_100016EC
/* 0136EC 100016EC */ .asciz "#%s not within a conditional"
                      .balign 4

glabel STR_1000170C
/* 01370C 1000170C */ .asciz "#else or #elif after #else"
                      .balign 4

.section .late_rodata
glabel jtbl_1000207C
/* 01407C 1000207C F0400334 */ .gpword .L0040AB54
/* 014080 10002080 F04007F0 */ .gpword .L0040B010
/* 014084 10002084 F04007F0 */ .gpword .L0040B010
/* 014088 10002088 F04007F0 */ .gpword .L0040B010
/* 01408C 1000208C F04007F0 */ .gpword .L0040B010
/* 014090 10002090 F04007F0 */ .gpword .L0040B010
/* 014094 10002094 F04007F0 */ .gpword .L0040B010
/* 014098 10002098 F04007F0 */ .gpword .L0040B010
/* 01409C 1000209C F04007F0 */ .gpword .L0040B010
/* 0140A0 100020A0 F04007F0 */ .gpword .L0040B010
/* 0140A4 100020A4 F04007F0 */ .gpword .L0040B010
/* 0140A8 100020A8 F04007F0 */ .gpword .L0040B010
/* 0140AC 100020AC F04007F0 */ .gpword .L0040B010
/* 0140B0 100020B0 F04007F0 */ .gpword .L0040B010
/* 0140B4 100020B4 F04007F0 */ .gpword .L0040B010
/* 0140B8 100020B8 F04007F0 */ .gpword .L0040B010
/* 0140BC 100020BC F04007F0 */ .gpword .L0040B010
/* 0140C0 100020C0 F04007F0 */ .gpword .L0040B010
/* 0140C4 100020C4 F04007F0 */ .gpword .L0040B010
/* 0140C8 100020C8 F04007F0 */ .gpword .L0040B010
/* 0140CC 100020CC F04007F0 */ .gpword .L0040B010
/* 0140D0 100020D0 F04007F0 */ .gpword .L0040B010
/* 0140D4 100020D4 F04007F0 */ .gpword .L0040B010
/* 0140D8 100020D8 F04007F0 */ .gpword .L0040B010
/* 0140DC 100020DC F04002BC */ .gpword .L0040AADC
/* 0140E0 100020E0 F0400354 */ .gpword .L0040AB74
/* 0140E4 100020E4 F04007F0 */ .gpword .L0040B010
/* 0140E8 100020E8 F04007F0 */ .gpword .L0040B010
/* 0140EC 100020EC F04007F0 */ .gpword .L0040B010
/* 0140F0 100020F0 F04002BC */ .gpword .L0040AADC
/* 0140F4 100020F4 F04007F0 */ .gpword .L0040B010
/* 0140F8 100020F8 F04007F0 */ .gpword .L0040B010
/* 0140FC 100020FC F04007F0 */ .gpword .L0040B010
/* 014100 10002100 F04007F0 */ .gpword .L0040B010
/* 014104 10002104 F04007F0 */ .gpword .L0040B010
/* 014108 10002108 F04007F0 */ .gpword .L0040B010
/* 01410C 1000210C F04007F0 */ .gpword .L0040B010
/* 014110 10002110 F0400230 */ .gpword .L0040AA50

glabel jtbl_10002114
/* 014114 10002114 F0400664 */ .gpword .L0040AE84
/* 014118 10002118 F0400664 */ .gpword .L0040AE84
/* 01411C 1000211C F0400664 */ .gpword .L0040AE84
/* 014120 10002120 F04006C4 */ .gpword .L0040AEE4
/* 014124 10002124 F04007F0 */ .gpword .L0040B010
/* 014128 10002128 F040070C */ .gpword .L0040AF2C
/* 01412C 1000212C F04007F0 */ .gpword .L0040B010
/* 014130 10002130 F04007F0 */ .gpword .L0040B010
/* 014134 10002134 F04007F0 */ .gpword .L0040B010
/* 014138 10002138 F04006C4 */ .gpword .L0040AEE4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel skip_if_group # 35
# _gp_disp: 0xFBFFEA8
.set noreorder; .cpload $t9; # .set reorder
/* 00A984 0040A984 27BDFFA0 */  addiu       $sp, $sp, -0x60
/* 00A988 0040A988 AFBF0044 */  sw          $ra, 0x44($sp)
/* 00A98C 0040A98C AFBE0040 */  sw          $fp, 0x40($sp)
/* 00A990 0040A990 AFBC003C */  sw          $gp, 0x3C($sp)
/* 00A994 0040A994 AFB70038 */  sw          $s7, 0x38($sp)
/* 00A998 0040A998 AFB60034 */  sw          $s6, 0x34($sp)
/* 00A99C 0040A99C AFB50030 */  sw          $s5, 0x30($sp)
/* 00A9A0 0040A9A0 AFB4002C */  sw          $s4, 0x2C($sp)
/* 00A9A4 0040A9A4 AFB30028 */  sw          $s3, 0x28($sp)
/* 00A9A8 0040A9A8 AFB20024 */  sw          $s2, 0x24($sp)
/* 00A9AC 0040A9AC AFB10020 */  sw          $s1, 0x20($sp)
/* 00A9B0 0040A9B0 AFB0001C */  sw          $s0, 0x1C($sp)
/* 00A9B4 0040A9B4 AFA40060 */  sw          $a0, 0x60($sp)
/* 00A9B8 0040A9B8 AFA50064 */  sw          $a1, 0x64($sp)
/* 00A9BC 0040A9BC 8C900014 */  lw          $s0, 0x14($a0)
/* 00A9C0 0040A9C0 8C980008 */  lw          $t8, 0x8($a0)
/* 00A9C4 0040A9C4 8C8F0010 */  lw          $t7, 0x10($a0)
/* 00A9C8 0040A9C8 8F8882D0 */  lw          $t0, %got(if_stack)($gp)
/* 00A9CC 0040A9CC 01F8C821 */  addu        $t9, $t7, $t8
/* 00A9D0 0040A9D0 8D080000 */  lw          $t0, 0x0($t0)
/* 00A9D4 0040A9D4 0219082B */  sltu        $at, $s0, $t9
/* 00A9D8 0040A9D8 AFB90054 */  sw          $t9, 0x54($sp)
/* 00A9DC 0040A9DC AFB00048 */  sw          $s0, 0x48($sp)
/* 00A9E0 0040A9E0 10200190 */  beqz        $at, .L0040B024
/* 00A9E4 0040A9E4 AFA8004C */   sw         $t0, 0x4C($sp)
/* 00A9E8 0040A9E8 8F9E834C */  lw          $fp, %got(is_idchar)($gp)
/* 00A9EC 0040A9EC 8F978354 */  lw          $s7, %got(is_hor_space)($gp)
/* 00A9F0 0040A9F0 2416005C */  addiu       $s6, $zero, 0x5C
/* 00A9F4 0040A9F4 2414000A */  addiu       $s4, $zero, 0xA
/* 00A9F8 0040A9F8 2412002A */  addiu       $s2, $zero, 0x2A
/* 00A9FC 0040A9FC 2411002F */  addiu       $s1, $zero, 0x2F
.L0040AA00:
/* 00AA00 0040AA00 92020000 */  lbu         $v0, 0x0($s0)
/* 00AA04 0040AA04 26100001 */  addiu       $s0, $s0, 0x1
/* 00AA08 0040AA08 2C410030 */  sltiu       $at, $v0, 0x30
/* 00AA0C 0040AA0C 14200005 */  bnez        $at, .L0040AA24
/* 00AA10 0040AA10 2449FFF6 */   addiu      $t1, $v0, -0xA
/* 00AA14 0040AA14 10560041 */  beq         $v0, $s6, .L0040AB1C
/* 00AA18 0040AA18 8FAD0054 */   lw         $t5, 0x54($sp)
/* 00AA1C 0040AA1C 1000017D */  b           .L0040B014
/* 00AA20 0040AA20 8FB80054 */   lw         $t8, 0x54($sp)
.L0040AA24:
/* 00AA24 0040AA24 2D210026 */  sltiu       $at, $t1, 0x26
/* 00AA28 0040AA28 1020017A */  beqz        $at, .L0040B014
/* 00AA2C 0040AA2C 8FB80054 */   lw         $t8, 0x54($sp)
/* 00AA30 0040AA30 8F81804C */  lw          $at, %got(jtbl_1000207C)($gp)
/* 00AA34 0040AA34 00094880 */  sll         $t1, $t1, 2
/* 00AA38 0040AA38 00290821 */  addu        $at, $at, $t1
/* 00AA3C 0040AA3C 8C29207C */  lw          $t1, %lo(jtbl_1000207C)($at)
/* 00AA40 0040AA40 00000000 */  nop
/* 00AA44 0040AA44 013C4821 */  addu        $t1, $t1, $gp
/* 00AA48 0040AA48 01200008 */  jr          $t1
/* 00AA4C 0040AA4C 00000000 */   nop
.L0040AA50:
/* 00AA50 0040AA50 92040000 */  lbu         $a0, 0x0($s0)
/* 00AA54 0040AA54 00000000 */  nop
/* 00AA58 0040AA58 16C4000C */  bne         $s6, $a0, .L0040AA8C
/* 00AA5C 0040AA5C 00000000 */   nop
/* 00AA60 0040AA60 920A0001 */  lbu         $t2, 0x1($s0)
/* 00AA64 0040AA64 00000000 */  nop
/* 00AA68 0040AA68 168A0008 */  bne         $s4, $t2, .L0040AA8C
/* 00AA6C 0040AA6C 00000000 */   nop
/* 00AA70 0040AA70 8F998158 */  lw          $t9, %call16(newline_fix)($gp)
/* 00AA74 0040AA74 02002025 */  move        $a0, $s0
/* 00AA78 0040AA78 0320F809 */  jalr        $t9
/* 00AA7C 0040AA7C 00000000 */   nop
/* 00AA80 0040AA80 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AA84 0040AA84 92040000 */  lbu         $a0, 0x0($s0)
/* 00AA88 0040AA88 00000000 */  nop
.L0040AA8C:
/* 00AA8C 0040AA8C 12440009 */  beq         $s2, $a0, .L0040AAB4
/* 00AA90 0040AA90 00000000 */   nop
/* 00AA94 0040AA94 8F8B830C */  lw          $t3, %got(cplusplus)($gp)
/* 00AA98 0040AA98 00000000 */  nop
/* 00AA9C 0040AA9C 8D6B0000 */  lw          $t3, 0x0($t3)
/* 00AAA0 0040AAA0 00000000 */  nop
/* 00AAA4 0040AAA4 1160015B */  beqz        $t3, .L0040B014
/* 00AAA8 0040AAA8 8FB80054 */   lw         $t8, 0x54($sp)
/* 00AAAC 0040AAAC 16240159 */  bne         $s1, $a0, .L0040B014
/* 00AAB0 0040AAB0 8FB80054 */   lw         $t8, 0x54($sp)
.L0040AAB4:
/* 00AAB4 0040AAB4 8FA40060 */  lw          $a0, 0x60($sp)
/* 00AAB8 0040AAB8 26100001 */  addiu       $s0, $s0, 0x1
/* 00AABC 0040AABC AC900014 */  sw          $s0, 0x14($a0)
/* 00AAC0 0040AAC0 8F9981C8 */  lw          $t9, %call16(skip_to_end_of_comment)($gp)
/* 00AAC4 0040AAC4 24850004 */  addiu       $a1, $a0, 0x4
/* 00AAC8 0040AAC8 0320F809 */  jalr        $t9
/* 00AACC 0040AACC 00000000 */   nop
/* 00AAD0 0040AAD0 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AAD4 0040AAD4 1000014E */  b           .L0040B010
/* 00AAD8 0040AAD8 00408025 */   move       $s0, $v0
.L0040AADC:
/* 00AADC 0040AADC 8F8C8338 */  lw          $t4, %got(traditional)($gp)
/* 00AAE0 0040AAE0 8FA20060 */  lw          $v0, 0x60($sp)
/* 00AAE4 0040AAE4 8D8C0000 */  lw          $t4, 0x0($t4)
/* 00AAE8 0040AAE8 8FA50054 */  lw          $a1, 0x54($sp)
/* 00AAEC 0040AAEC 15800148 */  bnez        $t4, .L0040B010
/* 00AAF0 0040AAF0 2604FFFF */   addiu      $a0, $s0, -0x1
/* 00AAF4 0040AAF4 8F9981CC */  lw          $t9, %call16(skip_quoted_string)($gp)
/* 00AAF8 0040AAF8 8C460004 */  lw          $a2, 0x4($v0)
/* 00AAFC 0040AAFC AFA00014 */  sw          $zero, 0x14($sp)
/* 00AB00 0040AB00 AFA00010 */  sw          $zero, 0x10($sp)
/* 00AB04 0040AB04 0320F809 */  jalr        $t9
/* 00AB08 0040AB08 24470004 */   addiu      $a3, $v0, 0x4
/* 00AB0C 0040AB0C 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AB10 0040AB10 1000013F */  b           .L0040B010
/* 00AB14 0040AB14 00408025 */   move       $s0, $v0
/* 00AB18 0040AB18 8FAD0054 */  lw          $t5, 0x54($sp)
.L0040AB1C:
/* 00AB1C 0040AB1C 00000000 */  nop
/* 00AB20 0040AB20 020D082B */  sltu        $at, $s0, $t5
/* 00AB24 0040AB24 1020013B */  beqz        $at, .L0040B014
/* 00AB28 0040AB28 8FB80054 */   lw         $t8, 0x54($sp)
/* 00AB2C 0040AB2C 920E0000 */  lbu         $t6, 0x0($s0)
/* 00AB30 0040AB30 8FAF0060 */  lw          $t7, 0x60($sp)
/* 00AB34 0040AB34 168E0005 */  bne         $s4, $t6, .L0040AB4C
/* 00AB38 0040AB38 00000000 */   nop
/* 00AB3C 0040AB3C 8DF80004 */  lw          $t8, 0x4($t7)
/* 00AB40 0040AB40 00000000 */  nop
/* 00AB44 0040AB44 27080001 */  addiu       $t0, $t8, 0x1
/* 00AB48 0040AB48 ADE80004 */  sw          $t0, 0x4($t7)
.L0040AB4C:
/* 00AB4C 0040AB4C 10000130 */  b           .L0040B010
/* 00AB50 0040AB50 26100001 */   addiu      $s0, $s0, 0x1
.L0040AB54:
/* 00AB54 0040AB54 8FB90060 */  lw          $t9, 0x60($sp)
/* 00AB58 0040AB58 00000000 */  nop
/* 00AB5C 0040AB5C 8F290004 */  lw          $t1, 0x4($t9)
/* 00AB60 0040AB60 00000000 */  nop
/* 00AB64 0040AB64 252A0001 */  addiu       $t2, $t1, 0x1
/* 00AB68 0040AB68 AF2A0004 */  sw          $t2, 0x4($t9)
/* 00AB6C 0040AB6C 10000128 */  b           .L0040B010
/* 00AB70 0040AB70 AFB00048 */   sw         $s0, 0x48($sp)
.L0040AB74:
/* 00AB74 0040AB74 8FAC0060 */  lw          $t4, 0x60($sp)
/* 00AB78 0040AB78 260BFFFF */  addiu       $t3, $s0, -0x1
/* 00AB7C 0040AB7C AD8B0014 */  sw          $t3, 0x14($t4)
/* 00AB80 0040AB80 8FAD0048 */  lw          $t5, 0x48($sp)
/* 00AB84 0040AB84 00000000 */  nop
/* 00AB88 0040AB88 11A00122 */  beqz        $t5, .L0040B014
/* 00AB8C 0040AB8C 8FB80054 */   lw         $t8, 0x54($sp)
/* 00AB90 0040AB90 8F83830C */  lw          $v1, %got(cplusplus)($gp)
/* 00AB94 0040AB94 8FB00048 */  lw          $s0, 0x48($sp)
/* 00AB98 0040AB98 8C630000 */  lw          $v1, 0x0($v1)
/* 00AB9C 0040AB9C 00000000 */  nop
.L0040ABA0:
/* 00ABA0 0040ABA0 92040000 */  lbu         $a0, 0x0($s0)
.L0040ABA4:
/* 00ABA4 0040ABA4 00000000 */  nop
/* 00ABA8 0040ABA8 02E47021 */  addu        $t6, $s7, $a0
/* 00ABAC 0040ABAC 91D80000 */  lbu         $t8, 0x0($t6)
/* 00ABB0 0040ABB0 00000000 */  nop
/* 00ABB4 0040ABB4 13000003 */  beqz        $t8, .L0040ABC4
/* 00ABB8 0040ABB8 00000000 */   nop
/* 00ABBC 0040ABBC 1000FFF8 */  b           .L0040ABA0
/* 00ABC0 0040ABC0 26100001 */   addiu      $s0, $s0, 0x1
.L0040ABC4:
/* 00ABC4 0040ABC4 16C40007 */  bne         $s6, $a0, .L0040ABE4
/* 00ABC8 0040ABC8 00000000 */   nop
/* 00ABCC 0040ABCC 92080001 */  lbu         $t0, 0x1($s0)
/* 00ABD0 0040ABD0 00000000 */  nop
/* 00ABD4 0040ABD4 16880003 */  bne         $s4, $t0, .L0040ABE4
/* 00ABD8 0040ABD8 00000000 */   nop
/* 00ABDC 0040ABDC 1000FFF0 */  b           .L0040ABA0
/* 00ABE0 0040ABE0 26100002 */   addiu      $s0, $s0, 0x2
.L0040ABE4:
/* 00ABE4 0040ABE4 16240017 */  bne         $s1, $a0, .L0040AC44
/* 00ABE8 0040ABE8 00000000 */   nop
/* 00ABEC 0040ABEC 920F0001 */  lbu         $t7, 0x1($s0)
/* 00ABF0 0040ABF0 00000000 */  nop
/* 00ABF4 0040ABF4 164F0013 */  bne         $s2, $t7, .L0040AC44
/* 00ABF8 0040ABF8 00000000 */   nop
/* 00ABFC 0040ABFC 92090002 */  lbu         $t1, 0x2($s0)
/* 00AC00 0040AC00 26100002 */  addiu       $s0, $s0, 0x2
/* 00AC04 0040AC04 16490005 */  bne         $s2, $t1, .L0040AC1C
/* 00AC08 0040AC08 00000000 */   nop
/* 00AC0C 0040AC0C 920A0001 */  lbu         $t2, 0x1($s0)
/* 00AC10 0040AC10 00000000 */  nop
/* 00AC14 0040AC14 122A0009 */  beq         $s1, $t2, .L0040AC3C
/* 00AC18 0040AC18 00000000 */   nop
.L0040AC1C:
/* 00AC1C 0040AC1C 92190001 */  lbu         $t9, 0x1($s0)
/* 00AC20 0040AC20 26100001 */  addiu       $s0, $s0, 0x1
/* 00AC24 0040AC24 1659FFFD */  bne         $s2, $t9, .L0040AC1C
/* 00AC28 0040AC28 00000000 */   nop
/* 00AC2C 0040AC2C 920B0001 */  lbu         $t3, 0x1($s0)
/* 00AC30 0040AC30 00000000 */  nop
/* 00AC34 0040AC34 162BFFF9 */  bne         $s1, $t3, .L0040AC1C
/* 00AC38 0040AC38 00000000 */   nop
.L0040AC3C:
/* 00AC3C 0040AC3C 1000FFD8 */  b           .L0040ABA0
/* 00AC40 0040AC40 26100002 */   addiu      $s0, $s0, 0x2
.L0040AC44:
/* 00AC44 0040AC44 10600012 */  beqz        $v1, .L0040AC90
/* 00AC48 0040AC48 8FB80060 */   lw         $t8, 0x60($sp)
/* 00AC4C 0040AC4C 16240010 */  bne         $s1, $a0, .L0040AC90
/* 00AC50 0040AC50 8FB80060 */   lw         $t8, 0x60($sp)
/* 00AC54 0040AC54 920C0001 */  lbu         $t4, 0x1($s0)
/* 00AC58 0040AC58 00000000 */  nop
/* 00AC5C 0040AC5C 162C000C */  bne         $s1, $t4, .L0040AC90
/* 00AC60 0040AC60 8FB80060 */   lw         $t8, 0x60($sp)
/* 00AC64 0040AC64 920D0002 */  lbu         $t5, 0x2($s0)
/* 00AC68 0040AC68 26100003 */  addiu       $s0, $s0, 0x3
/* 00AC6C 0040AC6C 128DFFCC */  beq         $s4, $t5, .L0040ABA0
/* 00AC70 0040AC70 00000000 */   nop
.L0040AC74:
/* 00AC74 0040AC74 920E0000 */  lbu         $t6, 0x0($s0)
/* 00AC78 0040AC78 26100001 */  addiu       $s0, $s0, 0x1
/* 00AC7C 0040AC7C 168EFFFD */  bne         $s4, $t6, .L0040AC74
/* 00AC80 0040AC80 00000000 */   nop
/* 00AC84 0040AC84 1000FFC7 */  b           .L0040ABA4
/* 00AC88 0040AC88 92040000 */   lbu        $a0, 0x0($s0)
/* 00AC8C 0040AC8C 8FB80060 */  lw          $t8, 0x60($sp)
.L0040AC90:
/* 00AC90 0040AC90 00000000 */  nop
/* 00AC94 0040AC94 8F020014 */  lw          $v0, 0x14($t8)
/* 00AC98 0040AC98 00000000 */  nop
/* 00AC9C 0040AC9C 12020003 */  beq         $s0, $v0, .L0040ACAC
/* 00ACA0 0040ACA0 00000000 */   nop
/* 00ACA4 0040ACA4 100000DA */  b           .L0040B010
/* 00ACA8 0040ACA8 24500001 */   addiu      $s0, $v0, 0x1
.L0040ACAC:
/* 00ACAC 0040ACAC 8F9582C4 */  lw          $s5, %got(directive_table)($gp)
/* 00ACB0 0040ACB0 24500001 */  addiu       $s0, $v0, 0x1
.L0040ACB4:
/* 00ACB4 0040ACB4 92040000 */  lbu         $a0, 0x0($s0)
/* 00ACB8 0040ACB8 00000000 */  nop
/* 00ACBC 0040ACBC 02E44021 */  addu        $t0, $s7, $a0
/* 00ACC0 0040ACC0 910F0000 */  lbu         $t7, 0x0($t0)
/* 00ACC4 0040ACC4 00000000 */  nop
/* 00ACC8 0040ACC8 11E00003 */  beqz        $t7, .L0040ACD8
/* 00ACCC 0040ACCC 00000000 */   nop
/* 00ACD0 0040ACD0 1000FFF8 */  b           .L0040ACB4
/* 00ACD4 0040ACD4 26100001 */   addiu      $s0, $s0, 0x1
.L0040ACD8:
/* 00ACD8 0040ACD8 16C40007 */  bne         $s6, $a0, .L0040ACF8
/* 00ACDC 0040ACDC 00000000 */   nop
/* 00ACE0 0040ACE0 92090001 */  lbu         $t1, 0x1($s0)
/* 00ACE4 0040ACE4 00000000 */  nop
/* 00ACE8 0040ACE8 16890003 */  bne         $s4, $t1, .L0040ACF8
/* 00ACEC 0040ACEC 00000000 */   nop
/* 00ACF0 0040ACF0 1000FFF0 */  b           .L0040ACB4
/* 00ACF4 0040ACF4 26100002 */   addiu      $s0, $s0, 0x2
.L0040ACF8:
/* 00ACF8 0040ACF8 16240018 */  bne         $s1, $a0, .L0040AD5C
/* 00ACFC 0040ACFC 02009825 */   move       $s3, $s0
/* 00AD00 0040AD00 920A0001 */  lbu         $t2, 0x1($s0)
/* 00AD04 0040AD04 00000000 */  nop
/* 00AD08 0040AD08 164A0014 */  bne         $s2, $t2, .L0040AD5C
/* 00AD0C 0040AD0C 02009825 */   move       $s3, $s0
/* 00AD10 0040AD10 92190002 */  lbu         $t9, 0x2($s0)
/* 00AD14 0040AD14 26100002 */  addiu       $s0, $s0, 0x2
/* 00AD18 0040AD18 16590005 */  bne         $s2, $t9, .L0040AD30
/* 00AD1C 0040AD1C 00000000 */   nop
/* 00AD20 0040AD20 920B0001 */  lbu         $t3, 0x1($s0)
/* 00AD24 0040AD24 00000000 */  nop
/* 00AD28 0040AD28 122B0009 */  beq         $s1, $t3, .L0040AD50
/* 00AD2C 0040AD2C 00000000 */   nop
.L0040AD30:
/* 00AD30 0040AD30 920C0001 */  lbu         $t4, 0x1($s0)
/* 00AD34 0040AD34 26100001 */  addiu       $s0, $s0, 0x1
/* 00AD38 0040AD38 164CFFFD */  bne         $s2, $t4, .L0040AD30
/* 00AD3C 0040AD3C 00000000 */   nop
/* 00AD40 0040AD40 920D0001 */  lbu         $t5, 0x1($s0)
/* 00AD44 0040AD44 00000000 */  nop
/* 00AD48 0040AD48 162DFFF9 */  bne         $s1, $t5, .L0040AD30
/* 00AD4C 0040AD4C 00000000 */   nop
.L0040AD50:
/* 00AD50 0040AD50 1000FFD8 */  b           .L0040ACB4
/* 00AD54 0040AD54 26100002 */   addiu      $s0, $s0, 0x2
/* 00AD58 0040AD58 02009825 */  move        $s3, $s0
.L0040AD5C:
/* 00AD5C 0040AD5C 03C47021 */  addu        $t6, $fp, $a0
.L0040AD60:
/* 00AD60 0040AD60 91C30000 */  lbu         $v1, 0x0($t6)
/* 00AD64 0040AD64 00000000 */  nop
/* 00AD68 0040AD68 10600003 */  beqz        $v1, .L0040AD78
/* 00AD6C 0040AD6C 00000000 */   nop
/* 00AD70 0040AD70 10000013 */  b           .L0040ADC0
/* 00AD74 0040AD74 26100001 */   addiu      $s0, $s0, 0x1
.L0040AD78:
/* 00AD78 0040AD78 16C4000E */  bne         $s6, $a0, .L0040ADB4
/* 00AD7C 0040AD7C 00000000 */   nop
/* 00AD80 0040AD80 92180001 */  lbu         $t8, 0x1($s0)
/* 00AD84 0040AD84 00000000 */  nop
/* 00AD88 0040AD88 1698000A */  bne         $s4, $t8, .L0040ADB4
/* 00AD8C 0040AD8C 00000000 */   nop
/* 00AD90 0040AD90 8F99815C */  lw          $t9, %call16(name_newline_fix)($gp)
/* 00AD94 0040AD94 02002025 */  move        $a0, $s0
/* 00AD98 0040AD98 0320F809 */  jalr        $t9
/* 00AD9C 0040AD9C 00000000 */   nop
/* 00ADA0 0040ADA0 92080000 */  lbu         $t0, 0x0($s0)
/* 00ADA4 0040ADA4 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00ADA8 0040ADA8 03C87821 */  addu        $t7, $fp, $t0
/* 00ADAC 0040ADAC 91E30000 */  lbu         $v1, 0x0($t7)
/* 00ADB0 0040ADB0 00000000 */  nop
.L0040ADB4:
/* 00ADB4 0040ADB4 10600005 */  beqz        $v1, .L0040ADCC
/* 00ADB8 0040ADB8 00000000 */   nop
/* 00ADBC 0040ADBC 26100001 */  addiu       $s0, $s0, 0x1
.L0040ADC0:
/* 00ADC0 0040ADC0 92040000 */  lbu         $a0, 0x0($s0)
/* 00ADC4 0040ADC4 1000FFE6 */  b           .L0040AD60
/* 00ADC8 0040ADC8 03C47021 */   addu       $t6, $fp, $a0
.L0040ADCC:
/* 00ADCC 0040ADCC 8F8982C4 */  lw          $t1, %got(directive_table)($gp)
/* 00ADD0 0040ADD0 00000000 */  nop
/* 00ADD4 0040ADD4 8D290000 */  lw          $t1, 0x0($t1)
/* 00ADD8 0040ADD8 00000000 */  nop
/* 00ADDC 0040ADDC 0520008D */  bltz        $t1, .L0040B014
/* 00ADE0 0040ADE0 8FB80054 */   lw         $t8, 0x54($sp)
/* 00ADE4 0040ADE4 8F8A82C4 */  lw          $t2, %got(directive_table)($gp)
/* 00ADE8 0040ADE8 00000000 */  nop
/* 00ADEC 0040ADEC 8D420000 */  lw          $v0, 0x0($t2)
/* 00ADF0 0040ADF0 00000000 */  nop
.L0040ADF4:
/* 00ADF4 0040ADF4 8F998090 */  lw          $t9, %call16(strncmp)($gp)
/* 00ADF8 0040ADF8 8EA50008 */  lw          $a1, 0x8($s5)
/* 00ADFC 0040ADFC 02602025 */  move        $a0, $s3
/* 00AE00 0040AE00 0320F809 */  jalr        $t9
/* 00AE04 0040AE04 00403025 */   move       $a2, $v0
/* 00AE08 0040AE08 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AE0C 0040AE0C 1440007C */  bnez        $v0, .L0040B000
/* 00AE10 0040AE10 00000000 */   nop
/* 00AE14 0040AE14 8EB90000 */  lw          $t9, 0x0($s5)
/* 00AE18 0040AE18 00000000 */  nop
/* 00AE1C 0040AE1C 03335821 */  addu        $t3, $t9, $s3
/* 00AE20 0040AE20 916C0000 */  lbu         $t4, 0x0($t3)
/* 00AE24 0040AE24 00000000 */  nop
/* 00AE28 0040AE28 03CC6821 */  addu        $t5, $fp, $t4
/* 00AE2C 0040AE2C 91AE0000 */  lbu         $t6, 0x0($t5)
/* 00AE30 0040AE30 00000000 */  nop
/* 00AE34 0040AE34 15C00072 */  bnez        $t6, .L0040B000
/* 00AE38 0040AE38 00000000 */   nop
/* 00AE3C 0040AE3C 8FB80064 */  lw          $t8, 0x64($sp)
/* 00AE40 0040AE40 00000000 */  nop
/* 00AE44 0040AE44 1700007B */  bnez        $t8, .L0040B034
/* 00AE48 0040AE48 8FBF0044 */   lw         $ra, 0x44($sp)
/* 00AE4C 0040AE4C 8EA8000C */  lw          $t0, 0xC($s5)
/* 00AE50 0040AE50 00000000 */  nop
/* 00AE54 0040AE54 250FFFFD */  addiu       $t7, $t0, -0x3
/* 00AE58 0040AE58 2DE1000A */  sltiu       $at, $t7, 0xA
/* 00AE5C 0040AE5C 1020006D */  beqz        $at, .L0040B014
/* 00AE60 0040AE60 8FB80054 */   lw         $t8, 0x54($sp)
/* 00AE64 0040AE64 8F81804C */  lw          $at, %got(jtbl_10002114)($gp)
/* 00AE68 0040AE68 000F7880 */  sll         $t7, $t7, 2
/* 00AE6C 0040AE6C 002F0821 */  addu        $at, $at, $t7
/* 00AE70 0040AE70 8C2F2114 */  lw          $t7, %lo(jtbl_10002114)($at)
/* 00AE74 0040AE74 00000000 */  nop
/* 00AE78 0040AE78 01FC7821 */  addu        $t7, $t7, $gp
/* 00AE7C 0040AE7C 01E00008 */  jr          $t7
/* 00AE80 0040AE80 00000000 */   nop
.L0040AE84:
/* 00AE84 0040AE84 8F998250 */  lw          $t9, %call16(xcalloc)($gp)
/* 00AE88 0040AE88 24040001 */  addiu       $a0, $zero, 0x1
/* 00AE8C 0040AE8C 0320F809 */  jalr        $t9
/* 00AE90 0040AE90 24050014 */   addiu      $a1, $zero, 0x14
/* 00AE94 0040AE94 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AE98 0040AE98 00000000 */  nop
/* 00AE9C 0040AE9C 8F8982D0 */  lw          $t1, %got(if_stack)($gp)
/* 00AEA0 0040AEA0 8F8182D0 */  lw          $at, %got(if_stack)($gp)
/* 00AEA4 0040AEA4 8D290000 */  lw          $t1, 0x0($t1)
/* 00AEA8 0040AEA8 00000000 */  nop
/* 00AEAC 0040AEAC AC490000 */  sw          $t1, 0x0($v0)
/* 00AEB0 0040AEB0 8FAA0060 */  lw          $t2, 0x60($sp)
/* 00AEB4 0040AEB4 AC220000 */  sw          $v0, 0x0($at)
/* 00AEB8 0040AEB8 8D590004 */  lw          $t9, 0x4($t2)
/* 00AEBC 0040AEBC 00000000 */  nop
/* 00AEC0 0040AEC0 AC590008 */  sw          $t9, 0x8($v0)
/* 00AEC4 0040AEC4 8FAB0060 */  lw          $t3, 0x60($sp)
/* 00AEC8 0040AEC8 00000000 */  nop
/* 00AECC 0040AECC 8D6C0000 */  lw          $t4, 0x0($t3)
/* 00AED0 0040AED0 00000000 */  nop
/* 00AED4 0040AED4 AC4C0004 */  sw          $t4, 0x4($v0)
/* 00AED8 0040AED8 8EAD000C */  lw          $t5, 0xC($s5)
/* 00AEDC 0040AEDC 1000004C */  b           .L0040B010
/* 00AEE0 0040AEE0 AC4D0010 */   sw         $t5, 0x10($v0)
.L0040AEE4:
/* 00AEE4 0040AEE4 8F8E8324 */  lw          $t6, %got(pedantic)($gp)
/* 00AEE8 0040AEE8 00000000 */  nop
/* 00AEEC 0040AEEC 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00AEF0 0040AEF0 00000000 */  nop
/* 00AEF4 0040AEF4 11C0000D */  beqz        $t6, .L0040AF2C
/* 00AEF8 0040AEF8 00000000 */   nop
/* 00AEFC 0040AEFC 8F8882D0 */  lw          $t0, %got(if_stack)($gp)
/* 00AF00 0040AF00 8FB8004C */  lw          $t8, 0x4C($sp)
/* 00AF04 0040AF04 8D080000 */  lw          $t0, 0x0($t0)
/* 00AF08 0040AF08 00000000 */  nop
/* 00AF0C 0040AF0C 13080007 */  beq         $t8, $t0, .L0040AF2C
/* 00AF10 0040AF10 00000000 */   nop
/* 00AF14 0040AF14 8F9981C4 */  lw          $t9, %call16(validate_else)($gp)
/* 00AF18 0040AF18 02002025 */  move        $a0, $s0
/* 00AF1C 0040AF1C 0320F809 */  jalr        $t9
/* 00AF20 0040AF20 00000000 */   nop
/* 00AF24 0040AF24 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AF28 0040AF28 00000000 */  nop
.L0040AF2C:
/* 00AF2C 0040AF2C 8F8F829C */  lw          $t7, %got(indepth)($gp)
/* 00AF30 0040AF30 8F8A8340 */  lw          $t2, %got(instack)($gp)
/* 00AF34 0040AF34 8DEF0000 */  lw          $t7, 0x0($t7)
/* 00AF38 0040AF38 8F8382D0 */  lw          $v1, %got(if_stack)($gp)
/* 00AF3C 0040AF3C 000F48C0 */  sll         $t1, $t7, 3
/* 00AF40 0040AF40 012F4821 */  addu        $t1, $t1, $t7
/* 00AF44 0040AF44 00094880 */  sll         $t1, $t1, 2
/* 00AF48 0040AF48 012AC821 */  addu        $t9, $t1, $t2
/* 00AF4C 0040AF4C 8F2B001C */  lw          $t3, 0x1C($t9)
/* 00AF50 0040AF50 8C630000 */  lw          $v1, 0x0($v1)
/* 00AF54 0040AF54 8FAC004C */  lw          $t4, 0x4C($sp)
/* 00AF58 0040AF58 146B0009 */  bne         $v1, $t3, .L0040AF80
/* 00AF5C 0040AF5C 00000000 */   nop
/* 00AF60 0040AF60 8F84804C */  lw          $a0, %got(STR_100016EC)($gp)
/* 00AF64 0040AF64 8F9981E4 */  lw          $t9, %call16(error)($gp)
/* 00AF68 0040AF68 8EA50008 */  lw          $a1, 0x8($s5)
/* 00AF6C 0040AF6C 0320F809 */  jalr        $t9
/* 00AF70 0040AF70 248416EC */   addiu      $a0, $a0, %lo(STR_100016EC)
/* 00AF74 0040AF74 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AF78 0040AF78 10000026 */  b           .L0040B014
/* 00AF7C 0040AF7C 8FB80054 */   lw         $t8, 0x54($sp)
.L0040AF80:
/* 00AF80 0040AF80 1183002C */  beq         $t4, $v1, .L0040B034
/* 00AF84 0040AF84 8FBF0044 */   lw         $ra, 0x44($sp)
/* 00AF88 0040AF88 8EA4000C */  lw          $a0, 0xC($s5)
/* 00AF8C 0040AF8C 2401000C */  addiu       $at, $zero, 0xC
/* 00AF90 0040AF90 10810012 */  beq         $a0, $at, .L0040AFDC
/* 00AF94 0040AF94 00000000 */   nop
/* 00AF98 0040AF98 8C6D0010 */  lw          $t5, 0x10($v1)
/* 00AF9C 0040AF9C 24010006 */  addiu       $at, $zero, 0x6
/* 00AFA0 0040AFA0 15A1000C */  bne         $t5, $at, .L0040AFD4
/* 00AFA4 0040AFA4 00000000 */   nop
/* 00AFA8 0040AFA8 8F84804C */  lw          $a0, %got(STR_1000170C)($gp)
/* 00AFAC 0040AFAC 8F9981E4 */  lw          $t9, %call16(error)($gp)
/* 00AFB0 0040AFB0 2484170C */  addiu       $a0, $a0, %lo(STR_1000170C)
/* 00AFB4 0040AFB4 0320F809 */  jalr        $t9
/* 00AFB8 0040AFB8 00000000 */   nop
/* 00AFBC 0040AFBC 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AFC0 0040AFC0 8EA4000C */  lw          $a0, 0xC($s5)
/* 00AFC4 0040AFC4 8F8382D0 */  lw          $v1, %got(if_stack)($gp)
/* 00AFC8 0040AFC8 00000000 */  nop
/* 00AFCC 0040AFCC 8C630000 */  lw          $v1, 0x0($v1)
/* 00AFD0 0040AFD0 00000000 */  nop
.L0040AFD4:
/* 00AFD4 0040AFD4 1000000E */  b           .L0040B010
/* 00AFD8 0040AFD8 AC640010 */   sw         $a0, 0x10($v1)
.L0040AFDC:
/* 00AFDC 0040AFDC 8C6E0000 */  lw          $t6, 0x0($v1)
/* 00AFE0 0040AFE0 8F8182D0 */  lw          $at, %got(if_stack)($gp)
/* 00AFE4 0040AFE4 8F99808C */  lw          $t9, %call16(free)($gp)
/* 00AFE8 0040AFE8 00602025 */  move        $a0, $v1
/* 00AFEC 0040AFEC 0320F809 */  jalr        $t9
/* 00AFF0 0040AFF0 AC2E0000 */   sw         $t6, 0x0($at)
/* 00AFF4 0040AFF4 8FBC003C */  lw          $gp, 0x3C($sp)
/* 00AFF8 0040AFF8 10000006 */  b           .L0040B014
/* 00AFFC 0040AFFC 8FB80054 */   lw         $t8, 0x54($sp)
.L0040B000:
/* 00B000 0040B000 8EA20014 */  lw          $v0, 0x14($s5)
/* 00B004 0040B004 26B50014 */  addiu       $s5, $s5, 0x14
/* 00B008 0040B008 0441FF7A */  bgez        $v0, .L0040ADF4
/* 00B00C 0040B00C 00000000 */   nop
.L0040B010:
/* 00B010 0040B010 8FB80054 */  lw          $t8, 0x54($sp)
.L0040B014:
/* 00B014 0040B014 00000000 */  nop
/* 00B018 0040B018 0218082B */  sltu        $at, $s0, $t8
/* 00B01C 0040B01C 1420FE78 */  bnez        $at, .L0040AA00
/* 00B020 0040B020 00000000 */   nop
.L0040B024:
/* 00B024 0040B024 8FA80060 */  lw          $t0, 0x60($sp)
/* 00B028 0040B028 00000000 */  nop
/* 00B02C 0040B02C AD100014 */  sw          $s0, 0x14($t0)
/* 00B030 0040B030 8FBF0044 */  lw          $ra, 0x44($sp)
.L0040B034:
/* 00B034 0040B034 8FB0001C */  lw          $s0, 0x1C($sp)
/* 00B038 0040B038 8FB10020 */  lw          $s1, 0x20($sp)
/* 00B03C 0040B03C 8FB20024 */  lw          $s2, 0x24($sp)
/* 00B040 0040B040 8FB30028 */  lw          $s3, 0x28($sp)
/* 00B044 0040B044 8FB4002C */  lw          $s4, 0x2C($sp)
/* 00B048 0040B048 8FB50030 */  lw          $s5, 0x30($sp)
/* 00B04C 0040B04C 8FB60034 */  lw          $s6, 0x34($sp)
/* 00B050 0040B050 8FB70038 */  lw          $s7, 0x38($sp)
/* 00B054 0040B054 8FBE0040 */  lw          $fp, 0x40($sp)
/* 00B058 0040B058 03E00008 */  jr          $ra
/* 00B05C 0040B05C 27BD0060 */   addiu      $sp, $sp, 0x60
