/* Generated by spimdisasm 1.10.3 */

glabel _md_st_ifdmax # 174
# _gp_disp: 0xFBFC100
.set noreorder; .cpload $t9; # .set reorder
/* 0149CC 004149CC 8F8E83CC */  lw          $t6, %got(st_pchdr)($gp)
/* 0149D0 004149D0 00000000 */  nop
/* 0149D4 004149D4 8DCE0000 */  lw          $t6, 0x0($t6)
/* 0149D8 004149D8 00000000 */  nop
/* 0149DC 004149DC 8DC2000C */  lw          $v0, 0xC($t6)
/* 0149E0 004149E0 03E00008 */  jr          $ra
/* 0149E4 004149E4 00000000 */   nop
