/* Generated by spimdisasm 1.10.3 */

glabel alloc_scb # 278
# _gp_disp: 0xFBF2270
.set noreorder; .cpload $t9; # .set reorder
/* 01E85C 0041E85C 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 01E860 0041E860 8F9982C4 */  lw          $t9, %call16(alloc_page)($gp)
/* 01E864 0041E864 AFBF001C */  sw          $ra, 0x1C($sp)
/* 01E868 0041E868 AFA40020 */  sw          $a0, 0x20($sp)
/* 01E86C 0041E86C AFBC0018 */  sw          $gp, 0x18($sp)
/* 01E870 0041E870 00A02025 */  move        $a0, $a1
/* 01E874 0041E874 0320F809 */  jalr        $t9
/* 01E878 0041E878 AFA50024 */   sw         $a1, 0x24($sp)
/* 01E87C 0041E87C 8FAE0020 */  lw          $t6, 0x20($sp)
/* 01E880 0041E880 8FBC0018 */  lw          $gp, 0x18($sp)
/* 01E884 0041E884 8FA60024 */  lw          $a2, 0x24($sp)
/* 01E888 0041E888 10400013 */  beqz        $v0, .L0041E8D8
/* 01E88C 0041E88C ADC20000 */   sw         $v0, 0x0($t6)
/* 01E890 0041E890 00462021 */  addu        $a0, $v0, $a2
/* 01E894 0041E894 2484FFF8 */  addiu       $a0, $a0, -0x8
/* 01E898 0041E898 00822823 */  subu        $a1, $a0, $v0
/* 01E89C 0041E89C 00067823 */  negu        $t7, $a2
/* 01E8A0 0041E8A0 24B8FFF2 */  addiu       $t8, $a1, -0xE
/* 01E8A4 0041E8A4 AC4F000C */  sw          $t7, 0xC($v0)
/* 01E8A8 0041E8A8 AC400000 */  sw          $zero, 0x0($v0)
/* 01E8AC 0041E8AC AC400004 */  sw          $zero, 0x4($v0)
/* 01E8B0 0041E8B0 AC400010 */  sw          $zero, 0x10($v0)
/* 01E8B4 0041E8B4 AC580014 */  sw          $t8, 0x14($v0)
/* 01E8B8 0041E8B8 24B9FFF0 */  addiu       $t9, $a1, -0x10
/* 01E8BC 0041E8BC 24080001 */  addiu       $t0, $zero, 0x1
/* 01E8C0 0041E8C0 AC990000 */  sw          $t9, 0x0($a0)
/* 01E8C4 0041E8C4 AC880004 */  sw          $t0, 0x4($a0)
/* 01E8C8 0041E8C8 24430010 */  addiu       $v1, $v0, 0x10
/* 01E8CC 0041E8CC AC430018 */  sw          $v1, 0x18($v0)
/* 01E8D0 0041E8D0 AC43001C */  sw          $v1, 0x1C($v0)
/* 01E8D4 0041E8D4 AC430008 */  sw          $v1, 0x8($v0)
.L0041E8D8:
/* 01E8D8 0041E8D8 8FBF001C */  lw          $ra, 0x1C($sp)
/* 01E8DC 0041E8DC 27BD0020 */  addiu       $sp, $sp, 0x20
/* 01E8E0 0041E8E0 03E00008 */  jr          $ra
/* 01E8E4 0041E8E4 00000000 */   nop
