/* Generated by spimdisasm 1.10.3 */

glabel alloc_release # 280
# _gp_disp: 0xFBF20C4
.set noreorder; .cpload $t9; # .set reorder
/* 01EA08 0041EA08 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 01EA0C 0041EA0C AFBF0024 */  sw          $ra, 0x24($sp)
/* 01EA10 0041EA10 AFBC0020 */  sw          $gp, 0x20($sp)
/* 01EA14 0041EA14 AFB1001C */  sw          $s1, 0x1C($sp)
/* 01EA18 0041EA18 AFB00018 */  sw          $s0, 0x18($sp)
/* 01EA1C 0041EA1C 8C820000 */  lw          $v0, 0x0($a0)
/* 01EA20 0041EA20 00A08825 */  move        $s1, $a1
/* 01EA24 0041EA24 10450009 */  beq         $v0, $a1, .L0041EA4C
/* 01EA28 0041EA28 00000000 */   nop
/* 01EA2C 0041EA2C 10400007 */  beqz        $v0, .L0041EA4C
/* 01EA30 0041EA30 00000000 */   nop
.L0041EA34:
/* 01EA34 0041EA34 8C420000 */  lw          $v0, 0x0($v0)
/* 01EA38 0041EA38 00000000 */  nop
/* 01EA3C 0041EA3C 10450003 */  beq         $v0, $a1, .L0041EA4C
/* 01EA40 0041EA40 00000000 */   nop
/* 01EA44 0041EA44 1440FFFB */  bnez        $v0, .L0041EA34
/* 01EA48 0041EA48 00000000 */   nop
.L0041EA4C:
/* 01EA4C 0041EA4C 1040001D */  beqz        $v0, .L0041EAC4
/* 01EA50 0041EA50 8FBF0024 */   lw         $ra, 0x24($sp)
/* 01EA54 0041EA54 8CB00000 */  lw          $s0, 0x0($a1)
/* 01EA58 0041EA58 00000000 */  nop
/* 01EA5C 0041EA5C 12000002 */  beqz        $s0, .L0041EA68
/* 01EA60 0041EA60 00000000 */   nop
/* 01EA64 0041EA64 AE000004 */  sw          $zero, 0x4($s0)
.L0041EA68:
/* 01EA68 0041EA68 1200000D */  beqz        $s0, .L0041EAA0
/* 01EA6C 0041EA6C 00000000 */   nop
/* 01EA70 0041EA70 8E0E000C */  lw          $t6, 0xC($s0)
/* 01EA74 0041EA74 00000000 */  nop
/* 01EA78 0041EA78 05C10009 */  bgez        $t6, .L0041EAA0
/* 01EA7C 0041EA7C 00000000 */   nop
.L0041EA80:
/* 01EA80 0041EA80 8E100000 */  lw          $s0, 0x0($s0)
/* 01EA84 0041EA84 00000000 */  nop
/* 01EA88 0041EA88 12000005 */  beqz        $s0, .L0041EAA0
/* 01EA8C 0041EA8C 00000000 */   nop
/* 01EA90 0041EA90 8E0F000C */  lw          $t7, 0xC($s0)
/* 01EA94 0041EA94 00000000 */  nop
/* 01EA98 0041EA98 05E0FFF9 */  bltz        $t7, .L0041EA80
/* 01EA9C 0041EA9C 00000000 */   nop
.L0041EAA0:
/* 01EAA0 0041EAA0 AC900000 */  sw          $s0, 0x0($a0)
.L0041EAA4:
/* 01EAA4 0041EAA4 8F9982C8 */  lw          $t9, %call16(alloc_free)($gp)
/* 01EAA8 0041EAA8 8E300004 */  lw          $s0, 0x4($s1)
/* 01EAAC 0041EAAC 0320F809 */  jalr        $t9
/* 01EAB0 0041EAB0 02202025 */   move       $a0, $s1
/* 01EAB4 0041EAB4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 01EAB8 0041EAB8 1600FFFA */  bnez        $s0, .L0041EAA4
/* 01EABC 0041EABC 02008825 */   move       $s1, $s0
/* 01EAC0 0041EAC0 8FBF0024 */  lw          $ra, 0x24($sp)
.L0041EAC4:
/* 01EAC4 0041EAC4 8FB00018 */  lw          $s0, 0x18($sp)
/* 01EAC8 0041EAC8 8FB1001C */  lw          $s1, 0x1C($sp)
/* 01EACC 0041EACC 03E00008 */  jr          $ra
/* 01EAD0 0041EAD0 27BD0028 */   addiu      $sp, $sp, 0x28
