.section .rodata
glabel STR_100059BC
/* 0249BC 100059BC */ .asciz "identifer expected"
                      .balign 4

glabel STR_100059D0
/* 0249D0 100059D0 */ .asciz "invalid symbol for .globl "
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040BC84 # 64
# _gp_disp: 0xFC04E3C
.set noreorder; .cpload $t9; # .set reorder
/* 00BC90 0040BC90 27BDFFB0 */  addiu       $sp, $sp, -0x50
/* 00BC94 0040BC94 8F828378 */  lw          $v0, %got(Tokench)($gp)
/* 00BC98 0040BC98 AFB70030 */  sw          $s7, 0x30($sp)
/* 00BC9C 0040BC9C 8F978050 */  lw          $s7, %got(STR_100059BC)($gp)
/* 00BCA0 0040BCA0 AFB2001C */  sw          $s2, 0x1C($sp)
/* 00BCA4 0040BCA4 AFB10018 */  sw          $s1, 0x18($sp)
/* 00BCA8 0040BCA8 AFB00014 */  sw          $s0, 0x14($sp)
/* 00BCAC 0040BCAC AFBE0038 */  sw          $fp, 0x38($sp)
/* 00BCB0 0040BCB0 AFB6002C */  sw          $s6, 0x2C($sp)
/* 00BCB4 0040BCB4 AFB50028 */  sw          $s5, 0x28($sp)
/* 00BCB8 0040BCB8 AFB40024 */  sw          $s4, 0x24($sp)
/* 00BCBC 0040BCBC AFB30020 */  sw          $s3, 0x20($sp)
/* 00BCC0 0040BCC0 8F90837C */  lw          $s0, %got(Tstring)($gp)
/* 00BCC4 0040BCC4 8F9183A0 */  lw          $s1, %got(binasm_rec)($gp)
/* 00BCC8 0040BCC8 8F928378 */  lw          $s2, %got(Tokench)($gp)
/* 00BCCC 0040BCCC 90420000 */  lbu         $v0, 0x0($v0)
/* 00BCD0 0040BCD0 AFBF003C */  sw          $ra, 0x3C($sp)
/* 00BCD4 0040BCD4 AFBC0034 */  sw          $gp, 0x34($sp)
/* 00BCD8 0040BCD8 2413002C */  addiu       $s3, $zero, 0x2C
/* 00BCDC 0040BCDC 27B4004C */  addiu       $s4, $sp, 0x4C
/* 00BCE0 0040BCE0 27B50048 */  addiu       $s5, $sp, 0x48
/* 00BCE4 0040BCE4 24160069 */  addiu       $s6, $zero, 0x69
/* 00BCE8 0040BCE8 241E0023 */  addiu       $fp, $zero, 0x23
/* 00BCEC 0040BCEC 26F759BC */  addiu       $s7, $s7, %lo(STR_100059BC)
.L0040BCF0:
/* 00BCF0 0040BCF0 12C20008 */  beq         $s6, $v0, .L0040BD14
/* 00BCF4 0040BCF4 02E02025 */   move       $a0, $s7
/* 00BCF8 0040BCF8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00BCFC 0040BCFC 00002825 */  move        $a1, $zero
/* 00BD00 0040BD00 0320F809 */  jalr        $t9
/* 00BD04 0040BD04 24060001 */   addiu      $a2, $zero, 0x1
/* 00BD08 0040BD08 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BD0C 0040BD0C 10000053 */  b           .L0040BE5C
/* 00BD10 0040BD10 92420000 */   lbu        $v0, 0x0($s2)
.L0040BD14:
/* 00BD14 0040BD14 8F99816C */  lw          $t9, %call16(LookUp)($gp)
/* 00BD18 0040BD18 02002025 */  move        $a0, $s0
/* 00BD1C 0040BD1C 0320F809 */  jalr        $t9
/* 00BD20 0040BD20 02802825 */   move       $a1, $s4
/* 00BD24 0040BD24 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BD28 0040BD28 14400007 */  bnez        $v0, .L0040BD48
/* 00BD2C 0040BD2C 02002025 */   move       $a0, $s0
/* 00BD30 0040BD30 8F99818C */  lw          $t9, %call16(EnterSym)($gp)
/* 00BD34 0040BD34 02802825 */  move        $a1, $s4
/* 00BD38 0040BD38 0320F809 */  jalr        $t9
/* 00BD3C 0040BD3C 24060001 */   addiu      $a2, $zero, 0x1
/* 00BD40 0040BD40 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BD44 0040BD44 00000000 */  nop
.L0040BD48:
/* 00BD48 0040BD48 8FAE004C */  lw          $t6, 0x4C($sp)
/* 00BD4C 0040BD4C 8F998150 */  lw          $t9, %call16(sym_define)($gp)
/* 00BD50 0040BD50 8DC40018 */  lw          $a0, 0x18($t6)
/* 00BD54 0040BD54 24050022 */  addiu       $a1, $zero, 0x22
/* 00BD58 0040BD58 0320F809 */  jalr        $t9
/* 00BD5C 0040BD5C 00003025 */   move       $a2, $zero
/* 00BD60 0040BD60 8FAF004C */  lw          $t7, 0x4C($sp)
/* 00BD64 0040BD64 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BD68 0040BD68 8DF80010 */  lw          $t8, 0x10($t7)
/* 00BD6C 0040BD6C 24010003 */  addiu       $at, $zero, 0x3
/* 00BD70 0040BD70 17010032 */  bne         $t8, $at, .L0040BE3C
/* 00BD74 0040BD74 02002825 */   move       $a1, $s0
/* 00BD78 0040BD78 92280005 */  lbu         $t0, 0x5($s1)
/* 00BD7C 0040BD7C 8DF90018 */  lw          $t9, 0x18($t7)
/* 00BD80 0040BD80 3109FFC0 */  andi        $t1, $t0, 0xFFC0
/* 00BD84 0040BD84 352A0012 */  ori         $t2, $t1, 0x12
/* 00BD88 0040BD88 A22A0005 */  sb          $t2, 0x5($s1)
/* 00BD8C 0040BD8C AE390000 */  sw          $t9, 0x0($s1)
/* 00BD90 0040BD90 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 00BD94 0040BD94 00000000 */  nop
/* 00BD98 0040BD98 0320F809 */  jalr        $t9
/* 00BD9C 0040BD9C 00000000 */   nop
/* 00BDA0 0040BDA0 924B0000 */  lbu         $t3, 0x0($s2)
/* 00BDA4 0040BDA4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BDA8 0040BDA8 166B0007 */  bne         $s3, $t3, .L0040BDC8
/* 00BDAC 0040BDAC 00000000 */   nop
/* 00BDB0 0040BDB0 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 00BDB4 0040BDB4 00000000 */  nop
/* 00BDB8 0040BDB8 0320F809 */  jalr        $t9
/* 00BDBC 0040BDBC 00000000 */   nop
/* 00BDC0 0040BDC0 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BDC4 0040BDC4 00000000 */  nop
.L0040BDC8:
/* 00BDC8 0040BDC8 8F99816C */  lw          $t9, %call16(LookUp)($gp)
/* 00BDCC 0040BDCC 02002025 */  move        $a0, $s0
/* 00BDD0 0040BDD0 0320F809 */  jalr        $t9
/* 00BDD4 0040BDD4 02A02825 */   move       $a1, $s5
/* 00BDD8 0040BDD8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BDDC 0040BDDC 14400007 */  bnez        $v0, .L0040BDFC
/* 00BDE0 0040BDE0 02002025 */   move       $a0, $s0
/* 00BDE4 0040BDE4 8F99818C */  lw          $t9, %call16(EnterSym)($gp)
/* 00BDE8 0040BDE8 02A02825 */  move        $a1, $s5
/* 00BDEC 0040BDEC 0320F809 */  jalr        $t9
/* 00BDF0 0040BDF0 24060001 */   addiu      $a2, $zero, 0x1
/* 00BDF4 0040BDF4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BDF8 0040BDF8 00000000 */  nop
.L0040BDFC:
/* 00BDFC 0040BDFC 8FAC0048 */  lw          $t4, 0x48($sp)
/* 00BE00 0040BE00 8FAD004C */  lw          $t5, 0x4C($sp)
/* 00BE04 0040BE04 00000000 */  nop
/* 00BE08 0040BE08 118D0004 */  beq         $t4, $t5, .L0040BE1C
/* 00BE0C 0040BE0C 00000000 */   nop
/* 00BE10 0040BE10 8D8E0018 */  lw          $t6, 0x18($t4)
/* 00BE14 0040BE14 10000002 */  b           .L0040BE20
/* 00BE18 0040BE18 AE2E0008 */   sw         $t6, 0x8($s1)
.L0040BE1C:
/* 00BE1C 0040BE1C AE200008 */  sw          $zero, 0x8($s1)
.L0040BE20:
/* 00BE20 0040BE20 8F9981A8 */  lw          $t9, %call16(put_binasmfyle)($gp)
/* 00BE24 0040BE24 00000000 */  nop
/* 00BE28 0040BE28 0320F809 */  jalr        $t9
/* 00BE2C 0040BE2C 00000000 */   nop
/* 00BE30 0040BE30 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BE34 0040BE34 10000009 */  b           .L0040BE5C
/* 00BE38 0040BE38 92420000 */   lbu        $v0, 0x0($s2)
.L0040BE3C:
/* 00BE3C 0040BE3C 8F848050 */  lw          $a0, %got(STR_100059D0)($gp)
/* 00BE40 0040BE40 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00BE44 0040BE44 24060001 */  addiu       $a2, $zero, 0x1
/* 00BE48 0040BE48 0320F809 */  jalr        $t9
/* 00BE4C 0040BE4C 248459D0 */   addiu      $a0, $a0, %lo(STR_100059D0)
/* 00BE50 0040BE50 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BE54 0040BE54 00000000 */  nop
/* 00BE58 0040BE58 92420000 */  lbu         $v0, 0x0($s2)
.L0040BE5C:
/* 00BE5C 0040BE5C 00000000 */  nop
/* 00BE60 0040BE60 13C20008 */  beq         $fp, $v0, .L0040BE84
/* 00BE64 0040BE64 00000000 */   nop
/* 00BE68 0040BE68 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 00BE6C 0040BE6C 00000000 */  nop
/* 00BE70 0040BE70 0320F809 */  jalr        $t9
/* 00BE74 0040BE74 00000000 */   nop
/* 00BE78 0040BE78 8FBC0034 */  lw          $gp, 0x34($sp)
/* 00BE7C 0040BE7C 92420000 */  lbu         $v0, 0x0($s2)
/* 00BE80 0040BE80 00000000 */  nop
.L0040BE84:
/* 00BE84 0040BE84 1262FF9A */  beq         $s3, $v0, .L0040BCF0
/* 00BE88 0040BE88 00000000 */   nop
/* 00BE8C 0040BE8C 8FBF003C */  lw          $ra, 0x3C($sp)
/* 00BE90 0040BE90 8FB00014 */  lw          $s0, 0x14($sp)
/* 00BE94 0040BE94 8FB10018 */  lw          $s1, 0x18($sp)
/* 00BE98 0040BE98 8FB2001C */  lw          $s2, 0x1C($sp)
/* 00BE9C 0040BE9C 8FB30020 */  lw          $s3, 0x20($sp)
/* 00BEA0 0040BEA0 8FB40024 */  lw          $s4, 0x24($sp)
/* 00BEA4 0040BEA4 8FB50028 */  lw          $s5, 0x28($sp)
/* 00BEA8 0040BEA8 8FB6002C */  lw          $s6, 0x2C($sp)
/* 00BEAC 0040BEAC 8FB70030 */  lw          $s7, 0x30($sp)
/* 00BEB0 0040BEB0 8FBE0038 */  lw          $fp, 0x38($sp)
/* 00BEB4 0040BEB4 03E00008 */  jr          $ra
/* 00BEB8 0040BEB8 27BD0050 */   addiu      $sp, $sp, 0x50
