.section .rodata
glabel STR_10005A78
/* 024A78 10005A78 */ .asciz "identifier expected"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040C830 # 75
# _gp_disp: 0xFC04290
.set noreorder; .cpload $t9; # .set reorder
/* 00C83C 0040C83C 8F8E8344 */  lw          $t6, %got(LastLabel)($gp)
/* 00C840 0040C840 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 00C844 0040C844 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00C848 0040C848 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00C84C 0040C84C AFBC0018 */  sw          $gp, 0x18($sp)
/* 00C850 0040C850 11C00009 */  beqz        $t6, .L0040C878
/* 00C854 0040C854 00802825 */   move       $a1, $a0
/* 00C858 0040C858 8F998014 */  lw          $t9, %got(func_00405574)($gp)
/* 00C85C 0040C85C 00002025 */  move        $a0, $zero
/* 00C860 0040C860 27395574 */  addiu       $t9, $t9, %lo(func_00405574)
/* 00C864 0040C864 0320F809 */  jalr        $t9
/* 00C868 0040C868 AFA50020 */   sw         $a1, 0x20($sp)
/* 00C86C 0040C86C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C870 0040C870 8FA50020 */  lw          $a1, 0x20($sp)
/* 00C874 0040C874 00000000 */  nop
.L0040C878:
/* 00C878 0040C878 8F81833C */  lw          $at, %got(isStruct)($gp)
/* 00C87C 0040C87C 8F8383A0 */  lw          $v1, %got(binasm_rec)($gp)
/* 00C880 0040C880 AC200000 */  sw          $zero, 0x0($at)
/* 00C884 0040C884 90790005 */  lbu         $t9, 0x5($v1)
/* 00C888 0040C888 30B8003F */  andi        $t8, $a1, 0x3F
/* 00C88C 0040C88C 3328FFC0 */  andi        $t0, $t9, 0xFFC0
/* 00C890 0040C890 03084825 */  or          $t1, $t8, $t0
/* 00C894 0040C894 24010024 */  addiu       $at, $zero, 0x24
/* 00C898 0040C898 14A10016 */  bne         $a1, $at, .L0040C8F4
/* 00C89C 0040C89C A0690005 */   sb         $t1, 0x5($v1)
/* 00C8A0 0040C8A0 8F8A8378 */  lw          $t2, %got(Tokench)($gp)
/* 00C8A4 0040C8A4 24010069 */  addiu       $at, $zero, 0x69
/* 00C8A8 0040C8A8 914A0000 */  lbu         $t2, 0x0($t2)
/* 00C8AC 0040C8AC 00002825 */  move        $a1, $zero
/* 00C8B0 0040C8B0 15410008 */  bne         $t2, $at, .L0040C8D4
/* 00C8B4 0040C8B4 00000000 */   nop
/* 00C8B8 0040C8B8 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 00C8BC 0040C8BC 00000000 */  nop
/* 00C8C0 0040C8C0 0320F809 */  jalr        $t9
/* 00C8C4 0040C8C4 00000000 */   nop
/* 00C8C8 0040C8C8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C8CC 0040C8CC 10000013 */  b           .L0040C91C
/* 00C8D0 0040C8D0 8FBF001C */   lw         $ra, 0x1C($sp)
.L0040C8D4:
/* 00C8D4 0040C8D4 8F848050 */  lw          $a0, %got(STR_10005A78)($gp)
/* 00C8D8 0040C8D8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00C8DC 0040C8DC 24060001 */  addiu       $a2, $zero, 0x1
/* 00C8E0 0040C8E0 0320F809 */  jalr        $t9
/* 00C8E4 0040C8E4 24845A78 */   addiu      $a0, $a0, %lo(STR_10005A78)
/* 00C8E8 0040C8E8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C8EC 0040C8EC 1000000B */  b           .L0040C91C
/* 00C8F0 0040C8F0 8FBF001C */   lw         $ra, 0x1C($sp)
.L0040C8F4:
/* 00C8F4 0040C8F4 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 00C8F8 0040C8F8 00000000 */  nop
/* 00C8FC 0040C8FC 0320F809 */  jalr        $t9
/* 00C900 0040C900 00000000 */   nop
/* 00C904 0040C904 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C908 0040C908 00000000 */  nop
/* 00C90C 0040C90C 8F8383A0 */  lw          $v1, %got(binasm_rec)($gp)
/* 00C910 0040C910 00000000 */  nop
/* 00C914 0040C914 AC620000 */  sw          $v0, 0x0($v1)
/* 00C918 0040C918 8FBF001C */  lw          $ra, 0x1C($sp)
.L0040C91C:
/* 00C91C 0040C91C 27BD0020 */  addiu       $sp, $sp, 0x20
/* 00C920 0040C920 03E00008 */  jr          $ra
/* 00C924 0040C924 00000000 */   nop
