.section .rodata
glabel STR_100056D4
/* 0246D4 100056D4 */ .asciz "version stamp does not match"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040A208 # 47
# _gp_disp: 0xFC068B8
.set noreorder; .cpload $t9; # .set reorder
/* 00A214 0040A214 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 00A218 0040A218 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 00A21C 0040A21C AFBF001C */  sw          $ra, 0x1C($sp)
/* 00A220 0040A220 0320F809 */  jalr        $t9
/* 00A224 0040A224 AFBC0018 */   sw         $gp, 0x18($sp)
/* 00A228 0040A228 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A22C 0040A22C AFA20024 */  sw          $v0, 0x24($sp)
/* 00A230 0040A230 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 00A234 0040A234 00000000 */  nop
/* 00A238 0040A238 0320F809 */  jalr        $t9
/* 00A23C 0040A23C 00000000 */   nop
/* 00A240 0040A240 8FAE0024 */  lw          $t6, 0x24($sp)
/* 00A244 0040A244 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A248 0040A248 24010003 */  addiu       $at, $zero, 0x3
/* 00A24C 0040A24C 11C10008 */  beq         $t6, $at, .L0040A270
/* 00A250 0040A250 00002825 */   move       $a1, $zero
/* 00A254 0040A254 8F848050 */  lw          $a0, %got(STR_100056D4)($gp)
/* 00A258 0040A258 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00A25C 0040A25C 24060002 */  addiu       $a2, $zero, 0x2
/* 00A260 0040A260 0320F809 */  jalr        $t9
/* 00A264 0040A264 248456D4 */   addiu      $a0, $a0, %lo(STR_100056D4)
/* 00A268 0040A268 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A26C 0040A26C 00000000 */  nop
.L0040A270:
/* 00A270 0040A270 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00A274 0040A274 27BD0028 */  addiu       $sp, $sp, 0x28
/* 00A278 0040A278 03E00008 */  jr          $ra
/* 00A27C 0040A27C 00000000 */   nop
