.section .rodata
glabel STR_10005730
/* 024730 10005730 */ .asciz ".shift_addr expression not 1"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040A530 # 50
# _gp_disp: 0xFC06590
.set noreorder; .cpload $t9; # .set reorder
/* 00A53C 0040A53C 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 00A540 0040A540 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 00A544 0040A544 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00A548 0040A548 0320F809 */  jalr        $t9
/* 00A54C 0040A54C AFBC0018 */   sw         $gp, 0x18($sp)
/* 00A550 0040A550 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A554 0040A554 24010001 */  addiu       $at, $zero, 0x1
/* 00A558 0040A558 1041000B */  beq         $v0, $at, .L0040A588
/* 00A55C 0040A55C 00401825 */   move       $v1, $v0
/* 00A560 0040A560 8F848050 */  lw          $a0, %got(STR_10005730)($gp)
/* 00A564 0040A564 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00A568 0040A568 00002825 */  move        $a1, $zero
/* 00A56C 0040A56C 24060001 */  addiu       $a2, $zero, 0x1
/* 00A570 0040A570 AFA20024 */  sw          $v0, 0x24($sp)
/* 00A574 0040A574 0320F809 */  jalr        $t9
/* 00A578 0040A578 24845730 */   addiu      $a0, $a0, %lo(STR_10005730)
/* 00A57C 0040A57C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A580 0040A580 8FA30024 */  lw          $v1, 0x24($sp)
/* 00A584 0040A584 00000000 */  nop
.L0040A588:
/* 00A588 0040A588 8F8283A0 */  lw          $v0, %got(binasm_rec)($gp)
/* 00A58C 0040A58C 00000000 */  nop
/* 00A590 0040A590 904E0005 */  lbu         $t6, 0x5($v0)
/* 00A594 0040A594 AC400000 */  sw          $zero, 0x0($v0)
/* 00A598 0040A598 31CFFFC0 */  andi        $t7, $t6, 0xFFC0
/* 00A59C 0040A59C 35F80039 */  ori         $t8, $t7, 0x39
/* 00A5A0 0040A5A0 A0580005 */  sb          $t8, 0x5($v0)
/* 00A5A4 0040A5A4 AC430008 */  sw          $v1, 0x8($v0)
/* 00A5A8 0040A5A8 8F9981A8 */  lw          $t9, %call16(put_binasmfyle)($gp)
/* 00A5AC 0040A5AC 00000000 */  nop
/* 00A5B0 0040A5B0 0320F809 */  jalr        $t9
/* 00A5B4 0040A5B4 00000000 */   nop
/* 00A5B8 0040A5B8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00A5BC 0040A5BC 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00A5C0 0040A5C0 8F8183B4 */  lw          $at, %got(shftaddr)($gp)
/* 00A5C4 0040A5C4 24190001 */  addiu       $t9, $zero, 0x1
/* 00A5C8 0040A5C8 27BD0028 */  addiu       $sp, $sp, 0x28
/* 00A5CC 0040A5CC 03E00008 */  jr          $ra
/* 00A5D0 0040A5D0 AC390000 */   sw         $t9, 0x0($at)
