/* Generated by spimdisasm 1.10.3 */

glabel func_0040E180 # 86
# _gp_disp: 0xFC02940
.set noreorder; .cpload $t9; # .set reorder
/* 00E18C 0040E18C 27BDFEE0 */  addiu       $sp, $sp, -0x120
/* 00E190 0040E190 AFA50124 */  sw          $a1, 0x124($sp)
/* 00E194 0040E194 8F9980EC */  lw          $t9, %call16(sprintf)($gp)
/* 00E198 0040E198 AFA60128 */  sw          $a2, 0x128($sp)
/* 00E19C 0040E19C 8FA60124 */  lw          $a2, 0x124($sp)
/* 00E1A0 0040E1A0 00802825 */  move        $a1, $a0
/* 00E1A4 0040E1A4 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00E1A8 0040E1A8 AFA40120 */  sw          $a0, 0x120($sp)
/* 00E1AC 0040E1AC AFBC0018 */  sw          $gp, 0x18($sp)
/* 00E1B0 0040E1B0 0320F809 */  jalr        $t9
/* 00E1B4 0040E1B4 27A40020 */   addiu      $a0, $sp, 0x20
/* 00E1B8 0040E1B8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00E1BC 0040E1BC 8FA50128 */  lw          $a1, 0x128($sp)
/* 00E1C0 0040E1C0 8F9981CC */  lw          $t9, %call16(postcerror)($gp)
/* 00E1C4 0040E1C4 27A40020 */  addiu       $a0, $sp, 0x20
/* 00E1C8 0040E1C8 0320F809 */  jalr        $t9
/* 00E1CC 0040E1CC 00000000 */   nop
/* 00E1D0 0040E1D0 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00E1D4 0040E1D4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00E1D8 0040E1D8 03E00008 */  jr          $ra
/* 00E1DC 0040E1DC 27BD0120 */   addiu      $sp, $sp, 0x120
