.section .rodata
glabel STR_1000677C
/* 02577C 1000677C */ .asciz "Right paren expected"
                      .balign 4

glabel STR_10006794
/* 025794 10006794 */ .asciz "undefined symbol in expression"
                      .balign 4

glabel STR_100067B4
/* 0257B4 100067B4 */ .asciz "Symbol must have absolute value"
                      .balign 4

glabel STR_100067D4
/* 0257D4 100067D4 */ .asciz "String within expression may have only one character"
                      .balign 4

glabel STR_1000680C
/* 02580C 1000680C */ .asciz "Invalid symbol in expression"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_00411B84 # 123
# _gp_disp: 0xFBFEF3C
.set noreorder; .cpload $t9; # .set reorder
/* 011B90 00411B90 27BDFFB8 */  addiu       $sp, $sp, -0x48
/* 011B94 00411B94 8F838378 */  lw          $v1, %got(Tokench)($gp)
/* 011B98 00411B98 240E0000 */  addiu       $t6, $zero, 0x0
/* 011B9C 00411B9C 90630000 */  lbu         $v1, 0x0($v1)
/* 011BA0 00411BA0 240F0000 */  addiu       $t7, $zero, 0x0
/* 011BA4 00411BA4 2401002D */  addiu       $at, $zero, 0x2D
/* 011BA8 00411BA8 AFBF001C */  sw          $ra, 0x1C($sp)
/* 011BAC 00411BAC AFBC0018 */  sw          $gp, 0x18($sp)
/* 011BB0 00411BB0 AFAF003C */  sw          $t7, 0x3C($sp)
/* 011BB4 00411BB4 AFAE0038 */  sw          $t6, 0x38($sp)
/* 011BB8 00411BB8 AFA00044 */  sw          $zero, 0x44($sp)
/* 011BBC 00411BBC 1461000C */  bne         $v1, $at, .L00411BF0
/* 011BC0 00411BC0 AFA00040 */   sw         $zero, 0x40($sp)
/* 011BC4 00411BC4 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 011BC8 00411BC8 24180001 */  addiu       $t8, $zero, 0x1
/* 011BCC 00411BCC 0320F809 */  jalr        $t9
/* 011BD0 00411BD0 AFB80044 */   sw         $t8, 0x44($sp)
/* 011BD4 00411BD4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011BD8 00411BD8 00000000 */  nop
/* 011BDC 00411BDC 8F838378 */  lw          $v1, %got(Tokench)($gp)
/* 011BE0 00411BE0 00000000 */  nop
/* 011BE4 00411BE4 90630000 */  lbu         $v1, 0x0($v1)
/* 011BE8 00411BE8 1000001E */  b           .L00411C64
/* 011BEC 00411BEC 24010022 */   addiu      $at, $zero, 0x22
.L00411BF0:
/* 011BF0 00411BF0 2401002B */  addiu       $at, $zero, 0x2B
/* 011BF4 00411BF4 1461000D */  bne         $v1, $at, .L00411C2C
/* 011BF8 00411BF8 2401007E */   addiu      $at, $zero, 0x7E
/* 011BFC 00411BFC 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 011C00 00411C00 00000000 */  nop
/* 011C04 00411C04 0320F809 */  jalr        $t9
/* 011C08 00411C08 00000000 */   nop
/* 011C0C 00411C0C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011C10 00411C10 00000000 */  nop
/* 011C14 00411C14 8F838378 */  lw          $v1, %got(Tokench)($gp)
/* 011C18 00411C18 00000000 */  nop
/* 011C1C 00411C1C 90630000 */  lbu         $v1, 0x0($v1)
/* 011C20 00411C20 10000010 */  b           .L00411C64
/* 011C24 00411C24 24010022 */   addiu      $at, $zero, 0x22
/* 011C28 00411C28 2401007E */  addiu       $at, $zero, 0x7E
.L00411C2C:
/* 011C2C 00411C2C 1461000C */  bne         $v1, $at, .L00411C60
/* 011C30 00411C30 24190001 */   addiu      $t9, $zero, 0x1
/* 011C34 00411C34 AFB90040 */  sw          $t9, 0x40($sp)
/* 011C38 00411C38 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 011C3C 00411C3C 00000000 */  nop
/* 011C40 00411C40 0320F809 */  jalr        $t9
/* 011C44 00411C44 00000000 */   nop
/* 011C48 00411C48 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011C4C 00411C4C 00000000 */  nop
/* 011C50 00411C50 8F838378 */  lw          $v1, %got(Tokench)($gp)
/* 011C54 00411C54 00000000 */  nop
/* 011C58 00411C58 90630000 */  lbu         $v1, 0x0($v1)
/* 011C5C 00411C5C 00000000 */  nop
.L00411C60:
/* 011C60 00411C60 24010022 */  addiu       $at, $zero, 0x22
.L00411C64:
/* 011C64 00411C64 10610056 */  beq         $v1, $at, .L00411DC0
/* 011C68 00411C68 24180000 */   addiu      $t8, $zero, 0x0
/* 011C6C 00411C6C 24010028 */  addiu       $at, $zero, 0x28
/* 011C70 00411C70 10610009 */  beq         $v1, $at, .L00411C98
/* 011C74 00411C74 24010064 */   addiu      $at, $zero, 0x64
/* 011C78 00411C78 10610047 */  beq         $v1, $at, .L00411D98
/* 011C7C 00411C7C 24010068 */   addiu      $at, $zero, 0x68
/* 011C80 00411C80 10610045 */  beq         $v1, $at, .L00411D98
/* 011C84 00411C84 24010069 */   addiu      $at, $zero, 0x69
/* 011C88 00411C88 1061001E */  beq         $v1, $at, .L00411D04
/* 011C8C 00411C8C 00002825 */   move       $a1, $zero
/* 011C90 00411C90 1000005D */  b           .L00411E08
/* 011C94 00411C94 00000000 */   nop
.L00411C98:
/* 011C98 00411C98 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 011C9C 00411C9C 00000000 */  nop
/* 011CA0 00411CA0 0320F809 */  jalr        $t9
/* 011CA4 00411CA4 00000000 */   nop
/* 011CA8 00411CA8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011CAC 00411CAC 00000000 */  nop
/* 011CB0 00411CB0 8F998018 */  lw          $t9, %got(func_00412548)($gp)
/* 011CB4 00411CB4 00000000 */  nop
/* 011CB8 00411CB8 27392548 */  addiu       $t9, $t9, %lo(func_00412548)
/* 011CBC 00411CBC 0320F809 */  jalr        $t9
/* 011CC0 00411CC0 00000000 */   nop
/* 011CC4 00411CC4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011CC8 00411CC8 24010029 */  addiu       $at, $zero, 0x29
/* 011CCC 00411CCC 8F888378 */  lw          $t0, %got(Tokench)($gp)
/* 011CD0 00411CD0 AFA20038 */  sw          $v0, 0x38($sp)
/* 011CD4 00411CD4 91080000 */  lbu         $t0, 0x0($t0)
/* 011CD8 00411CD8 AFA3003C */  sw          $v1, 0x3C($sp)
/* 011CDC 00411CDC 11010057 */  beq         $t0, $at, .L00411E3C
/* 011CE0 00411CE0 00002825 */   move       $a1, $zero
/* 011CE4 00411CE4 8F848050 */  lw          $a0, %got(STR_1000677C)($gp)
/* 011CE8 00411CE8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 011CEC 00411CEC 24060001 */  addiu       $a2, $zero, 0x1
/* 011CF0 00411CF0 0320F809 */  jalr        $t9
/* 011CF4 00411CF4 2484677C */   addiu      $a0, $a0, %lo(STR_1000677C)
/* 011CF8 00411CF8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011CFC 00411CFC 10000050 */  b           .L00411E40
/* 011D00 00411D00 8FA90044 */   lw         $t1, 0x44($sp)
.L00411D04:
/* 011D04 00411D04 8F99816C */  lw          $t9, %call16(LookUp)($gp)
/* 011D08 00411D08 8F84837C */  lw          $a0, %got(Tstring)($gp)
/* 011D0C 00411D0C 0320F809 */  jalr        $t9
/* 011D10 00411D10 27A50034 */   addiu      $a1, $sp, 0x34
/* 011D14 00411D14 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011D18 00411D18 8FA90034 */  lw          $t1, 0x34($sp)
/* 011D1C 00411D1C 8F87837C */  lw          $a3, %got(Tstring)($gp)
/* 011D20 00411D20 14400009 */  bnez        $v0, .L00411D48
/* 011D24 00411D24 00002825 */   move       $a1, $zero
/* 011D28 00411D28 8F848050 */  lw          $a0, %got(STR_10006794)($gp)
/* 011D2C 00411D2C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 011D30 00411D30 24060001 */  addiu       $a2, $zero, 0x1
/* 011D34 00411D34 0320F809 */  jalr        $t9
/* 011D38 00411D38 24846794 */   addiu      $a0, $a0, %lo(STR_10006794)
/* 011D3C 00411D3C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011D40 00411D40 1000003F */  b           .L00411E40
/* 011D44 00411D44 8FA90044 */   lw         $t1, 0x44($sp)
.L00411D48:
/* 011D48 00411D48 8D2A0010 */  lw          $t2, 0x10($t1)
/* 011D4C 00411D4C 24010004 */  addiu       $at, $zero, 0x4
/* 011D50 00411D50 11410009 */  beq         $t2, $at, .L00411D78
/* 011D54 00411D54 00E02825 */   move       $a1, $a3
/* 011D58 00411D58 8F848050 */  lw          $a0, %got(STR_100067B4)($gp)
/* 011D5C 00411D5C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 011D60 00411D60 24060001 */  addiu       $a2, $zero, 0x1
/* 011D64 00411D64 0320F809 */  jalr        $t9
/* 011D68 00411D68 248467B4 */   addiu      $a0, $a0, %lo(STR_100067B4)
/* 011D6C 00411D6C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011D70 00411D70 10000033 */  b           .L00411E40
/* 011D74 00411D74 8FA90044 */   lw         $t1, 0x44($sp)
.L00411D78:
/* 011D78 00411D78 8FAB0034 */  lw          $t3, 0x34($sp)
/* 011D7C 00411D7C 00000000 */  nop
/* 011D80 00411D80 8D6C0008 */  lw          $t4, 0x8($t3)
/* 011D84 00411D84 00000000 */  nop
/* 011D88 00411D88 000C77C3 */  sra         $t6, $t4, 31
/* 011D8C 00411D8C AFAE0038 */  sw          $t6, 0x38($sp)
/* 011D90 00411D90 1000002A */  b           .L00411E3C
/* 011D94 00411D94 AFAC003C */   sw         $t4, 0x3C($sp)
.L00411D98:
/* 011D98 00411D98 8F998018 */  lw          $t9, %got(func_0040F77C)($gp)
/* 011D9C 00411D9C 8F84837C */  lw          $a0, %got(Tstring)($gp)
/* 011DA0 00411DA0 8FA50044 */  lw          $a1, 0x44($sp)
/* 011DA4 00411DA4 2739F77C */  addiu       $t9, $t9, %lo(func_0040F77C)
/* 011DA8 00411DA8 0320F809 */  jalr        $t9
/* 011DAC 00411DAC AFA00044 */   sw         $zero, 0x44($sp)
/* 011DB0 00411DB0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011DB4 00411DB4 AFA20038 */  sw          $v0, 0x38($sp)
/* 011DB8 00411DB8 10000020 */  b           .L00411E3C
/* 011DBC 00411DBC AFA3003C */   sw         $v1, 0x3C($sp)
.L00411DC0:
/* 011DC0 00411DC0 8F888380 */  lw          $t0, %got(Tstringlength)($gp)
/* 011DC4 00411DC4 8F87837C */  lw          $a3, %got(Tstring)($gp)
/* 011DC8 00411DC8 8D080000 */  lw          $t0, 0x0($t0)
/* 011DCC 00411DCC 90ED0000 */  lbu         $t5, 0x0($a3)
/* 011DD0 00411DD0 29010002 */  slti        $at, $t0, 0x2
/* 011DD4 00411DD4 AFB80038 */  sw          $t8, 0x38($sp)
/* 011DD8 00411DD8 AFA00044 */  sw          $zero, 0x44($sp)
/* 011DDC 00411DDC 14200017 */  bnez        $at, .L00411E3C
/* 011DE0 00411DE0 AFAD003C */   sw         $t5, 0x3C($sp)
/* 011DE4 00411DE4 8F848050 */  lw          $a0, %got(STR_100067D4)($gp)
/* 011DE8 00411DE8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 011DEC 00411DEC 00E02825 */  move        $a1, $a3
/* 011DF0 00411DF0 24060001 */  addiu       $a2, $zero, 0x1
/* 011DF4 00411DF4 0320F809 */  jalr        $t9
/* 011DF8 00411DF8 248467D4 */   addiu      $a0, $a0, %lo(STR_100067D4)
/* 011DFC 00411DFC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011E00 00411E00 1000000F */  b           .L00411E40
/* 011E04 00411E04 8FA90044 */   lw         $t1, 0x44($sp)
.L00411E08:
/* 011E08 00411E08 8F848050 */  lw          $a0, %got(STR_1000680C)($gp)
/* 011E0C 00411E0C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 011E10 00411E10 24060001 */  addiu       $a2, $zero, 0x1
/* 011E14 00411E14 0320F809 */  jalr        $t9
/* 011E18 00411E18 2484680C */   addiu      $a0, $a0, %lo(STR_1000680C)
/* 011E1C 00411E1C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011E20 00411E20 00000000 */  nop
/* 011E24 00411E24 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 011E28 00411E28 00000000 */  nop
/* 011E2C 00411E2C 0320F809 */  jalr        $t9
/* 011E30 00411E30 00000000 */   nop
/* 011E34 00411E34 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011E38 00411E38 00000000 */  nop
.L00411E3C:
/* 011E3C 00411E3C 8FA90044 */  lw          $t1, 0x44($sp)
.L00411E40:
/* 011E40 00411E40 8FAE0040 */  lw          $t6, 0x40($sp)
/* 011E44 00411E44 1120000A */  beqz        $t1, .L00411E70
/* 011E48 00411E48 00000000 */   nop
/* 011E4C 00411E4C 8FAA0038 */  lw          $t2, 0x38($sp)
/* 011E50 00411E50 8FAB003C */  lw          $t3, 0x3C($sp)
/* 011E54 00411E54 01406027 */  not         $t4, $t2
/* 011E58 00411E58 2D610001 */  sltiu       $at, $t3, 0x1
/* 011E5C 00411E5C 01816021 */  addu        $t4, $t4, $at
/* 011E60 00411E60 000B6823 */  negu        $t5, $t3
/* 011E64 00411E64 AFAD002C */  sw          $t5, 0x2C($sp)
/* 011E68 00411E68 1000000E */  b           .L00411EA4
/* 011E6C 00411E6C AFAC0028 */   sw         $t4, 0x28($sp)
.L00411E70:
/* 011E70 00411E70 11C00009 */  beqz        $t6, .L00411E98
/* 011E74 00411E74 8FAA0038 */   lw         $t2, 0x38($sp)
/* 011E78 00411E78 8FB80038 */  lw          $t8, 0x38($sp)
/* 011E7C 00411E7C 8FB9003C */  lw          $t9, 0x3C($sp)
/* 011E80 00411E80 03004027 */  not         $t0, $t8
/* 011E84 00411E84 03204827 */  not         $t1, $t9
/* 011E88 00411E88 AFA9002C */  sw          $t1, 0x2C($sp)
/* 011E8C 00411E8C 10000005 */  b           .L00411EA4
/* 011E90 00411E90 AFA80028 */   sw         $t0, 0x28($sp)
/* 011E94 00411E94 8FAA0038 */  lw          $t2, 0x38($sp)
.L00411E98:
/* 011E98 00411E98 8FAB003C */  lw          $t3, 0x3C($sp)
/* 011E9C 00411E9C AFAA0028 */  sw          $t2, 0x28($sp)
/* 011EA0 00411EA0 AFAB002C */  sw          $t3, 0x2C($sp)
.L00411EA4:
/* 011EA4 00411EA4 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 011EA8 00411EA8 00000000 */  nop
/* 011EAC 00411EAC 0320F809 */  jalr        $t9
/* 011EB0 00411EB0 00000000 */   nop
/* 011EB4 00411EB4 8FBF001C */  lw          $ra, 0x1C($sp)
/* 011EB8 00411EB8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 011EBC 00411EBC 8FA20028 */  lw          $v0, 0x28($sp)
/* 011EC0 00411EC0 8FA3002C */  lw          $v1, 0x2C($sp)
/* 011EC4 00411EC4 03E00008 */  jr          $ra
/* 011EC8 00411EC8 27BD0048 */   addiu      $sp, $sp, 0x48
