.section .rodata
glabel STR_1000648C
/* 02548C 1000648C */ .asciz "Badly delimited hexadecimal literal"
                      .balign 4

glabel STR_100064B0
/* 0254B0 100064B0 */ .asciz "Hex floating point literal too long"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040FD98 # 110
# _gp_disp: 0xFC00D28
.set noreorder; .cpload $t9; # .set reorder
/* 00FDA4 0040FDA4 8F818378 */  lw          $at, %got(Tokench)($gp)
/* 00FDA8 0040FDA8 240E0068 */  addiu       $t6, $zero, 0x68
/* 00FDAC 0040FDAC A02E0000 */  sb          $t6, 0x0($at)
/* 00FDB0 0040FDB0 8F818384 */  lw          $at, %got(token_tmp)($gp)
/* 00FDB4 0040FDB4 240F0078 */  addiu       $t7, $zero, 0x78
/* 00FDB8 0040FDB8 A02F0001 */  sb          $t7, 0x1($at)
/* 00FDBC 0040FDBC 8F818380 */  lw          $at, %got(Tstringlength)($gp)
/* 00FDC0 0040FDC0 8F828364 */  lw          $v0, %got(nextinline)($gp)
/* 00FDC4 0040FDC4 24180002 */  addiu       $t8, $zero, 0x2
/* 00FDC8 0040FDC8 AC380000 */  sw          $t8, 0x0($at)
/* 00FDCC 0040FDCC 8C590000 */  lw          $t9, 0x0($v0)
/* 00FDD0 0040FDD0 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* 00FDD4 0040FDD4 27280001 */  addiu       $t0, $t9, 0x1
/* 00FDD8 0040FDD8 8F998018 */  lw          $t9, %got(func_0040FC20)($gp)
/* 00FDDC 0040FDDC AFBF001C */  sw          $ra, 0x1C($sp)
/* 00FDE0 0040FDE0 2739FC20 */  addiu       $t9, $t9, %lo(func_0040FC20)
/* 00FDE4 0040FDE4 AFBC0018 */  sw          $gp, 0x18($sp)
/* 00FDE8 0040FDE8 24040010 */  addiu       $a0, $zero, 0x10
/* 00FDEC 0040FDEC 0320F809 */  jalr        $t9
/* 00FDF0 0040FDF0 AC480000 */   sw         $t0, 0x0($v0)
/* 00FDF4 0040FDF4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FDF8 0040FDF8 00402825 */  move        $a1, $v0
/* 00FDFC 0040FDFC 8F838364 */  lw          $v1, %got(nextinline)($gp)
/* 00FE00 0040FE00 8F898360 */  lw          $t1, %got(linelength)($gp)
/* 00FE04 0040FE04 8C630000 */  lw          $v1, 0x0($v1)
/* 00FE08 0040FE08 8D290000 */  lw          $t1, 0x0($t1)
/* 00FE0C 0040FE0C 00000000 */  nop
/* 00FE10 0040FE10 0123082A */  slt         $at, $t1, $v1
/* 00FE14 0040FE14 14200017 */  bnez        $at, .L0040FE74
/* 00FE18 0040FE18 00000000 */   nop
/* 00FE1C 0040FE1C 8F8A8368 */  lw          $t2, %got(line)($gp)
/* 00FE20 0040FE20 2401002E */  addiu       $at, $zero, 0x2E
/* 00FE24 0040FE24 006A5821 */  addu        $t3, $v1, $t2
/* 00FE28 0040FE28 916C0000 */  lbu         $t4, 0x0($t3)
/* 00FE2C 0040FE2C 240D0066 */  addiu       $t5, $zero, 0x66
/* 00FE30 0040FE30 15810010 */  bne         $t4, $at, .L0040FE74
/* 00FE34 0040FE34 00000000 */   nop
/* 00FE38 0040FE38 8F818378 */  lw          $at, %got(Tokench)($gp)
/* 00FE3C 0040FE3C 8F998174 */  lw          $t9, %call16(consume)($gp)
/* 00FE40 0040FE40 AFA2002C */  sw          $v0, 0x2C($sp)
/* 00FE44 0040FE44 0320F809 */  jalr        $t9
/* 00FE48 0040FE48 A02D0000 */   sb         $t5, 0x0($at)
/* 00FE4C 0040FE4C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FE50 0040FE50 24040010 */  addiu       $a0, $zero, 0x10
/* 00FE54 0040FE54 8F998018 */  lw          $t9, %got(func_0040FC20)($gp)
/* 00FE58 0040FE58 00000000 */  nop
/* 00FE5C 0040FE5C 2739FC20 */  addiu       $t9, $t9, %lo(func_0040FC20)
/* 00FE60 0040FE60 0320F809 */  jalr        $t9
/* 00FE64 0040FE64 00000000 */   nop
/* 00FE68 0040FE68 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00FE6C 0040FE6C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FE70 0040FE70 00A22825 */  or          $a1, $a1, $v0
.L0040FE74:
/* 00FE74 0040FE74 10A00068 */  beqz        $a1, .L00410018
/* 00FE78 0040FE78 00000000 */   nop
/* 00FE7C 0040FE7C 8F838364 */  lw          $v1, %got(nextinline)($gp)
/* 00FE80 0040FE80 8F8E8360 */  lw          $t6, %got(linelength)($gp)
/* 00FE84 0040FE84 8C630000 */  lw          $v1, 0x0($v1)
/* 00FE88 0040FE88 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00FE8C 0040FE8C 00000000 */  nop
/* 00FE90 0040FE90 01C3082A */  slt         $at, $t6, $v1
/* 00FE94 0040FE94 14200060 */  bnez        $at, .L00410018
/* 00FE98 0040FE98 00000000 */   nop
/* 00FE9C 0040FE9C 8F8F8368 */  lw          $t7, %got(line)($gp)
/* 00FEA0 0040FEA0 8F99808C */  lw          $t9, %call16(tolower)($gp)
/* 00FEA4 0040FEA4 006FC021 */  addu        $t8, $v1, $t7
/* 00FEA8 0040FEA8 93040000 */  lbu         $a0, 0x0($t8)
/* 00FEAC 0040FEAC 0320F809 */  jalr        $t9
/* 00FEB0 0040FEB0 AFA5002C */   sw         $a1, 0x2C($sp)
/* 00FEB4 0040FEB4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FEB8 0040FEB8 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00FEBC 0040FEBC 8F998364 */  lw          $t9, %got(nextinline)($gp)
/* 00FEC0 0040FEC0 8F888368 */  lw          $t0, %got(line)($gp)
/* 00FEC4 0040FEC4 8F390000 */  lw          $t9, 0x0($t9)
/* 00FEC8 0040FEC8 304900FF */  andi        $t1, $v0, 0xFF
/* 00FECC 0040FECC 24010068 */  addiu       $at, $zero, 0x68
/* 00FED0 0040FED0 03281821 */  addu        $v1, $t9, $t0
/* 00FED4 0040FED4 15210050 */  bne         $t1, $at, .L00410018
/* 00FED8 0040FED8 A0620000 */   sb         $v0, 0x0($v1)
/* 00FEDC 0040FEDC 8F818378 */  lw          $at, %got(Tokench)($gp)
/* 00FEE0 0040FEE0 8F998174 */  lw          $t9, %call16(consume)($gp)
/* 00FEE4 0040FEE4 240A0066 */  addiu       $t2, $zero, 0x66
/* 00FEE8 0040FEE8 0320F809 */  jalr        $t9
/* 00FEEC 0040FEEC A02A0000 */   sb         $t2, 0x0($at)
/* 00FEF0 0040FEF0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FEF4 0040FEF4 240B000A */  addiu       $t3, $zero, 0xA
/* 00FEF8 0040FEF8 8F828360 */  lw          $v0, %got(linelength)($gp)
/* 00FEFC 0040FEFC 8F838364 */  lw          $v1, %got(nextinline)($gp)
/* 00FF00 0040FF00 8C420000 */  lw          $v0, 0x0($v0)
/* 00FF04 0040FF04 8C630000 */  lw          $v1, 0x0($v1)
/* 00FF08 0040FF08 00000000 */  nop
/* 00FF0C 0040FF0C 0043082A */  slt         $at, $v0, $v1
/* 00FF10 0040FF10 10200004 */  beqz        $at, .L0040FF24
/* 00FF14 0040FF14 0062082A */   slt        $at, $v1, $v0
/* 00FF18 0040FF18 1000003F */  b           .L00410018
/* 00FF1C 0040FF1C 00002825 */   move       $a1, $zero
/* 00FF20 0040FF20 0062082A */  slt         $at, $v1, $v0
.L0040FF24:
/* 00FF24 0040FF24 10200020 */  beqz        $at, .L0040FFA8
/* 00FF28 0040FF28 AFAB0024 */   sw         $t3, 0x24($sp)
/* 00FF2C 0040FF2C 8F8C8368 */  lw          $t4, %got(line)($gp)
/* 00FF30 0040FF30 8F99808C */  lw          $t9, %call16(tolower)($gp)
/* 00FF34 0040FF34 006C6821 */  addu        $t5, $v1, $t4
/* 00FF38 0040FF38 91A40001 */  lbu         $a0, 0x1($t5)
/* 00FF3C 0040FF3C 0320F809 */  jalr        $t9
/* 00FF40 0040FF40 00000000 */   nop
/* 00FF44 0040FF44 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FF48 0040FF48 24010030 */  addiu       $at, $zero, 0x30
/* 00FF4C 0040FF4C 8F8E8364 */  lw          $t6, %got(nextinline)($gp)
/* 00FF50 0040FF50 8F8F8368 */  lw          $t7, %got(line)($gp)
/* 00FF54 0040FF54 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00FF58 0040FF58 305900FF */  andi        $t9, $v0, 0xFF
/* 00FF5C 0040FF5C 01CF1821 */  addu        $v1, $t6, $t7
/* 00FF60 0040FF60 90780000 */  lbu         $t8, 0x0($v1)
/* 00FF64 0040FF64 A0620001 */  sb          $v0, 0x1($v1)
/* 00FF68 0040FF68 1701000F */  bne         $t8, $at, .L0040FFA8
/* 00FF6C 0040FF6C 24010078 */   addiu      $at, $zero, 0x78
/* 00FF70 0040FF70 1721000E */  bne         $t9, $at, .L0040FFAC
/* 00FF74 0040FF74 8FA90024 */   lw         $t1, 0x24($sp)
/* 00FF78 0040FF78 8F998174 */  lw          $t9, %call16(consume)($gp)
/* 00FF7C 0040FF7C 24080010 */  addiu       $t0, $zero, 0x10
/* 00FF80 0040FF80 0320F809 */  jalr        $t9
/* 00FF84 0040FF84 AFA80024 */   sw         $t0, 0x24($sp)
/* 00FF88 0040FF88 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FF8C 0040FF8C 00000000 */  nop
/* 00FF90 0040FF90 8F998174 */  lw          $t9, %call16(consume)($gp)
/* 00FF94 0040FF94 00000000 */  nop
/* 00FF98 0040FF98 0320F809 */  jalr        $t9
/* 00FF9C 0040FF9C 00000000 */   nop
/* 00FFA0 0040FFA0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FFA4 0040FFA4 00000000 */  nop
.L0040FFA8:
/* 00FFA8 0040FFA8 8FA90024 */  lw          $t1, 0x24($sp)
.L0040FFAC:
/* 00FFAC 0040FFAC 2401000A */  addiu       $at, $zero, 0xA
/* 00FFB0 0040FFB0 15210012 */  bne         $t1, $at, .L0040FFFC
/* 00FFB4 0040FFB4 00000000 */   nop
/* 00FFB8 0040FFB8 8F8A8364 */  lw          $t2, %got(nextinline)($gp)
/* 00FFBC 0040FFBC 8F8B8368 */  lw          $t3, %got(line)($gp)
/* 00FFC0 0040FFC0 8D4A0000 */  lw          $t2, 0x0($t2)
/* 00FFC4 0040FFC4 2401002B */  addiu       $at, $zero, 0x2B
/* 00FFC8 0040FFC8 014B6021 */  addu        $t4, $t2, $t3
/* 00FFCC 0040FFCC 91820000 */  lbu         $v0, 0x0($t4)
/* 00FFD0 0040FFD0 00000000 */  nop
/* 00FFD4 0040FFD4 10410003 */  beq         $v0, $at, .L0040FFE4
/* 00FFD8 0040FFD8 2401002D */   addiu      $at, $zero, 0x2D
/* 00FFDC 0040FFDC 14410007 */  bne         $v0, $at, .L0040FFFC
/* 00FFE0 0040FFE0 00000000 */   nop
.L0040FFE4:
/* 00FFE4 0040FFE4 8F998174 */  lw          $t9, %call16(consume)($gp)
/* 00FFE8 0040FFE8 00000000 */  nop
/* 00FFEC 0040FFEC 0320F809 */  jalr        $t9
/* 00FFF0 0040FFF0 00000000 */   nop
/* 00FFF4 0040FFF4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00FFF8 0040FFF8 00000000 */  nop
.L0040FFFC:
/* 00FFFC 0040FFFC 8F998018 */  lw          $t9, %got(func_0040FC20)($gp)
/* 010000 00410000 8FA40024 */  lw          $a0, 0x24($sp)
/* 010004 00410004 2739FC20 */  addiu       $t9, $t9, %lo(func_0040FC20)
/* 010008 00410008 0320F809 */  jalr        $t9
/* 01000C 0041000C 00000000 */   nop
/* 010010 00410010 8FBC0018 */  lw          $gp, 0x18($sp)
/* 010014 00410014 00402825 */  move        $a1, $v0
.L00410018:
/* 010018 00410018 14A00009 */  bnez        $a1, .L00410040
/* 01001C 0041001C 24060001 */   addiu      $a2, $zero, 0x1
/* 010020 00410020 8F848050 */  lw          $a0, %got(STR_1000648C)($gp)
/* 010024 00410024 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 010028 00410028 00002825 */  move        $a1, $zero
/* 01002C 0041002C 0320F809 */  jalr        $t9
/* 010030 00410030 2484648C */   addiu      $a0, $a0, %lo(STR_1000648C)
/* 010034 00410034 8FBC0018 */  lw          $gp, 0x18($sp)
/* 010038 00410038 10000008 */  b           .L0041005C
/* 01003C 0041003C 00000000 */   nop
.L00410040:
/* 010040 00410040 8F998018 */  lw          $t9, %got(func_0040FB2C)($gp)
/* 010044 00410044 00000000 */  nop
/* 010048 00410048 2739FB2C */  addiu       $t9, $t9, %lo(func_0040FB2C)
/* 01004C 0041004C 0320F809 */  jalr        $t9
/* 010050 00410050 00000000 */   nop
/* 010054 00410054 8FBC0018 */  lw          $gp, 0x18($sp)
/* 010058 00410058 00000000 */  nop
.L0041005C:
/* 01005C 0041005C 8F8D8378 */  lw          $t5, %got(Tokench)($gp)
/* 010060 00410060 24010066 */  addiu       $at, $zero, 0x66
/* 010064 00410064 91AD0000 */  lbu         $t5, 0x0($t5)
/* 010068 00410068 00000000 */  nop
/* 01006C 0041006C 15A10013 */  bne         $t5, $at, .L004100BC
/* 010070 00410070 8FBF001C */   lw         $ra, 0x1C($sp)
/* 010074 00410074 8F8E8380 */  lw          $t6, %got(Tstringlength)($gp)
/* 010078 00410078 00002825 */  move        $a1, $zero
/* 01007C 0041007C 8DCE0000 */  lw          $t6, 0x0($t6)
/* 010080 00410080 00000000 */  nop
/* 010084 00410084 29C10400 */  slti        $at, $t6, 0x400
/* 010088 00410088 1420000C */  bnez        $at, .L004100BC
/* 01008C 0041008C 8FBF001C */   lw         $ra, 0x1C($sp)
/* 010090 00410090 8F848050 */  lw          $a0, %got(STR_100064B0)($gp)
/* 010094 00410094 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 010098 00410098 24060001 */  addiu       $a2, $zero, 0x1
/* 01009C 0041009C 0320F809 */  jalr        $t9
/* 0100A0 004100A0 248464B0 */   addiu      $a0, $a0, %lo(STR_100064B0)
/* 0100A4 004100A4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 0100A8 004100A8 240F03FF */  addiu       $t7, $zero, 0x3FF
/* 0100AC 004100AC 8F818380 */  lw          $at, %got(Tstringlength)($gp)
/* 0100B0 004100B0 00000000 */  nop
/* 0100B4 004100B4 AC2F0000 */  sw          $t7, 0x0($at)
/* 0100B8 004100B8 8FBF001C */  lw          $ra, 0x1C($sp)
.L004100BC:
/* 0100BC 004100BC 27BD0030 */  addiu       $sp, $sp, 0x30
/* 0100C0 004100C0 03E00008 */  jr          $ra
/* 0100C4 004100C4 00000000 */   nop
