.section .rodata
glabel STR_100059EC
/* 0249EC 100059EC */ .asciz "Bad id in expression"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040BEBC # 65
# _gp_disp: 0xFC04C04
.set noreorder; .cpload $t9; # .set reorder
/* 00BEC8 0040BEC8 8F8E8378 */  lw          $t6, %got(Tokench)($gp)
/* 00BECC 0040BECC 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 00BED0 0040BED0 91CE0000 */  lbu         $t6, 0x0($t6)
/* 00BED4 0040BED4 24010069 */  addiu       $at, $zero, 0x69
/* 00BED8 0040BED8 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00BEDC 0040BEDC AFBC0018 */  sw          $gp, 0x18($sp)
/* 00BEE0 0040BEE0 AFA40028 */  sw          $a0, 0x28($sp)
/* 00BEE4 0040BEE4 AFA5002C */  sw          $a1, 0x2C($sp)
/* 00BEE8 0040BEE8 15C1004B */  bne         $t6, $at, .L0040C018
/* 00BEEC 0040BEEC AFA60030 */   sw         $a2, 0x30($sp)
/* 00BEF0 0040BEF0 8F99816C */  lw          $t9, %call16(LookUp)($gp)
/* 00BEF4 0040BEF4 8F84837C */  lw          $a0, %got(Tstring)($gp)
/* 00BEF8 0040BEF8 0320F809 */  jalr        $t9
/* 00BEFC 0040BEFC 27A50024 */   addiu      $a1, $sp, 0x24
/* 00BF00 0040BF00 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00BF04 0040BF04 14400007 */  bnez        $v0, .L0040BF24
/* 00BF08 0040BF08 27A50024 */   addiu      $a1, $sp, 0x24
/* 00BF0C 0040BF0C 8F99818C */  lw          $t9, %call16(EnterSym)($gp)
/* 00BF10 0040BF10 8F84837C */  lw          $a0, %got(Tstring)($gp)
/* 00BF14 0040BF14 0320F809 */  jalr        $t9
/* 00BF18 0040BF18 24060001 */   addiu      $a2, $zero, 0x1
/* 00BF1C 0040BF1C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00BF20 0040BF20 00000000 */  nop
.L0040BF24:
/* 00BF24 0040BF24 8FAF0024 */  lw          $t7, 0x24($sp)
/* 00BF28 0040BF28 24010004 */  addiu       $at, $zero, 0x4
/* 00BF2C 0040BF2C 8DE20010 */  lw          $v0, 0x10($t7)
/* 00BF30 0040BF30 8FA4002C */  lw          $a0, 0x2C($sp)
/* 00BF34 0040BF34 14410009 */  bne         $v0, $at, .L0040BF5C
/* 00BF38 0040BF38 24010003 */   addiu      $at, $zero, 0x3
/* 00BF3C 0040BF3C 8F9981A0 */  lw          $t9, %call16(GetItem)($gp)
/* 00BF40 0040BF40 8FA50030 */  lw          $a1, 0x30($sp)
/* 00BF44 0040BF44 0320F809 */  jalr        $t9
/* 00BF48 0040BF48 00000000 */   nop
/* 00BF4C 0040BF4C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00BF50 0040BF50 10000039 */  b           .L0040C038
/* 00BF54 0040BF54 24020001 */   addiu      $v0, $zero, 0x1
/* 00BF58 0040BF58 24010003 */  addiu       $at, $zero, 0x3
.L0040BF5C:
/* 00BF5C 0040BF5C 14410020 */  bne         $v0, $at, .L0040BFE0
/* 00BF60 0040BF60 24060001 */   addiu      $a2, $zero, 0x1
/* 00BF64 0040BF64 8FB80024 */  lw          $t8, 0x24($sp)
/* 00BF68 0040BF68 8FA80028 */  lw          $t0, 0x28($sp)
/* 00BF6C 0040BF6C 8F190018 */  lw          $t9, 0x18($t8)
/* 00BF70 0040BF70 00000000 */  nop
/* 00BF74 0040BF74 AD190000 */  sw          $t9, 0x0($t0)
/* 00BF78 0040BF78 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 00BF7C 0040BF7C 00000000 */  nop
/* 00BF80 0040BF80 0320F809 */  jalr        $t9
/* 00BF84 0040BF84 00000000 */   nop
/* 00BF88 0040BF88 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00BF8C 0040BF8C 8FA4002C */  lw          $a0, 0x2C($sp)
/* 00BF90 0040BF90 8F998014 */  lw          $t9, %got(func_00405A80)($gp)
/* 00BF94 0040BF94 8FA50030 */  lw          $a1, 0x30($sp)
/* 00BF98 0040BF98 27395A80 */  addiu       $t9, $t9, %lo(func_00405A80)
/* 00BF9C 0040BF9C 0320F809 */  jalr        $t9
/* 00BFA0 0040BFA0 00000000 */   nop
/* 00BFA4 0040BFA4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00BFA8 0040BFA8 2401002C */  addiu       $at, $zero, 0x2C
/* 00BFAC 0040BFAC 8F898378 */  lw          $t1, %got(Tokench)($gp)
/* 00BFB0 0040BFB0 00000000 */  nop
/* 00BFB4 0040BFB4 91290000 */  lbu         $t1, 0x0($t1)
/* 00BFB8 0040BFB8 00000000 */  nop
/* 00BFBC 0040BFBC 1521001E */  bne         $t1, $at, .L0040C038
/* 00BFC0 0040BFC0 24020001 */   addiu      $v0, $zero, 0x1
/* 00BFC4 0040BFC4 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 00BFC8 0040BFC8 00000000 */  nop
/* 00BFCC 0040BFCC 0320F809 */  jalr        $t9
/* 00BFD0 0040BFD0 00000000 */   nop
/* 00BFD4 0040BFD4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00BFD8 0040BFD8 10000017 */  b           .L0040C038
/* 00BFDC 0040BFDC 24020001 */   addiu      $v0, $zero, 0x1
.L0040BFE0:
/* 00BFE0 0040BFE0 8F848050 */  lw          $a0, %got(STR_100059EC)($gp)
/* 00BFE4 0040BFE4 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00BFE8 0040BFE8 8F85837C */  lw          $a1, %got(Tstring)($gp)
/* 00BFEC 0040BFEC 0320F809 */  jalr        $t9
/* 00BFF0 0040BFF0 248459EC */   addiu      $a0, $a0, %lo(STR_100059EC)
/* 00BFF4 0040BFF4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00BFF8 0040BFF8 00000000 */  nop
/* 00BFFC 0040BFFC 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 00C000 0040C000 00000000 */  nop
/* 00C004 0040C004 0320F809 */  jalr        $t9
/* 00C008 0040C008 00000000 */   nop
/* 00C00C 0040C00C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C010 0040C010 10000009 */  b           .L0040C038
/* 00C014 0040C014 00001025 */   move       $v0, $zero
.L0040C018:
/* 00C018 0040C018 8F9981A0 */  lw          $t9, %call16(GetItem)($gp)
/* 00C01C 0040C01C 8FA4002C */  lw          $a0, 0x2C($sp)
/* 00C020 0040C020 8FA50030 */  lw          $a1, 0x30($sp)
/* 00C024 0040C024 0320F809 */  jalr        $t9
/* 00C028 0040C028 00000000 */   nop
/* 00C02C 0040C02C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C030 0040C030 00000000 */  nop
/* 00C034 0040C034 24020001 */  addiu       $v0, $zero, 0x1
.L0040C038:
/* 00C038 0040C038 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00C03C 0040C03C 27BD0028 */  addiu       $sp, $sp, 0x28
/* 00C040 0040C040 03E00008 */  jr          $ra
/* 00C044 0040C044 00000000 */   nop
