/* Generated by spimdisasm 1.10.3 */

glabel func_00409FD0 # 43
# _gp_disp: 0xFC06AF0
.set noreorder; .cpload $t9; # .set reorder
/* 009FDC 00409FDC 8F998190 */  lw          $t9, %call16(GetRegister)($gp)
/* 009FE0 00409FE0 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* 009FE4 00409FE4 AFBF002C */  sw          $ra, 0x2C($sp)
/* 009FE8 00409FE8 AFBC0028 */  sw          $gp, 0x28($sp)
/* 009FEC 00409FEC 0320F809 */  jalr        $t9
/* 009FF0 00409FF0 AFA40030 */   sw         $a0, 0x30($sp)
/* 009FF4 00409FF4 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009FF8 00409FF8 1040000E */  beqz        $v0, .L0040A034
/* 009FFC 00409FFC 00002025 */   move       $a0, $zero
/* 00A000 0040A000 8F998014 */  lw          $t9, %got(func_00405178)($gp)
/* 00A004 0040A004 8C460014 */  lw          $a2, 0x14($v0)
/* 00A008 0040A008 8FA50030 */  lw          $a1, 0x30($sp)
/* 00A00C 0040A00C 240E0007 */  addiu       $t6, $zero, 0x7
/* 00A010 0040A010 240F0048 */  addiu       $t7, $zero, 0x48
/* 00A014 0040A014 27395178 */  addiu       $t9, $t9, %lo(func_00405178)
/* 00A018 0040A018 AFAF0014 */  sw          $t7, 0x14($sp)
/* 00A01C 0040A01C AFAE0010 */  sw          $t6, 0x10($sp)
/* 00A020 0040A020 AFA00018 */  sw          $zero, 0x18($sp)
/* 00A024 0040A024 0320F809 */  jalr        $t9
/* 00A028 0040A028 24070048 */   addiu      $a3, $zero, 0x48
/* 00A02C 0040A02C 8FBC0028 */  lw          $gp, 0x28($sp)
/* 00A030 0040A030 00000000 */  nop
.L0040A034:
/* 00A034 0040A034 8FBF002C */  lw          $ra, 0x2C($sp)
/* 00A038 0040A038 27BD0030 */  addiu       $sp, $sp, 0x30
/* 00A03C 0040A03C 03E00008 */  jr          $ra
/* 00A040 0040A040 00000000 */   nop
