.section .rodata
glabel STR_10005428
/* 024428 10005428 */ .asciz "invalid external expression"
                      .balign 4

glabel STR_10005444
/* 024444 10005444 */ .asciz "stmt extends past logical end"
                      .balign 4

glabel STR_10005464
/* 024464 10005464 */ .asciz "JAL should not use same register twice"
                      .balign 4

glabel STR_1000548C
/* 02448C 1000548C */ .asciz "invalid symbol for address"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_00408C80 # 37
# _gp_disp: 0xFC07E40
.set noreorder; .cpload $t9; # .set reorder
/* 008C8C 00408C8C 27BDFFA8 */  addiu       $sp, $sp, -0x58
/* 008C90 00408C90 2401002B */  addiu       $at, $zero, 0x2B
/* 008C94 00408C94 AFBF002C */  sw          $ra, 0x2C($sp)
/* 008C98 00408C98 AFBC0028 */  sw          $gp, 0x28($sp)
/* 008C9C 00408C9C AFB00024 */  sw          $s0, 0x24($sp)
/* 008CA0 00408CA0 14810003 */  bne         $a0, $at, .L00408CB0
/* 008CA4 00408CA4 00803025 */   move       $a2, $a0
/* 008CA8 00408CA8 10000005 */  b           .L00408CC0
/* 008CAC 00408CAC 24060022 */   addiu      $a2, $zero, 0x22
.L00408CB0:
/* 008CB0 00408CB0 24010032 */  addiu       $at, $zero, 0x32
/* 008CB4 00408CB4 14C10002 */  bne         $a2, $at, .L00408CC0
/* 008CB8 00408CB8 00000000 */   nop
/* 008CBC 00408CBC 24060023 */  addiu       $a2, $zero, 0x23
.L00408CC0:
/* 008CC0 00408CC0 8F8F8378 */  lw          $t7, %got(Tokench)($gp)
/* 008CC4 00408CC4 240E0048 */  addiu       $t6, $zero, 0x48
/* 008CC8 00408CC8 91EF0000 */  lbu         $t7, 0x0($t7)
/* 008CCC 00408CCC 24010069 */  addiu       $at, $zero, 0x69
/* 008CD0 00408CD0 AFA0004C */  sw          $zero, 0x4C($sp)
/* 008CD4 00408CD4 AFA00054 */  sw          $zero, 0x54($sp)
/* 008CD8 00408CD8 AFAE0048 */  sw          $t6, 0x48($sp)
/* 008CDC 00408CDC 15E100D2 */  bne         $t7, $at, .L00409028
/* 008CE0 00408CE0 AFA00050 */   sw         $zero, 0x50($sp)
/* 008CE4 00408CE4 8F99816C */  lw          $t9, %call16(LookUp)($gp)
/* 008CE8 00408CE8 27B00050 */  addiu       $s0, $sp, 0x50
/* 008CEC 00408CEC 8F84837C */  lw          $a0, %got(Tstring)($gp)
/* 008CF0 00408CF0 02002825 */  move        $a1, $s0
/* 008CF4 00408CF4 0320F809 */  jalr        $t9
/* 008CF8 00408CF8 AFA60058 */   sw         $a2, 0x58($sp)
/* 008CFC 00408CFC 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008D00 00408D00 14400007 */  bnez        $v0, .L00408D20
/* 008D04 00408D04 02002825 */   move       $a1, $s0
/* 008D08 00408D08 8F99818C */  lw          $t9, %call16(EnterSym)($gp)
/* 008D0C 00408D0C 8F84837C */  lw          $a0, %got(Tstring)($gp)
/* 008D10 00408D10 0320F809 */  jalr        $t9
/* 008D14 00408D14 24060001 */   addiu      $a2, $zero, 0x1
/* 008D18 00408D18 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008D1C 00408D1C 00000000 */  nop
.L00408D20:
/* 008D20 00408D20 8FB80050 */  lw          $t8, 0x50($sp)
/* 008D24 00408D24 24010003 */  addiu       $at, $zero, 0x3
/* 008D28 00408D28 8F020010 */  lw          $v0, 0x10($t8)
/* 008D2C 00408D2C 00000000 */  nop
/* 008D30 00408D30 1441006D */  bne         $v0, $at, .L00408EE8
/* 008D34 00408D34 00000000 */   nop
/* 008D38 00408D38 8F9983BC */  lw          $t9, %got(list_extsyms)($gp)
/* 008D3C 00408D3C 00000000 */  nop
/* 008D40 00408D40 8F390000 */  lw          $t9, 0x0($t9)
/* 008D44 00408D44 00000000 */  nop
/* 008D48 00408D48 13200009 */  beqz        $t9, .L00408D70
/* 008D4C 00408D4C 00000000 */   nop
/* 008D50 00408D50 8F998014 */  lw          $t9, %got(func_004054E8)($gp)
/* 008D54 00408D54 8F040018 */  lw          $a0, 0x18($t8)
/* 008D58 00408D58 8F85837C */  lw          $a1, %got(Tstring)($gp)
/* 008D5C 00408D5C 273954E8 */  addiu       $t9, $t9, %lo(func_004054E8)
/* 008D60 00408D60 0320F809 */  jalr        $t9
/* 008D64 00408D64 00000000 */   nop
/* 008D68 00408D68 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008D6C 00408D6C 00000000 */  nop
.L00408D70:
/* 008D70 00408D70 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 008D74 00408D74 00000000 */  nop
/* 008D78 00408D78 0320F809 */  jalr        $t9
/* 008D7C 00408D7C 00000000 */   nop
/* 008D80 00408D80 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008D84 00408D84 2401002B */  addiu       $at, $zero, 0x2B
/* 008D88 00408D88 8F838378 */  lw          $v1, %got(Tokench)($gp)
/* 008D8C 00408D8C AFA0003C */  sw          $zero, 0x3C($sp)
/* 008D90 00408D90 90630000 */  lbu         $v1, 0x0($v1)
/* 008D94 00408D94 00000000 */  nop
/* 008D98 00408D98 1061000F */  beq         $v1, $at, .L00408DD8
/* 008D9C 00408D9C 2401002D */   addiu      $at, $zero, 0x2D
/* 008DA0 00408DA0 1061000D */  beq         $v1, $at, .L00408DD8
/* 008DA4 00408DA4 24010023 */   addiu      $at, $zero, 0x23
/* 008DA8 00408DA8 1061000B */  beq         $v1, $at, .L00408DD8
/* 008DAC 00408DAC 2410002C */   addiu      $s0, $zero, 0x2C
/* 008DB0 00408DB0 12030009 */  beq         $s0, $v1, .L00408DD8
/* 008DB4 00408DB4 00002825 */   move       $a1, $zero
/* 008DB8 00408DB8 8F848050 */  lw          $a0, %got(STR_10005428)($gp)
/* 008DBC 00408DBC 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 008DC0 00408DC0 24060001 */  addiu       $a2, $zero, 0x1
/* 008DC4 00408DC4 0320F809 */  jalr        $t9
/* 008DC8 00408DC8 24845428 */   addiu      $a0, $a0, %lo(STR_10005428)
/* 008DCC 00408DCC 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008DD0 00408DD0 100000CE */  b           .L0040910C
/* 008DD4 00408DD4 8FBF002C */   lw         $ra, 0x2C($sp)
.L00408DD8:
/* 008DD8 00408DD8 24010023 */  addiu       $at, $zero, 0x23
/* 008DDC 00408DDC 10610098 */  beq         $v1, $at, .L00409040
/* 008DE0 00408DE0 2410002C */   addiu      $s0, $zero, 0x2C
/* 008DE4 00408DE4 1203000C */  beq         $s0, $v1, .L00408E18
/* 008DE8 00408DE8 24010023 */   addiu      $at, $zero, 0x23
/* 008DEC 00408DEC 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 008DF0 00408DF0 00000000 */  nop
/* 008DF4 00408DF4 0320F809 */  jalr        $t9
/* 008DF8 00408DF8 00000000 */   nop
/* 008DFC 00408DFC 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008E00 00408E00 AFA2004C */  sw          $v0, 0x4C($sp)
/* 008E04 00408E04 8F838378 */  lw          $v1, %got(Tokench)($gp)
/* 008E08 00408E08 00000000 */  nop
/* 008E0C 00408E0C 90630000 */  lbu         $v1, 0x0($v1)
/* 008E10 00408E10 00000000 */  nop
/* 008E14 00408E14 24010023 */  addiu       $at, $zero, 0x23
.L00408E18:
/* 008E18 00408E18 1061008A */  beq         $v1, $at, .L00409044
/* 008E1C 00408E1C 8FAB0054 */   lw         $t3, 0x54($sp)
/* 008E20 00408E20 16030007 */  bne         $s0, $v1, .L00408E40
/* 008E24 00408E24 00000000 */   nop
/* 008E28 00408E28 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 008E2C 00408E2C 00000000 */  nop
/* 008E30 00408E30 0320F809 */  jalr        $t9
/* 008E34 00408E34 00000000 */   nop
/* 008E38 00408E38 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008E3C 00408E3C 00000000 */  nop
.L00408E40:
/* 008E40 00408E40 8F998190 */  lw          $t9, %call16(GetRegister)($gp)
/* 008E44 00408E44 00000000 */  nop
/* 008E48 00408E48 0320F809 */  jalr        $t9
/* 008E4C 00408E4C 00000000 */   nop
/* 008E50 00408E50 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008E54 00408E54 10400007 */  beqz        $v0, .L00408E74
/* 008E58 00408E58 AFA2003C */   sw         $v0, 0x3C($sp)
/* 008E5C 00408E5C 8F888378 */  lw          $t0, %got(Tokench)($gp)
/* 008E60 00408E60 24010023 */  addiu       $at, $zero, 0x23
/* 008E64 00408E64 91080000 */  lbu         $t0, 0x0($t0)
/* 008E68 00408E68 00000000 */  nop
/* 008E6C 00408E6C 1501000F */  bne         $t0, $at, .L00408EAC
/* 008E70 00408E70 00000000 */   nop
.L00408E74:
/* 008E74 00408E74 8F898378 */  lw          $t1, %got(Tokench)($gp)
/* 008E78 00408E78 24010023 */  addiu       $at, $zero, 0x23
/* 008E7C 00408E7C 91290000 */  lbu         $t1, 0x0($t1)
/* 008E80 00408E80 00002825 */  move        $a1, $zero
/* 008E84 00408E84 152100A1 */  bne         $t1, $at, .L0040910C
/* 008E88 00408E88 8FBF002C */   lw         $ra, 0x2C($sp)
/* 008E8C 00408E8C 8F848050 */  lw          $a0, %got(STR_10005444)($gp)
/* 008E90 00408E90 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 008E94 00408E94 24060001 */  addiu       $a2, $zero, 0x1
/* 008E98 00408E98 0320F809 */  jalr        $t9
/* 008E9C 00408E9C 24845444 */   addiu      $a0, $a0, %lo(STR_10005444)
/* 008EA0 00408EA0 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008EA4 00408EA4 10000099 */  b           .L0040910C
/* 008EA8 00408EA8 8FBF002C */   lw         $ra, 0x2C($sp)
.L00408EAC:
/* 008EAC 00408EAC 8F998190 */  lw          $t9, %call16(GetRegister)($gp)
/* 008EB0 00408EB0 00000000 */  nop
/* 008EB4 00408EB4 0320F809 */  jalr        $t9
/* 008EB8 00408EB8 00000000 */   nop
/* 008EBC 00408EBC 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008EC0 00408EC0 10400091 */  beqz        $v0, .L00409108
/* 008EC4 00408EC4 AFA20040 */   sw         $v0, 0x40($sp)
/* 008EC8 00408EC8 8F8A8378 */  lw          $t2, %got(Tokench)($gp)
/* 008ECC 00408ECC 24010023 */  addiu       $at, $zero, 0x23
/* 008ED0 00408ED0 914A0000 */  lbu         $t2, 0x0($t2)
/* 008ED4 00408ED4 00000000 */  nop
/* 008ED8 00408ED8 1141005A */  beq         $t2, $at, .L00409044
/* 008EDC 00408EDC 8FAB0054 */   lw         $t3, 0x54($sp)
/* 008EE0 00408EE0 1000008A */  b           .L0040910C
/* 008EE4 00408EE4 8FBF002C */   lw         $ra, 0x2C($sp)
.L00408EE8:
/* 008EE8 00408EE8 1440003E */  bnez        $v0, .L00408FE4
/* 008EEC 00408EEC 24010004 */   addiu      $at, $zero, 0x4
/* 008EF0 00408EF0 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 008EF4 00408EF4 00000000 */  nop
/* 008EF8 00408EF8 0320F809 */  jalr        $t9
/* 008EFC 00408EFC 00000000 */   nop
/* 008F00 00408F00 8FAB0050 */  lw          $t3, 0x50($sp)
/* 008F04 00408F04 8FAC0058 */  lw          $t4, 0x58($sp)
/* 008F08 00408F08 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008F0C 00408F0C 24020023 */  addiu       $v0, $zero, 0x23
/* 008F10 00408F10 AFA00050 */  sw          $zero, 0x50($sp)
/* 008F14 00408F14 1582004A */  bne         $t4, $v0, .L00409040
/* 008F18 00408F18 AFAB0054 */   sw         $t3, 0x54($sp)
/* 008F1C 00408F1C 8F838378 */  lw          $v1, %got(Tokench)($gp)
/* 008F20 00408F20 2410002C */  addiu       $s0, $zero, 0x2C
/* 008F24 00408F24 90630000 */  lbu         $v1, 0x0($v1)
/* 008F28 00408F28 00000000 */  nop
/* 008F2C 00408F2C 10430045 */  beq         $v0, $v1, .L00409044
/* 008F30 00408F30 8FAB0054 */   lw         $t3, 0x54($sp)
/* 008F34 00408F34 16030075 */  bne         $s0, $v1, .L0040910C
/* 008F38 00408F38 8FBF002C */   lw         $ra, 0x2C($sp)
/* 008F3C 00408F3C 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 008F40 00408F40 00000000 */  nop
/* 008F44 00408F44 0320F809 */  jalr        $t9
/* 008F48 00408F48 00000000 */   nop
/* 008F4C 00408F4C 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008F50 00408F50 27B00038 */  addiu       $s0, $sp, 0x38
.L00408F54:
/* 008F54 00408F54 8F998190 */  lw          $t9, %call16(GetRegister)($gp)
/* 008F58 00408F58 26100004 */  addiu       $s0, $s0, 0x4
/* 008F5C 00408F5C 0320F809 */  jalr        $t9
/* 008F60 00408F60 00000000 */   nop
/* 008F64 00408F64 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008F68 00408F68 10400067 */  beqz        $v0, .L00409108
/* 008F6C 00408F6C AE020000 */   sw         $v0, 0x0($s0)
/* 008F70 00408F70 27AD0044 */  addiu       $t5, $sp, 0x44
/* 008F74 00408F74 120D0008 */  beq         $s0, $t5, .L00408F98
/* 008F78 00408F78 27AF0040 */   addiu      $t7, $sp, 0x40
/* 008F7C 00408F7C 8F8E8378 */  lw          $t6, %got(Tokench)($gp)
/* 008F80 00408F80 24010023 */  addiu       $at, $zero, 0x23
/* 008F84 00408F84 91CE0000 */  lbu         $t6, 0x0($t6)
/* 008F88 00408F88 00000000 */  nop
/* 008F8C 00408F8C 15C1FFF1 */  bne         $t6, $at, .L00408F54
/* 008F90 00408F90 00000000 */   nop
/* 008F94 00408F94 27AF0040 */  addiu       $t7, $sp, 0x40
.L00408F98:
/* 008F98 00408F98 120F002A */  beq         $s0, $t7, .L00409044
/* 008F9C 00408F9C 8FAB0054 */   lw         $t3, 0x54($sp)
/* 008FA0 00408FA0 8FB90054 */  lw          $t9, 0x54($sp)
/* 008FA4 00408FA4 8FA8003C */  lw          $t0, 0x3C($sp)
/* 008FA8 00408FA8 8F380014 */  lw          $t8, 0x14($t9)
/* 008FAC 00408FAC AFA80054 */  sw          $t0, 0x54($sp)
/* 008FB0 00408FB0 AFB80048 */  sw          $t8, 0x48($sp)
/* 008FB4 00408FB4 8D0A0014 */  lw          $t2, 0x14($t0)
/* 008FB8 00408FB8 24060002 */  addiu       $a2, $zero, 0x2
/* 008FBC 00408FBC 170A0021 */  bne         $t8, $t2, .L00409044
/* 008FC0 00408FC0 8FAB0054 */   lw         $t3, 0x54($sp)
/* 008FC4 00408FC4 8F848050 */  lw          $a0, %got(STR_10005464)($gp)
/* 008FC8 00408FC8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 008FCC 00408FCC 8F85837C */  lw          $a1, %got(Tstring)($gp)
/* 008FD0 00408FD0 0320F809 */  jalr        $t9
/* 008FD4 00408FD4 24845464 */   addiu      $a0, $a0, %lo(STR_10005464)
/* 008FD8 00408FD8 8FBC0028 */  lw          $gp, 0x28($sp)
/* 008FDC 00408FDC 10000019 */  b           .L00409044
/* 008FE0 00408FE0 8FAB0054 */   lw         $t3, 0x54($sp)
.L00408FE4:
/* 008FE4 00408FE4 14410008 */  bne         $v0, $at, .L00409008
/* 008FE8 00408FE8 24060001 */   addiu      $a2, $zero, 0x1
/* 008FEC 00408FEC 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 008FF0 00408FF0 AFA00050 */  sw          $zero, 0x50($sp)
/* 008FF4 00408FF4 0320F809 */  jalr        $t9
/* 008FF8 00408FF8 00000000 */   nop
/* 008FFC 00408FFC 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009000 00409000 1000000F */  b           .L00409040
/* 009004 00409004 AFA2004C */   sw         $v0, 0x4C($sp)
.L00409008:
/* 009008 00409008 8F848050 */  lw          $a0, %got(STR_1000548C)($gp)
/* 00900C 0040900C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 009010 00409010 8F85837C */  lw          $a1, %got(Tstring)($gp)
/* 009014 00409014 0320F809 */  jalr        $t9
/* 009018 00409018 2484548C */   addiu      $a0, $a0, %lo(STR_1000548C)
/* 00901C 0040901C 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009020 00409020 1000003A */  b           .L0040910C
/* 009024 00409024 8FBF002C */   lw         $ra, 0x2C($sp)
.L00409028:
/* 009028 00409028 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 00902C 0040902C AFA60058 */  sw          $a2, 0x58($sp)
/* 009030 00409030 0320F809 */  jalr        $t9
/* 009034 00409034 00000000 */   nop
/* 009038 00409038 8FBC0028 */  lw          $gp, 0x28($sp)
/* 00903C 0040903C AFA2004C */  sw          $v0, 0x4C($sp)
.L00409040:
/* 009040 00409040 8FAB0054 */  lw          $t3, 0x54($sp)
.L00409044:
/* 009044 00409044 8FAE0050 */  lw          $t6, 0x50($sp)
/* 009048 00409048 1160000F */  beqz        $t3, .L00409088
/* 00904C 0040904C 00002025 */   move       $a0, $zero
/* 009050 00409050 8F998014 */  lw          $t9, %got(func_00405178)($gp)
/* 009054 00409054 8D660014 */  lw          $a2, 0x14($t3)
/* 009058 00409058 8FA50058 */  lw          $a1, 0x58($sp)
/* 00905C 0040905C 8FA70048 */  lw          $a3, 0x48($sp)
/* 009060 00409060 240C0007 */  addiu       $t4, $zero, 0x7
/* 009064 00409064 240D0048 */  addiu       $t5, $zero, 0x48
/* 009068 00409068 27395178 */  addiu       $t9, $t9, %lo(func_00405178)
/* 00906C 0040906C AFAD0014 */  sw          $t5, 0x14($sp)
/* 009070 00409070 AFAC0010 */  sw          $t4, 0x10($sp)
/* 009074 00409074 0320F809 */  jalr        $t9
/* 009078 00409078 AFA00018 */   sw         $zero, 0x18($sp)
/* 00907C 0040907C 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009080 00409080 10000022 */  b           .L0040910C
/* 009084 00409084 8FBF002C */   lw         $ra, 0x2C($sp)
.L00409088:
/* 009088 00409088 11C00011 */  beqz        $t6, .L004090D0
/* 00908C 0040908C 00002025 */   move       $a0, $zero
/* 009090 00409090 8DC40018 */  lw          $a0, 0x18($t6)
/* 009094 00409094 24190048 */  addiu       $t9, $zero, 0x48
/* 009098 00409098 AFB90014 */  sw          $t9, 0x14($sp)
/* 00909C 0040909C 8F998014 */  lw          $t9, %got(func_00405178)($gp)
/* 0090A0 004090A0 8FB8004C */  lw          $t8, 0x4C($sp)
/* 0090A4 004090A4 8FA50058 */  lw          $a1, 0x58($sp)
/* 0090A8 004090A8 240F0006 */  addiu       $t7, $zero, 0x6
/* 0090AC 004090AC 27395178 */  addiu       $t9, $t9, %lo(func_00405178)
/* 0090B0 004090B0 AFAF0010 */  sw          $t7, 0x10($sp)
/* 0090B4 004090B4 24060048 */  addiu       $a2, $zero, 0x48
/* 0090B8 004090B8 24070048 */  addiu       $a3, $zero, 0x48
/* 0090BC 004090BC 0320F809 */  jalr        $t9
/* 0090C0 004090C0 AFB80018 */   sw         $t8, 0x18($sp)
/* 0090C4 004090C4 8FBC0028 */  lw          $gp, 0x28($sp)
/* 0090C8 004090C8 10000010 */  b           .L0040910C
/* 0090CC 004090CC 8FBF002C */   lw         $ra, 0x2C($sp)
.L004090D0:
/* 0090D0 004090D0 8F998014 */  lw          $t9, %got(func_00405178)($gp)
/* 0090D4 004090D4 8FAA004C */  lw          $t2, 0x4C($sp)
/* 0090D8 004090D8 8FA50058 */  lw          $a1, 0x58($sp)
/* 0090DC 004090DC 24080006 */  addiu       $t0, $zero, 0x6
/* 0090E0 004090E0 24090048 */  addiu       $t1, $zero, 0x48
/* 0090E4 004090E4 27395178 */  addiu       $t9, $t9, %lo(func_00405178)
/* 0090E8 004090E8 AFA90014 */  sw          $t1, 0x14($sp)
/* 0090EC 004090EC AFA80010 */  sw          $t0, 0x10($sp)
/* 0090F0 004090F0 24060048 */  addiu       $a2, $zero, 0x48
/* 0090F4 004090F4 24070048 */  addiu       $a3, $zero, 0x48
/* 0090F8 004090F8 0320F809 */  jalr        $t9
/* 0090FC 004090FC AFAA0018 */   sw         $t2, 0x18($sp)
/* 009100 00409100 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009104 00409104 00000000 */  nop
.L00409108:
/* 009108 00409108 8FBF002C */  lw          $ra, 0x2C($sp)
.L0040910C:
/* 00910C 0040910C 8FB00024 */  lw          $s0, 0x24($sp)
/* 009110 00409110 03E00008 */  jr          $ra
/* 009114 00409114 27BD0058 */   addiu      $sp, $sp, 0x58
