/* Generated by spimdisasm 1.10.3 */

glabel func_0040A6B8 # 52
# _gp_disp: 0xFC06408
.set noreorder; .cpload $t9; # .set reorder
/* 00A6C4 0040A6C4 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* 00A6C8 0040A6C8 AFB30024 */  sw          $s3, 0x24($sp)
/* 00A6CC 0040A6CC 8F9383A0 */  lw          $s3, %got(binasm_rec)($gp)
/* 00A6D0 0040A6D0 308F003F */  andi        $t7, $a0, 0x3F
/* 00A6D4 0040A6D4 92780005 */  lbu         $t8, 0x5($s3)
/* 00A6D8 0040A6D8 8F838380 */  lw          $v1, %got(Tstringlength)($gp)
/* 00A6DC 0040A6DC 3319FFC0 */  andi        $t9, $t8, 0xFFC0
/* 00A6E0 0040A6E0 01F94025 */  or          $t0, $t7, $t9
/* 00A6E4 0040A6E4 AE600000 */  sw          $zero, 0x0($s3)
/* 00A6E8 0040A6E8 A2680005 */  sb          $t0, 0x5($s3)
/* 00A6EC 0040A6EC 8C630000 */  lw          $v1, 0x0($v1)
/* 00A6F0 0040A6F0 AFB1001C */  sw          $s1, 0x1C($sp)
/* 00A6F4 0040A6F4 AFBF002C */  sw          $ra, 0x2C($sp)
/* 00A6F8 0040A6F8 AFBC0028 */  sw          $gp, 0x28($sp)
/* 00A6FC 0040A6FC AFB20020 */  sw          $s2, 0x20($sp)
/* 00A700 0040A700 AFB00018 */  sw          $s0, 0x18($sp)
/* 00A704 0040A704 24020010 */  addiu       $v0, $zero, 0x10
/* 00A708 0040A708 00008825 */  move        $s1, $zero
/* 00A70C 0040A70C 18600017 */  blez        $v1, .L0040A76C
/* 00A710 0040A710 AE630008 */   sw         $v1, 0x8($s3)
/* 00A714 0040A714 8F90837C */  lw          $s0, %got(Tstring)($gp)
/* 00A718 0040A718 24120010 */  addiu       $s2, $zero, 0x10
.L0040A71C:
/* 00A71C 0040A71C 1452000B */  bne         $v0, $s2, .L0040A74C
/* 00A720 0040A720 00000000 */   nop
/* 00A724 0040A724 8F9981A8 */  lw          $t9, %call16(put_binasmfyle)($gp)
/* 00A728 0040A728 00000000 */  nop
/* 00A72C 0040A72C 0320F809 */  jalr        $t9
/* 00A730 0040A730 00000000 */   nop
/* 00A734 0040A734 8FBC0028 */  lw          $gp, 0x28($sp)
/* 00A738 0040A738 00001025 */  move        $v0, $zero
/* 00A73C 0040A73C 8F838380 */  lw          $v1, %got(Tstringlength)($gp)
/* 00A740 0040A740 00000000 */  nop
/* 00A744 0040A744 8C630000 */  lw          $v1, 0x0($v1)
/* 00A748 0040A748 00000000 */  nop
.L0040A74C:
/* 00A74C 0040A74C 92090000 */  lbu         $t1, 0x0($s0)
/* 00A750 0040A750 26310001 */  addiu       $s1, $s1, 0x1
/* 00A754 0040A754 0223082A */  slt         $at, $s1, $v1
/* 00A758 0040A758 02625021 */  addu        $t2, $s3, $v0
/* 00A75C 0040A75C 26100001 */  addiu       $s0, $s0, 0x1
/* 00A760 0040A760 24420001 */  addiu       $v0, $v0, 0x1
/* 00A764 0040A764 1420FFED */  bnez        $at, .L0040A71C
/* 00A768 0040A768 A1490000 */   sb         $t1, 0x0($t2)
.L0040A76C:
/* 00A76C 0040A76C 8F9981A8 */  lw          $t9, %call16(put_binasmfyle)($gp)
/* 00A770 0040A770 00000000 */  nop
/* 00A774 0040A774 0320F809 */  jalr        $t9
/* 00A778 0040A778 00000000 */   nop
/* 00A77C 0040A77C 8FBF002C */  lw          $ra, 0x2C($sp)
/* 00A780 0040A780 8FBC0028 */  lw          $gp, 0x28($sp)
/* 00A784 0040A784 8FB00018 */  lw          $s0, 0x18($sp)
/* 00A788 0040A788 8FB1001C */  lw          $s1, 0x1C($sp)
/* 00A78C 0040A78C 8FB20020 */  lw          $s2, 0x20($sp)
/* 00A790 0040A790 8FB30024 */  lw          $s3, 0x24($sp)
/* 00A794 0040A794 03E00008 */  jr          $ra
/* 00A798 0040A798 27BD0030 */   addiu      $sp, $sp, 0x30
