.section .rodata
glabel STR_1000563C
/* 02463C 1000563C */ .asciz "expression required"
                      .balign 4

glabel STR_10005650
/* 024650 10005650 */ .asciz "coprocessor operation > 25 bits"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_00409ECC # 42
# _gp_disp: 0xFC06BF4
.set noreorder; .cpload $t9; # .set reorder
/* 009ED8 00409ED8 8F828378 */  lw          $v0, %got(Tokench)($gp)
/* 009EDC 00409EDC 27BDFFC8 */  addiu       $sp, $sp, -0x38
/* 009EE0 00409EE0 90420000 */  lbu         $v0, 0x0($v0)
/* 009EE4 00409EE4 24010069 */  addiu       $at, $zero, 0x69
/* 009EE8 00409EE8 AFBF002C */  sw          $ra, 0x2C($sp)
/* 009EEC 00409EEC AFBC0028 */  sw          $gp, 0x28($sp)
/* 009EF0 00409EF0 1041000A */  beq         $v0, $at, .L00409F1C
/* 009EF4 00409EF4 AFA40038 */   sw         $a0, 0x38($sp)
/* 009EF8 00409EF8 24010064 */  addiu       $at, $zero, 0x64
/* 009EFC 00409EFC 10410007 */  beq         $v0, $at, .L00409F1C
/* 009F00 00409F00 24010068 */   addiu      $at, $zero, 0x68
/* 009F04 00409F04 10410005 */  beq         $v0, $at, .L00409F1C
/* 009F08 00409F08 2401002B */   addiu      $at, $zero, 0x2B
/* 009F0C 00409F0C 10410003 */  beq         $v0, $at, .L00409F1C
/* 009F10 00409F10 2401002D */   addiu      $at, $zero, 0x2D
/* 009F14 00409F14 14410008 */  bne         $v0, $at, .L00409F38
/* 009F18 00409F18 00002825 */   move       $a1, $zero
.L00409F1C:
/* 009F1C 00409F1C 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 009F20 00409F20 00000000 */  nop
/* 009F24 00409F24 0320F809 */  jalr        $t9
/* 009F28 00409F28 00000000 */   nop
/* 009F2C 00409F2C 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009F30 00409F30 10000009 */  b           .L00409F58
/* 009F34 00409F34 00401825 */   move       $v1, $v0
.L00409F38:
/* 009F38 00409F38 8F848050 */  lw          $a0, %got(STR_1000563C)($gp)
/* 009F3C 00409F3C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 009F40 00409F40 24060001 */  addiu       $a2, $zero, 0x1
/* 009F44 00409F44 0320F809 */  jalr        $t9
/* 009F48 00409F48 2484563C */   addiu      $a0, $a0, %lo(STR_1000563C)
/* 009F4C 00409F4C 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009F50 00409F50 1000001C */  b           .L00409FC4
/* 009F54 00409F54 8FBF002C */   lw         $ra, 0x2C($sp)
.L00409F58:
/* 009F58 00409F58 00027642 */  srl         $t6, $v0, 25
/* 009F5C 00409F5C 11C0000A */  beqz        $t6, .L00409F88
/* 009F60 00409F60 00002825 */   move       $a1, $zero
/* 009F64 00409F64 8F848050 */  lw          $a0, %got(STR_10005650)($gp)
/* 009F68 00409F68 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 009F6C 00409F6C 24060001 */  addiu       $a2, $zero, 0x1
/* 009F70 00409F70 AFA30034 */  sw          $v1, 0x34($sp)
/* 009F74 00409F74 0320F809 */  jalr        $t9
/* 009F78 00409F78 24845650 */   addiu      $a0, $a0, %lo(STR_10005650)
/* 009F7C 00409F7C 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009F80 00409F80 8FA30034 */  lw          $v1, 0x34($sp)
/* 009F84 00409F84 00000000 */  nop
.L00409F88:
/* 009F88 00409F88 8F998014 */  lw          $t9, %got(func_00405178)($gp)
/* 009F8C 00409F8C 8FA50038 */  lw          $a1, 0x38($sp)
/* 009F90 00409F90 240F0002 */  addiu       $t7, $zero, 0x2
/* 009F94 00409F94 24180048 */  addiu       $t8, $zero, 0x48
/* 009F98 00409F98 27395178 */  addiu       $t9, $t9, %lo(func_00405178)
/* 009F9C 00409F9C AFB80014 */  sw          $t8, 0x14($sp)
/* 009FA0 00409FA0 AFAF0010 */  sw          $t7, 0x10($sp)
/* 009FA4 00409FA4 00002025 */  move        $a0, $zero
/* 009FA8 00409FA8 24060048 */  addiu       $a2, $zero, 0x48
/* 009FAC 00409FAC 24070048 */  addiu       $a3, $zero, 0x48
/* 009FB0 00409FB0 0320F809 */  jalr        $t9
/* 009FB4 00409FB4 AFA30018 */   sw         $v1, 0x18($sp)
/* 009FB8 00409FB8 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009FBC 00409FBC 00000000 */  nop
/* 009FC0 00409FC0 8FBF002C */  lw          $ra, 0x2C($sp)
.L00409FC4:
/* 009FC4 00409FC4 27BD0038 */  addiu       $sp, $sp, 0x38
/* 009FC8 00409FC8 03E00008 */  jr          $ra
/* 009FCC 00409FCC 00000000 */   nop
