/* Generated by spimdisasm 1.10.3 */

glabel func_0040C460 # 71
# _gp_disp: 0xFC04660
.set noreorder; .cpload $t9; # .set reorder
/* 00C46C 0040C46C 8F8383A0 */  lw          $v1, %got(binasm_rec)($gp)
/* 00C470 0040C470 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 00C474 0040C474 906E0005 */  lbu         $t6, 0x5($v1)
/* 00C478 0040C478 AC600000 */  sw          $zero, 0x0($v1)
/* 00C47C 0040C47C 31CFFFC0 */  andi        $t7, $t6, 0xFFC0
/* 00C480 0040C480 35F8003C */  ori         $t8, $t7, 0x3C
/* 00C484 0040C484 A0780005 */  sb          $t8, 0x5($v1)
/* 00C488 0040C488 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 00C48C 0040C48C AFBF001C */  sw          $ra, 0x1C($sp)
/* 00C490 0040C490 0320F809 */  jalr        $t9
/* 00C494 0040C494 AFBC0018 */   sw         $gp, 0x18($sp)
/* 00C498 0040C498 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C49C 0040C49C 00000000 */  nop
/* 00C4A0 0040C4A0 8F8383A0 */  lw          $v1, %got(binasm_rec)($gp)
/* 00C4A4 0040C4A4 00000000 */  nop
/* 00C4A8 0040C4A8 AC620008 */  sw          $v0, 0x8($v1)
/* 00C4AC 0040C4AC 8F9981A8 */  lw          $t9, %call16(put_binasmfyle)($gp)
/* 00C4B0 0040C4B0 00000000 */  nop
/* 00C4B4 0040C4B4 0320F809 */  jalr        $t9
/* 00C4B8 0040C4B8 00000000 */   nop
/* 00C4BC 0040C4BC 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00C4C0 0040C4C0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00C4C4 0040C4C4 03E00008 */  jr          $ra
/* 00C4C8 0040C4C8 27BD0020 */   addiu      $sp, $sp, 0x20
