.section .rodata
glabel STR_10004CA8
/* 023CA8 10004CA8 */ .asciz "Used $at without .set noat"
                      .balign 4

glabel STR_10004CC4
/* 023CC4 10004CC4 */ .asciz "Should be gp register"
                      .balign 4

glabel STR_10004CDC
/* 023CDC 10004CDC */ .asciz "Should be even gp register"
                      .balign 4

glabel STR_10004CF8
/* 023CF8 10004CF8 */ .asciz "Should be gp register"
                      .balign 4

glabel STR_10004D10
/* 023D10 10004D10 */ .asciz "Used $at without .set noat"
                      .balign 4

glabel STR_10004D2C
/* 023D2C 10004D2C */ .asciz "Should be coprocessor register"
                      .balign 4

glabel STR_10004D4C
/* 023D4C 10004D4C */ .asciz "Should be even coprocessor register"
                      .balign 4

glabel STR_10004D70
/* 023D70 10004D70 */ .asciz "Should be floating point register"
                      .balign 4

glabel STR_10004D94
/* 023D94 10004D94 */ .asciz "Should be even floating point register"
                      .balign 4

glabel STR_10004DBC
/* 023DBC 10004DBC */ .asciz "Should be even floating point register"
                      .balign 4

glabel STR_10004DE4
/* 023DE4 10004DE4 */ .asciz "Should be multiple-of-4 floating point register"
                      .balign 4

glabel STR_10004E14
/* 023E14 10004E14 */ .asciz "Should be fp double or gp single register"
                      .balign 4

glabel STR_10004E40
/* 023E40 10004E40 */ .asciz "Should be multiple-of-2 register"
                      .balign 4

glabel STR_10004E64
/* 023E64 10004E64 */ .asciz "Should be multiple-of-2 register"
                      .balign 4

glabel STR_10004E88
/* 023E88 10004E88 */ .asciz "Should be multiple-of-4 register"
                      .balign 4

glabel STR_10004EAC
/* 023EAC 10004EAC */ .asciz "Should be floating point condition code register"
                      .balign 4

.section .late_rodata
glabel jtbl_10005C3C
/* 024C3C 10005C3C F03F46A8 */ .gpword .L00405168
/* 024C40 10005C40 F03F4180 */ .gpword .L00404C40
/* 024C44 10005C44 F03F4214 */ .gpword .L00404CD4
/* 024C48 10005C48 F03F427C */ .gpword .L00404D3C
/* 024C4C 10005C4C F03F43C0 */ .gpword .L00404E80
/* 024C50 10005C50 F03F4408 */ .gpword .L00404EC8
/* 024C54 10005C54 F03F4470 */ .gpword .L00404F30
/* 024C58 10005C58 F03F4314 */ .gpword .L00404DD4
/* 024C5C 10005C5C F03F4358 */ .gpword .L00404E18
/* 024C60 10005C60 F03F4528 */ .gpword .L00404FE8
/* 024C64 10005C64 F03F4584 */ .gpword .L00405044
/* 024C68 10005C68 F03F45D8 */ .gpword .L00405098
/* 024C6C 10005C6C F03F4664 */ .gpword .L00405124


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_00404B80 # 10
# _gp_disp: 0xFC0BF40
.set noreorder; .cpload $t9; # .set reorder
/* 004B8C 00404B8C 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 004B90 00404B90 24030001 */  addiu       $v1, $zero, 0x1
/* 004B94 00404B94 AFBF001C */  sw          $ra, 0x1C($sp)
/* 004B98 00404B98 AFBC0018 */  sw          $gp, 0x18($sp)
/* 004B9C 00404B9C 10830006 */  beq         $a0, $v1, .L00404BB8
/* 004BA0 00404BA0 00803825 */   move       $a3, $a0
/* 004BA4 00404BA4 24010002 */  addiu       $at, $zero, 0x2
/* 004BA8 00404BA8 1081000B */  beq         $a0, $at, .L00404BD8
/* 004BAC 00404BAC 24010003 */   addiu      $at, $zero, 0x3
/* 004BB0 00404BB0 10810011 */  beq         $a0, $at, .L00404BF8
/* 004BB4 00404BB4 00000000 */   nop
.L00404BB8:
/* 004BB8 00404BB8 8F8F82F8 */  lw          $t7, %got(asm_info)($gp)
/* 004BBC 00404BBC 000670C0 */  sll         $t6, $a2, 3
/* 004BC0 00404BC0 01CFC021 */  addu        $t8, $t6, $t7
/* 004BC4 00404BC4 8F020004 */  lw          $v0, 0x4($t8)
/* 004BC8 00404BC8 00000000 */  nop
/* 004BCC 00404BCC 0002CC40 */  sll         $t9, $v0, 17
/* 004BD0 00404BD0 10000010 */  b           .L00404C14
/* 004BD4 00404BD4 001916C2 */   srl        $v0, $t9, 27
.L00404BD8:
/* 004BD8 00404BD8 8F8A82F8 */  lw          $t2, %got(asm_info)($gp)
/* 004BDC 00404BDC 000648C0 */  sll         $t1, $a2, 3
/* 004BE0 00404BE0 012A5821 */  addu        $t3, $t1, $t2
/* 004BE4 00404BE4 8D620004 */  lw          $v0, 0x4($t3)
/* 004BE8 00404BE8 00000000 */  nop
/* 004BEC 00404BEC 00026580 */  sll         $t4, $v0, 22
/* 004BF0 00404BF0 10000008 */  b           .L00404C14
/* 004BF4 00404BF4 000C16C2 */   srl        $v0, $t4, 27
.L00404BF8:
/* 004BF8 00404BF8 8F8F82F8 */  lw          $t7, %got(asm_info)($gp)
/* 004BFC 00404BFC 000670C0 */  sll         $t6, $a2, 3
/* 004C00 00404C00 01CFC021 */  addu        $t8, $t6, $t7
/* 004C04 00404C04 8F020004 */  lw          $v0, 0x4($t8)
/* 004C08 00404C08 00000000 */  nop
/* 004C0C 00404C0C 3059001F */  andi        $t9, $v0, 0x1F
/* 004C10 00404C10 03201025 */  move        $v0, $t9
.L00404C14:
/* 004C14 00404C14 2C41000D */  sltiu       $at, $v0, 0xD
/* 004C18 00404C18 10200154 */  beqz        $at, .L0040516C
/* 004C1C 00404C1C 8FBF001C */   lw         $ra, 0x1C($sp)
/* 004C20 00404C20 8F818050 */  lw          $at, %got(jtbl_10005C3C)($gp)
/* 004C24 00404C24 00024080 */  sll         $t0, $v0, 2
/* 004C28 00404C28 00280821 */  addu        $at, $at, $t0
/* 004C2C 00404C2C 8C285C3C */  lw          $t0, %lo(jtbl_10005C3C)($at)
/* 004C30 00404C30 00000000 */  nop
/* 004C34 00404C34 011C4021 */  addu        $t0, $t0, $gp
/* 004C38 00404C38 01000008 */  jr          $t0
/* 004C3C 00404C3C 00000000 */   nop
.L00404C40:
/* 004C40 00404C40 8F898338 */  lw          $t1, %got(atflag)($gp)
/* 004C44 00404C44 00000000 */  nop
/* 004C48 00404C48 8D290000 */  lw          $t1, 0x0($t1)
/* 004C4C 00404C4C 00000000 */  nop
/* 004C50 00404C50 1120000F */  beqz        $t1, .L00404C90
/* 004C54 00404C54 00000000 */   nop
/* 004C58 00404C58 14A3000D */  bne         $a1, $v1, .L00404C90
/* 004C5C 00404C5C 00075080 */   sll        $t2, $a3, 2
/* 004C60 00404C60 8F8B8060 */  lw          $t3, %got(D_10000004)($gp)
/* 004C64 00404C64 8F848050 */  lw          $a0, %got(STR_10004CA8)($gp)
/* 004C68 00404C68 256B0004 */  addiu       $t3, $t3, %lo(D_10000004)
/* 004C6C 00404C6C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004C70 00404C70 014B6021 */  addu        $t4, $t2, $t3
/* 004C74 00404C74 8D850000 */  lw          $a1, 0x0($t4)
/* 004C78 00404C78 24060002 */  addiu       $a2, $zero, 0x2
/* 004C7C 00404C7C 0320F809 */  jalr        $t9
/* 004C80 00404C80 24844CA8 */   addiu      $a0, $a0, %lo(STR_10004CA8)
/* 004C84 00404C84 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004C88 00404C88 10000138 */  b           .L0040516C
/* 004C8C 00404C8C 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404C90:
/* 004C90 00404C90 04A00003 */  bltz        $a1, .L00404CA0
/* 004C94 00404C94 28A10020 */   slti       $at, $a1, 0x20
/* 004C98 00404C98 14200134 */  bnez        $at, .L0040516C
/* 004C9C 00404C9C 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404CA0:
/* 004CA0 00404CA0 8F8E8060 */  lw          $t6, %got(D_10000004)($gp)
/* 004CA4 00404CA4 00076880 */  sll         $t5, $a3, 2
/* 004CA8 00404CA8 25CE0004 */  addiu       $t6, $t6, %lo(D_10000004)
/* 004CAC 00404CAC 8F848050 */  lw          $a0, %got(STR_10004CC4)($gp)
/* 004CB0 00404CB0 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004CB4 00404CB4 01AE7821 */  addu        $t7, $t5, $t6
/* 004CB8 00404CB8 8DE50000 */  lw          $a1, 0x0($t7)
/* 004CBC 00404CBC 24060001 */  addiu       $a2, $zero, 0x1
/* 004CC0 00404CC0 0320F809 */  jalr        $t9
/* 004CC4 00404CC4 24844CC4 */   addiu      $a0, $a0, %lo(STR_10004CC4)
/* 004CC8 00404CC8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004CCC 00404CCC 10000127 */  b           .L0040516C
/* 004CD0 00404CD0 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404CD4:
/* 004CD4 00404CD4 8F988328 */  lw          $t8, %got(isa)($gp)
/* 004CD8 00404CD8 00000000 */  nop
/* 004CDC 00404CDC 93180000 */  lbu         $t8, 0x0($t8)
/* 004CE0 00404CE0 00000000 */  nop
/* 004CE4 00404CE4 2B010003 */  slti        $at, $t8, 0x3
/* 004CE8 00404CE8 10200120 */  beqz        $at, .L0040516C
/* 004CEC 00404CEC 8FBF001C */   lw         $ra, 0x1C($sp)
/* 004CF0 00404CF0 04A00005 */  bltz        $a1, .L00404D08
/* 004CF4 00404CF4 28A10020 */   slti       $at, $a1, 0x20
/* 004CF8 00404CF8 10200003 */  beqz        $at, .L00404D08
/* 004CFC 00404CFC 30B90001 */   andi       $t9, $a1, 0x1
/* 004D00 00404D00 1320011A */  beqz        $t9, .L0040516C
/* 004D04 00404D04 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404D08:
/* 004D08 00404D08 8F898060 */  lw          $t1, %got(D_10000004)($gp)
/* 004D0C 00404D0C 00074080 */  sll         $t0, $a3, 2
/* 004D10 00404D10 25290004 */  addiu       $t1, $t1, %lo(D_10000004)
/* 004D14 00404D14 8F848050 */  lw          $a0, %got(STR_10004CDC)($gp)
/* 004D18 00404D18 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004D1C 00404D1C 01095021 */  addu        $t2, $t0, $t1
/* 004D20 00404D20 8D450000 */  lw          $a1, 0x0($t2)
/* 004D24 00404D24 24060001 */  addiu       $a2, $zero, 0x1
/* 004D28 00404D28 0320F809 */  jalr        $t9
/* 004D2C 00404D2C 24844CDC */   addiu      $a0, $a0, %lo(STR_10004CDC)
/* 004D30 00404D30 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004D34 00404D34 1000010D */  b           .L0040516C
/* 004D38 00404D38 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404D3C:
/* 004D3C 00404D3C 04A00002 */  bltz        $a1, .L00404D48
/* 004D40 00404D40 28A10020 */   slti       $at, $a1, 0x20
/* 004D44 00404D44 1420000F */  bnez        $at, .L00404D84
.L00404D48:
/* 004D48 00404D48 24010048 */   addiu      $at, $zero, 0x48
/* 004D4C 00404D4C 10A1000D */  beq         $a1, $at, .L00404D84
/* 004D50 00404D50 00075880 */   sll        $t3, $a3, 2
/* 004D54 00404D54 8F8C8060 */  lw          $t4, %got(D_10000004)($gp)
/* 004D58 00404D58 8F848050 */  lw          $a0, %got(STR_10004CF8)($gp)
/* 004D5C 00404D5C 258C0004 */  addiu       $t4, $t4, %lo(D_10000004)
/* 004D60 00404D60 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004D64 00404D64 016C6821 */  addu        $t5, $t3, $t4
/* 004D68 00404D68 8DA50000 */  lw          $a1, 0x0($t5)
/* 004D6C 00404D6C 24060001 */  addiu       $a2, $zero, 0x1
/* 004D70 00404D70 0320F809 */  jalr        $t9
/* 004D74 00404D74 24844CF8 */   addiu      $a0, $a0, %lo(STR_10004CF8)
/* 004D78 00404D78 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004D7C 00404D7C 100000FB */  b           .L0040516C
/* 004D80 00404D80 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404D84:
/* 004D84 00404D84 8F8E8338 */  lw          $t6, %got(atflag)($gp)
/* 004D88 00404D88 00000000 */  nop
/* 004D8C 00404D8C 8DCE0000 */  lw          $t6, 0x0($t6)
/* 004D90 00404D90 00000000 */  nop
/* 004D94 00404D94 11C000F5 */  beqz        $t6, .L0040516C
/* 004D98 00404D98 8FBF001C */   lw         $ra, 0x1C($sp)
/* 004D9C 00404D9C 14A300F2 */  bne         $a1, $v1, .L00405168
/* 004DA0 00404DA0 00077880 */   sll        $t7, $a3, 2
/* 004DA4 00404DA4 8F988060 */  lw          $t8, %got(D_10000004)($gp)
/* 004DA8 00404DA8 8F848050 */  lw          $a0, %got(STR_10004D10)($gp)
/* 004DAC 00404DAC 27180004 */  addiu       $t8, $t8, %lo(D_10000004)
/* 004DB0 00404DB0 01F8C821 */  addu        $t9, $t7, $t8
/* 004DB4 00404DB4 8F250000 */  lw          $a1, 0x0($t9)
/* 004DB8 00404DB8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004DBC 00404DBC 24060002 */  addiu       $a2, $zero, 0x2
/* 004DC0 00404DC0 0320F809 */  jalr        $t9
/* 004DC4 00404DC4 24844D10 */   addiu      $a0, $a0, %lo(STR_10004D10)
/* 004DC8 00404DC8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004DCC 00404DCC 100000E7 */  b           .L0040516C
/* 004DD0 00404DD0 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404DD4:
/* 004DD4 00404DD4 04A00003 */  bltz        $a1, .L00404DE4
/* 004DD8 00404DD8 28A10020 */   slti       $at, $a1, 0x20
/* 004DDC 00404DDC 142000E3 */  bnez        $at, .L0040516C
/* 004DE0 00404DE0 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404DE4:
/* 004DE4 00404DE4 8F898060 */  lw          $t1, %got(D_10000004)($gp)
/* 004DE8 00404DE8 00074080 */  sll         $t0, $a3, 2
/* 004DEC 00404DEC 25290004 */  addiu       $t1, $t1, %lo(D_10000004)
/* 004DF0 00404DF0 8F848050 */  lw          $a0, %got(STR_10004D2C)($gp)
/* 004DF4 00404DF4 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004DF8 00404DF8 01095021 */  addu        $t2, $t0, $t1
/* 004DFC 00404DFC 8D450000 */  lw          $a1, 0x0($t2)
/* 004E00 00404E00 24060001 */  addiu       $a2, $zero, 0x1
/* 004E04 00404E04 0320F809 */  jalr        $t9
/* 004E08 00404E08 24844D2C */   addiu      $a0, $a0, %lo(STR_10004D2C)
/* 004E0C 00404E0C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004E10 00404E10 100000D6 */  b           .L0040516C
/* 004E14 00404E14 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404E18:
/* 004E18 00404E18 8F8B8328 */  lw          $t3, %got(isa)($gp)
/* 004E1C 00404E1C 00000000 */  nop
/* 004E20 00404E20 916B0000 */  lbu         $t3, 0x0($t3)
/* 004E24 00404E24 00000000 */  nop
/* 004E28 00404E28 29610003 */  slti        $at, $t3, 0x3
/* 004E2C 00404E2C 102000CF */  beqz        $at, .L0040516C
/* 004E30 00404E30 8FBF001C */   lw         $ra, 0x1C($sp)
/* 004E34 00404E34 04A00005 */  bltz        $a1, .L00404E4C
/* 004E38 00404E38 28A10020 */   slti       $at, $a1, 0x20
/* 004E3C 00404E3C 10200003 */  beqz        $at, .L00404E4C
/* 004E40 00404E40 30AC0001 */   andi       $t4, $a1, 0x1
/* 004E44 00404E44 118000C9 */  beqz        $t4, .L0040516C
/* 004E48 00404E48 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404E4C:
/* 004E4C 00404E4C 8F8E8060 */  lw          $t6, %got(D_10000004)($gp)
/* 004E50 00404E50 00076880 */  sll         $t5, $a3, 2
/* 004E54 00404E54 25CE0004 */  addiu       $t6, $t6, %lo(D_10000004)
/* 004E58 00404E58 8F848050 */  lw          $a0, %got(STR_10004D4C)($gp)
/* 004E5C 00404E5C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004E60 00404E60 01AE7821 */  addu        $t7, $t5, $t6
/* 004E64 00404E64 8DE50000 */  lw          $a1, 0x0($t7)
/* 004E68 00404E68 24060001 */  addiu       $a2, $zero, 0x1
/* 004E6C 00404E6C 0320F809 */  jalr        $t9
/* 004E70 00404E70 24844D4C */   addiu      $a0, $a0, %lo(STR_10004D4C)
/* 004E74 00404E74 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004E78 00404E78 100000BC */  b           .L0040516C
/* 004E7C 00404E7C 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404E80:
/* 004E80 00404E80 28A10020 */  slti        $at, $a1, 0x20
/* 004E84 00404E84 14200004 */  bnez        $at, .L00404E98
/* 004E88 00404E88 0007C080 */   sll        $t8, $a3, 2
/* 004E8C 00404E8C 28A10040 */  slti        $at, $a1, 0x40
/* 004E90 00404E90 142000B6 */  bnez        $at, .L0040516C
/* 004E94 00404E94 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404E98:
/* 004E98 00404E98 8F998060 */  lw          $t9, %got(D_10000004)($gp)
/* 004E9C 00404E9C 8F848050 */  lw          $a0, %got(STR_10004D70)($gp)
/* 004EA0 00404EA0 27390004 */  addiu       $t9, $t9, %lo(D_10000004)
/* 004EA4 00404EA4 03194021 */  addu        $t0, $t8, $t9
/* 004EA8 00404EA8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004EAC 00404EAC 8D050000 */  lw          $a1, 0x0($t0)
/* 004EB0 00404EB0 24060001 */  addiu       $a2, $zero, 0x1
/* 004EB4 00404EB4 0320F809 */  jalr        $t9
/* 004EB8 00404EB8 24844D70 */   addiu      $a0, $a0, %lo(STR_10004D70)
/* 004EBC 00404EBC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004EC0 00404EC0 100000AA */  b           .L0040516C
/* 004EC4 00404EC4 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404EC8:
/* 004EC8 00404EC8 8F898328 */  lw          $t1, %got(isa)($gp)
/* 004ECC 00404ECC 00000000 */  nop
/* 004ED0 00404ED0 91290000 */  lbu         $t1, 0x0($t1)
/* 004ED4 00404ED4 00000000 */  nop
/* 004ED8 00404ED8 29210003 */  slti        $at, $t1, 0x3
/* 004EDC 00404EDC 102000A2 */  beqz        $at, .L00405168
/* 004EE0 00404EE0 28A10020 */   slti       $at, $a1, 0x20
/* 004EE4 00404EE4 14200006 */  bnez        $at, .L00404F00
/* 004EE8 00404EE8 00075880 */   sll        $t3, $a3, 2
/* 004EEC 00404EEC 28A10040 */  slti        $at, $a1, 0x40
/* 004EF0 00404EF0 10200003 */  beqz        $at, .L00404F00
/* 004EF4 00404EF4 30AA0001 */   andi       $t2, $a1, 0x1
/* 004EF8 00404EF8 1140009C */  beqz        $t2, .L0040516C
/* 004EFC 00404EFC 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404F00:
/* 004F00 00404F00 8F8C8060 */  lw          $t4, %got(D_10000004)($gp)
/* 004F04 00404F04 8F848050 */  lw          $a0, %got(STR_10004D94)($gp)
/* 004F08 00404F08 258C0004 */  addiu       $t4, $t4, %lo(D_10000004)
/* 004F0C 00404F0C 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004F10 00404F10 016C6821 */  addu        $t5, $t3, $t4
/* 004F14 00404F14 8DA50000 */  lw          $a1, 0x0($t5)
/* 004F18 00404F18 24060001 */  addiu       $a2, $zero, 0x1
/* 004F1C 00404F1C 0320F809 */  jalr        $t9
/* 004F20 00404F20 24844D94 */   addiu      $a0, $a0, %lo(STR_10004D94)
/* 004F24 00404F24 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004F28 00404F28 10000090 */  b           .L0040516C
/* 004F2C 00404F2C 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404F30:
/* 004F30 00404F30 8F8E8328 */  lw          $t6, %got(isa)($gp)
/* 004F34 00404F34 00000000 */  nop
/* 004F38 00404F38 91CE0000 */  lbu         $t6, 0x0($t6)
/* 004F3C 00404F3C 00000000 */  nop
/* 004F40 00404F40 29C10003 */  slti        $at, $t6, 0x3
/* 004F44 00404F44 14200014 */  bnez        $at, .L00404F98
/* 004F48 00404F48 28A10020 */   slti       $at, $a1, 0x20
/* 004F4C 00404F4C 14200006 */  bnez        $at, .L00404F68
/* 004F50 00404F50 0007C080 */   sll        $t8, $a3, 2
/* 004F54 00404F54 28A10040 */  slti        $at, $a1, 0x40
/* 004F58 00404F58 10200003 */  beqz        $at, .L00404F68
/* 004F5C 00404F5C 30AF0001 */   andi       $t7, $a1, 0x1
/* 004F60 00404F60 11E00082 */  beqz        $t7, .L0040516C
/* 004F64 00404F64 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404F68:
/* 004F68 00404F68 8F998060 */  lw          $t9, %got(D_10000004)($gp)
/* 004F6C 00404F6C 8F848050 */  lw          $a0, %got(STR_10004DBC)($gp)
/* 004F70 00404F70 27390004 */  addiu       $t9, $t9, %lo(D_10000004)
/* 004F74 00404F74 03194021 */  addu        $t0, $t8, $t9
/* 004F78 00404F78 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004F7C 00404F7C 8D050000 */  lw          $a1, 0x0($t0)
/* 004F80 00404F80 24060001 */  addiu       $a2, $zero, 0x1
/* 004F84 00404F84 0320F809 */  jalr        $t9
/* 004F88 00404F88 24844DBC */   addiu      $a0, $a0, %lo(STR_10004DBC)
/* 004F8C 00404F8C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004F90 00404F90 10000076 */  b           .L0040516C
/* 004F94 00404F94 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404F98:
/* 004F98 00404F98 28A10020 */  slti        $at, $a1, 0x20
/* 004F9C 00404F9C 14200006 */  bnez        $at, .L00404FB8
/* 004FA0 00404FA0 00075080 */   sll        $t2, $a3, 2
/* 004FA4 00404FA4 28A10040 */  slti        $at, $a1, 0x40
/* 004FA8 00404FA8 10200003 */  beqz        $at, .L00404FB8
/* 004FAC 00404FAC 30A90003 */   andi       $t1, $a1, 0x3
/* 004FB0 00404FB0 1120006E */  beqz        $t1, .L0040516C
/* 004FB4 00404FB4 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404FB8:
/* 004FB8 00404FB8 8F8B8060 */  lw          $t3, %got(D_10000004)($gp)
/* 004FBC 00404FBC 8F848050 */  lw          $a0, %got(STR_10004DE4)($gp)
/* 004FC0 00404FC0 256B0004 */  addiu       $t3, $t3, %lo(D_10000004)
/* 004FC4 00404FC4 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 004FC8 00404FC8 014B6021 */  addu        $t4, $t2, $t3
/* 004FCC 00404FCC 8D850000 */  lw          $a1, 0x0($t4)
/* 004FD0 00404FD0 24060001 */  addiu       $a2, $zero, 0x1
/* 004FD4 00404FD4 0320F809 */  jalr        $t9
/* 004FD8 00404FD8 24844DE4 */   addiu      $a0, $a0, %lo(STR_10004DE4)
/* 004FDC 00404FDC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 004FE0 00404FE0 10000062 */  b           .L0040516C
/* 004FE4 00404FE4 8FBF001C */   lw         $ra, 0x1C($sp)
.L00404FE8:
/* 004FE8 00404FE8 8F8D8328 */  lw          $t5, %got(isa)($gp)
/* 004FEC 00404FEC 00000000 */  nop
/* 004FF0 00404FF0 91AD0000 */  lbu         $t5, 0x0($t5)
/* 004FF4 00404FF4 00000000 */  nop
/* 004FF8 00404FF8 29A10003 */  slti        $at, $t5, 0x3
/* 004FFC 00404FFC 1020005A */  beqz        $at, .L00405168
/* 005000 00405000 28A10020 */   slti       $at, $a1, 0x20
/* 005004 00405004 14200058 */  bnez        $at, .L00405168
/* 005008 00405008 30AE0001 */   andi       $t6, $a1, 0x1
/* 00500C 0040500C 11C00056 */  beqz        $t6, .L00405168
/* 005010 00405010 00077880 */   sll        $t7, $a3, 2
/* 005014 00405014 8F988060 */  lw          $t8, %got(D_10000004)($gp)
/* 005018 00405018 8F848050 */  lw          $a0, %got(STR_10004E14)($gp)
/* 00501C 0040501C 27180004 */  addiu       $t8, $t8, %lo(D_10000004)
/* 005020 00405020 01F8C821 */  addu        $t9, $t7, $t8
/* 005024 00405024 8F250000 */  lw          $a1, 0x0($t9)
/* 005028 00405028 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00502C 0040502C 24060001 */  addiu       $a2, $zero, 0x1
/* 005030 00405030 0320F809 */  jalr        $t9
/* 005034 00405034 24844E14 */   addiu      $a0, $a0, %lo(STR_10004E14)
/* 005038 00405038 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00503C 0040503C 1000004B */  b           .L0040516C
/* 005040 00405040 8FBF001C */   lw         $ra, 0x1C($sp)
.L00405044:
/* 005044 00405044 8F888328 */  lw          $t0, %got(isa)($gp)
/* 005048 00405048 30A90001 */  andi        $t1, $a1, 0x1
/* 00504C 0040504C 91080000 */  lbu         $t0, 0x0($t0)
/* 005050 00405050 00000000 */  nop
/* 005054 00405054 29010003 */  slti        $at, $t0, 0x3
/* 005058 00405058 10200044 */  beqz        $at, .L0040516C
/* 00505C 0040505C 8FBF001C */   lw         $ra, 0x1C($sp)
/* 005060 00405060 11200041 */  beqz        $t1, .L00405168
/* 005064 00405064 00075080 */   sll        $t2, $a3, 2
/* 005068 00405068 8F8B8060 */  lw          $t3, %got(D_10000004)($gp)
/* 00506C 0040506C 8F848050 */  lw          $a0, %got(STR_10004E40)($gp)
/* 005070 00405070 256B0004 */  addiu       $t3, $t3, %lo(D_10000004)
/* 005074 00405074 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 005078 00405078 014B6021 */  addu        $t4, $t2, $t3
/* 00507C 0040507C 8D850000 */  lw          $a1, 0x0($t4)
/* 005080 00405080 24060001 */  addiu       $a2, $zero, 0x1
/* 005084 00405084 0320F809 */  jalr        $t9
/* 005088 00405088 24844E40 */   addiu      $a0, $a0, %lo(STR_10004E40)
/* 00508C 0040508C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 005090 00405090 10000036 */  b           .L0040516C
/* 005094 00405094 8FBF001C */   lw         $ra, 0x1C($sp)
.L00405098:
/* 005098 00405098 8F8D8328 */  lw          $t5, %got(isa)($gp)
/* 00509C 0040509C 30AE0001 */  andi        $t6, $a1, 0x1
/* 0050A0 004050A0 91AD0000 */  lbu         $t5, 0x0($t5)
/* 0050A4 004050A4 30A80003 */  andi        $t0, $a1, 0x3
/* 0050A8 004050A8 29A10003 */  slti        $at, $t5, 0x3
/* 0050AC 004050AC 1420000F */  bnez        $at, .L004050EC
/* 0050B0 004050B0 00000000 */   nop
/* 0050B4 004050B4 11C0002C */  beqz        $t6, .L00405168
/* 0050B8 004050B8 00077880 */   sll        $t7, $a3, 2
/* 0050BC 004050BC 8F988060 */  lw          $t8, %got(D_10000004)($gp)
/* 0050C0 004050C0 8F848050 */  lw          $a0, %got(STR_10004E64)($gp)
/* 0050C4 004050C4 27180004 */  addiu       $t8, $t8, %lo(D_10000004)
/* 0050C8 004050C8 01F8C821 */  addu        $t9, $t7, $t8
/* 0050CC 004050CC 8F250000 */  lw          $a1, 0x0($t9)
/* 0050D0 004050D0 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 0050D4 004050D4 24060001 */  addiu       $a2, $zero, 0x1
/* 0050D8 004050D8 0320F809 */  jalr        $t9
/* 0050DC 004050DC 24844E64 */   addiu      $a0, $a0, %lo(STR_10004E64)
/* 0050E0 004050E0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 0050E4 004050E4 10000021 */  b           .L0040516C
/* 0050E8 004050E8 8FBF001C */   lw         $ra, 0x1C($sp)
.L004050EC:
/* 0050EC 004050EC 1100001E */  beqz        $t0, .L00405168
/* 0050F0 004050F0 00074880 */   sll        $t1, $a3, 2
/* 0050F4 004050F4 8F8A8060 */  lw          $t2, %got(D_10000004)($gp)
/* 0050F8 004050F8 8F848050 */  lw          $a0, %got(STR_10004E88)($gp)
/* 0050FC 004050FC 254A0004 */  addiu       $t2, $t2, %lo(D_10000004)
/* 005100 00405100 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 005104 00405104 012A5821 */  addu        $t3, $t1, $t2
/* 005108 00405108 8D650000 */  lw          $a1, 0x0($t3)
/* 00510C 0040510C 24060001 */  addiu       $a2, $zero, 0x1
/* 005110 00405110 0320F809 */  jalr        $t9
/* 005114 00405114 24844E88 */   addiu      $a0, $a0, %lo(STR_10004E88)
/* 005118 00405118 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00511C 0040511C 10000013 */  b           .L0040516C
/* 005120 00405120 8FBF001C */   lw         $ra, 0x1C($sp)
.L00405124:
/* 005124 00405124 28A10040 */  slti        $at, $a1, 0x40
/* 005128 00405128 14200004 */  bnez        $at, .L0040513C
/* 00512C 0040512C 00076080 */   sll        $t4, $a3, 2
/* 005130 00405130 28A10048 */  slti        $at, $a1, 0x48
/* 005134 00405134 1420000D */  bnez        $at, .L0040516C
/* 005138 00405138 8FBF001C */   lw         $ra, 0x1C($sp)
.L0040513C:
/* 00513C 0040513C 8F8D8060 */  lw          $t5, %got(D_10000004)($gp)
/* 005140 00405140 8F848050 */  lw          $a0, %got(STR_10004EAC)($gp)
/* 005144 00405144 25AD0004 */  addiu       $t5, $t5, %lo(D_10000004)
/* 005148 00405148 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00514C 0040514C 018D7021 */  addu        $t6, $t4, $t5
/* 005150 00405150 8DC50000 */  lw          $a1, 0x0($t6)
/* 005154 00405154 24060001 */  addiu       $a2, $zero, 0x1
/* 005158 00405158 0320F809 */  jalr        $t9
/* 00515C 0040515C 24844EAC */   addiu      $a0, $a0, %lo(STR_10004EAC)
/* 005160 00405160 8FBC0018 */  lw          $gp, 0x18($sp)
/* 005164 00405164 00000000 */  nop
.L00405168:
/* 005168 00405168 8FBF001C */  lw          $ra, 0x1C($sp)
.L0040516C:
/* 00516C 0040516C 27BD0020 */  addiu       $sp, $sp, 0x20
/* 005170 00405170 03E00008 */  jr          $ra
/* 005174 00405174 00000000 */   nop
