.section .rodata
glabel STR_10005784
/* 024784 10005784 */ .asciz "value must be -128..255"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040A958 # 54
# _gp_disp: 0xFC06168
.set noreorder; .cpload $t9; # .set reorder
/* 00A964 0040A964 27BDFFB0 */  addiu       $sp, $sp, -0x50
/* 00A968 0040A968 8F8E8344 */  lw          $t6, %got(LastLabel)($gp)
/* 00A96C 0040A96C AFBF003C */  sw          $ra, 0x3C($sp)
/* 00A970 0040A970 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00A974 0040A974 AFBC0038 */  sw          $gp, 0x38($sp)
/* 00A978 0040A978 AFB70034 */  sw          $s7, 0x34($sp)
/* 00A97C 0040A97C AFB60030 */  sw          $s6, 0x30($sp)
/* 00A980 0040A980 AFB5002C */  sw          $s5, 0x2C($sp)
/* 00A984 0040A984 AFB40028 */  sw          $s4, 0x28($sp)
/* 00A988 0040A988 AFB30024 */  sw          $s3, 0x24($sp)
/* 00A98C 0040A98C AFB20020 */  sw          $s2, 0x20($sp)
/* 00A990 0040A990 AFB1001C */  sw          $s1, 0x1C($sp)
/* 00A994 0040A994 11C00008 */  beqz        $t6, .L0040A9B8
/* 00A998 0040A998 AFB00018 */   sw         $s0, 0x18($sp)
/* 00A99C 0040A99C 8F998014 */  lw          $t9, %got(func_00405574)($gp)
/* 00A9A0 0040A9A0 00002025 */  move        $a0, $zero
/* 00A9A4 0040A9A4 27395574 */  addiu       $t9, $t9, %lo(func_00405574)
/* 00A9A8 0040A9A8 0320F809 */  jalr        $t9
/* 00A9AC 0040A9AC 00000000 */   nop
/* 00A9B0 0040A9B0 8FBC0038 */  lw          $gp, 0x38($sp)
/* 00A9B4 0040A9B4 00000000 */  nop
.L0040A9B8:
/* 00A9B8 0040A9B8 8F978050 */  lw          $s7, %got(STR_10005784)($gp)
/* 00A9BC 0040A9BC 8F968378 */  lw          $s6, %got(Tokench)($gp)
/* 00A9C0 0040A9C0 8F94833C */  lw          $s4, %got(isStruct)($gp)
/* 00A9C4 0040A9C4 8F918340 */  lw          $s1, %got(StructOrg)($gp)
/* 00A9C8 0040A9C8 8F9083A0 */  lw          $s0, %got(binasm_rec)($gp)
/* 00A9CC 0040A9CC 24150023 */  addiu       $s5, $zero, 0x23
/* 00A9D0 0040A9D0 27B3004C */  addiu       $s3, $sp, 0x4C
/* 00A9D4 0040A9D4 27B20048 */  addiu       $s2, $sp, 0x48
/* 00A9D8 0040A9D8 26F75784 */  addiu       $s7, $s7, %lo(STR_10005784)
.L0040A9DC:
/* 00A9DC 0040A9DC 8F9981A0 */  lw          $t9, %call16(GetItem)($gp)
/* 00A9E0 0040A9E0 02402025 */  move        $a0, $s2
/* 00A9E4 0040A9E4 0320F809 */  jalr        $t9
/* 00A9E8 0040A9E8 02602825 */   move       $a1, $s3
/* 00A9EC 0040A9EC 8E8F0000 */  lw          $t7, 0x0($s4)
/* 00A9F0 0040A9F0 8FBC0038 */  lw          $gp, 0x38($sp)
/* 00A9F4 0040A9F4 11E0000D */  beqz        $t7, .L0040AA2C
/* 00A9F8 0040A9F8 8FA20048 */   lw         $v0, 0x48($sp)
/* 00A9FC 0040A9FC 8FA3004C */  lw          $v1, 0x4C($sp)
/* 00AA00 0040AA00 00000000 */  nop
/* 00AA04 0040AA04 1C600003 */  bgtz        $v1, .L0040AA14
/* 00AA08 0040AA08 00601025 */   move       $v0, $v1
/* 00AA0C 0040AA0C 10000001 */  b           .L0040AA14
/* 00AA10 0040AA10 24020001 */   addiu      $v0, $zero, 0x1
.L0040AA14:
/* 00AA14 0040AA14 8E380000 */  lw          $t8, 0x0($s1)
/* 00AA18 0040AA18 00000000 */  nop
/* 00AA1C 0040AA1C 0058C821 */  addu        $t9, $v0, $t8
/* 00AA20 0040AA20 1000001D */  b           .L0040AA98
/* 00AA24 0040AA24 AE390000 */   sw         $t9, 0x0($s1)
/* 00AA28 0040AA28 8FA20048 */  lw          $v0, 0x48($sp)
.L0040AA2C:
/* 00AA2C 0040AA2C 02E02025 */  move        $a0, $s7
/* 00AA30 0040AA30 2841FF80 */  slti        $at, $v0, -0x80
/* 00AA34 0040AA34 14200004 */  bnez        $at, .L0040AA48
/* 00AA38 0040AA38 28410100 */   slti       $at, $v0, 0x100
/* 00AA3C 0040AA3C 14200008 */  bnez        $at, .L0040AA60
/* 00AA40 0040AA40 00000000 */   nop
/* 00AA44 0040AA44 AFA20048 */  sw          $v0, 0x48($sp)
.L0040AA48:
/* 00AA48 0040AA48 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00AA4C 0040AA4C 00002825 */  move        $a1, $zero
/* 00AA50 0040AA50 0320F809 */  jalr        $t9
/* 00AA54 0040AA54 24060001 */   addiu      $a2, $zero, 0x1
/* 00AA58 0040AA58 8FBC0038 */  lw          $gp, 0x38($sp)
/* 00AA5C 0040AA5C 00001025 */  move        $v0, $zero
.L0040AA60:
/* 00AA60 0040AA60 92080005 */  lbu         $t0, 0x5($s0)
/* 00AA64 0040AA64 8FA3004C */  lw          $v1, 0x4C($sp)
/* 00AA68 0040AA68 3109FFC0 */  andi        $t1, $t0, 0xFFC0
/* 00AA6C 0040AA6C 352A0007 */  ori         $t2, $t1, 0x7
/* 00AA70 0040AA70 AE000000 */  sw          $zero, 0x0($s0)
/* 00AA74 0040AA74 A20A0005 */  sb          $t2, 0x5($s0)
/* 00AA78 0040AA78 AE020008 */  sw          $v0, 0x8($s0)
/* 00AA7C 0040AA7C AE03000C */  sw          $v1, 0xC($s0)
/* 00AA80 0040AA80 8F9981A8 */  lw          $t9, %call16(put_binasmfyle)($gp)
/* 00AA84 0040AA84 AFA20048 */  sw          $v0, 0x48($sp)
/* 00AA88 0040AA88 0320F809 */  jalr        $t9
/* 00AA8C 0040AA8C 00000000 */   nop
/* 00AA90 0040AA90 8FBC0038 */  lw          $gp, 0x38($sp)
/* 00AA94 0040AA94 00000000 */  nop
.L0040AA98:
/* 00AA98 0040AA98 92CB0000 */  lbu         $t3, 0x0($s6)
/* 00AA9C 0040AA9C 00000000 */  nop
/* 00AAA0 0040AAA0 16ABFFCE */  bne         $s5, $t3, .L0040A9DC
/* 00AAA4 0040AAA4 00000000 */   nop
/* 00AAA8 0040AAA8 8FBF003C */  lw          $ra, 0x3C($sp)
/* 00AAAC 0040AAAC 8FB00018 */  lw          $s0, 0x18($sp)
/* 00AAB0 0040AAB0 8FB1001C */  lw          $s1, 0x1C($sp)
/* 00AAB4 0040AAB4 8FB20020 */  lw          $s2, 0x20($sp)
/* 00AAB8 0040AAB8 8FB30024 */  lw          $s3, 0x24($sp)
/* 00AABC 0040AABC 8FB40028 */  lw          $s4, 0x28($sp)
/* 00AAC0 0040AAC0 8FB5002C */  lw          $s5, 0x2C($sp)
/* 00AAC4 0040AAC4 8FB60030 */  lw          $s6, 0x30($sp)
/* 00AAC8 0040AAC8 8FB70034 */  lw          $s7, 0x34($sp)
/* 00AACC 0040AACC 03E00008 */  jr          $ra
/* 00AAD0 0040AAD0 27BD0050 */   addiu      $sp, $sp, 0x50
