.section .rodata
glabel STR_10005AEC
/* 024AEC 10005AEC */ .asciz "Reserved name used as label"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040D284 # 84
# _gp_disp: 0xFC0383C
.set noreorder; .cpload $t9; # .set reorder
/* 00D290 0040D290 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 00D294 0040D294 8F99816C */  lw          $t9, %call16(LookUp)($gp)
/* 00D298 0040D298 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00D29C 0040D29C AFB00014 */  sw          $s0, 0x14($sp)
/* 00D2A0 0040D2A0 00808025 */  move        $s0, $a0
/* 00D2A4 0040D2A4 AFBC0018 */  sw          $gp, 0x18($sp)
/* 00D2A8 0040D2A8 0320F809 */  jalr        $t9
/* 00D2AC 0040D2AC 27A50024 */   addiu      $a1, $sp, 0x24
/* 00D2B0 0040D2B0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00D2B4 0040D2B4 14400007 */  bnez        $v0, .L0040D2D4
/* 00D2B8 0040D2B8 02002025 */   move       $a0, $s0
/* 00D2BC 0040D2BC 8F99818C */  lw          $t9, %call16(EnterSym)($gp)
/* 00D2C0 0040D2C0 27A50024 */  addiu       $a1, $sp, 0x24
/* 00D2C4 0040D2C4 0320F809 */  jalr        $t9
/* 00D2C8 0040D2C8 00003025 */   move       $a2, $zero
/* 00D2CC 0040D2CC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00D2D0 0040D2D0 00000000 */  nop
.L0040D2D4:
/* 00D2D4 0040D2D4 8FAE0024 */  lw          $t6, 0x24($sp)
/* 00D2D8 0040D2D8 24010003 */  addiu       $at, $zero, 0x3
/* 00D2DC 0040D2DC 8DC20010 */  lw          $v0, 0x10($t6)
/* 00D2E0 0040D2E0 8FAF0024 */  lw          $t7, 0x24($sp)
/* 00D2E4 0040D2E4 1041000B */  beq         $v0, $at, .L0040D314
/* 00D2E8 0040D2E8 24010004 */   addiu      $at, $zero, 0x4
/* 00D2EC 0040D2EC 10410009 */  beq         $v0, $at, .L0040D314
/* 00D2F0 0040D2F0 02002825 */   move       $a1, $s0
/* 00D2F4 0040D2F4 8F848050 */  lw          $a0, %got(STR_10005AEC)($gp)
/* 00D2F8 0040D2F8 8F9981C8 */  lw          $t9, %call16(posterror)($gp)
/* 00D2FC 0040D2FC 24060001 */  addiu       $a2, $zero, 0x1
/* 00D300 0040D300 0320F809 */  jalr        $t9
/* 00D304 0040D304 24845AEC */   addiu      $a0, $a0, %lo(STR_10005AEC)
/* 00D308 0040D308 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00D30C 0040D30C 10000034 */  b           .L0040D3E0
/* 00D310 0040D310 8FBF001C */   lw         $ra, 0x1C($sp)
.L0040D314:
/* 00D314 0040D314 8F85832C */  lw          $a1, %got(CurrentSegment)($gp)
/* 00D318 0040D318 8F998150 */  lw          $t9, %call16(sym_define)($gp)
/* 00D31C 0040D31C 8DE40018 */  lw          $a0, 0x18($t7)
/* 00D320 0040D320 8CA50000 */  lw          $a1, 0x0($a1)
/* 00D324 0040D324 0320F809 */  jalr        $t9
/* 00D328 0040D328 00003025 */   move       $a2, $zero
/* 00D32C 0040D32C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00D330 0040D330 8FB80024 */  lw          $t8, 0x24($sp)
/* 00D334 0040D334 8F8383A0 */  lw          $v1, %got(binasm_rec)($gp)
/* 00D338 0040D338 8F190018 */  lw          $t9, 0x18($t8)
/* 00D33C 0040D33C 90680005 */  lbu         $t0, 0x5($v1)
/* 00D340 0040D340 8F8A83BC */  lw          $t2, %got(list_extsyms)($gp)
/* 00D344 0040D344 3109FFC0 */  andi        $t1, $t0, 0xFFC0
/* 00D348 0040D348 A0690005 */  sb          $t1, 0x5($v1)
/* 00D34C 0040D34C AC790000 */  sw          $t9, 0x0($v1)
/* 00D350 0040D350 8D4A0000 */  lw          $t2, 0x0($t2)
/* 00D354 0040D354 00000000 */  nop
/* 00D358 0040D358 1140001A */  beqz        $t2, .L0040D3C4
/* 00D35C 0040D35C 00000000 */   nop
/* 00D360 0040D360 920B0000 */  lbu         $t3, 0x0($s0)
/* 00D364 0040D364 8F8C8078 */  lw          $t4, %got(__ctype)($gp)
/* 00D368 0040D368 8FB80024 */  lw          $t8, 0x24($sp)
/* 00D36C 0040D36C 016C6821 */  addu        $t5, $t3, $t4
/* 00D370 0040D370 91AE0001 */  lbu         $t6, 0x1($t5)
/* 00D374 0040D374 8FB90024 */  lw          $t9, 0x24($sp)
/* 00D378 0040D378 31CF0004 */  andi        $t7, $t6, 0x4
/* 00D37C 0040D37C 11E00009 */  beqz        $t7, .L0040D3A4
/* 00D380 0040D380 00000000 */   nop
/* 00D384 0040D384 8F998014 */  lw          $t9, %got(func_004054E8)($gp)
/* 00D388 0040D388 8F040018 */  lw          $a0, 0x18($t8)
/* 00D38C 0040D38C 273954E8 */  addiu       $t9, $t9, %lo(func_004054E8)
/* 00D390 0040D390 0320F809 */  jalr        $t9
/* 00D394 0040D394 00002825 */   move       $a1, $zero
/* 00D398 0040D398 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00D39C 0040D39C 10000009 */  b           .L0040D3C4
/* 00D3A0 0040D3A0 00000000 */   nop
.L0040D3A4:
/* 00D3A4 0040D3A4 8F240018 */  lw          $a0, 0x18($t9)
/* 00D3A8 0040D3A8 8F998014 */  lw          $t9, %got(func_004054E8)($gp)
/* 00D3AC 0040D3AC 02002825 */  move        $a1, $s0
/* 00D3B0 0040D3B0 273954E8 */  addiu       $t9, $t9, %lo(func_004054E8)
/* 00D3B4 0040D3B4 0320F809 */  jalr        $t9
/* 00D3B8 0040D3B8 00000000 */   nop
/* 00D3BC 0040D3BC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00D3C0 0040D3C0 00000000 */  nop
.L0040D3C4:
/* 00D3C4 0040D3C4 8F9981A8 */  lw          $t9, %call16(put_binasmfyle)($gp)
/* 00D3C8 0040D3C8 00000000 */  nop
/* 00D3CC 0040D3CC 0320F809 */  jalr        $t9
/* 00D3D0 0040D3D0 00000000 */   nop
/* 00D3D4 0040D3D4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00D3D8 0040D3D8 00000000 */  nop
/* 00D3DC 0040D3DC 8FBF001C */  lw          $ra, 0x1C($sp)
.L0040D3E0:
/* 00D3E0 0040D3E0 8FB00014 */  lw          $s0, 0x14($sp)
/* 00D3E4 0040D3E4 03E00008 */  jr          $ra
/* 00D3E8 0040D3E8 27BD0028 */   addiu      $sp, $sp, 0x28
