.section .rodata
glabel STR_10006114
/* 025114 10006114 */ .asciz "Expected global in data_localize"
                      .balign 4

glabel STR_10006138
/* 025138 10006138 */ .asciz "Expected non-Proc in data_localize"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel func_0040E3F0 # 89
# _gp_disp: 0xFC026D0
.set noreorder; .cpload $t9; # .set reorder
/* 00E3FC 0040E3FC 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* 00E400 0040E400 8F9981EC */  lw          $t9, %call16(st_pdn_idn)($gp)
/* 00E404 0040E404 AFBF0024 */  sw          $ra, 0x24($sp)
/* 00E408 0040E408 AFBC0020 */  sw          $gp, 0x20($sp)
/* 00E40C 0040E40C AFB0001C */  sw          $s0, 0x1C($sp)
/* 00E410 0040E410 AFA50034 */  sw          $a1, 0x34($sp)
/* 00E414 0040E414 AFA60038 */  sw          $a2, 0x38($sp)
/* 00E418 0040E418 0320F809 */  jalr        $t9
/* 00E41C 0040E41C AFA7003C */   sw         $a3, 0x3C($sp)
/* 00E420 0040E420 AFA2002C */  sw          $v0, 0x2C($sp)
/* 00E424 0040E424 8C4E0000 */  lw          $t6, 0x0($v0)
/* 00E428 0040E428 3C017FFF */  lui         $at, (0x7FFFFFFF >> 16)
/* 00E42C 0040E42C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E430 0040E430 3421FFFF */  ori         $at, $at, (0x7FFFFFFF & 0xFFFF)
/* 00E434 0040E434 11C10009 */  beq         $t6, $at, .L0040E45C
/* 00E438 0040E438 8FAF002C */   lw         $t7, 0x2C($sp)
/* 00E43C 0040E43C 8F848050 */  lw          $a0, %got(STR_10006114)($gp)
/* 00E440 0040E440 8F9981CC */  lw          $t9, %call16(postcerror)($gp)
/* 00E444 0040E444 00002825 */  move        $a1, $zero
/* 00E448 0040E448 0320F809 */  jalr        $t9
/* 00E44C 0040E44C 24846114 */   addiu      $a0, $a0, %lo(STR_10006114)
/* 00E450 0040E450 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E454 0040E454 00000000 */  nop
/* 00E458 0040E458 8FAF002C */  lw          $t7, 0x2C($sp)
.L0040E45C:
/* 00E45C 0040E45C 8F9981E4 */  lw          $t9, %call16(st_pext_iext)($gp)
/* 00E460 0040E460 8DE40004 */  lw          $a0, 0x4($t7)
/* 00E464 0040E464 0320F809 */  jalr        $t9
/* 00E468 0040E468 00000000 */   nop
/* 00E46C 0040E46C 8FB80034 */  lw          $t8, 0x34($sp)
/* 00E470 0040E470 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E474 0040E474 2401000E */  addiu       $at, $zero, 0xE
/* 00E478 0040E478 13010004 */  beq         $t8, $at, .L0040E48C
/* 00E47C 0040E47C 00408025 */   move       $s0, $v0
/* 00E480 0040E480 24010006 */  addiu       $at, $zero, 0x6
/* 00E484 0040E484 17010008 */  bne         $t8, $at, .L0040E4A8
/* 00E488 0040E488 00000000 */   nop
.L0040E48C:
/* 00E48C 0040E48C 8F848050 */  lw          $a0, %got(STR_10006138)($gp)
/* 00E490 0040E490 8F9981CC */  lw          $t9, %call16(postcerror)($gp)
/* 00E494 0040E494 00002825 */  move        $a1, $zero
/* 00E498 0040E498 0320F809 */  jalr        $t9
/* 00E49C 0040E49C 24846138 */   addiu      $a0, $a0, %lo(STR_10006138)
/* 00E4A0 0040E4A0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E4A4 0040E4A4 00000000 */  nop
.L0040E4A8:
/* 00E4A8 0040E4A8 8F998274 */  lw          $t9, %call16(st_str_extiss)($gp)
/* 00E4AC 0040E4AC 8E040004 */  lw          $a0, 0x4($s0)
/* 00E4B0 0040E4B0 0320F809 */  jalr        $t9
/* 00E4B4 0040E4B4 00000000 */   nop
/* 00E4B8 0040E4B8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E4BC 0040E4BC 00402025 */  move        $a0, $v0
/* 00E4C0 0040E4C0 8F998260 */  lw          $t9, %call16(st_stradd)($gp)
/* 00E4C4 0040E4C4 00000000 */  nop
/* 00E4C8 0040E4C8 0320F809 */  jalr        $t9
/* 00E4CC 0040E4CC 00000000 */   nop
/* 00E4D0 0040E4D0 3C19000F */  lui         $t9, (0xFFFFF >> 16)
/* 00E4D4 0040E4D4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E4D8 0040E4D8 3739FFFF */  ori         $t9, $t9, (0xFFFFF & 0xFFFF)
/* 00E4DC 0040E4DC AFB90010 */  sw          $t9, 0x10($sp)
/* 00E4E0 0040E4E0 8F9981F0 */  lw          $t9, %call16(st_symadd)($gp)
/* 00E4E4 0040E4E4 8FA5003C */  lw          $a1, 0x3C($sp)
/* 00E4E8 0040E4E8 8FA60034 */  lw          $a2, 0x34($sp)
/* 00E4EC 0040E4EC 8FA70038 */  lw          $a3, 0x38($sp)
/* 00E4F0 0040E4F0 0320F809 */  jalr        $t9
/* 00E4F4 0040E4F4 00402025 */   move       $a0, $v0
/* 00E4F8 0040E4F8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E4FC 0040E4FC 8FA8002C */  lw          $t0, 0x2C($sp)
/* 00E500 0040E500 00000000 */  nop
/* 00E504 0040E504 AD020004 */  sw          $v0, 0x4($t0)
/* 00E508 0040E508 8F998248 */  lw          $t9, %call16(st_currentifd)($gp)
/* 00E50C 0040E50C 00000000 */  nop
/* 00E510 0040E510 0320F809 */  jalr        $t9
/* 00E514 0040E514 00000000 */   nop
/* 00E518 0040E518 8FA9002C */  lw          $t1, 0x2C($sp)
/* 00E51C 0040E51C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00E520 0040E520 AD220000 */  sw          $v0, 0x0($t1)
/* 00E524 0040E524 920A000C */  lbu         $t2, 0xC($s0)
/* 00E528 0040E528 00000000 */  nop
/* 00E52C 0040E52C 314BFF03 */  andi        $t3, $t2, 0xFF03
/* 00E530 0040E530 A20B000C */  sb          $t3, 0xC($s0)
/* 00E534 0040E534 960C000C */  lhu         $t4, 0xC($s0)
/* 00E538 0040E538 00000000 */  nop
/* 00E53C 0040E53C 318DFC1F */  andi        $t5, $t4, 0xFC1F
/* 00E540 0040E540 A60D000C */  sh          $t5, 0xC($s0)
/* 00E544 0040E544 8FBF0024 */  lw          $ra, 0x24($sp)
/* 00E548 0040E548 8FB0001C */  lw          $s0, 0x1C($sp)
/* 00E54C 0040E54C 03E00008 */  jr          $ra
/* 00E550 0040E550 27BD0030 */   addiu      $sp, $sp, 0x30
