/* Generated by spimdisasm 1.10.3 */

glabel GetItem # 132
# _gp_disp: 0xFBFE06C
.set noreorder; .cpload $t9; # .set reorder
/* 012A60 00412A60 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 012A64 00412A64 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 012A68 00412A68 AFBF001C */  sw          $ra, 0x1C($sp)
/* 012A6C 00412A6C AFBC0018 */  sw          $gp, 0x18($sp)
/* 012A70 00412A70 AFA40020 */  sw          $a0, 0x20($sp)
/* 012A74 00412A74 0320F809 */  jalr        $t9
/* 012A78 00412A78 AFA50024 */   sw         $a1, 0x24($sp)
/* 012A7C 00412A7C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 012A80 00412A80 8FAE0020 */  lw          $t6, 0x20($sp)
/* 012A84 00412A84 8F8F8378 */  lw          $t7, %got(Tokench)($gp)
/* 012A88 00412A88 ADC20000 */  sw          $v0, 0x0($t6)
/* 012A8C 00412A8C 91EF0000 */  lbu         $t7, 0x0($t7)
/* 012A90 00412A90 2401003A */  addiu       $at, $zero, 0x3A
/* 012A94 00412A94 15E10010 */  bne         $t7, $at, .L00412AD8
/* 012A98 00412A98 8FA80024 */   lw         $t0, 0x24($sp)
/* 012A9C 00412A9C 8F99817C */  lw          $t9, %call16(nexttoken)($gp)
/* 012AA0 00412AA0 00000000 */  nop
/* 012AA4 00412AA4 0320F809 */  jalr        $t9
/* 012AA8 00412AA8 00000000 */   nop
/* 012AAC 00412AAC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 012AB0 00412AB0 00000000 */  nop
/* 012AB4 00412AB4 8F998194 */  lw          $t9, %call16(GetExpr)($gp)
/* 012AB8 00412AB8 00000000 */  nop
/* 012ABC 00412ABC 0320F809 */  jalr        $t9
/* 012AC0 00412AC0 00000000 */   nop
/* 012AC4 00412AC4 8FB80024 */  lw          $t8, 0x24($sp)
/* 012AC8 00412AC8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 012ACC 00412ACC 10000004 */  b           .L00412AE0
/* 012AD0 00412AD0 AF020000 */   sw         $v0, 0x0($t8)
/* 012AD4 00412AD4 8FA80024 */  lw          $t0, 0x24($sp)
.L00412AD8:
/* 012AD8 00412AD8 24190001 */  addiu       $t9, $zero, 0x1
/* 012ADC 00412ADC AD190000 */  sw          $t9, 0x0($t0)
.L00412AE0:
/* 012AE0 00412AE0 8FBF001C */  lw          $ra, 0x1C($sp)
/* 012AE4 00412AE4 27BD0020 */  addiu       $sp, $sp, 0x20
/* 012AE8 00412AE8 03E00008 */  jr          $ra
/* 012AEC 00412AEC 00000000 */   nop
