.section .rodata
glabel STR_10007C8C
/* 026C8C 10007C8C */ .asciz "%s\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel postcerror # 151
# _gp_disp: 0xFBFD578
.set noreorder; .cpload $t9; # .set reorder
/* 013554 00413554 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 013558 00413558 8F9981BC */  lw          $t9, %call16(call_name_and_line)($gp)
/* 01355C 0041355C AFBF001C */  sw          $ra, 0x1C($sp)
/* 013560 00413560 AFA40020 */  sw          $a0, 0x20($sp)
/* 013564 00413564 AFBC0018 */  sw          $gp, 0x18($sp)
/* 013568 00413568 0320F809 */  jalr        $t9
/* 01356C 0041356C 00A02025 */   move       $a0, $a1
/* 013570 00413570 8FA60020 */  lw          $a2, 0x20($sp)
/* 013574 00413574 8FBC0018 */  lw          $gp, 0x18($sp)
/* 013578 00413578 10C0000A */  beqz        $a2, .L004135A4
/* 01357C 0041357C 8FBF001C */   lw         $ra, 0x1C($sp)
/* 013580 00413580 8F84807C */  lw          $a0, %got(__iob)($gp)
/* 013584 00413584 8F858050 */  lw          $a1, %got(STR_10007C8C)($gp)
/* 013588 00413588 8F998090 */  lw          $t9, %call16(fprintf)($gp)
/* 01358C 0041358C 24840020 */  addiu       $a0, $a0, 0x20
/* 013590 00413590 0320F809 */  jalr        $t9
/* 013594 00413594 24A57C8C */   addiu      $a1, $a1, %lo(STR_10007C8C)
/* 013598 00413598 8FBC0018 */  lw          $gp, 0x18($sp)
/* 01359C 0041359C 00000000 */  nop
/* 0135A0 004135A0 8FBF001C */  lw          $ra, 0x1C($sp)
.L004135A4:
/* 0135A4 004135A4 27BD0020 */  addiu       $sp, $sp, 0x20
/* 0135A8 004135A8 03E00008 */  jr          $ra
/* 0135AC 004135AC 00000000 */   nop
