/* Generated by spimdisasm 1.10.3 */

glabel st_auxbtadd # 203
# _gp_disp: 0xFBF9F20
.set noreorder; .cpload $t9; # .set reorder
/* 016BAC 00416BAC 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 016BB0 00416BB0 8F9980B0 */  lw          $t9, %call16(memset)($gp)
/* 016BB4 00416BB4 AFBF001C */  sw          $ra, 0x1C($sp)
/* 016BB8 00416BB8 AFA40028 */  sw          $a0, 0x28($sp)
/* 016BBC 00416BBC AFBC0018 */  sw          $gp, 0x18($sp)
/* 016BC0 00416BC0 27A40024 */  addiu       $a0, $sp, 0x24
/* 016BC4 00416BC4 00002825 */  move        $a1, $zero
/* 016BC8 00416BC8 0320F809 */  jalr        $t9
/* 016BCC 00416BCC 24060004 */   addiu      $a2, $zero, 0x4
/* 016BD0 00416BD0 8FAF0028 */  lw          $t7, 0x28($sp)
/* 016BD4 00416BD4 93B90024 */  lbu         $t9, 0x24($sp)
/* 016BD8 00416BD8 31F8003F */  andi        $t8, $t7, 0x3F
/* 016BDC 00416BDC 3328FFC0 */  andi        $t0, $t9, 0xFFC0
/* 016BE0 00416BE0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 016BE4 00416BE4 03084825 */  or          $t1, $t8, $t0
/* 016BE8 00416BE8 A3A90024 */  sb          $t1, 0x24($sp)
/* 016BEC 00416BEC 8FA40024 */  lw          $a0, 0x24($sp)
/* 016BF0 00416BF0 8F998258 */  lw          $t9, %call16(st_auxadd)($gp)
/* 016BF4 00416BF4 AFA40000 */  sw          $a0, 0x0($sp)
/* 016BF8 00416BF8 0320F809 */  jalr        $t9
/* 016BFC 00416BFC 00000000 */   nop
/* 016C00 00416C00 8FBF001C */  lw          $ra, 0x1C($sp)
/* 016C04 00416C04 8FBC0018 */  lw          $gp, 0x18($sp)
/* 016C08 00416C08 03E00008 */  jr          $ra
/* 016C0C 00416C0C 27BD0028 */   addiu      $sp, $sp, 0x28
