/* Generated by spimdisasm 1.10.3 */

glabel st_currentpchdr # 224
# _gp_disp: 0xFBF89A4
.set noreorder; .cpload $t9; # .set reorder
/* 018128 00418128 8F8283CC */  lw          $v0, %got(st_pchdr)($gp)
/* 01812C 0041812C 00000000 */  nop
/* 018130 00418130 8C420000 */  lw          $v0, 0x0($v0)
/* 018134 00418134 03E00008 */  jr          $ra
/* 018138 00418138 00000000 */   nop
