.section .rodata
glabel STR_10008020
/* 027020 10008020 */ .asciz "st_cuinit: cannot allocate current chdr\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel st_cuinit # 155
# _gp_disp: 0xFBFD250
.set noreorder; .cpload $t9; # .set reorder
/* 01387C 0041387C 8F9980C4 */  lw          $t9, %call16(calloc)($gp)
/* 013880 00413880 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 013884 00413884 AFBF001C */  sw          $ra, 0x1C($sp)
/* 013888 00413888 AFBC0018 */  sw          $gp, 0x18($sp)
/* 01388C 0041388C 240400BC */  addiu       $a0, $zero, 0xBC
/* 013890 00413890 0320F809 */  jalr        $t9
/* 013894 00413894 24050001 */   addiu      $a1, $zero, 0x1
/* 013898 00413898 8FBC0018 */  lw          $gp, 0x18($sp)
/* 01389C 0041389C 00401825 */  move        $v1, $v0
/* 0138A0 004138A0 8F8583CC */  lw          $a1, %got(st_pchdr)($gp)
/* 0138A4 004138A4 1440000C */  bnez        $v0, .L004138D8
/* 0138A8 004138A8 ACA20000 */   sw         $v0, 0x0($a1)
/* 0138AC 004138AC 8F848054 */  lw          $a0, %got(STR_10008020)($gp)
/* 0138B0 004138B0 8F99820C */  lw          $t9, %call16(_md_st_error)($gp)
/* 0138B4 004138B4 24848020 */  addiu       $a0, $a0, %lo(STR_10008020)
/* 0138B8 004138B8 0320F809 */  jalr        $t9
/* 0138BC 004138BC 00000000 */   nop
/* 0138C0 004138C0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 0138C4 004138C4 00000000 */  nop
/* 0138C8 004138C8 8F8583CC */  lw          $a1, %got(st_pchdr)($gp)
/* 0138CC 004138CC 00000000 */  nop
/* 0138D0 004138D0 8CA30000 */  lw          $v1, 0x0($a1)
/* 0138D4 004138D4 00000000 */  nop
.L004138D8:
/* 0138D8 004138D8 240E0002 */  addiu       $t6, $zero, 0x2
/* 0138DC 004138DC AC6E003C */  sw          $t6, 0x3C($v1)
/* 0138E0 004138E0 8FBF001C */  lw          $ra, 0x1C($sp)
/* 0138E4 004138E4 8CA20000 */  lw          $v0, 0x0($a1)
/* 0138E8 004138E8 03E00008 */  jr          $ra
/* 0138EC 004138EC 27BD0020 */   addiu      $sp, $sp, 0x20
