/* Generated by spimdisasm 1.10.3 */

glabel st_changedn # 195
# _gp_disp: 0xFBFA880
.set noreorder; .cpload $t9; # .set reorder
/* 01624C 0041624C 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 016250 00416250 8F9981EC */  lw          $t9, %call16(st_pdn_idn)($gp)
/* 016254 00416254 AFBF001C */  sw          $ra, 0x1C($sp)
/* 016258 00416258 AFBC0018 */  sw          $gp, 0x18($sp)
/* 01625C 0041625C AFA50024 */  sw          $a1, 0x24($sp)
/* 016260 00416260 0320F809 */  jalr        $t9
/* 016264 00416264 AFA60028 */   sw         $a2, 0x28($sp)
/* 016268 00416268 8FAE0024 */  lw          $t6, 0x24($sp)
/* 01626C 0041626C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 016270 00416270 AC4E0000 */  sw          $t6, 0x0($v0)
/* 016274 00416274 8FAF0028 */  lw          $t7, 0x28($sp)
/* 016278 00416278 00000000 */  nop
/* 01627C 0041627C AC4F0004 */  sw          $t7, 0x4($v0)
/* 016280 00416280 8FBF001C */  lw          $ra, 0x1C($sp)
/* 016284 00416284 27BD0020 */  addiu       $sp, $sp, 0x20
/* 016288 00416288 03E00008 */  jr          $ra
/* 01628C 0041628C 00000000 */   nop
