.section .rodata
glabel STR_1000851C
/* 02751C 1000851C */ .asciz "st_paux_ifd_iaux: ifd (%d) or iline (%d) out of range\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel st_pline_ifd_iline # 220
# _gp_disp: 0xFBF8D04
.set noreorder; .cpload $t9; # .set reorder
/* 017DC8 00417DC8 8F8E83CC */  lw          $t6, %got(st_pchdr)($gp)
/* 017DCC 00417DCC 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 017DD0 00417DD0 8DCE0000 */  lw          $t6, 0x0($t6)
/* 017DD4 00417DD4 AFBF001C */  sw          $ra, 0x1C($sp)
/* 017DD8 00417DD8 AFBC0018 */  sw          $gp, 0x18($sp)
/* 017DDC 00417DDC 8DCF0004 */  lw          $t7, 0x4($t6)
/* 017DE0 00417DE0 00803825 */  move        $a3, $a0
/* 017DE4 00417DE4 15E0000B */  bnez        $t7, .L00417E14
/* 017DE8 00417DE8 00A03025 */   move       $a2, $a1
/* 017DEC 00417DEC 8F848060 */  lw          $a0, %got(D_10001390)($gp)
/* 017DF0 00417DF0 8F9981B8 */  lw          $t9, %call16(st_internal)($gp)
/* 017DF4 00417DF4 AFA5002C */  sw          $a1, 0x2C($sp)
/* 017DF8 00417DF8 AFA70028 */  sw          $a3, 0x28($sp)
/* 017DFC 00417DFC 0320F809 */  jalr        $t9
/* 017E00 00417E00 24841390 */   addiu      $a0, $a0, %lo(D_10001390)
/* 017E04 00417E04 8FBC0018 */  lw          $gp, 0x18($sp)
/* 017E08 00417E08 8FA6002C */  lw          $a2, 0x2C($sp)
/* 017E0C 00417E0C 8FA70028 */  lw          $a3, 0x28($sp)
/* 017E10 00417E10 00000000 */  nop
.L00417E14:
/* 017E14 00417E14 04E00016 */  bltz        $a3, .L00417E70
/* 017E18 00417E18 00E02825 */   move       $a1, $a3
/* 017E1C 00417E1C 04C00014 */  bltz        $a2, .L00417E70
/* 017E20 00417E20 00000000 */   nop
/* 017E24 00417E24 8F8283CC */  lw          $v0, %got(st_pchdr)($gp)
/* 017E28 00417E28 00000000 */  nop
/* 017E2C 00417E2C 8C420000 */  lw          $v0, 0x0($v0)
/* 017E30 00417E30 00000000 */  nop
/* 017E34 00417E34 8C58000C */  lw          $t8, 0xC($v0)
/* 017E38 00417E38 00000000 */  nop
/* 017E3C 00417E3C 00F8082A */  slt         $at, $a3, $t8
/* 017E40 00417E40 1020000B */  beqz        $at, .L00417E70
/* 017E44 00417E44 00000000 */   nop
/* 017E48 00417E48 8C590004 */  lw          $t9, 0x4($v0)
/* 017E4C 00417E4C 00074180 */  sll         $t0, $a3, 6
/* 017E50 00417E50 03281821 */  addu        $v1, $t9, $t0
/* 017E54 00417E54 8C690000 */  lw          $t1, 0x0($v1)
/* 017E58 00417E58 00000000 */  nop
/* 017E5C 00417E5C 8D2A001C */  lw          $t2, 0x1C($t1)
/* 017E60 00417E60 00000000 */  nop
/* 017E64 00417E64 00CA082A */  slt         $at, $a2, $t2
/* 017E68 00417E68 14200011 */  bnez        $at, .L00417EB0
/* 017E6C 00417E6C 00000000 */   nop
.L00417E70:
/* 017E70 00417E70 8F848054 */  lw          $a0, %got(STR_1000851C)($gp)
/* 017E74 00417E74 8F9981B8 */  lw          $t9, %call16(st_internal)($gp)
/* 017E78 00417E78 00075980 */  sll         $t3, $a3, 6
/* 017E7C 00417E7C AFAB0024 */  sw          $t3, 0x24($sp)
/* 017E80 00417E80 AFA6002C */  sw          $a2, 0x2C($sp)
/* 017E84 00417E84 0320F809 */  jalr        $t9
/* 017E88 00417E88 2484851C */   addiu      $a0, $a0, %lo(STR_1000851C)
/* 017E8C 00417E8C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 017E90 00417E90 8FAE0024 */  lw          $t6, 0x24($sp)
/* 017E94 00417E94 8F8C83CC */  lw          $t4, %got(st_pchdr)($gp)
/* 017E98 00417E98 8FA6002C */  lw          $a2, 0x2C($sp)
/* 017E9C 00417E9C 8D8C0000 */  lw          $t4, 0x0($t4)
/* 017EA0 00417EA0 00000000 */  nop
/* 017EA4 00417EA4 8D8D0004 */  lw          $t5, 0x4($t4)
/* 017EA8 00417EA8 00000000 */  nop
/* 017EAC 00417EAC 01AE1821 */  addu        $v1, $t5, $t6
.L00417EB0:
/* 017EB0 00417EB0 8C6F0024 */  lw          $t7, 0x24($v1)
/* 017EB4 00417EB4 8FBF001C */  lw          $ra, 0x1C($sp)
/* 017EB8 00417EB8 0006C080 */  sll         $t8, $a2, 2
/* 017EBC 00417EBC 27BD0028 */  addiu       $sp, $sp, 0x28
/* 017EC0 00417EC0 03E00008 */  jr          $ra
/* 017EC4 00417EC4 01F81021 */   addu       $v0, $t7, $t8
