/* Generated by spimdisasm 1.10.3 */

glabel st_printf_3 # 140
# _gp_disp: 0xFBFDB9C
.set noreorder; .cpload $t9; # .set reorder
/* 012F30 00412F30 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 012F34 00412F34 AFA50024 */  sw          $a1, 0x24($sp)
/* 012F38 00412F38 00802825 */  move        $a1, $a0
/* 012F3C 00412F3C AFA40020 */  sw          $a0, 0x20($sp)
/* 012F40 00412F40 8F84807C */  lw          $a0, %got(__iob)($gp)
/* 012F44 00412F44 8F998090 */  lw          $t9, %call16(fprintf)($gp)
/* 012F48 00412F48 00C03825 */  move        $a3, $a2
/* 012F4C 00412F4C 8FA60024 */  lw          $a2, 0x24($sp)
/* 012F50 00412F50 AFBF001C */  sw          $ra, 0x1C($sp)
/* 012F54 00412F54 AFBC0018 */  sw          $gp, 0x18($sp)
/* 012F58 00412F58 0320F809 */  jalr        $t9
/* 012F5C 00412F5C 24840020 */   addiu      $a0, $a0, 0x20
/* 012F60 00412F60 8FBF001C */  lw          $ra, 0x1C($sp)
/* 012F64 00412F64 8FBC0018 */  lw          $gp, 0x18($sp)
/* 012F68 00412F68 03E00008 */  jr          $ra
/* 012F6C 00412F6C 27BD0020 */   addiu      $sp, $sp, 0x20
