.section .rodata
glabel STR_100084C8
/* 0274C8 100084C8 */ .asciz "st_stradd: argument is nil\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel st_stradd # 216
# _gp_disp: 0xFBF9010
.set noreorder; .cpload $t9; # .set reorder
/* 017ABC 00417ABC 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 017AC0 00417AC0 AFBF0024 */  sw          $ra, 0x24($sp)
/* 017AC4 00417AC4 AFBC0020 */  sw          $gp, 0x20($sp)
/* 017AC8 00417AC8 AFB2001C */  sw          $s2, 0x1C($sp)
/* 017ACC 00417ACC AFB10018 */  sw          $s1, 0x18($sp)
/* 017AD0 00417AD0 AFB00014 */  sw          $s0, 0x14($sp)
/* 017AD4 00417AD4 14800008 */  bnez        $a0, .L00417AF8
/* 017AD8 00417AD8 AFA40028 */   sw         $a0, 0x28($sp)
/* 017ADC 00417ADC 8F848054 */  lw          $a0, %got(STR_100084C8)($gp)
/* 017AE0 00417AE0 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 017AE4 00417AE4 248484C8 */  addiu       $a0, $a0, %lo(STR_100084C8)
/* 017AE8 00417AE8 0320F809 */  jalr        $t9
/* 017AEC 00417AEC 00000000 */   nop
/* 017AF0 00417AF0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 017AF4 00417AF4 00000000 */  nop
.L00417AF8:
/* 017AF8 00417AF8 8F9980F8 */  lw          $t9, %call16(strlen)($gp)
/* 017AFC 00417AFC 8FA40028 */  lw          $a0, 0x28($sp)
/* 017B00 00417B00 0320F809 */  jalr        $t9
/* 017B04 00417B04 00000000 */   nop
/* 017B08 00417B08 8FBC0020 */  lw          $gp, 0x20($sp)
/* 017B0C 00417B0C 24520001 */  addiu       $s2, $v0, 0x1
/* 017B10 00417B10 8F8F83CC */  lw          $t7, %got(st_pchdr)($gp)
/* 017B14 00417B14 00000000 */  nop
/* 017B18 00417B18 8DEF0000 */  lw          $t7, 0x0($t7)
/* 017B1C 00417B1C 00000000 */  nop
/* 017B20 00417B20 8DF80004 */  lw          $t8, 0x4($t7)
/* 017B24 00417B24 00000000 */  nop
/* 017B28 00417B28 17000008 */  bnez        $t8, .L00417B4C
/* 017B2C 00417B2C 00000000 */   nop
/* 017B30 00417B30 8F848060 */  lw          $a0, %got(D_10001390)($gp)
/* 017B34 00417B34 8F9981B8 */  lw          $t9, %call16(st_internal)($gp)
/* 017B38 00417B38 24841390 */  addiu       $a0, $a0, %lo(D_10001390)
/* 017B3C 00417B3C 0320F809 */  jalr        $t9
/* 017B40 00417B40 00000000 */   nop
/* 017B44 00417B44 8FBC0020 */  lw          $gp, 0x20($sp)
/* 017B48 00417B48 00000000 */  nop
.L00417B4C:
/* 017B4C 00417B4C 8F9183D0 */  lw          $s1, %got(pcfdcur)($gp)
/* 017B50 00417B50 00000000 */  nop
/* 017B54 00417B54 8E300000 */  lw          $s0, 0x0($s1)
/* 017B58 00417B58 00000000 */  nop
/* 017B5C 00417B5C 16000009 */  bnez        $s0, .L00417B84
/* 017B60 00417B60 00000000 */   nop
/* 017B64 00417B64 8F848060 */  lw          $a0, %got(D_100013CC)($gp)
/* 017B68 00417B68 8F9981B8 */  lw          $t9, %call16(st_internal)($gp)
/* 017B6C 00417B6C 248413CC */  addiu       $a0, $a0, %lo(D_100013CC)
/* 017B70 00417B70 0320F809 */  jalr        $t9
/* 017B74 00417B74 00000000 */   nop
/* 017B78 00417B78 8FBC0020 */  lw          $gp, 0x20($sp)
/* 017B7C 00417B7C 8E300000 */  lw          $s0, 0x0($s1)
/* 017B80 00417B80 00000000 */  nop
.L00417B84:
/* 017B84 00417B84 8E19003C */  lw          $t9, 0x3C($s0)
/* 017B88 00417B88 00000000 */  nop
/* 017B8C 00417B8C 33280080 */  andi        $t0, $t9, 0x80
/* 017B90 00417B90 11000009 */  beqz        $t0, .L00417BB8
/* 017B94 00417B94 00000000 */   nop
/* 017B98 00417B98 8F848060 */  lw          $a0, %got(D_10001400)($gp)
/* 017B9C 00417B9C 8F9981B8 */  lw          $t9, %call16(st_internal)($gp)
/* 017BA0 00417BA0 24841400 */  addiu       $a0, $a0, %lo(D_10001400)
/* 017BA4 00417BA4 0320F809 */  jalr        $t9
/* 017BA8 00417BA8 00000000 */   nop
/* 017BAC 00417BAC 8FBC0020 */  lw          $gp, 0x20($sp)
/* 017BB0 00417BB0 8E300000 */  lw          $s0, 0x0($s1)
/* 017BB4 00417BB4 00000000 */  nop
.L00417BB8:
/* 017BB8 00417BB8 8E090000 */  lw          $t1, 0x0($s0)
/* 017BBC 00417BBC 8E0A0018 */  lw          $t2, 0x18($s0)
/* 017BC0 00417BC0 8D23000C */  lw          $v1, 0xC($t1)
/* 017BC4 00417BC4 00000000 */  nop
/* 017BC8 00417BC8 00725821 */  addu        $t3, $v1, $s2
/* 017BCC 00417BCC 014B082A */  slt         $at, $t2, $t3
/* 017BD0 00417BD0 10200014 */  beqz        $at, .L00417C24
/* 017BD4 00417BD4 00000000 */   nop
.L00417BD8:
/* 017BD8 00417BD8 8F998268 */  lw          $t9, %call16(st_malloc)($gp)
/* 017BDC 00417BDC 8E040014 */  lw          $a0, 0x14($s0)
/* 017BE0 00417BE0 26050018 */  addiu       $a1, $s0, 0x18
/* 017BE4 00417BE4 24060001 */  addiu       $a2, $zero, 0x1
/* 017BE8 00417BE8 0320F809 */  jalr        $t9
/* 017BEC 00417BEC 24070200 */   addiu      $a3, $zero, 0x200
/* 017BF0 00417BF0 8E2C0000 */  lw          $t4, 0x0($s1)
/* 017BF4 00417BF4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 017BF8 00417BF8 AD820014 */  sw          $v0, 0x14($t4)
/* 017BFC 00417BFC 8E300000 */  lw          $s0, 0x0($s1)
/* 017C00 00417C00 00000000 */  nop
/* 017C04 00417C04 8E0D0000 */  lw          $t5, 0x0($s0)
/* 017C08 00417C08 8E0E0018 */  lw          $t6, 0x18($s0)
/* 017C0C 00417C0C 8DA3000C */  lw          $v1, 0xC($t5)
/* 017C10 00417C10 00000000 */  nop
/* 017C14 00417C14 00727821 */  addu        $t7, $v1, $s2
/* 017C18 00417C18 01CF082A */  slt         $at, $t6, $t7
/* 017C1C 00417C1C 1420FFEE */  bnez        $at, .L00417BD8
/* 017C20 00417C20 00000000 */   nop
.L00417C24:
/* 017C24 00417C24 8E180014 */  lw          $t8, 0x14($s0)
/* 017C28 00417C28 8F998104 */  lw          $t9, %call16(strcpy)($gp)
/* 017C2C 00417C2C 8FA50028 */  lw          $a1, 0x28($sp)
/* 017C30 00417C30 0320F809 */  jalr        $t9
/* 017C34 00417C34 03032021 */   addu       $a0, $t8, $v1
/* 017C38 00417C38 8E390000 */  lw          $t9, 0x0($s1)
/* 017C3C 00417C3C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 017C40 00417C40 8F240000 */  lw          $a0, 0x0($t9)
/* 017C44 00417C44 00000000 */  nop
/* 017C48 00417C48 8C82000C */  lw          $v0, 0xC($a0)
/* 017C4C 00417C4C 00000000 */  nop
/* 017C50 00417C50 00524021 */  addu        $t0, $v0, $s2
/* 017C54 00417C54 AC88000C */  sw          $t0, 0xC($a0)
/* 017C58 00417C58 8FBF0024 */  lw          $ra, 0x24($sp)
/* 017C5C 00417C5C 8FB2001C */  lw          $s2, 0x1C($sp)
/* 017C60 00417C60 8FB10018 */  lw          $s1, 0x18($sp)
/* 017C64 00417C64 8FB00014 */  lw          $s0, 0x14($sp)
/* 017C68 00417C68 03E00008 */  jr          $ra
/* 017C6C 00417C6C 27BD0028 */   addiu      $sp, $sp, 0x28
