.section .rodata
glabel STR_10008960
/* 027960 10008960 */ .asciz "w"
                      .balign 4

glabel STR_10008964
/* 027964 10008964 */ .asciz "st_writest: cannot write to file number %d\n"
                      .balign 4

glabel STR_10008990
/* 027990 10008990 */ .asciz "cannot write round bytes for lines\n"
                      .balign 4

glabel STR_100089B4
/* 0279B4 100089B4 */ .asciz "cannot write round bytes for strings\n"
                      .balign 4

glabel STR_100089DC
/* 0279DC 100089DC */ .asciz "cannot write round bytes for strings\n"
                      .balign 4

glabel STR_10008A04
/* 027A04 10008A04 */ .asciz "cannot write symbol header\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel st_writest # 239
# _gp_disp: 0xFBF6B20
.set noreorder; .cpload $t9; # .set reorder
/* 019FAC 00419FAC 27BDFE28 */  addiu       $sp, $sp, -0x1D8
/* 019FB0 00419FB0 8F998084 */  lw          $t9, %call16(bzero)($gp)
/* 019FB4 00419FB4 AFB00014 */  sw          $s0, 0x14($sp)
/* 019FB8 00419FB8 00808025 */  move        $s0, $a0
/* 019FBC 00419FBC AFBF003C */  sw          $ra, 0x3C($sp)
/* 019FC0 00419FC0 AFA501DC */  sw          $a1, 0x1DC($sp)
/* 019FC4 00419FC4 AFBE0038 */  sw          $fp, 0x38($sp)
/* 019FC8 00419FC8 AFBC0034 */  sw          $gp, 0x34($sp)
/* 019FCC 00419FCC AFB70030 */  sw          $s7, 0x30($sp)
/* 019FD0 00419FD0 AFB6002C */  sw          $s6, 0x2C($sp)
/* 019FD4 00419FD4 AFB50028 */  sw          $s5, 0x28($sp)
/* 019FD8 00419FD8 AFB40024 */  sw          $s4, 0x24($sp)
/* 019FDC 00419FDC AFB30020 */  sw          $s3, 0x20($sp)
/* 019FE0 00419FE0 AFB2001C */  sw          $s2, 0x1C($sp)
/* 019FE4 00419FE4 AFB10018 */  sw          $s1, 0x18($sp)
/* 019FE8 00419FE8 24050048 */  addiu       $a1, $zero, 0x48
/* 019FEC 00419FEC 27A4018C */  addiu       $a0, $sp, 0x18C
/* 019FF0 00419FF0 0320F809 */  jalr        $t9
/* 019FF4 00419FF4 AFA00120 */   sw         $zero, 0x120($sp)
/* 019FF8 00419FF8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 019FFC 00419FFC 27A40128 */  addiu       $a0, $sp, 0x128
/* 01A000 0041A000 8F998084 */  lw          $t9, %call16(bzero)($gp)
/* 01A004 0041A004 24050060 */  addiu       $a1, $zero, 0x60
/* 01A008 0041A008 0320F809 */  jalr        $t9
/* 01A00C 0041A00C 00000000 */   nop
/* 01A010 0041A010 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A014 0041A014 00000000 */  nop
/* 01A018 0041A018 8F99824C */  lw          $t9, %call16(st_ifdmax)($gp)
/* 01A01C 0041A01C 00000000 */  nop
/* 01A020 0041A020 0320F809 */  jalr        $t9
/* 01A024 0041A024 00000000 */   nop
/* 01A028 0041A028 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A02C 0041A02C AFA20114 */  sw          $v0, 0x114($sp)
/* 01A030 0041A030 8F998128 */  lw          $t9, %call16(lseek)($gp)
/* 01A034 0041A034 02002025 */  move        $a0, $s0
/* 01A038 0041A038 00002825 */  move        $a1, $zero
/* 01A03C 0041A03C 0320F809 */  jalr        $t9
/* 01A040 0041A040 24060001 */   addiu      $a2, $zero, 0x1
/* 01A044 0041A044 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A048 0041A048 AFA20110 */  sw          $v0, 0x110($sp)
/* 01A04C 0041A04C 8F998128 */  lw          $t9, %call16(lseek)($gp)
/* 01A050 0041A050 02002025 */  move        $a0, $s0
/* 01A054 0041A054 24050060 */  addiu       $a1, $zero, 0x60
/* 01A058 0041A058 0320F809 */  jalr        $t9
/* 01A05C 0041A05C 24060001 */   addiu      $a2, $zero, 0x1
/* 01A060 0041A060 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A064 0041A064 8FAE0114 */  lw          $t6, 0x114($sp)
/* 01A068 0041A068 8F8F83CC */  lw          $t7, %got(st_pchdr)($gp)
/* 01A06C 0041A06C AFA2011C */  sw          $v0, 0x11C($sp)
/* 01A070 0041A070 8DEF0000 */  lw          $t7, 0x0($t7)
/* 01A074 0041A074 02002025 */  move        $a0, $s0
/* 01A078 0041A078 ADEE000C */  sw          $t6, 0xC($t7)
/* 01A07C 0041A07C 8F9980E8 */  lw          $t9, %call16(dup)($gp)
/* 01A080 0041A080 00000000 */  nop
/* 01A084 0041A084 0320F809 */  jalr        $t9
/* 01A088 0041A088 00000000 */   nop
/* 01A08C 0041A08C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A090 0041A090 00402025 */  move        $a0, $v0
/* 01A094 0041A094 8F858054 */  lw          $a1, %got(STR_10008960)($gp)
/* 01A098 0041A098 8F998120 */  lw          $t9, %call16(fdopen)($gp)
/* 01A09C 0041A09C 24A58960 */  addiu       $a1, $a1, %lo(STR_10008960)
/* 01A0A0 0041A0A0 0320F809 */  jalr        $t9
/* 01A0A4 0041A0A4 00000000 */   nop
/* 01A0A8 0041A0A8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A0AC 0041A0AC 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A0B0 0041A0B0 1440000A */  bnez        $v0, .L0041A0DC
/* 01A0B4 0041A0B4 AFA2010C */   sw         $v0, 0x10C($sp)
/* 01A0B8 0041A0B8 8F848054 */  lw          $a0, %got(STR_10008964)($gp)
/* 01A0BC 0041A0BC 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01A0C0 0041A0C0 02002825 */  move        $a1, $s0
/* 01A0C4 0041A0C4 AFAB0120 */  sw          $t3, 0x120($sp)
/* 01A0C8 0041A0C8 0320F809 */  jalr        $t9
/* 01A0CC 0041A0CC 24848964 */   addiu      $a0, $a0, %lo(STR_10008964)
/* 01A0D0 0041A0D0 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A0D4 0041A0D4 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A0D8 0041A0D8 00000000 */  nop
.L0041A0DC:
/* 01A0DC 0041A0DC 8FB801DC */  lw          $t8, 0x1DC($sp)
/* 01A0E0 0041A0E0 00000000 */  nop
/* 01A0E4 0041A0E4 33190004 */  andi        $t9, $t8, 0x4
/* 01A0E8 0041A0E8 132000E5 */  beqz        $t9, .L0041A480
/* 01A0EC 0041A0EC 8FB801DC */   lw         $t8, 0x1DC($sp)
/* 01A0F0 0041A0F0 8FAC0114 */  lw          $t4, 0x114($sp)
/* 01A0F4 0041A0F4 2416FFFF */  addiu       $s6, $zero, -0x1
/* 01A0F8 0041A0F8 198000C0 */  blez        $t4, .L0041A3FC
/* 01A0FC 0041A0FC 8FB9012C */   lw         $t9, 0x12C($sp)
/* 01A100 0041A100 AFA00118 */  sw          $zero, 0x118($sp)
/* 01A104 0041A104 27BE0068 */  addiu       $fp, $sp, 0x68
.L0041A108:
/* 01A108 0041A108 8F9981F8 */  lw          $t9, %call16(st_pcfd_ifd)($gp)
/* 01A10C 0041A10C 8FA40118 */  lw          $a0, 0x118($sp)
/* 01A110 0041A110 AFA00124 */  sw          $zero, 0x124($sp)
/* 01A114 0041A114 0320F809 */  jalr        $t9
/* 01A118 0041A118 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A11C 0041A11C 8C4D0000 */  lw          $t5, 0x0($v0)
/* 01A120 0041A120 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A124 0041A124 AFAD0188 */  sw          $t5, 0x188($sp)
/* 01A128 0041A128 8DA3001C */  lw          $v1, 0x1C($t5)
/* 01A12C 0041A12C 8FAA0124 */  lw          $t2, 0x124($sp)
/* 01A130 0041A130 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A134 0041A134 106000AB */  beqz        $v1, .L0041A3E4
/* 01A138 0041A138 00404825 */   move       $t1, $v0
/* 01A13C 0041A13C 8C4F0024 */  lw          $t7, 0x24($v0)
/* 01A140 0041A140 8FB8012C */  lw          $t8, 0x12C($sp)
/* 01A144 0041A144 11E000A7 */  beqz        $t7, .L0041A3E4
/* 01A148 0041A148 03036021 */   addu       $t4, $t8, $v1
/* 01A14C 0041A14C ADB80018 */  sw          $t8, 0x18($t5)
/* 01A150 0041A150 AFAC012C */  sw          $t4, 0x12C($sp)
/* 01A154 0041A154 ADAB0040 */  sw          $t3, 0x40($t5)
/* 01A158 0041A158 AFA00108 */  sw          $zero, 0x108($sp)
/* 01A15C 0041A15C 95B1002A */  lhu         $s1, 0x2A($t5)
/* 01A160 0041A160 00000000 */  nop
/* 01A164 0041A164 1220009D */  beqz        $s1, .L0041A3DC
/* 01A168 0041A168 8FB80188 */   lw         $t8, 0x188($sp)
/* 01A16C 0041A16C AFA00058 */  sw          $zero, 0x58($sp)
.L0041A170:
/* 01A170 0041A170 8D2D0034 */  lw          $t5, 0x34($t1)
/* 01A174 0041A174 8FAE0058 */  lw          $t6, 0x58($sp)
/* 01A178 0041A178 00000000 */  nop
/* 01A17C 0041A17C 01AE4021 */  addu        $t0, $t5, $t6
/* 01A180 0041A180 8D0F0008 */  lw          $t7, 0x8($t0)
/* 01A184 0041A184 00000000 */  nop
/* 01A188 0041A188 12CF008C */  beq         $s6, $t7, .L0041A3BC
/* 01A18C 0041A18C 8FAC0108 */   lw         $t4, 0x108($sp)
/* 01A190 0041A190 8D180028 */  lw          $t8, 0x28($t0)
/* 01A194 0041A194 00000000 */  nop
/* 01A198 0041A198 12D80088 */  beq         $s6, $t8, .L0041A3BC
/* 01A19C 0041A19C 8FAC0108 */   lw         $t4, 0x108($sp)
/* 01A1A0 0041A1A0 8D0C002C */  lw          $t4, 0x2C($t0)
/* 01A1A4 0041A1A4 8FB90188 */  lw          $t9, 0x188($sp)
/* 01A1A8 0041A1A8 12CC0084 */  beq         $s6, $t4, .L0041A3BC
/* 01A1AC 0041A1AC 8FAC0108 */   lw         $t4, 0x108($sp)
/* 01A1B0 0041A1B0 8F2D0040 */  lw          $t5, 0x40($t9)
/* 01A1B4 0041A1B4 00002025 */  move        $a0, $zero
/* 01A1B8 0041A1B8 016D7023 */  subu        $t6, $t3, $t5
/* 01A1BC 0041A1BC AD0E0030 */  sw          $t6, 0x30($t0)
/* 01A1C0 0041A1C0 8FAF0188 */  lw          $t7, 0x188($sp)
/* 01A1C4 0041A1C4 00000000 */  nop
/* 01A1C8 0041A1C8 95F1002A */  lhu         $s1, 0x2A($t7)
/* 01A1CC 0041A1CC 8DE5001C */  lw          $a1, 0x1C($t7)
/* 01A1D0 0041A1D0 12200017 */  beqz        $s1, .L0041A230
/* 01A1D4 0041A1D4 00000000 */   nop
/* 01A1D8 0041A1D8 8D060008 */  lw          $a2, 0x8($t0)
/* 01A1DC 0041A1DC 8D230034 */  lw          $v1, 0x34($t1)
/* 01A1E0 0041A1E0 00000000 */  nop
.L0041A1E4:
/* 01A1E4 0041A1E4 8C620008 */  lw          $v0, 0x8($v1)
/* 01A1E8 0041A1E8 24840001 */  addiu       $a0, $a0, 0x1
/* 01A1EC 0041A1EC 00C2082A */  slt         $at, $a2, $v0
/* 01A1F0 0041A1F0 1020000D */  beqz        $at, .L0041A228
/* 01A1F4 0041A1F4 0091082B */   sltu       $at, $a0, $s1
/* 01A1F8 0041A1F8 8C780028 */  lw          $t8, 0x28($v1)
/* 01A1FC 0041A1FC 00000000 */  nop
/* 01A200 0041A200 12D80009 */  beq         $s6, $t8, .L0041A228
/* 01A204 0041A204 0091082B */   sltu       $at, $a0, $s1
/* 01A208 0041A208 8C6C002C */  lw          $t4, 0x2C($v1)
/* 01A20C 0041A20C 0045082A */  slt         $at, $v0, $a1
/* 01A210 0041A210 12CC0004 */  beq         $s6, $t4, .L0041A224
/* 01A214 0041A214 00000000 */   nop
/* 01A218 0041A218 10200003 */  beqz        $at, .L0041A228
/* 01A21C 0041A21C 0091082B */   sltu       $at, $a0, $s1
/* 01A220 0041A220 00402825 */  move        $a1, $v0
.L0041A224:
/* 01A224 0041A224 0091082B */  sltu        $at, $a0, $s1
.L0041A228:
/* 01A228 0041A228 1420FFEE */  bnez        $at, .L0041A1E4
/* 01A22C 0041A22C 24630034 */   addiu      $v1, $v1, 0x34
.L0041A230:
/* 01A230 0041A230 18A00062 */  blez        $a1, .L0041A3BC
/* 01A234 0041A234 8FAC0108 */   lw         $t4, 0x108($sp)
/* 01A238 0041A238 8D060008 */  lw          $a2, 0x8($t0)
/* 01A23C 0041A23C 02C09025 */  move        $s2, $s6
/* 01A240 0041A240 04C0005D */  bltz        $a2, .L0041A3B8
/* 01A244 0041A244 0006C880 */   sll        $t9, $a2, 2
/* 01A248 0041A248 8D220024 */  lw          $v0, 0x24($t1)
/* 01A24C 0041A24C 0005B880 */  sll         $s7, $a1, 2
/* 01A250 0041A250 00599821 */  addu        $s3, $v0, $t9
/* 01A254 0041A254 00571821 */  addu        $v1, $v0, $s7
/* 01A258 0041A258 8D150028 */  lw          $s5, 0x28($t0)
/* 01A25C 0041A25C 0073082B */  sltu        $at, $v1, $s3
/* 01A260 0041A260 0000A025 */  move        $s4, $zero
/* 01A264 0041A264 14200054 */  bnez        $at, .L0041A3B8
/* 01A268 0041A268 03C08025 */   move       $s0, $fp
.L0041A26C:
/* 01A26C 0041A26C 16630003 */  bne         $s3, $v1, .L0041A27C
/* 01A270 0041A270 24010008 */   addiu      $at, $zero, 0x8
/* 01A274 0041A274 1000000B */  b           .L0041A2A4
/* 01A278 0041A278 24030001 */   addiu      $v1, $zero, 0x1
.L0041A27C:
/* 01A27C 0041A27C 8E620000 */  lw          $v0, 0x0($s3)
/* 01A280 0041A280 00000000 */  nop
/* 01A284 0041A284 14400004 */  bnez        $v0, .L0041A298
/* 01A288 0041A288 00402025 */   move       $a0, $v0
/* 01A28C 0041A28C 8D040028 */  lw          $a0, 0x28($t0)
/* 01A290 0041A290 10000002 */  b           .L0041A29C
/* 01A294 0041A294 00951823 */   subu       $v1, $a0, $s5
.L0041A298:
/* 01A298 0041A298 00951823 */  subu        $v1, $a0, $s5
.L0041A29C:
/* 01A29C 0041A29C 00036C00 */  sll         $t5, $v1, 16
/* 01A2A0 0041A2A0 000D1C03 */  sra         $v1, $t5, 16
.L0041A2A4:
/* 01A2A4 0041A2A4 14600003 */  bnez        $v1, .L0041A2B4
/* 01A2A8 0041A2A8 03C02025 */   move       $a0, $fp
/* 01A2AC 0041A2AC 1641001B */  bne         $s2, $at, .L0041A31C
/* 01A2B0 0041A2B0 26020003 */   addiu      $v0, $s0, 0x3
.L0041A2B4:
/* 01A2B4 0041A2B4 1256000A */  beq         $s2, $s6, .L0041A2E0
/* 01A2B8 0041A2B8 02A3A821 */   addu       $s5, $s5, $v1
/* 01A2BC 0041A2BC 2A81FFF9 */  slti        $at, $s4, -0x7
/* 01A2C0 0041A2C0 14200007 */  bnez        $at, .L0041A2E0
/* 01A2C4 0041A2C4 2A810008 */   slti       $at, $s4, 0x8
/* 01A2C8 0041A2C8 10200005 */  beqz        $at, .L0041A2E0
/* 01A2CC 0041A2CC 00146100 */   sll        $t4, $s4, 4
/* 01A2D0 0041A2D0 0192C825 */  or          $t9, $t4, $s2
/* 01A2D4 0041A2D4 A2190000 */  sb          $t9, 0x0($s0)
/* 01A2D8 0041A2D8 1000000A */  b           .L0041A304
/* 01A2DC 0041A2DC 26100001 */   addiu      $s0, $s0, 0x1
.L0041A2E0:
/* 01A2E0 0041A2E0 12560008 */  beq         $s2, $s6, .L0041A304
/* 01A2E4 0041A2E4 00147A03 */   sra        $t7, $s4, 8
/* 01A2E8 0041A2E8 A2120000 */  sb          $s2, 0x0($s0)
/* 01A2EC 0041A2EC 820D0000 */  lb          $t5, 0x0($s0)
/* 01A2F0 0041A2F0 A20F0001 */  sb          $t7, 0x1($s0)
/* 01A2F4 0041A2F4 35AE0080 */  ori         $t6, $t5, 0x80
/* 01A2F8 0041A2F8 A20E0000 */  sb          $t6, 0x0($s0)
/* 01A2FC 0041A2FC A2140002 */  sb          $s4, 0x2($s0)
/* 01A300 0041A300 26100003 */  addiu       $s0, $s0, 0x3
.L0041A304:
/* 01A304 0041A304 0003A400 */  sll         $s4, $v1, 16
/* 01A308 0041A308 00146403 */  sra         $t4, $s4, 16
/* 01A30C 0041A30C 00009025 */  move        $s2, $zero
/* 01A310 0041A310 0180A025 */  move        $s4, $t4
/* 01A314 0041A314 10000002 */  b           .L0041A320
/* 01A318 0041A318 26020003 */   addiu      $v0, $s0, 0x3
.L0041A31C:
/* 01A31C 0041A31C 26520001 */  addiu       $s2, $s2, 0x1
.L0041A320:
/* 01A320 0041A320 27B900E8 */  addiu       $t9, $sp, 0xE8
/* 01A324 0041A324 0059082B */  sltu        $at, $v0, $t9
/* 01A328 0041A328 10200008 */  beqz        $at, .L0041A34C
/* 01A32C 0041A32C 021E8823 */   subu       $s1, $s0, $fp
/* 01A330 0041A330 8D2D0024 */  lw          $t5, 0x24($t1)
/* 01A334 0041A334 021E7023 */  subu        $t6, $s0, $fp
/* 01A338 0041A338 01B71821 */  addu        $v1, $t5, $s7
/* 01A33C 0041A33C 16630016 */  bne         $s3, $v1, .L0041A398
/* 01A340 0041A340 00000000 */   nop
/* 01A344 0041A344 19C00014 */  blez        $t6, .L0041A398
/* 01A348 0041A348 00000000 */   nop
.L0041A34C:
/* 01A34C 0041A34C 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A350 0041A350 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A354 0041A354 02202825 */  move        $a1, $s1
/* 01A358 0041A358 24060001 */  addiu       $a2, $zero, 0x1
/* 01A35C 0041A35C AFA800FC */  sw          $t0, 0xFC($sp)
/* 01A360 0041A360 AFA901D4 */  sw          $t1, 0x1D4($sp)
/* 01A364 0041A364 AFAA0124 */  sw          $t2, 0x124($sp)
/* 01A368 0041A368 0320F809 */  jalr        $t9
/* 01A36C 0041A36C AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A370 0041A370 8FA901D4 */  lw          $t1, 0x1D4($sp)
/* 01A374 0041A374 8FAA0124 */  lw          $t2, 0x124($sp)
/* 01A378 0041A378 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A37C 0041A37C 8D2F0024 */  lw          $t7, 0x24($t1)
/* 01A380 0041A380 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A384 0041A384 8FA800FC */  lw          $t0, 0xFC($sp)
/* 01A388 0041A388 03C08025 */  move        $s0, $fp
/* 01A38C 0041A38C 01515021 */  addu        $t2, $t2, $s1
/* 01A390 0041A390 01715821 */  addu        $t3, $t3, $s1
/* 01A394 0041A394 01F71821 */  addu        $v1, $t7, $s7
.L0041A398:
/* 01A398 0041A398 26730004 */  addiu       $s3, $s3, 0x4
/* 01A39C 0041A39C 0073082B */  sltu        $at, $v1, $s3
/* 01A3A0 0041A3A0 1020FFB2 */  beqz        $at, .L0041A26C
/* 01A3A4 0041A3A4 00000000 */   nop
/* 01A3A8 0041A3A8 8FB80188 */  lw          $t8, 0x188($sp)
/* 01A3AC 0041A3AC 00000000 */  nop
/* 01A3B0 0041A3B0 9711002A */  lhu         $s1, 0x2A($t8)
/* 01A3B4 0041A3B4 00000000 */  nop
.L0041A3B8:
/* 01A3B8 0041A3B8 8FAC0108 */  lw          $t4, 0x108($sp)
.L0041A3BC:
/* 01A3BC 0041A3BC 8FAD0058 */  lw          $t5, 0x58($sp)
/* 01A3C0 0041A3C0 25990001 */  addiu       $t9, $t4, 0x1
/* 01A3C4 0041A3C4 0331082B */  sltu        $at, $t9, $s1
/* 01A3C8 0041A3C8 25AE0034 */  addiu       $t6, $t5, 0x34
/* 01A3CC 0041A3CC AFAE0058 */  sw          $t6, 0x58($sp)
/* 01A3D0 0041A3D0 1420FF67 */  bnez        $at, .L0041A170
/* 01A3D4 0041A3D4 AFB90108 */   sw         $t9, 0x108($sp)
/* 01A3D8 0041A3D8 8FB80188 */  lw          $t8, 0x188($sp)
.L0041A3DC:
/* 01A3DC 0041A3DC 00000000 */  nop
/* 01A3E0 0041A3E0 AF0A0044 */  sw          $t2, 0x44($t8)
.L0041A3E4:
/* 01A3E4 0041A3E4 8FA20118 */  lw          $v0, 0x118($sp)
/* 01A3E8 0041A3E8 8FAC0114 */  lw          $t4, 0x114($sp)
/* 01A3EC 0041A3EC 24420001 */  addiu       $v0, $v0, 0x1
/* 01A3F0 0041A3F0 144CFF45 */  bne         $v0, $t4, .L0041A108
/* 01A3F4 0041A3F4 AFA20118 */   sw         $v0, 0x118($sp)
/* 01A3F8 0041A3F8 8FB9012C */  lw          $t9, 0x12C($sp)
.L0041A3FC:
/* 01A3FC 0041A3FC 000B8023 */  negu        $s0, $t3
/* 01A400 0041A400 1320001E */  beqz        $t9, .L0041A47C
/* 01A404 0041A404 320D0003 */   andi       $t5, $s0, 0x3
/* 01A408 0041A408 11A00019 */  beqz        $t5, .L0041A470
/* 01A40C 0041A40C 01A08025 */   move       $s0, $t5
/* 01A410 0041A410 8F848064 */  lw          $a0, %got(B_1000A980)($gp)
/* 01A414 0041A414 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A418 0041A418 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A41C 0041A41C 24050001 */  addiu       $a1, $zero, 0x1
/* 01A420 0041A420 01A03025 */  move        $a2, $t5
/* 01A424 0041A424 AFAB0120 */  sw          $t3, 0x120($sp)
/* 01A428 0041A428 0320F809 */  jalr        $t9
/* 01A42C 0041A42C 2484A980 */   addiu      $a0, $a0, %lo(B_1000A980)
/* 01A430 0041A430 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A434 0041A434 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A438 0041A438 10500009 */  beq         $v0, $s0, .L0041A460
/* 01A43C 0041A43C 00000000 */   nop
/* 01A440 0041A440 8F848054 */  lw          $a0, %got(STR_10008990)($gp)
/* 01A444 0041A444 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01A448 0041A448 AFAB0120 */  sw          $t3, 0x120($sp)
/* 01A44C 0041A44C 0320F809 */  jalr        $t9
/* 01A450 0041A450 24848990 */   addiu      $a0, $a0, %lo(STR_10008990)
/* 01A454 0041A454 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A458 0041A458 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A45C 0041A45C 00000000 */  nop
.L0041A460:
/* 01A460 0041A460 256B0003 */  addiu       $t3, $t3, 0x3
/* 01A464 0041A464 2401FFFC */  addiu       $at, $zero, -0x4
/* 01A468 0041A468 01617024 */  and         $t6, $t3, $at
/* 01A46C 0041A46C 01C05825 */  move        $t3, $t6
.L0041A470:
/* 01A470 0041A470 8FAF011C */  lw          $t7, 0x11C($sp)
/* 01A474 0041A474 AFAB0130 */  sw          $t3, 0x130($sp)
/* 01A478 0041A478 AFAF0134 */  sw          $t7, 0x134($sp)
.L0041A47C:
/* 01A47C 0041A47C 8FB801DC */  lw          $t8, 0x1DC($sp)
.L0041A480:
/* 01A480 0041A480 00000000 */  nop
/* 01A484 0041A484 330C0100 */  andi        $t4, $t8, 0x100
/* 01A488 0041A488 11800045 */  beqz        $t4, .L0041A5A0
/* 01A48C 0041A48C 8FAD01DC */   lw         $t5, 0x1DC($sp)
/* 01A490 0041A490 8FB9011C */  lw          $t9, 0x11C($sp)
/* 01A494 0041A494 8FAE0114 */  lw          $t6, 0x114($sp)
/* 01A498 0041A498 032B6821 */  addu        $t5, $t9, $t3
/* 01A49C 0041A49C AFAD011C */  sw          $t5, 0x11C($sp)
/* 01A4A0 0041A4A0 19C00039 */  blez        $t6, .L0041A588
/* 01A4A4 0041A4A4 00005825 */   move       $t3, $zero
/* 01A4A8 0041A4A8 8F928310 */  lw          $s2, %got(msg_werr)($gp)
/* 01A4AC 0041A4AC AFA00118 */  sw          $zero, 0x118($sp)
/* 01A4B0 0041A4B0 24100034 */  addiu       $s0, $zero, 0x34
.L0041A4B4:
/* 01A4B4 0041A4B4 8F9981F8 */  lw          $t9, %call16(st_pcfd_ifd)($gp)
/* 01A4B8 0041A4B8 8FA40118 */  lw          $a0, 0x118($sp)
/* 01A4BC 0041A4BC 0320F809 */  jalr        $t9
/* 01A4C0 0041A4C0 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A4C4 0041A4C4 8C4F0000 */  lw          $t7, 0x0($v0)
/* 01A4C8 0041A4C8 97B801B4 */  lhu         $t8, 0x1B4($sp)
/* 01A4CC 0041A4CC AFAF0188 */  sw          $t7, 0x188($sp)
/* 01A4D0 0041A4D0 95F1002A */  lhu         $s1, 0x2A($t7)
/* 01A4D4 0041A4D4 97AC01B6 */  lhu         $t4, 0x1B6($sp)
/* 01A4D8 0041A4D8 02300019 */  multu       $s1, $s0
/* 01A4DC 0041A4DC 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A4E0 0041A4E0 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A4E4 0041A4E4 030CC821 */  addu        $t9, $t8, $t4
/* 01A4E8 0041A4E8 A5F90028 */  sh          $t9, 0x28($t7)
/* 01A4EC 0041A4EC 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A4F0 0041A4F0 02002825 */  move        $a1, $s0
/* 01A4F4 0041A4F4 02203025 */  move        $a2, $s1
/* 01A4F8 0041A4F8 00002012 */  mflo        $a0
/* 01A4FC 0041A4FC 01645821 */  addu        $t3, $t3, $a0
/* 01A500 0041A500 12200013 */  beqz        $s1, .L0041A550
/* 01A504 0041A504 97B801B4 */   lhu        $t8, 0x1B4($sp)
/* 01A508 0041A508 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A50C 0041A50C 8C440034 */  lw          $a0, 0x34($v0)
/* 01A510 0041A510 0320F809 */  jalr        $t9
/* 01A514 0041A514 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A518 0041A518 8FAE0188 */  lw          $t6, 0x188($sp)
/* 01A51C 0041A51C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A520 0041A520 95CF002A */  lhu         $t7, 0x2A($t6)
/* 01A524 0041A524 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A528 0041A528 104F0009 */  beq         $v0, $t7, .L0041A550
/* 01A52C 0041A52C 97B801B4 */   lhu        $t8, 0x1B4($sp)
/* 01A530 0041A530 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01A534 0041A534 02402025 */  move        $a0, $s2
/* 01A538 0041A538 0320F809 */  jalr        $t9
/* 01A53C 0041A53C AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A540 0041A540 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A544 0041A544 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A548 0041A548 00000000 */  nop
/* 01A54C 0041A54C 97B801B4 */  lhu         $t8, 0x1B4($sp)
.L0041A550:
/* 01A550 0041A550 97AC01B6 */  lhu         $t4, 0x1B6($sp)
/* 01A554 0041A554 8FAD0188 */  lw          $t5, 0x188($sp)
/* 01A558 0041A558 030CC821 */  addu        $t9, $t8, $t4
/* 01A55C 0041A55C A7B901B4 */  sh          $t9, 0x1B4($sp)
/* 01A560 0041A560 95A2002A */  lhu         $v0, 0x2A($t5)
/* 01A564 0041A564 8FA30118 */  lw          $v1, 0x118($sp)
/* 01A568 0041A568 8FAE0140 */  lw          $t6, 0x140($sp)
/* 01A56C 0041A56C 8FB80114 */  lw          $t8, 0x114($sp)
/* 01A570 0041A570 24630001 */  addiu       $v1, $v1, 0x1
/* 01A574 0041A574 01C27821 */  addu        $t7, $t6, $v0
/* 01A578 0041A578 AFAF0140 */  sw          $t7, 0x140($sp)
/* 01A57C 0041A57C AFA30118 */  sw          $v1, 0x118($sp)
/* 01A580 0041A580 1478FFCC */  bne         $v1, $t8, .L0041A4B4
/* 01A584 0041A584 A7A201B6 */   sh         $v0, 0x1B6($sp)
.L0041A588:
/* 01A588 0041A588 8FAC0140 */  lw          $t4, 0x140($sp)
/* 01A58C 0041A58C 8FB9011C */  lw          $t9, 0x11C($sp)
/* 01A590 0041A590 11800003 */  beqz        $t4, .L0041A5A0
/* 01A594 0041A594 8FAD01DC */   lw         $t5, 0x1DC($sp)
/* 01A598 0041A598 AFB90144 */  sw          $t9, 0x144($sp)
/* 01A59C 0041A59C 8FAD01DC */  lw          $t5, 0x1DC($sp)
.L0041A5A0:
/* 01A5A0 0041A5A0 8F928310 */  lw          $s2, %got(msg_werr)($gp)
/* 01A5A4 0041A5A4 31AE0002 */  andi        $t6, $t5, 0x2
/* 01A5A8 0041A5A8 11C00043 */  beqz        $t6, .L0041A6B8
/* 01A5AC 0041A5AC 8FB901DC */   lw         $t9, 0x1DC($sp)
/* 01A5B0 0041A5B0 8FAF011C */  lw          $t7, 0x11C($sp)
/* 01A5B4 0041A5B4 8FAC0114 */  lw          $t4, 0x114($sp)
/* 01A5B8 0041A5B8 01EBC021 */  addu        $t8, $t7, $t3
/* 01A5BC 0041A5BC AFB8011C */  sw          $t8, 0x11C($sp)
/* 01A5C0 0041A5C0 19800037 */  blez        $t4, .L0041A6A0
/* 01A5C4 0041A5C4 00005825 */   move       $t3, $zero
/* 01A5C8 0041A5C8 AFA00118 */  sw          $zero, 0x118($sp)
/* 01A5CC 0041A5CC 2410000C */  addiu       $s0, $zero, 0xC
.L0041A5D0:
/* 01A5D0 0041A5D0 8F9981F8 */  lw          $t9, %call16(st_pcfd_ifd)($gp)
/* 01A5D4 0041A5D4 8FA40118 */  lw          $a0, 0x118($sp)
/* 01A5D8 0041A5D8 0320F809 */  jalr        $t9
/* 01A5DC 0041A5DC AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A5E0 0041A5E0 8C590000 */  lw          $t9, 0x0($v0)
/* 01A5E4 0041A5E4 8FAD019C */  lw          $t5, 0x19C($sp)
/* 01A5E8 0041A5E8 AFB90188 */  sw          $t9, 0x188($sp)
/* 01A5EC 0041A5EC 8F260014 */  lw          $a2, 0x14($t9)
/* 01A5F0 0041A5F0 8FAE01A0 */  lw          $t6, 0x1A0($sp)
/* 01A5F4 0041A5F4 00D00019 */  multu       $a2, $s0
/* 01A5F8 0041A5F8 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A5FC 0041A5FC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A600 0041A600 01AE7821 */  addu        $t7, $t5, $t6
/* 01A604 0041A604 AF2F0010 */  sw          $t7, 0x10($t9)
/* 01A608 0041A608 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A60C 0041A60C 02002825 */  move        $a1, $s0
/* 01A610 0041A610 00002012 */  mflo        $a0
/* 01A614 0041A614 01645821 */  addu        $t3, $t3, $a0
/* 01A618 0041A618 10C00013 */  beqz        $a2, .L0041A668
/* 01A61C 0041A61C 8FAD019C */   lw         $t5, 0x19C($sp)
/* 01A620 0041A620 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A624 0041A624 8C440004 */  lw          $a0, 0x4($v0)
/* 01A628 0041A628 0320F809 */  jalr        $t9
/* 01A62C 0041A62C AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A630 0041A630 8FAC0188 */  lw          $t4, 0x188($sp)
/* 01A634 0041A634 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A638 0041A638 8D990014 */  lw          $t9, 0x14($t4)
/* 01A63C 0041A63C 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A640 0041A640 10590009 */  beq         $v0, $t9, .L0041A668
/* 01A644 0041A644 8FAD019C */   lw         $t5, 0x19C($sp)
/* 01A648 0041A648 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01A64C 0041A64C 02402025 */  move        $a0, $s2
/* 01A650 0041A650 0320F809 */  jalr        $t9
/* 01A654 0041A654 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A658 0041A658 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A65C 0041A65C 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A660 0041A660 00000000 */  nop
/* 01A664 0041A664 8FAD019C */  lw          $t5, 0x19C($sp)
.L0041A668:
/* 01A668 0041A668 8FAE01A0 */  lw          $t6, 0x1A0($sp)
/* 01A66C 0041A66C 8FB80188 */  lw          $t8, 0x188($sp)
/* 01A670 0041A670 01AE7821 */  addu        $t7, $t5, $t6
/* 01A674 0041A674 AFAF019C */  sw          $t7, 0x19C($sp)
/* 01A678 0041A678 8F040014 */  lw          $a0, 0x14($t8)
/* 01A67C 0041A67C 8FAD0118 */  lw          $t5, 0x118($sp)
/* 01A680 0041A680 8FAC0148 */  lw          $t4, 0x148($sp)
/* 01A684 0041A684 8FAF0114 */  lw          $t7, 0x114($sp)
/* 01A688 0041A688 25AE0001 */  addiu       $t6, $t5, 0x1
/* 01A68C 0041A68C 0184C821 */  addu        $t9, $t4, $a0
/* 01A690 0041A690 AFB90148 */  sw          $t9, 0x148($sp)
/* 01A694 0041A694 AFAE0118 */  sw          $t6, 0x118($sp)
/* 01A698 0041A698 15CFFFCD */  bne         $t6, $t7, .L0041A5D0
/* 01A69C 0041A69C AFA401A0 */   sw         $a0, 0x1A0($sp)
.L0041A6A0:
/* 01A6A0 0041A6A0 8FB80148 */  lw          $t8, 0x148($sp)
/* 01A6A4 0041A6A4 8FAC011C */  lw          $t4, 0x11C($sp)
/* 01A6A8 0041A6A8 13000003 */  beqz        $t8, .L0041A6B8
/* 01A6AC 0041A6AC 8FB901DC */   lw         $t9, 0x1DC($sp)
/* 01A6B0 0041A6B0 AFAC014C */  sw          $t4, 0x14C($sp)
/* 01A6B4 0041A6B4 8FB901DC */  lw          $t9, 0x1DC($sp)
.L0041A6B8:
/* 01A6B8 0041A6B8 2410000C */  addiu       $s0, $zero, 0xC
/* 01A6BC 0041A6BC 332D0020 */  andi        $t5, $t9, 0x20
/* 01A6C0 0041A6C0 11A00042 */  beqz        $t5, .L0041A7CC
/* 01A6C4 0041A6C4 8FAC01DC */   lw         $t4, 0x1DC($sp)
/* 01A6C8 0041A6C8 8FAE011C */  lw          $t6, 0x11C($sp)
/* 01A6CC 0041A6CC 8FB80114 */  lw          $t8, 0x114($sp)
/* 01A6D0 0041A6D0 01CB7821 */  addu        $t7, $t6, $t3
/* 01A6D4 0041A6D4 AFAF011C */  sw          $t7, 0x11C($sp)
/* 01A6D8 0041A6D8 1B000036 */  blez        $t8, .L0041A7B4
/* 01A6DC 0041A6DC 00005825 */   move       $t3, $zero
/* 01A6E0 0041A6E0 AFA00118 */  sw          $zero, 0x118($sp)
.L0041A6E4:
/* 01A6E4 0041A6E4 8F9981F8 */  lw          $t9, %call16(st_pcfd_ifd)($gp)
/* 01A6E8 0041A6E8 8FA40118 */  lw          $a0, 0x118($sp)
/* 01A6EC 0041A6EC 0320F809 */  jalr        $t9
/* 01A6F0 0041A6F0 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A6F4 0041A6F4 8C4C0000 */  lw          $t4, 0x0($v0)
/* 01A6F8 0041A6F8 8FB901AC */  lw          $t9, 0x1AC($sp)
/* 01A6FC 0041A6FC AFAC0188 */  sw          $t4, 0x188($sp)
/* 01A700 0041A700 8D860024 */  lw          $a2, 0x24($t4)
/* 01A704 0041A704 8FAD01B0 */  lw          $t5, 0x1B0($sp)
/* 01A708 0041A708 00D00019 */  multu       $a2, $s0
/* 01A70C 0041A70C 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A710 0041A710 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A714 0041A714 032D7021 */  addu        $t6, $t9, $t5
/* 01A718 0041A718 AD8E0020 */  sw          $t6, 0x20($t4)
/* 01A71C 0041A71C 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A720 0041A720 02002825 */  move        $a1, $s0
/* 01A724 0041A724 00002012 */  mflo        $a0
/* 01A728 0041A728 01645821 */  addu        $t3, $t3, $a0
/* 01A72C 0041A72C 10C00013 */  beqz        $a2, .L0041A77C
/* 01A730 0041A730 8FB901AC */   lw         $t9, 0x1AC($sp)
/* 01A734 0041A734 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A738 0041A738 8C44001C */  lw          $a0, 0x1C($v0)
/* 01A73C 0041A73C 0320F809 */  jalr        $t9
/* 01A740 0041A740 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A744 0041A744 8FB80188 */  lw          $t8, 0x188($sp)
/* 01A748 0041A748 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A74C 0041A74C 8F0C0024 */  lw          $t4, 0x24($t8)
/* 01A750 0041A750 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A754 0041A754 104C0009 */  beq         $v0, $t4, .L0041A77C
/* 01A758 0041A758 8FB901AC */   lw         $t9, 0x1AC($sp)
/* 01A75C 0041A75C 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01A760 0041A760 02402025 */  move        $a0, $s2
/* 01A764 0041A764 0320F809 */  jalr        $t9
/* 01A768 0041A768 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A76C 0041A76C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A770 0041A770 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A774 0041A774 00000000 */  nop
/* 01A778 0041A778 8FB901AC */  lw          $t9, 0x1AC($sp)
.L0041A77C:
/* 01A77C 0041A77C 8FAD01B0 */  lw          $t5, 0x1B0($sp)
/* 01A780 0041A780 8FAF0188 */  lw          $t7, 0x188($sp)
/* 01A784 0041A784 032D7021 */  addu        $t6, $t9, $t5
/* 01A788 0041A788 AFAE01AC */  sw          $t6, 0x1AC($sp)
/* 01A78C 0041A78C 8DE40024 */  lw          $a0, 0x24($t7)
/* 01A790 0041A790 8FB90118 */  lw          $t9, 0x118($sp)
/* 01A794 0041A794 8FB80150 */  lw          $t8, 0x150($sp)
/* 01A798 0041A798 8FAE0114 */  lw          $t6, 0x114($sp)
/* 01A79C 0041A79C 272D0001 */  addiu       $t5, $t9, 0x1
/* 01A7A0 0041A7A0 03046021 */  addu        $t4, $t8, $a0
/* 01A7A4 0041A7A4 AFAC0150 */  sw          $t4, 0x150($sp)
/* 01A7A8 0041A7A8 AFAD0118 */  sw          $t5, 0x118($sp)
/* 01A7AC 0041A7AC 15AEFFCD */  bne         $t5, $t6, .L0041A6E4
/* 01A7B0 0041A7B0 AFA401B0 */   sw         $a0, 0x1B0($sp)
.L0041A7B4:
/* 01A7B4 0041A7B4 8FAF0150 */  lw          $t7, 0x150($sp)
/* 01A7B8 0041A7B8 8FB8011C */  lw          $t8, 0x11C($sp)
/* 01A7BC 0041A7BC 11E00003 */  beqz        $t7, .L0041A7CC
/* 01A7C0 0041A7C0 8FAC01DC */   lw         $t4, 0x1DC($sp)
/* 01A7C4 0041A7C4 AFB80154 */  sw          $t8, 0x154($sp)
/* 01A7C8 0041A7C8 8FAC01DC */  lw          $t4, 0x1DC($sp)
.L0041A7CC:
/* 01A7CC 0041A7CC 00000000 */  nop
/* 01A7D0 0041A7D0 31990400 */  andi        $t9, $t4, 0x400
/* 01A7D4 0041A7D4 13200040 */  beqz        $t9, .L0041A8D8
/* 01A7D8 0041A7D8 8FB801DC */   lw         $t8, 0x1DC($sp)
/* 01A7DC 0041A7DC 8FAD011C */  lw          $t5, 0x11C($sp)
/* 01A7E0 0041A7E0 8FAF0114 */  lw          $t7, 0x114($sp)
/* 01A7E4 0041A7E4 01AB7021 */  addu        $t6, $t5, $t3
/* 01A7E8 0041A7E8 AFAE011C */  sw          $t6, 0x11C($sp)
/* 01A7EC 0041A7EC 19E00034 */  blez        $t7, .L0041A8C0
/* 01A7F0 0041A7F0 00005825 */   move       $t3, $zero
/* 01A7F4 0041A7F4 AFA00118 */  sw          $zero, 0x118($sp)
.L0041A7F8:
/* 01A7F8 0041A7F8 8F9981F8 */  lw          $t9, %call16(st_pcfd_ifd)($gp)
/* 01A7FC 0041A7FC 8FA40118 */  lw          $a0, 0x118($sp)
/* 01A800 0041A800 0320F809 */  jalr        $t9
/* 01A804 0041A804 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A808 0041A808 8C580000 */  lw          $t8, 0x0($v0)
/* 01A80C 0041A80C 8FAC01B8 */  lw          $t4, 0x1B8($sp)
/* 01A810 0041A810 AFB80188 */  sw          $t8, 0x188($sp)
/* 01A814 0041A814 8FB901BC */  lw          $t9, 0x1BC($sp)
/* 01A818 0041A818 8F060030 */  lw          $a2, 0x30($t8)
/* 01A81C 0041A81C 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A820 0041A820 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A824 0041A824 01996821 */  addu        $t5, $t4, $t9
/* 01A828 0041A828 00062080 */  sll         $a0, $a2, 2
/* 01A82C 0041A82C AF0D002C */  sw          $t5, 0x2C($t8)
/* 01A830 0041A830 10C00014 */  beqz        $a2, .L0041A884
/* 01A834 0041A834 01645821 */   addu       $t3, $t3, $a0
/* 01A838 0041A838 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A83C 0041A83C 8C44000C */  lw          $a0, 0xC($v0)
/* 01A840 0041A840 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A844 0041A844 AFAB0120 */  sw          $t3, 0x120($sp)
/* 01A848 0041A848 0320F809 */  jalr        $t9
/* 01A84C 0041A84C 24050004 */   addiu      $a1, $zero, 0x4
/* 01A850 0041A850 8FAF0188 */  lw          $t7, 0x188($sp)
/* 01A854 0041A854 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A858 0041A858 8DF80030 */  lw          $t8, 0x30($t7)
/* 01A85C 0041A85C 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A860 0041A860 10580009 */  beq         $v0, $t8, .L0041A888
/* 01A864 0041A864 8FAC01B8 */   lw         $t4, 0x1B8($sp)
/* 01A868 0041A868 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01A86C 0041A86C 02402025 */  move        $a0, $s2
/* 01A870 0041A870 0320F809 */  jalr        $t9
/* 01A874 0041A874 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A878 0041A878 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A87C 0041A87C 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A880 0041A880 00000000 */  nop
.L0041A884:
/* 01A884 0041A884 8FAC01B8 */  lw          $t4, 0x1B8($sp)
.L0041A888:
/* 01A888 0041A888 8FB901BC */  lw          $t9, 0x1BC($sp)
/* 01A88C 0041A88C 8FAE0188 */  lw          $t6, 0x188($sp)
/* 01A890 0041A890 01996821 */  addu        $t5, $t4, $t9
/* 01A894 0041A894 AFAD01B8 */  sw          $t5, 0x1B8($sp)
/* 01A898 0041A898 8DC40030 */  lw          $a0, 0x30($t6)
/* 01A89C 0041A89C 8FAC0118 */  lw          $t4, 0x118($sp)
/* 01A8A0 0041A8A0 8FAF0158 */  lw          $t7, 0x158($sp)
/* 01A8A4 0041A8A4 8FAD0114 */  lw          $t5, 0x114($sp)
/* 01A8A8 0041A8A8 25990001 */  addiu       $t9, $t4, 0x1
/* 01A8AC 0041A8AC 01E4C021 */  addu        $t8, $t7, $a0
/* 01A8B0 0041A8B0 AFB80158 */  sw          $t8, 0x158($sp)
/* 01A8B4 0041A8B4 AFB90118 */  sw          $t9, 0x118($sp)
/* 01A8B8 0041A8B8 172DFFCF */  bne         $t9, $t5, .L0041A7F8
/* 01A8BC 0041A8BC AFA401BC */   sw         $a0, 0x1BC($sp)
.L0041A8C0:
/* 01A8C0 0041A8C0 8FAE0158 */  lw          $t6, 0x158($sp)
/* 01A8C4 0041A8C4 8FAF011C */  lw          $t7, 0x11C($sp)
/* 01A8C8 0041A8C8 11C00003 */  beqz        $t6, .L0041A8D8
/* 01A8CC 0041A8CC 8FB801DC */   lw         $t8, 0x1DC($sp)
/* 01A8D0 0041A8D0 AFAF015C */  sw          $t7, 0x15C($sp)
/* 01A8D4 0041A8D4 8FB801DC */  lw          $t8, 0x1DC($sp)
.L0041A8D8:
/* 01A8D8 0041A8D8 00000000 */  nop
/* 01A8DC 0041A8DC 330C0080 */  andi        $t4, $t8, 0x80
/* 01A8E0 0041A8E0 1180005B */  beqz        $t4, .L0041AA50
/* 01A8E4 0041A8E4 8FB801DC */   lw         $t8, 0x1DC($sp)
/* 01A8E8 0041A8E8 8FB9011C */  lw          $t9, 0x11C($sp)
/* 01A8EC 0041A8EC 8FAE0114 */  lw          $t6, 0x114($sp)
/* 01A8F0 0041A8F0 032B6821 */  addu        $t5, $t9, $t3
/* 01A8F4 0041A8F4 AFAD011C */  sw          $t5, 0x11C($sp)
/* 01A8F8 0041A8F8 19C00033 */  blez        $t6, .L0041A9C8
/* 01A8FC 0041A8FC 00005825 */   move       $t3, $zero
/* 01A900 0041A900 AFA00118 */  sw          $zero, 0x118($sp)
.L0041A904:
/* 01A904 0041A904 8F9981F8 */  lw          $t9, %call16(st_pcfd_ifd)($gp)
/* 01A908 0041A908 8FA40118 */  lw          $a0, 0x118($sp)
/* 01A90C 0041A90C 0320F809 */  jalr        $t9
/* 01A910 0041A910 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A914 0041A914 8C4F0000 */  lw          $t7, 0x0($v0)
/* 01A918 0041A918 8FB80194 */  lw          $t8, 0x194($sp)
/* 01A91C 0041A91C 8FAC0198 */  lw          $t4, 0x198($sp)
/* 01A920 0041A920 AFAF0188 */  sw          $t7, 0x188($sp)
/* 01A924 0041A924 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A928 0041A928 8DE6000C */  lw          $a2, 0xC($t7)
/* 01A92C 0041A92C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A930 0041A930 030CC821 */  addu        $t9, $t8, $t4
/* 01A934 0041A934 ADF90008 */  sw          $t9, 0x8($t7)
/* 01A938 0041A938 10C00014 */  beqz        $a2, .L0041A98C
/* 01A93C 0041A93C 01665821 */   addu       $t3, $t3, $a2
/* 01A940 0041A940 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A944 0041A944 8C440014 */  lw          $a0, 0x14($v0)
/* 01A948 0041A948 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A94C 0041A94C AFAB0120 */  sw          $t3, 0x120($sp)
/* 01A950 0041A950 0320F809 */  jalr        $t9
/* 01A954 0041A954 24050001 */   addiu      $a1, $zero, 0x1
/* 01A958 0041A958 8FAE0188 */  lw          $t6, 0x188($sp)
/* 01A95C 0041A95C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A960 0041A960 8DCF000C */  lw          $t7, 0xC($t6)
/* 01A964 0041A964 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A968 0041A968 104F0009 */  beq         $v0, $t7, .L0041A990
/* 01A96C 0041A96C 8FB80194 */   lw         $t8, 0x194($sp)
/* 01A970 0041A970 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01A974 0041A974 02402025 */  move        $a0, $s2
/* 01A978 0041A978 0320F809 */  jalr        $t9
/* 01A97C 0041A97C AFAB0120 */   sw         $t3, 0x120($sp)
/* 01A980 0041A980 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A984 0041A984 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01A988 0041A988 00000000 */  nop
.L0041A98C:
/* 01A98C 0041A98C 8FB80194 */  lw          $t8, 0x194($sp)
.L0041A990:
/* 01A990 0041A990 8FAC0198 */  lw          $t4, 0x198($sp)
/* 01A994 0041A994 8FAD0188 */  lw          $t5, 0x188($sp)
/* 01A998 0041A998 030CC821 */  addu        $t9, $t8, $t4
/* 01A99C 0041A99C AFB90194 */  sw          $t9, 0x194($sp)
/* 01A9A0 0041A9A0 8DA4000C */  lw          $a0, 0xC($t5)
/* 01A9A4 0041A9A4 8FB80118 */  lw          $t8, 0x118($sp)
/* 01A9A8 0041A9A8 8FAE0160 */  lw          $t6, 0x160($sp)
/* 01A9AC 0041A9AC 8FB90114 */  lw          $t9, 0x114($sp)
/* 01A9B0 0041A9B0 270C0001 */  addiu       $t4, $t8, 0x1
/* 01A9B4 0041A9B4 01C47821 */  addu        $t7, $t6, $a0
/* 01A9B8 0041A9B8 AFAF0160 */  sw          $t7, 0x160($sp)
/* 01A9BC 0041A9BC AFAC0118 */  sw          $t4, 0x118($sp)
/* 01A9C0 0041A9C0 1599FFD0 */  bne         $t4, $t9, .L0041A904
/* 01A9C4 0041A9C4 AFA40198 */   sw         $a0, 0x198($sp)
.L0041A9C8:
/* 01A9C8 0041A9C8 000B8023 */  negu        $s0, $t3
/* 01A9CC 0041A9CC 320D0003 */  andi        $t5, $s0, 0x3
/* 01A9D0 0041A9D0 11A00019 */  beqz        $t5, .L0041AA38
/* 01A9D4 0041A9D4 01A08025 */   move       $s0, $t5
/* 01A9D8 0041A9D8 8F848064 */  lw          $a0, %got(B_1000A980)($gp)
/* 01A9DC 0041A9DC 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01A9E0 0041A9E0 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01A9E4 0041A9E4 24050001 */  addiu       $a1, $zero, 0x1
/* 01A9E8 0041A9E8 01A03025 */  move        $a2, $t5
/* 01A9EC 0041A9EC AFAB0120 */  sw          $t3, 0x120($sp)
/* 01A9F0 0041A9F0 0320F809 */  jalr        $t9
/* 01A9F4 0041A9F4 2484A980 */   addiu      $a0, $a0, %lo(B_1000A980)
/* 01A9F8 0041A9F8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01A9FC 0041A9FC 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AA00 0041AA00 10500009 */  beq         $v0, $s0, .L0041AA28
/* 01AA04 0041AA04 00000000 */   nop
/* 01AA08 0041AA08 8F848054 */  lw          $a0, %got(STR_100089B4)($gp)
/* 01AA0C 0041AA0C 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01AA10 0041AA10 AFAB0120 */  sw          $t3, 0x120($sp)
/* 01AA14 0041AA14 0320F809 */  jalr        $t9
/* 01AA18 0041AA18 248489B4 */   addiu      $a0, $a0, %lo(STR_100089B4)
/* 01AA1C 0041AA1C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AA20 0041AA20 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AA24 0041AA24 00000000 */  nop
.L0041AA28:
/* 01AA28 0041AA28 256B0003 */  addiu       $t3, $t3, 0x3
/* 01AA2C 0041AA2C 2401FFFC */  addiu       $at, $zero, -0x4
/* 01AA30 0041AA30 01617024 */  and         $t6, $t3, $at
/* 01AA34 0041AA34 01C05825 */  move        $t3, $t6
.L0041AA38:
/* 01AA38 0041AA38 11600004 */  beqz        $t3, .L0041AA4C
/* 01AA3C 0041AA3C AFAB0160 */   sw         $t3, 0x160($sp)
/* 01AA40 0041AA40 8FAF011C */  lw          $t7, 0x11C($sp)
/* 01AA44 0041AA44 00000000 */  nop
/* 01AA48 0041AA48 AFAF0164 */  sw          $t7, 0x164($sp)
.L0041AA4C:
/* 01AA4C 0041AA4C 8FB801DC */  lw          $t8, 0x1DC($sp)
.L0041AA50:
/* 01AA50 0041AA50 00000000 */  nop
/* 01AA54 0041AA54 330C0800 */  andi        $t4, $t8, 0x800
/* 01AA58 0041AA58 11800044 */  beqz        $t4, .L0041AB6C
/* 01AA5C 0041AA5C 8FAF01DC */   lw         $t7, 0x1DC($sp)
/* 01AA60 0041AA60 8F8883CC */  lw          $t0, %got(st_pchdr)($gp)
/* 01AA64 0041AA64 8FAD011C */  lw          $t5, 0x11C($sp)
/* 01AA68 0041AA68 8D020000 */  lw          $v0, 0x0($t0)
/* 01AA6C 0041AA6C 01AB7021 */  addu        $t6, $t5, $t3
/* 01AA70 0041AA70 8C590028 */  lw          $t9, 0x28($v0)
/* 01AA74 0041AA74 AFAE011C */  sw          $t6, 0x11C($sp)
/* 01AA78 0041AA78 00005825 */  move        $t3, $zero
/* 01AA7C 0041AA7C 1320001D */  beqz        $t9, .L0041AAF4
/* 01AA80 0041AA80 AFB90168 */   sw         $t9, 0x168($sp)
/* 01AA84 0041AA84 8C4B0028 */  lw          $t3, 0x28($v0)
/* 01AA88 0041AA88 AFAE016C */  sw          $t6, 0x16C($sp)
/* 01AA8C 0041AA8C 8C430028 */  lw          $v1, 0x28($v0)
/* 01AA90 0041AA90 24050001 */  addiu       $a1, $zero, 0x1
/* 01AA94 0041AA94 10600017 */  beqz        $v1, .L0041AAF4
/* 01AA98 0041AA98 00603025 */   move       $a2, $v1
/* 01AA9C 0041AA9C 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01AAA0 0041AAA0 8C440024 */  lw          $a0, 0x24($v0)
/* 01AAA4 0041AAA4 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01AAA8 0041AAA8 0320F809 */  jalr        $t9
/* 01AAAC 0041AAAC AFAB0120 */   sw         $t3, 0x120($sp)
/* 01AAB0 0041AAB0 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AAB4 0041AAB4 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AAB8 0041AAB8 8F9883CC */  lw          $t8, %got(st_pchdr)($gp)
/* 01AABC 0041AABC 00000000 */  nop
/* 01AAC0 0041AAC0 8F180000 */  lw          $t8, 0x0($t8)
/* 01AAC4 0041AAC4 00000000 */  nop
/* 01AAC8 0041AAC8 8F0C0028 */  lw          $t4, 0x28($t8)
/* 01AACC 0041AACC 00000000 */  nop
/* 01AAD0 0041AAD0 104C0009 */  beq         $v0, $t4, .L0041AAF8
/* 01AAD4 0041AAD4 000B8023 */   negu       $s0, $t3
/* 01AAD8 0041AAD8 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01AADC 0041AADC 8F848314 */  lw          $a0, %got(msg_err)($gp)
/* 01AAE0 0041AAE0 0320F809 */  jalr        $t9
/* 01AAE4 0041AAE4 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01AAE8 0041AAE8 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AAEC 0041AAEC 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AAF0 0041AAF0 00000000 */  nop
.L0041AAF4:
/* 01AAF4 0041AAF4 000B8023 */  negu        $s0, $t3
.L0041AAF8:
/* 01AAF8 0041AAF8 32190003 */  andi        $t9, $s0, 0x3
/* 01AAFC 0041AAFC 13200019 */  beqz        $t9, .L0041AB64
/* 01AB00 0041AB00 03208025 */   move       $s0, $t9
/* 01AB04 0041AB04 03203025 */  move        $a2, $t9
/* 01AB08 0041AB08 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01AB0C 0041AB0C 8F848064 */  lw          $a0, %got(B_1000A980)($gp)
/* 01AB10 0041AB10 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01AB14 0041AB14 24050001 */  addiu       $a1, $zero, 0x1
/* 01AB18 0041AB18 AFAB0120 */  sw          $t3, 0x120($sp)
/* 01AB1C 0041AB1C 0320F809 */  jalr        $t9
/* 01AB20 0041AB20 2484A980 */   addiu      $a0, $a0, %lo(B_1000A980)
/* 01AB24 0041AB24 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AB28 0041AB28 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AB2C 0041AB2C 10500009 */  beq         $v0, $s0, .L0041AB54
/* 01AB30 0041AB30 00000000 */   nop
/* 01AB34 0041AB34 8F848054 */  lw          $a0, %got(STR_100089DC)($gp)
/* 01AB38 0041AB38 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01AB3C 0041AB3C AFAB0120 */  sw          $t3, 0x120($sp)
/* 01AB40 0041AB40 0320F809 */  jalr        $t9
/* 01AB44 0041AB44 248489DC */   addiu      $a0, $a0, %lo(STR_100089DC)
/* 01AB48 0041AB48 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AB4C 0041AB4C 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AB50 0041AB50 00000000 */  nop
.L0041AB54:
/* 01AB54 0041AB54 256B0003 */  addiu       $t3, $t3, 0x3
/* 01AB58 0041AB58 2401FFFC */  addiu       $at, $zero, -0x4
/* 01AB5C 0041AB5C 01616824 */  and         $t5, $t3, $at
/* 01AB60 0041AB60 01A05825 */  move        $t3, $t5
.L0041AB64:
/* 01AB64 0041AB64 AFAB0168 */  sw          $t3, 0x168($sp)
/* 01AB68 0041AB68 8FAF01DC */  lw          $t7, 0x1DC($sp)
.L0041AB6C:
/* 01AB6C 0041AB6C 8F8883CC */  lw          $t0, %got(st_pchdr)($gp)
/* 01AB70 0041AB70 8F918314 */  lw          $s1, %got(msg_err)($gp)
/* 01AB74 0041AB74 31EE0200 */  andi        $t6, $t7, 0x200
/* 01AB78 0041AB78 11C0002C */  beqz        $t6, .L0041AC2C
/* 01AB7C 0041AB7C 8FAC01DC */   lw         $t4, 0x1DC($sp)
/* 01AB80 0041AB80 8D020000 */  lw          $v0, 0x0($t0)
/* 01AB84 0041AB84 8FAC011C */  lw          $t4, 0x11C($sp)
/* 01AB88 0041AB88 8C58000C */  lw          $t8, 0xC($v0)
/* 01AB8C 0041AB8C 018BC821 */  addu        $t9, $t4, $t3
/* 01AB90 0041AB90 AFB9011C */  sw          $t9, 0x11C($sp)
/* 01AB94 0041AB94 00005825 */  move        $t3, $zero
/* 01AB98 0041AB98 13000021 */  beqz        $t8, .L0041AC20
/* 01AB9C 0041AB9C AFB80170 */   sw         $t8, 0x170($sp)
/* 01ABA0 0041ABA0 8C4B000C */  lw          $t3, 0xC($v0)
/* 01ABA4 0041ABA4 AFB90174 */  sw          $t9, 0x174($sp)
/* 01ABA8 0041ABA8 000B78C0 */  sll         $t7, $t3, 3
/* 01ABAC 0041ABAC 8C43000C */  lw          $v1, 0xC($v0)
/* 01ABB0 0041ABB0 01EB7821 */  addu        $t7, $t7, $t3
/* 01ABB4 0041ABB4 000F78C0 */  sll         $t7, $t7, 3
/* 01ABB8 0041ABB8 10600019 */  beqz        $v1, .L0041AC20
/* 01ABBC 0041ABBC 01E05825 */   move       $t3, $t7
/* 01ABC0 0041ABC0 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01ABC4 0041ABC4 8C440008 */  lw          $a0, 0x8($v0)
/* 01ABC8 0041ABC8 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01ABCC 0041ABCC AFAF0120 */  sw          $t7, 0x120($sp)
/* 01ABD0 0041ABD0 24050048 */  addiu       $a1, $zero, 0x48
/* 01ABD4 0041ABD4 0320F809 */  jalr        $t9
/* 01ABD8 0041ABD8 00603025 */   move       $a2, $v1
/* 01ABDC 0041ABDC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01ABE0 0041ABE0 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01ABE4 0041ABE4 8F8E83CC */  lw          $t6, %got(st_pchdr)($gp)
/* 01ABE8 0041ABE8 00000000 */  nop
/* 01ABEC 0041ABEC 8DCE0000 */  lw          $t6, 0x0($t6)
/* 01ABF0 0041ABF0 00000000 */  nop
/* 01ABF4 0041ABF4 8DD8000C */  lw          $t8, 0xC($t6)
/* 01ABF8 0041ABF8 00000000 */  nop
/* 01ABFC 0041ABFC 10580008 */  beq         $v0, $t8, .L0041AC20
/* 01AC00 0041AC00 00000000 */   nop
/* 01AC04 0041AC04 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01AC08 0041AC08 02202025 */  move        $a0, $s1
/* 01AC0C 0041AC0C 0320F809 */  jalr        $t9
/* 01AC10 0041AC10 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01AC14 0041AC14 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AC18 0041AC18 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AC1C 0041AC1C 00000000 */  nop
.L0041AC20:
/* 01AC20 0041AC20 8F8883CC */  lw          $t0, %got(st_pchdr)($gp)
/* 01AC24 0041AC24 00000000 */  nop
/* 01AC28 0041AC28 8FAC01DC */  lw          $t4, 0x1DC($sp)
.L0041AC2C:
/* 01AC2C 0041AC2C 8FAF011C */  lw          $t7, 0x11C($sp)
/* 01AC30 0041AC30 318D0040 */  andi        $t5, $t4, 0x40
/* 01AC34 0041AC34 11A0003F */  beqz        $t5, .L0041AD34
/* 01AC38 0041AC38 01EBC821 */   addu       $t9, $t7, $t3
/* 01AC3C 0041AC3C 8FAE0114 */  lw          $t6, 0x114($sp)
/* 01AC40 0041AC40 AFB9011C */  sw          $t9, 0x11C($sp)
/* 01AC44 0041AC44 19C00036 */  blez        $t6, .L0041AD20
/* 01AC48 0041AC48 00005825 */   move       $t3, $zero
/* 01AC4C 0041AC4C AFA00118 */  sw          $zero, 0x118($sp)
.L0041AC50:
/* 01AC50 0041AC50 8F9981F8 */  lw          $t9, %call16(st_pcfd_ifd)($gp)
/* 01AC54 0041AC54 8FA40118 */  lw          $a0, 0x118($sp)
/* 01AC58 0041AC58 0320F809 */  jalr        $t9
/* 01AC5C 0041AC5C AFAB0120 */   sw         $t3, 0x120($sp)
/* 01AC60 0041AC60 8C580000 */  lw          $t8, 0x0($v0)
/* 01AC64 0041AC64 8FAC01C0 */  lw          $t4, 0x1C0($sp)
/* 01AC68 0041AC68 AFB80188 */  sw          $t8, 0x188($sp)
/* 01AC6C 0041AC6C 8FAD01C4 */  lw          $t5, 0x1C4($sp)
/* 01AC70 0041AC70 8F060038 */  lw          $a2, 0x38($t8)
/* 01AC74 0041AC74 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01AC78 0041AC78 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AC7C 0041AC7C 018D7821 */  addu        $t7, $t4, $t5
/* 01AC80 0041AC80 00062080 */  sll         $a0, $a2, 2
/* 01AC84 0041AC84 AF0F0034 */  sw          $t7, 0x34($t8)
/* 01AC88 0041AC88 10C00014 */  beqz        $a2, .L0041ACDC
/* 01AC8C 0041AC8C 01645821 */   addu       $t3, $t3, $a0
/* 01AC90 0041AC90 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01AC94 0041AC94 8C44002C */  lw          $a0, 0x2C($v0)
/* 01AC98 0041AC98 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01AC9C 0041AC9C AFAB0120 */  sw          $t3, 0x120($sp)
/* 01ACA0 0041ACA0 0320F809 */  jalr        $t9
/* 01ACA4 0041ACA4 24050004 */   addiu      $a1, $zero, 0x4
/* 01ACA8 0041ACA8 8FAE0188 */  lw          $t6, 0x188($sp)
/* 01ACAC 0041ACAC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01ACB0 0041ACB0 8DD80038 */  lw          $t8, 0x38($t6)
/* 01ACB4 0041ACB4 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01ACB8 0041ACB8 10580009 */  beq         $v0, $t8, .L0041ACE0
/* 01ACBC 0041ACBC 8FAC01C0 */   lw         $t4, 0x1C0($sp)
/* 01ACC0 0041ACC0 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01ACC4 0041ACC4 02402025 */  move        $a0, $s2
/* 01ACC8 0041ACC8 0320F809 */  jalr        $t9
/* 01ACCC 0041ACCC AFAB0120 */   sw         $t3, 0x120($sp)
/* 01ACD0 0041ACD0 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01ACD4 0041ACD4 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01ACD8 0041ACD8 00000000 */  nop
.L0041ACDC:
/* 01ACDC 0041ACDC 8FAC01C0 */  lw          $t4, 0x1C0($sp)
.L0041ACE0:
/* 01ACE0 0041ACE0 8FAD01C4 */  lw          $t5, 0x1C4($sp)
/* 01ACE4 0041ACE4 8FB90188 */  lw          $t9, 0x188($sp)
/* 01ACE8 0041ACE8 018D7821 */  addu        $t7, $t4, $t5
/* 01ACEC 0041ACEC AFAF01C0 */  sw          $t7, 0x1C0($sp)
/* 01ACF0 0041ACF0 8F240038 */  lw          $a0, 0x38($t9)
/* 01ACF4 0041ACF4 8FAC0118 */  lw          $t4, 0x118($sp)
/* 01ACF8 0041ACF8 8FAE0178 */  lw          $t6, 0x178($sp)
/* 01ACFC 0041ACFC 8FAF0114 */  lw          $t7, 0x114($sp)
/* 01AD00 0041AD00 258D0001 */  addiu       $t5, $t4, 0x1
/* 01AD04 0041AD04 01C4C021 */  addu        $t8, $t6, $a0
/* 01AD08 0041AD08 AFB80178 */  sw          $t8, 0x178($sp)
/* 01AD0C 0041AD0C AFAD0118 */  sw          $t5, 0x118($sp)
/* 01AD10 0041AD10 15AFFFCF */  bne         $t5, $t7, .L0041AC50
/* 01AD14 0041AD14 AFA401C4 */   sw         $a0, 0x1C4($sp)
/* 01AD18 0041AD18 8F8883CC */  lw          $t0, %got(st_pchdr)($gp)
/* 01AD1C 0041AD1C 00000000 */  nop
.L0041AD20:
/* 01AD20 0041AD20 8FB90178 */  lw          $t9, 0x178($sp)
/* 01AD24 0041AD24 8FAE011C */  lw          $t6, 0x11C($sp)
/* 01AD28 0041AD28 13200003 */  beqz        $t9, .L0041AD38
/* 01AD2C 0041AD2C 8FB801DC */   lw         $t8, 0x1DC($sp)
/* 01AD30 0041AD30 AFAE017C */  sw          $t6, 0x17C($sp)
.L0041AD34:
/* 01AD34 0041AD34 8FB801DC */  lw          $t8, 0x1DC($sp)
.L0041AD38:
/* 01AD38 0041AD38 00000000 */  nop
/* 01AD3C 0041AD3C 330C0001 */  andi        $t4, $t8, 0x1
/* 01AD40 0041AD40 1180002A */  beqz        $t4, .L0041ADEC
/* 01AD44 0041AD44 8FAF01DC */   lw         $t7, 0x1DC($sp)
/* 01AD48 0041AD48 8D020000 */  lw          $v0, 0x0($t0)
/* 01AD4C 0041AD4C 8FAF011C */  lw          $t7, 0x11C($sp)
/* 01AD50 0041AD50 8C4D001C */  lw          $t5, 0x1C($v0)
/* 01AD54 0041AD54 01EBC821 */  addu        $t9, $t7, $t3
/* 01AD58 0041AD58 AFB9011C */  sw          $t9, 0x11C($sp)
/* 01AD5C 0041AD5C 00005825 */  move        $t3, $zero
/* 01AD60 0041AD60 11A0001F */  beqz        $t5, .L0041ADE0
/* 01AD64 0041AD64 AFAD0180 */   sw         $t5, 0x180($sp)
/* 01AD68 0041AD68 8C4B001C */  lw          $t3, 0x1C($v0)
/* 01AD6C 0041AD6C AFB90184 */  sw          $t9, 0x184($sp)
/* 01AD70 0041AD70 8C43001C */  lw          $v1, 0x1C($v0)
/* 01AD74 0041AD74 000BC100 */  sll         $t8, $t3, 4
/* 01AD78 0041AD78 10600019 */  beqz        $v1, .L0041ADE0
/* 01AD7C 0041AD7C 03005825 */   move       $t3, $t8
/* 01AD80 0041AD80 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01AD84 0041AD84 8C440018 */  lw          $a0, 0x18($v0)
/* 01AD88 0041AD88 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01AD8C 0041AD8C AFB80120 */  sw          $t8, 0x120($sp)
/* 01AD90 0041AD90 24050010 */  addiu       $a1, $zero, 0x10
/* 01AD94 0041AD94 0320F809 */  jalr        $t9
/* 01AD98 0041AD98 00603025 */   move       $a2, $v1
/* 01AD9C 0041AD9C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01ADA0 0041ADA0 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01ADA4 0041ADA4 8F8C83CC */  lw          $t4, %got(st_pchdr)($gp)
/* 01ADA8 0041ADA8 00000000 */  nop
/* 01ADAC 0041ADAC 8D8C0000 */  lw          $t4, 0x0($t4)
/* 01ADB0 0041ADB0 00000000 */  nop
/* 01ADB4 0041ADB4 8D8D001C */  lw          $t5, 0x1C($t4)
/* 01ADB8 0041ADB8 00000000 */  nop
/* 01ADBC 0041ADBC 104D0008 */  beq         $v0, $t5, .L0041ADE0
/* 01ADC0 0041ADC0 00000000 */   nop
/* 01ADC4 0041ADC4 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01ADC8 0041ADC8 02202025 */  move        $a0, $s1
/* 01ADCC 0041ADCC 0320F809 */  jalr        $t9
/* 01ADD0 0041ADD0 AFAB0120 */   sw         $t3, 0x120($sp)
/* 01ADD4 0041ADD4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01ADD8 0041ADD8 8FAB0120 */  lw          $t3, 0x120($sp)
/* 01ADDC 0041ADDC 00000000 */  nop
.L0041ADE0:
/* 01ADE0 0041ADE0 8F8883CC */  lw          $t0, %got(st_pchdr)($gp)
/* 01ADE4 0041ADE4 00000000 */  nop
/* 01ADE8 0041ADE8 8FAF01DC */  lw          $t7, 0x1DC($sp)
.L0041ADEC:
/* 01ADEC 0041ADEC 00000000 */  nop
/* 01ADF0 0041ADF0 31EE0010 */  andi        $t6, $t7, 0x10
/* 01ADF4 0041ADF4 11C00039 */  beqz        $t6, .L0041AEDC
/* 01ADF8 0041ADF8 00000000 */   nop
/* 01ADFC 0041ADFC 8D020000 */  lw          $v0, 0x0($t0)
/* 01AE00 0041AE00 00000000 */  nop
/* 01AE04 0041AE04 8C58003C */  lw          $t8, 0x3C($v0)
/* 01AE08 0041AE08 00000000 */  nop
/* 01AE0C 0041AE0C 13000033 */  beqz        $t8, .L0041AEDC
/* 01AE10 0041AE10 00000000 */   nop
/* 01AE14 0041AE14 8C590038 */  lw          $t9, 0x38($v0)
/* 01AE18 0041AE18 00000000 */  nop
/* 01AE1C 0041AE1C AF200000 */  sw          $zero, 0x0($t9)
/* 01AE20 0041AE20 8D0C0000 */  lw          $t4, 0x0($t0)
/* 01AE24 0041AE24 00000000 */  nop
/* 01AE28 0041AE28 8D8D0038 */  lw          $t5, 0x38($t4)
/* 01AE2C 0041AE2C 00000000 */  nop
/* 01AE30 0041AE30 ADA00004 */  sw          $zero, 0x4($t5)
/* 01AE34 0041AE34 8D0F0000 */  lw          $t7, 0x0($t0)
/* 01AE38 0041AE38 00000000 */  nop
/* 01AE3C 0041AE3C 8DEE0038 */  lw          $t6, 0x38($t7)
/* 01AE40 0041AE40 00000000 */  nop
/* 01AE44 0041AE44 ADC00008 */  sw          $zero, 0x8($t6)
/* 01AE48 0041AE48 8D180000 */  lw          $t8, 0x0($t0)
/* 01AE4C 0041AE4C 00000000 */  nop
/* 01AE50 0041AE50 8F190038 */  lw          $t9, 0x38($t8)
/* 01AE54 0041AE54 00000000 */  nop
/* 01AE58 0041AE58 AF20000C */  sw          $zero, 0xC($t9)
/* 01AE5C 0041AE5C 8D020000 */  lw          $v0, 0x0($t0)
/* 01AE60 0041AE60 8FAD011C */  lw          $t5, 0x11C($sp)
/* 01AE64 0041AE64 8C4C003C */  lw          $t4, 0x3C($v0)
/* 01AE68 0041AE68 01AB7821 */  addu        $t7, $t5, $t3
/* 01AE6C 0041AE6C AFAF011C */  sw          $t7, 0x11C($sp)
/* 01AE70 0041AE70 1180001A */  beqz        $t4, .L0041AEDC
/* 01AE74 0041AE74 AFAC0138 */   sw         $t4, 0x138($sp)
/* 01AE78 0041AE78 AFAF013C */  sw          $t7, 0x13C($sp)
/* 01AE7C 0041AE7C 8C43003C */  lw          $v1, 0x3C($v0)
/* 01AE80 0041AE80 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01AE84 0041AE84 10600015 */  beqz        $v1, .L0041AEDC
/* 01AE88 0041AE88 24050008 */   addiu      $a1, $zero, 0x8
/* 01AE8C 0041AE8C 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01AE90 0041AE90 8C440038 */  lw          $a0, 0x38($v0)
/* 01AE94 0041AE94 0320F809 */  jalr        $t9
/* 01AE98 0041AE98 00603025 */   move       $a2, $v1
/* 01AE9C 0041AE9C 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AEA0 0041AEA0 00000000 */  nop
/* 01AEA4 0041AEA4 8F9883CC */  lw          $t8, %got(st_pchdr)($gp)
/* 01AEA8 0041AEA8 00000000 */  nop
/* 01AEAC 0041AEAC 8F180000 */  lw          $t8, 0x0($t8)
/* 01AEB0 0041AEB0 00000000 */  nop
/* 01AEB4 0041AEB4 8F19003C */  lw          $t9, 0x3C($t8)
/* 01AEB8 0041AEB8 00000000 */  nop
/* 01AEBC 0041AEBC 10590007 */  beq         $v0, $t9, .L0041AEDC
/* 01AEC0 0041AEC0 00000000 */   nop
/* 01AEC4 0041AEC4 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01AEC8 0041AEC8 02202025 */  move        $a0, $s1
/* 01AECC 0041AECC 0320F809 */  jalr        $t9
/* 01AED0 0041AED0 00000000 */   nop
/* 01AED4 0041AED4 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AED8 0041AED8 00000000 */  nop
.L0041AEDC:
/* 01AEDC 0041AEDC 8F998094 */  lw          $t9, %call16(fflush)($gp)
/* 01AEE0 0041AEE0 8FA4010C */  lw          $a0, 0x10C($sp)
/* 01AEE4 0041AEE4 0320F809 */  jalr        $t9
/* 01AEE8 0041AEE8 00000000 */   nop
/* 01AEEC 0041AEEC 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AEF0 0041AEF0 8FA4010C */  lw          $a0, 0x10C($sp)
/* 01AEF4 0041AEF4 8F9980A0 */  lw          $t9, %call16(fseek)($gp)
/* 01AEF8 0041AEF8 8FA50110 */  lw          $a1, 0x110($sp)
/* 01AEFC 0041AEFC 0320F809 */  jalr        $t9
/* 01AF00 0041AF00 00003025 */   move       $a2, $zero
/* 01AF04 0041AF04 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AF08 0041AF08 240C0313 */  addiu       $t4, $zero, 0x313
/* 01AF0C 0041AF0C 8F8D830C */  lw          $t5, %got(stmagic)($gp)
/* 01AF10 0041AF10 8F9980A8 */  lw          $t9, %call16(fwrite)($gp)
/* 01AF14 0041AF14 85AD0000 */  lh          $t5, 0x0($t5)
/* 01AF18 0041AF18 8FA7010C */  lw          $a3, 0x10C($sp)
/* 01AF1C 0041AF1C A7AC012A */  sh          $t4, 0x12A($sp)
/* 01AF20 0041AF20 27A40128 */  addiu       $a0, $sp, 0x128
/* 01AF24 0041AF24 24050001 */  addiu       $a1, $zero, 0x1
/* 01AF28 0041AF28 24060060 */  addiu       $a2, $zero, 0x60
/* 01AF2C 0041AF2C 0320F809 */  jalr        $t9
/* 01AF30 0041AF30 A7AD0128 */   sh         $t5, 0x128($sp)
/* 01AF34 0041AF34 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AF38 0041AF38 24010060 */  addiu       $at, $zero, 0x60
/* 01AF3C 0041AF3C 10410008 */  beq         $v0, $at, .L0041AF60
/* 01AF40 0041AF40 00000000 */   nop
/* 01AF44 0041AF44 8F848054 */  lw          $a0, %got(STR_10008A04)($gp)
/* 01AF48 0041AF48 8F9981B0 */  lw          $t9, %call16(st_error)($gp)
/* 01AF4C 0041AF4C 24848A04 */  addiu       $a0, $a0, %lo(STR_10008A04)
/* 01AF50 0041AF50 0320F809 */  jalr        $t9
/* 01AF54 0041AF54 00000000 */   nop
/* 01AF58 0041AF58 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AF5C 0041AF5C 00000000 */  nop
.L0041AF60:
/* 01AF60 0041AF60 8F9980E4 */  lw          $t9, %call16(fclose)($gp)
/* 01AF64 0041AF64 8FA4010C */  lw          $a0, 0x10C($sp)
/* 01AF68 0041AF68 0320F809 */  jalr        $t9
/* 01AF6C 0041AF6C 00000000 */   nop
/* 01AF70 0041AF70 8FBF003C */  lw          $ra, 0x3C($sp)
/* 01AF74 0041AF74 8FBC0034 */  lw          $gp, 0x34($sp)
/* 01AF78 0041AF78 8FB00014 */  lw          $s0, 0x14($sp)
/* 01AF7C 0041AF7C 8FB10018 */  lw          $s1, 0x18($sp)
/* 01AF80 0041AF80 8FB2001C */  lw          $s2, 0x1C($sp)
/* 01AF84 0041AF84 8FB30020 */  lw          $s3, 0x20($sp)
/* 01AF88 0041AF88 8FB40024 */  lw          $s4, 0x24($sp)
/* 01AF8C 0041AF8C 8FB50028 */  lw          $s5, 0x28($sp)
/* 01AF90 0041AF90 8FB6002C */  lw          $s6, 0x2C($sp)
/* 01AF94 0041AF94 8FB70030 */  lw          $s7, 0x30($sp)
/* 01AF98 0041AF98 8FBE0038 */  lw          $fp, 0x38($sp)
/* 01AF9C 0041AF9C 03E00008 */  jr          $ra
/* 01AFA0 0041AFA0 27BD01D8 */   addiu      $sp, $sp, 0x1D8
