/* Generated by spimdisasm 1.10.3 */

glabel swap_fd # 247
# _gp_disp: 0xFBF506C
.set noreorder; .cpload $t9; # .set reorder
/* 01BA60 0041BA60 27BDFF70 */  addiu       $sp, $sp, -0x90
/* 01BA64 0041BA64 8F99828C */  lw          $t9, %call16(gethostsex)($gp)
/* 01BA68 0041BA68 AFBF0034 */  sw          $ra, 0x34($sp)
/* 01BA6C 0041BA6C AFB5002C */  sw          $s5, 0x2C($sp)
/* 01BA70 0041BA70 AFB40028 */  sw          $s4, 0x28($sp)
/* 01BA74 0041BA74 AFB00018 */  sw          $s0, 0x18($sp)
/* 01BA78 0041BA78 00808025 */  move        $s0, $a0
/* 01BA7C 0041BA7C 00A0A025 */  move        $s4, $a1
/* 01BA80 0041BA80 00C0A825 */  move        $s5, $a2
/* 01BA84 0041BA84 AFBC0030 */  sw          $gp, 0x30($sp)
/* 01BA88 0041BA88 AFB30024 */  sw          $s3, 0x24($sp)
/* 01BA8C 0041BA8C AFB20020 */  sw          $s2, 0x20($sp)
/* 01BA90 0041BA90 0320F809 */  jalr        $t9
/* 01BA94 0041BA94 AFB1001C */   sw         $s1, 0x1C($sp)
/* 01BA98 0041BA98 8FBC0030 */  lw          $gp, 0x30($sp)
/* 01BA9C 0041BA9C 1A800163 */  blez        $s4, .L0041C02C
/* 01BAA0 0041BAA0 00009825 */   move       $s3, $zero
/* 01BAA4 0041BAA4 02001825 */  move        $v1, $s0
/* 01BAA8 0041BAA8 3C1200FF */  lui         $s2, (0xFF0000 >> 16)
/* 01BAAC 0041BAAC 27B10040 */  addiu       $s1, $sp, 0x40
/* 01BAB0 0041BAB0 3C0400FF */  lui         $a0, (0xFF0000 >> 16)
.L0041BAB4:
/* 01BAB4 0041BAB4 0060C025 */  move        $t8, $v1
/* 01BAB8 0041BAB8 0220C825 */  move        $t9, $s1
/* 01BABC 0041BABC 246F0048 */  addiu       $t7, $v1, 0x48
.L0041BAC0:
/* 01BAC0 0041BAC0 8F010000 */  lw          $at, 0x0($t8)
/* 01BAC4 0041BAC4 2718000C */  addiu       $t8, $t8, 0xC
/* 01BAC8 0041BAC8 AF210000 */  sw          $at, 0x0($t9)
/* 01BACC 0041BACC 8F01FFF8 */  lw          $at, -0x8($t8)
/* 01BAD0 0041BAD0 2739000C */  addiu       $t9, $t9, 0xC
/* 01BAD4 0041BAD4 AF21FFF8 */  sw          $at, -0x8($t9)
/* 01BAD8 0041BAD8 8F01FFFC */  lw          $at, -0x4($t8)
/* 01BADC 0041BADC 170FFFF8 */  bne         $t8, $t7, .L0041BAC0
/* 01BAE0 0041BAE0 AF21FFFC */   sw         $at, -0x4($t9)
/* 01BAE4 0041BAE4 8FAE0040 */  lw          $t6, 0x40($sp)
/* 01BAE8 0041BAE8 8FA50054 */  lw          $a1, 0x54($sp)
/* 01BAEC 0041BAEC 000EC200 */  sll         $t8, $t6, 8
/* 01BAF0 0041BAF0 0312C824 */  and         $t9, $t8, $s2
/* 01BAF4 0041BAF4 000E7E00 */  sll         $t7, $t6, 24
/* 01BAF8 0041BAF8 01F9C025 */  or          $t8, $t7, $t9
/* 01BAFC 0041BAFC 000E7A02 */  srl         $t7, $t6, 8
/* 01BB00 0041BB00 31F9FF00 */  andi        $t9, $t7, 0xFF00
/* 01BB04 0041BB04 03197825 */  or          $t7, $t8, $t9
/* 01BB08 0041BB08 000EC602 */  srl         $t8, $t6, 24
/* 01BB0C 0041BB0C 01F8C825 */  or          $t9, $t7, $t8
/* 01BB10 0041BB10 8FAE0044 */  lw          $t6, 0x44($sp)
/* 01BB14 0041BB14 AFB90040 */  sw          $t9, 0x40($sp)
/* 01BB18 0041BB18 000EC200 */  sll         $t8, $t6, 8
/* 01BB1C 0041BB1C 0304C824 */  and         $t9, $t8, $a0
/* 01BB20 0041BB20 000E7E00 */  sll         $t7, $t6, 24
/* 01BB24 0041BB24 01F9C025 */  or          $t8, $t7, $t9
/* 01BB28 0041BB28 000E7A03 */  sra         $t7, $t6, 8
/* 01BB2C 0041BB2C 31F9FF00 */  andi        $t9, $t7, 0xFF00
/* 01BB30 0041BB30 8FAF0044 */  lw          $t7, 0x44($sp)
/* 01BB34 0041BB34 03197025 */  or          $t6, $t8, $t9
/* 01BB38 0041BB38 000FC602 */  srl         $t8, $t7, 24
/* 01BB3C 0041BB3C 01D8C825 */  or          $t9, $t6, $t8
/* 01BB40 0041BB40 8FAF0048 */  lw          $t7, 0x48($sp)
/* 01BB44 0041BB44 AFB90044 */  sw          $t9, 0x44($sp)
/* 01BB48 0041BB48 000FC200 */  sll         $t8, $t7, 8
/* 01BB4C 0041BB4C 0304C824 */  and         $t9, $t8, $a0
/* 01BB50 0041BB50 000F7600 */  sll         $t6, $t7, 24
/* 01BB54 0041BB54 01D9C025 */  or          $t8, $t6, $t9
/* 01BB58 0041BB58 000F7203 */  sra         $t6, $t7, 8
/* 01BB5C 0041BB5C 31D9FF00 */  andi        $t9, $t6, 0xFF00
/* 01BB60 0041BB60 8FAE0048 */  lw          $t6, 0x48($sp)
/* 01BB64 0041BB64 03197825 */  or          $t7, $t8, $t9
/* 01BB68 0041BB68 000EC602 */  srl         $t8, $t6, 24
/* 01BB6C 0041BB6C 01F8C825 */  or          $t9, $t7, $t8
/* 01BB70 0041BB70 8FAE004C */  lw          $t6, 0x4C($sp)
/* 01BB74 0041BB74 AFB90048 */  sw          $t9, 0x48($sp)
/* 01BB78 0041BB78 000EC200 */  sll         $t8, $t6, 8
/* 01BB7C 0041BB7C 0304C824 */  and         $t9, $t8, $a0
/* 01BB80 0041BB80 000E7E00 */  sll         $t7, $t6, 24
/* 01BB84 0041BB84 01F9C025 */  or          $t8, $t7, $t9
/* 01BB88 0041BB88 000E7A03 */  sra         $t7, $t6, 8
/* 01BB8C 0041BB8C 31F9FF00 */  andi        $t9, $t7, 0xFF00
/* 01BB90 0041BB90 8FAF004C */  lw          $t7, 0x4C($sp)
/* 01BB94 0041BB94 03197025 */  or          $t6, $t8, $t9
/* 01BB98 0041BB98 000FC602 */  srl         $t8, $t7, 24
/* 01BB9C 0041BB9C 01D8C825 */  or          $t9, $t6, $t8
/* 01BBA0 0041BBA0 8FAF0050 */  lw          $t7, 0x50($sp)
/* 01BBA4 0041BBA4 AFB9004C */  sw          $t9, 0x4C($sp)
/* 01BBA8 0041BBA8 000FC200 */  sll         $t8, $t7, 8
/* 01BBAC 0041BBAC 0304C824 */  and         $t9, $t8, $a0
/* 01BBB0 0041BBB0 000F7600 */  sll         $t6, $t7, 24
/* 01BBB4 0041BBB4 01D9C025 */  or          $t8, $t6, $t9
/* 01BBB8 0041BBB8 000F7203 */  sra         $t6, $t7, 8
/* 01BBBC 0041BBBC 31D9FF00 */  andi        $t9, $t6, 0xFF00
/* 01BBC0 0041BBC0 8FAE0050 */  lw          $t6, 0x50($sp)
/* 01BBC4 0041BBC4 03197825 */  or          $t7, $t8, $t9
/* 01BBC8 0041BBC8 000EC602 */  srl         $t8, $t6, 24
/* 01BBCC 0041BBCC 01F8C825 */  or          $t9, $t7, $t8
/* 01BBD0 0041BBD0 00057A00 */  sll         $t7, $a1, 8
/* 01BBD4 0041BBD4 01E4C024 */  and         $t8, $t7, $a0
/* 01BBD8 0041BBD8 AFB90050 */  sw          $t9, 0x50($sp)
/* 01BBDC 0041BBDC 00057600 */  sll         $t6, $a1, 24
/* 01BBE0 0041BBE0 01D8C825 */  or          $t9, $t6, $t8
/* 01BBE4 0041BBE4 00057A03 */  sra         $t7, $a1, 8
/* 01BBE8 0041BBE8 31EEFF00 */  andi        $t6, $t7, 0xFF00
/* 01BBEC 0041BBEC 8FA60058 */  lw          $a2, 0x58($sp)
/* 01BBF0 0041BBF0 032EC025 */  or          $t8, $t9, $t6
/* 01BBF4 0041BBF4 00057E02 */  srl         $t7, $a1, 24
/* 01BBF8 0041BBF8 030F2825 */  or          $a1, $t8, $t7
/* 01BBFC 0041BBFC 00067200 */  sll         $t6, $a2, 8
/* 01BC00 0041BC00 01C4C024 */  and         $t8, $t6, $a0
/* 01BC04 0041BC04 0006CE00 */  sll         $t9, $a2, 24
/* 01BC08 0041BC08 03387825 */  or          $t7, $t9, $t8
/* 01BC0C 0041BC0C 00067203 */  sra         $t6, $a2, 8
/* 01BC10 0041BC10 31D9FF00 */  andi        $t9, $t6, 0xFF00
/* 01BC14 0041BC14 8FA7005C */  lw          $a3, 0x5C($sp)
/* 01BC18 0041BC18 01F9C025 */  or          $t8, $t7, $t9
/* 01BC1C 0041BC1C 00067602 */  srl         $t6, $a2, 24
/* 01BC20 0041BC20 030E3025 */  or          $a2, $t8, $t6
/* 01BC24 0041BC24 0007CA00 */  sll         $t9, $a3, 8
/* 01BC28 0041BC28 0324C024 */  and         $t8, $t9, $a0
/* 01BC2C 0041BC2C 00077E00 */  sll         $t7, $a3, 24
/* 01BC30 0041BC30 01F87025 */  or          $t6, $t7, $t8
/* 01BC34 0041BC34 0007CA03 */  sra         $t9, $a3, 8
/* 01BC38 0041BC38 332FFF00 */  andi        $t7, $t9, 0xFF00
/* 01BC3C 0041BC3C 8FA80060 */  lw          $t0, 0x60($sp)
/* 01BC40 0041BC40 01CFC025 */  or          $t8, $t6, $t7
/* 01BC44 0041BC44 0007CE02 */  srl         $t9, $a3, 24
/* 01BC48 0041BC48 03193825 */  or          $a3, $t8, $t9
/* 01BC4C 0041BC4C 00087A00 */  sll         $t7, $t0, 8
/* 01BC50 0041BC50 01E4C024 */  and         $t8, $t7, $a0
/* 01BC54 0041BC54 00087600 */  sll         $t6, $t0, 24
/* 01BC58 0041BC58 01D8C825 */  or          $t9, $t6, $t8
/* 01BC5C 0041BC5C 00087A03 */  sra         $t7, $t0, 8
/* 01BC60 0041BC60 31EEFF00 */  andi        $t6, $t7, 0xFF00
/* 01BC64 0041BC64 8FA90064 */  lw          $t1, 0x64($sp)
/* 01BC68 0041BC68 032EC025 */  or          $t8, $t9, $t6
/* 01BC6C 0041BC6C 00087E02 */  srl         $t7, $t0, 24
/* 01BC70 0041BC70 030F4025 */  or          $t0, $t8, $t7
/* 01BC74 0041BC74 00097200 */  sll         $t6, $t1, 8
/* 01BC78 0041BC78 01C4C024 */  and         $t8, $t6, $a0
/* 01BC7C 0041BC7C 0009CE00 */  sll         $t9, $t1, 24
/* 01BC80 0041BC80 03387825 */  or          $t7, $t9, $t8
/* 01BC84 0041BC84 00097203 */  sra         $t6, $t1, 8
/* 01BC88 0041BC88 31D9FF00 */  andi        $t9, $t6, 0xFF00
/* 01BC8C 0041BC8C 01F9C025 */  or          $t8, $t7, $t9
/* 01BC90 0041BC90 00097602 */  srl         $t6, $t1, 24
/* 01BC94 0041BC94 030E4825 */  or          $t1, $t8, $t6
/* 01BC98 0041BC98 97AE0068 */  lhu         $t6, 0x68($sp)
/* 01BC9C 0041BC9C 87B90068 */  lh          $t9, 0x68($sp)
/* 01BCA0 0041BCA0 000E7A02 */  srl         $t7, $t6, 8
/* 01BCA4 0041BCA4 0019C200 */  sll         $t8, $t9, 8
/* 01BCA8 0041BCA8 030FC825 */  or          $t9, $t8, $t7
/* 01BCAC 0041BCAC A7B90068 */  sh          $t9, 0x68($sp)
/* 01BCB0 0041BCB0 97B9006A */  lhu         $t9, 0x6A($sp)
/* 01BCB4 0041BCB4 87B8006A */  lh          $t8, 0x6A($sp)
/* 01BCB8 0041BCB8 8FAA006C */  lw          $t2, 0x6C($sp)
/* 01BCBC 0041BCBC 00197202 */  srl         $t6, $t9, 8
/* 01BCC0 0041BCC0 00187A00 */  sll         $t7, $t8, 8
/* 01BCC4 0041BCC4 01EEC025 */  or          $t8, $t7, $t6
/* 01BCC8 0041BCC8 000A7A00 */  sll         $t7, $t2, 8
/* 01BCCC 0041BCCC 01E47024 */  and         $t6, $t7, $a0
/* 01BCD0 0041BCD0 A7B8006A */  sh          $t8, 0x6A($sp)
/* 01BCD4 0041BCD4 000ACE00 */  sll         $t9, $t2, 24
/* 01BCD8 0041BCD8 032EC025 */  or          $t8, $t9, $t6
/* 01BCDC 0041BCDC 000A7A03 */  sra         $t7, $t2, 8
/* 01BCE0 0041BCE0 31F9FF00 */  andi        $t9, $t7, 0xFF00
/* 01BCE4 0041BCE4 8FAB0070 */  lw          $t3, 0x70($sp)
/* 01BCE8 0041BCE8 03197025 */  or          $t6, $t8, $t9
/* 01BCEC 0041BCEC 000A7E02 */  srl         $t7, $t2, 24
/* 01BCF0 0041BCF0 01CF5025 */  or          $t2, $t6, $t7
/* 01BCF4 0041BCF4 000BCA00 */  sll         $t9, $t3, 8
/* 01BCF8 0041BCF8 03247024 */  and         $t6, $t9, $a0
/* 01BCFC 0041BCFC 000BC600 */  sll         $t8, $t3, 24
/* 01BD00 0041BD00 030E7825 */  or          $t7, $t8, $t6
/* 01BD04 0041BD04 000BCA03 */  sra         $t9, $t3, 8
/* 01BD08 0041BD08 3338FF00 */  andi        $t8, $t9, 0xFF00
/* 01BD0C 0041BD0C 8FAC0074 */  lw          $t4, 0x74($sp)
/* 01BD10 0041BD10 01F87025 */  or          $t6, $t7, $t8
/* 01BD14 0041BD14 000BCE02 */  srl         $t9, $t3, 24
/* 01BD18 0041BD18 01D95825 */  or          $t3, $t6, $t9
/* 01BD1C 0041BD1C 000CC200 */  sll         $t8, $t4, 8
/* 01BD20 0041BD20 03047024 */  and         $t6, $t8, $a0
/* 01BD24 0041BD24 000C7E00 */  sll         $t7, $t4, 24
/* 01BD28 0041BD28 01EEC825 */  or          $t9, $t7, $t6
/* 01BD2C 0041BD2C 000CC203 */  sra         $t8, $t4, 8
/* 01BD30 0041BD30 330FFF00 */  andi        $t7, $t8, 0xFF00
/* 01BD34 0041BD34 8FAD0078 */  lw          $t5, 0x78($sp)
/* 01BD38 0041BD38 032F7025 */  or          $t6, $t9, $t7
/* 01BD3C 0041BD3C 000CC602 */  srl         $t8, $t4, 24
/* 01BD40 0041BD40 01D86025 */  or          $t4, $t6, $t8
/* 01BD44 0041BD44 000D7A00 */  sll         $t7, $t5, 8
/* 01BD48 0041BD48 01E47024 */  and         $t6, $t7, $a0
/* 01BD4C 0041BD4C 000DCE00 */  sll         $t9, $t5, 24
/* 01BD50 0041BD50 032EC025 */  or          $t8, $t9, $t6
/* 01BD54 0041BD54 000D7A03 */  sra         $t7, $t5, 8
/* 01BD58 0041BD58 31F9FF00 */  andi        $t9, $t7, 0xFF00
/* 01BD5C 0041BD5C 8FBF0080 */  lw          $ra, 0x80($sp)
/* 01BD60 0041BD60 03197025 */  or          $t6, $t8, $t9
/* 01BD64 0041BD64 000D7E02 */  srl         $t7, $t5, 24
/* 01BD68 0041BD68 01CF6825 */  or          $t5, $t6, $t7
/* 01BD6C 0041BD6C 001FCA00 */  sll         $t9, $ra, 8
/* 01BD70 0041BD70 03247024 */  and         $t6, $t9, $a0
/* 01BD74 0041BD74 001FC600 */  sll         $t8, $ra, 24
/* 01BD78 0041BD78 030E7825 */  or          $t7, $t8, $t6
/* 01BD7C 0041BD7C 001FCA03 */  sra         $t9, $ra, 8
/* 01BD80 0041BD80 3338FF00 */  andi        $t8, $t9, 0xFF00
/* 01BD84 0041BD84 8FB00084 */  lw          $s0, 0x84($sp)
/* 01BD88 0041BD88 01F87025 */  or          $t6, $t7, $t8
/* 01BD8C 0041BD8C 001FCE02 */  srl         $t9, $ra, 24
/* 01BD90 0041BD90 01D9F825 */  or          $ra, $t6, $t9
/* 01BD94 0041BD94 0010C200 */  sll         $t8, $s0, 8
/* 01BD98 0041BD98 03047024 */  and         $t6, $t8, $a0
/* 01BD9C 0041BD9C 00107E00 */  sll         $t7, $s0, 24
/* 01BDA0 0041BDA0 01EEC825 */  or          $t9, $t7, $t6
/* 01BDA4 0041BDA4 0010C203 */  sra         $t8, $s0, 8
/* 01BDA8 0041BDA8 330FFF00 */  andi        $t7, $t8, 0xFF00
/* 01BDAC 0041BDAC 032F7025 */  or          $t6, $t9, $t7
/* 01BDB0 0041BDB0 0010C602 */  srl         $t8, $s0, 24
/* 01BDB4 0041BDB4 01D88025 */  or          $s0, $t6, $t8
/* 01BDB8 0041BDB8 AFB00084 */  sw          $s0, 0x84($sp)
/* 01BDBC 0041BDBC AFBF0080 */  sw          $ra, 0x80($sp)
/* 01BDC0 0041BDC0 AFAD0078 */  sw          $t5, 0x78($sp)
/* 01BDC4 0041BDC4 AFAC0074 */  sw          $t4, 0x74($sp)
/* 01BDC8 0041BDC8 AFAB0070 */  sw          $t3, 0x70($sp)
/* 01BDCC 0041BDCC AFAA006C */  sw          $t2, 0x6C($sp)
/* 01BDD0 0041BDD0 AFA90064 */  sw          $t1, 0x64($sp)
/* 01BDD4 0041BDD4 AFA80060 */  sw          $t0, 0x60($sp)
/* 01BDD8 0041BDD8 AFA7005C */  sw          $a3, 0x5C($sp)
/* 01BDDC 0041BDDC AFA60058 */  sw          $a2, 0x58($sp)
/* 01BDE0 0041BDE0 16A20048 */  bne         $s5, $v0, .L0041BF04
/* 01BDE4 0041BDE4 AFA50054 */   sw         $a1, 0x54($sp)
/* 01BDE8 0041BDE8 02207025 */  move        $t6, $s1
/* 01BDEC 0041BDEC 0060C025 */  move        $t8, $v1
/* 01BDF0 0041BDF0 262F0048 */  addiu       $t7, $s1, 0x48
.L0041BDF4:
/* 01BDF4 0041BDF4 8DC10000 */  lw          $at, 0x0($t6)
/* 01BDF8 0041BDF8 25CE000C */  addiu       $t6, $t6, 0xC
/* 01BDFC 0041BDFC AF010000 */  sw          $at, 0x0($t8)
/* 01BE00 0041BE00 8DC1FFF8 */  lw          $at, -0x8($t6)
/* 01BE04 0041BE04 2718000C */  addiu       $t8, $t8, 0xC
/* 01BE08 0041BE08 AF01FFF8 */  sw          $at, -0x8($t8)
/* 01BE0C 0041BE0C 8DC1FFFC */  lw          $at, -0x4($t6)
/* 01BE10 0041BE10 15CFFFF8 */  bne         $t6, $t7, .L0041BDF4
/* 01BE14 0041BE14 AF01FFFC */   sw         $at, -0x4($t8)
/* 01BE18 0041BE18 8FB9007C */  lw          $t9, 0x7C($sp)
/* 01BE1C 0041BE1C 00000000 */  nop
/* 01BE20 0041BE20 00197200 */  sll         $t6, $t9, 8
/* 01BE24 0041BE24 01D2C024 */  and         $t8, $t6, $s2
/* 01BE28 0041BE28 00197E00 */  sll         $t7, $t9, 24
/* 01BE2C 0041BE2C 01F87025 */  or          $t6, $t7, $t8
/* 01BE30 0041BE30 00197A02 */  srl         $t7, $t9, 8
/* 01BE34 0041BE34 31F8FF00 */  andi        $t8, $t7, 0xFF00
/* 01BE38 0041BE38 01D87825 */  or          $t7, $t6, $t8
/* 01BE3C 0041BE3C 00197602 */  srl         $t6, $t9, 24
/* 01BE40 0041BE40 01EEC825 */  or          $t9, $t7, $t6
/* 01BE44 0041BE44 AFB9007C */  sw          $t9, 0x7C($sp)
/* 01BE48 0041BE48 9078003C */  lbu         $t8, 0x3C($v1)
/* 01BE4C 0041BE4C 001970C0 */  sll         $t6, $t9, 3
/* 01BE50 0041BE50 3319FF07 */  andi        $t9, $t8, 0xFF07
/* 01BE54 0041BE54 01D97825 */  or          $t7, $t6, $t9
/* 01BE58 0041BE58 A06F003C */  sb          $t7, 0x3C($v1)
/* 01BE5C 0041BE5C 8FB8007C */  lw          $t8, 0x7C($sp)
/* 01BE60 0041BE60 00000000 */  nop
/* 01BE64 0041BE64 00187680 */  sll         $t6, $t8, 26
/* 01BE68 0041BE68 000ECFC2 */  srl         $t9, $t6, 31
/* 01BE6C 0041BE6C 906E003C */  lbu         $t6, 0x3C($v1)
/* 01BE70 0041BE70 00197880 */  sll         $t7, $t9, 2
/* 01BE74 0041BE74 31F80004 */  andi        $t8, $t7, 0x4
/* 01BE78 0041BE78 31D9FFFB */  andi        $t9, $t6, 0xFFFB
/* 01BE7C 0041BE7C 03197825 */  or          $t7, $t8, $t9
/* 01BE80 0041BE80 A06F003C */  sb          $t7, 0x3C($v1)
/* 01BE84 0041BE84 8FAE007C */  lw          $t6, 0x7C($sp)
/* 01BE88 0041BE88 00000000 */  nop
/* 01BE8C 0041BE8C 000EC640 */  sll         $t8, $t6, 25
/* 01BE90 0041BE90 0018CFC2 */  srl         $t9, $t8, 31
/* 01BE94 0041BE94 9078003C */  lbu         $t8, 0x3C($v1)
/* 01BE98 0041BE98 00197840 */  sll         $t7, $t9, 1
/* 01BE9C 0041BE9C 31EE0002 */  andi        $t6, $t7, 0x2
/* 01BEA0 0041BEA0 3319FFFD */  andi        $t9, $t8, 0xFFFD
/* 01BEA4 0041BEA4 01D97825 */  or          $t7, $t6, $t9
/* 01BEA8 0041BEA8 A06F003C */  sb          $t7, 0x3C($v1)
/* 01BEAC 0041BEAC 93B8007F */  lbu         $t8, 0x7F($sp)
/* 01BEB0 0041BEB0 00000000 */  nop
/* 01BEB4 0041BEB4 001871C2 */  srl         $t6, $t8, 7
/* 01BEB8 0041BEB8 31D90001 */  andi        $t9, $t6, 0x1
/* 01BEBC 0041BEBC 31F800FE */  andi        $t8, $t7, 0xFE
/* 01BEC0 0041BEC0 03387025 */  or          $t6, $t9, $t8
/* 01BEC4 0041BEC4 A06E003C */  sb          $t6, 0x3C($v1)
/* 01BEC8 0041BEC8 93B9007E */  lbu         $t9, 0x7E($sp)
/* 01BECC 0041BECC 906F003D */  lbu         $t7, 0x3D($v1)
/* 01BED0 0041BED0 00197180 */  sll         $t6, $t9, 6
/* 01BED4 0041BED4 31F9FF3F */  andi        $t9, $t7, 0xFF3F
/* 01BED8 0041BED8 01D9C025 */  or          $t8, $t6, $t9
/* 01BEDC 0041BEDC A078003D */  sb          $t8, 0x3D($v1)
/* 01BEE0 0041BEE0 8FAF007C */  lw          $t7, 0x7C($sp)
/* 01BEE4 0041BEE4 00000000 */  nop
/* 01BEE8 0041BEE8 000FCA82 */  srl         $t9, $t7, 10
/* 01BEEC 0041BEEC 946F003E */  lhu         $t7, 0x3E($v1)
/* 01BEF0 0041BEF0 33381FFF */  andi        $t8, $t9, 0x1FFF
/* 01BEF4 0041BEF4 31EEE000 */  andi        $t6, $t7, 0xE000
/* 01BEF8 0041BEF8 030EC825 */  or          $t9, $t8, $t6
/* 01BEFC 0041BEFC 10000048 */  b           .L0041C020
/* 01BF00 0041BF00 A479003E */   sh         $t9, 0x3E($v1)
.L0041BF04:
/* 01BF04 0041BF04 8C6F003C */  lw          $t7, 0x3C($v1)
/* 01BF08 0041BF08 93B9007F */  lbu         $t9, 0x7F($sp)
/* 01BF0C 0041BF0C 000FC6C2 */  srl         $t8, $t7, 27
/* 01BF10 0041BF10 330E001F */  andi        $t6, $t8, 0x1F
/* 01BF14 0041BF14 332FFFE0 */  andi        $t7, $t9, 0xFFE0
/* 01BF18 0041BF18 01CFC025 */  or          $t8, $t6, $t7
/* 01BF1C 0041BF1C A3B8007F */  sb          $t8, 0x7F($sp)
/* 01BF20 0041BF20 8C79003C */  lw          $t9, 0x3C($v1)
/* 01BF24 0041BF24 00000000 */  nop
/* 01BF28 0041BF28 00197140 */  sll         $t6, $t9, 5
/* 01BF2C 0041BF2C 000E7FC2 */  srl         $t7, $t6, 31
/* 01BF30 0041BF30 000FC940 */  sll         $t9, $t7, 5
/* 01BF34 0041BF34 332E0020 */  andi        $t6, $t9, 0x20
/* 01BF38 0041BF38 03007825 */  move        $t7, $t8
/* 01BF3C 0041BF3C 31F900DF */  andi        $t9, $t7, 0xDF
/* 01BF40 0041BF40 01D9C025 */  or          $t8, $t6, $t9
/* 01BF44 0041BF44 A3B8007F */  sb          $t8, 0x7F($sp)
/* 01BF48 0041BF48 8C6F003C */  lw          $t7, 0x3C($v1)
/* 01BF4C 0041BF4C 00000000 */  nop
/* 01BF50 0041BF50 000F7180 */  sll         $t6, $t7, 6
/* 01BF54 0041BF54 000ECFC2 */  srl         $t9, $t6, 31
/* 01BF58 0041BF58 00197980 */  sll         $t7, $t9, 6
/* 01BF5C 0041BF5C 31EE0040 */  andi        $t6, $t7, 0x40
/* 01BF60 0041BF60 0300C825 */  move        $t9, $t8
/* 01BF64 0041BF64 332F00BF */  andi        $t7, $t9, 0xBF
/* 01BF68 0041BF68 01CFC025 */  or          $t8, $t6, $t7
/* 01BF6C 0041BF6C A3B8007F */  sb          $t8, 0x7F($sp)
/* 01BF70 0041BF70 906E003C */  lbu         $t6, 0x3C($v1)
/* 01BF74 0041BF74 00000000 */  nop
/* 01BF78 0041BF78 000EC9C0 */  sll         $t9, $t6, 7
/* 01BF7C 0041BF7C 03007025 */  move        $t6, $t8
/* 01BF80 0041BF80 31CF007F */  andi        $t7, $t6, 0x7F
/* 01BF84 0041BF84 032FC025 */  or          $t8, $t9, $t7
/* 01BF88 0041BF88 A3B8007F */  sb          $t8, 0x7F($sp)
/* 01BF8C 0041BF8C 906E003D */  lbu         $t6, 0x3D($v1)
/* 01BF90 0041BF90 93B8007E */  lbu         $t8, 0x7E($sp)
/* 01BF94 0041BF94 000EC982 */  srl         $t9, $t6, 6
/* 01BF98 0041BF98 332F0003 */  andi        $t7, $t9, 0x3
/* 01BF9C 0041BF9C 330EFFFC */  andi        $t6, $t8, 0xFFFC
/* 01BFA0 0041BFA0 01EEC825 */  or          $t9, $t7, $t6
/* 01BFA4 0041BFA4 A3B9007E */  sb          $t9, 0x7E($sp)
/* 01BFA8 0041BFA8 8FAE007C */  lw          $t6, 0x7C($sp)
/* 01BFAC 0041BFAC 8C78003C */  lw          $t8, 0x3C($v1)
/* 01BFB0 0041BFB0 000ECA82 */  srl         $t9, $t6, 10
/* 01BFB4 0041BFB4 330F1FFF */  andi        $t7, $t8, 0x1FFF
/* 01BFB8 0041BFB8 01F9C026 */  xor         $t8, $t7, $t9
/* 01BFBC 0041BFBC 00187A80 */  sll         $t7, $t8, 10
/* 01BFC0 0041BFC0 01EEC826 */  xor         $t9, $t7, $t6
/* 01BFC4 0041BFC4 00197A00 */  sll         $t7, $t9, 8
/* 01BFC8 0041BFC8 01F27024 */  and         $t6, $t7, $s2
/* 01BFCC 0041BFCC 0019C600 */  sll         $t8, $t9, 24
/* 01BFD0 0041BFD0 030E7825 */  or          $t7, $t8, $t6
/* 01BFD4 0041BFD4 0019C202 */  srl         $t8, $t9, 8
/* 01BFD8 0041BFD8 330EFF00 */  andi        $t6, $t8, 0xFF00
/* 01BFDC 0041BFDC 01EEC025 */  or          $t8, $t7, $t6
/* 01BFE0 0041BFE0 00197E02 */  srl         $t7, $t9, 24
/* 01BFE4 0041BFE4 030F7025 */  or          $t6, $t8, $t7
/* 01BFE8 0041BFE8 AFB9007C */  sw          $t9, 0x7C($sp)
/* 01BFEC 0041BFEC AFAE007C */  sw          $t6, 0x7C($sp)
/* 01BFF0 0041BFF0 02207025 */  move        $t6, $s1
/* 01BFF4 0041BFF4 262F0048 */  addiu       $t7, $s1, 0x48
/* 01BFF8 0041BFF8 0060C025 */  move        $t8, $v1
.L0041BFFC:
/* 01BFFC 0041BFFC 8DC10000 */  lw          $at, 0x0($t6)
/* 01C000 0041C000 25CE000C */  addiu       $t6, $t6, 0xC
/* 01C004 0041C004 AF010000 */  sw          $at, 0x0($t8)
/* 01C008 0041C008 8DC1FFF8 */  lw          $at, -0x8($t6)
/* 01C00C 0041C00C 2718000C */  addiu       $t8, $t8, 0xC
/* 01C010 0041C010 AF01FFF8 */  sw          $at, -0x8($t8)
/* 01C014 0041C014 8DC1FFFC */  lw          $at, -0x4($t6)
/* 01C018 0041C018 15CFFFF8 */  bne         $t6, $t7, .L0041BFFC
/* 01C01C 0041C01C AF01FFFC */   sw         $at, -0x4($t8)
.L0041C020:
/* 01C020 0041C020 26730001 */  addiu       $s3, $s3, 0x1
/* 01C024 0041C024 1674FEA3 */  bne         $s3, $s4, .L0041BAB4
/* 01C028 0041C028 24630048 */   addiu      $v1, $v1, 0x48
.L0041C02C:
/* 01C02C 0041C02C 8FBF0034 */  lw          $ra, 0x34($sp)
/* 01C030 0041C030 8FB00018 */  lw          $s0, 0x18($sp)
/* 01C034 0041C034 8FB1001C */  lw          $s1, 0x1C($sp)
/* 01C038 0041C038 8FB20020 */  lw          $s2, 0x20($sp)
/* 01C03C 0041C03C 8FB30024 */  lw          $s3, 0x24($sp)
/* 01C040 0041C040 8FB40028 */  lw          $s4, 0x28($sp)
/* 01C044 0041C044 8FB5002C */  lw          $s5, 0x2C($sp)
/* 01C048 0041C048 03E00008 */  jr          $ra
/* 01C04C 0041C04C 27BD0090 */   addiu      $sp, $sp, 0x90
