/* Generated by spimdisasm 1.10.3 */

glabel swap_got # 264
/* 01D8A4 0041D8A4 AFA50004 */  sw          $a1, 0x4($sp)
/* 01D8A8 0041D8A8 8C820000 */  lw          $v0, 0x0($a0)
/* 01D8AC 0041D8AC 3C0100FF */  lui         $at, (0xFF0000 >> 16)
/* 01D8B0 0041D8B0 00027A00 */  sll         $t7, $v0, 8
/* 01D8B4 0041D8B4 01E1C024 */  and         $t8, $t7, $at
/* 01D8B8 0041D8B8 00027600 */  sll         $t6, $v0, 24
/* 01D8BC 0041D8BC 00024202 */  srl         $t0, $v0, 8
/* 01D8C0 0041D8C0 3109FF00 */  andi        $t1, $t0, 0xFF00
/* 01D8C4 0041D8C4 01D8C825 */  or          $t9, $t6, $t8
/* 01D8C8 0041D8C8 03295025 */  or          $t2, $t9, $t1
/* 01D8CC 0041D8CC 00025E02 */  srl         $t3, $v0, 24
/* 01D8D0 0041D8D0 014B6025 */  or          $t4, $t2, $t3
/* 01D8D4 0041D8D4 03E00008 */  jr          $ra
/* 01D8D8 0041D8D8 AC8C0000 */   sw         $t4, 0x0($a0)
