/* Generated by spimdisasm 1.10.3 */

glabel swap_dn # 252
/* 01CA9C 0041CA9C AFA60008 */  sw          $a2, 0x8($sp)
/* 01CAA0 0041CAA0 18A0004F */  blez        $a1, .L0041CBE0
/* 01CAA4 0041CAA4 00001025 */   move       $v0, $zero
/* 01CAA8 0041CAA8 30A30001 */  andi        $v1, $a1, 0x1
/* 01CAAC 0041CAAC 10600019 */  beqz        $v1, .L0041CB14
/* 01CAB0 0041CAB0 3C0900FF */   lui        $t1, (0xFF0000 >> 16)
/* 01CAB4 0041CAB4 8C860000 */  lw          $a2, 0x0($a0)
/* 01CAB8 0041CAB8 8C870004 */  lw          $a3, 0x4($a0)
/* 01CABC 0041CABC 00067602 */  srl         $t6, $a2, 24
/* 01CAC0 0041CAC0 00067E00 */  sll         $t7, $a2, 24
/* 01CAC4 0041CAC4 0006CA00 */  sll         $t9, $a2, 8
/* 01CAC8 0041CAC8 03295024 */  and         $t2, $t9, $t1
/* 01CACC 0041CACC 01CFC025 */  or          $t8, $t6, $t7
/* 01CAD0 0041CAD0 00066202 */  srl         $t4, $a2, 8
/* 01CAD4 0041CAD4 318DFF00 */  andi        $t5, $t4, 0xFF00
/* 01CAD8 0041CAD8 030A5825 */  or          $t3, $t8, $t2
/* 01CADC 0041CADC 016D7025 */  or          $t6, $t3, $t5
/* 01CAE0 0041CAE0 00075200 */  sll         $t2, $a3, 8
/* 01CAE4 0041CAE4 00077E02 */  srl         $t7, $a3, 24
/* 01CAE8 0041CAE8 0007CE00 */  sll         $t9, $a3, 24
/* 01CAEC 0041CAEC 01F9C025 */  or          $t8, $t7, $t9
/* 01CAF0 0041CAF0 01496024 */  and         $t4, $t2, $t1
/* 01CAF4 0041CAF4 AC8E0000 */  sw          $t6, 0x0($a0)
/* 01CAF8 0041CAF8 00076A02 */  srl         $t5, $a3, 8
/* 01CAFC 0041CAFC 31AEFF00 */  andi        $t6, $t5, 0xFF00
/* 01CB00 0041CB00 030C5825 */  or          $t3, $t8, $t4
/* 01CB04 0041CB04 016E7825 */  or          $t7, $t3, $t6
/* 01CB08 0041CB08 24020001 */  addiu       $v0, $zero, 0x1
/* 01CB0C 0041CB0C 10450034 */  beq         $v0, $a1, .L0041CBE0
/* 01CB10 0041CB10 AC8F0004 */   sw         $t7, 0x4($a0)
.L0041CB14:
/* 01CB14 0041CB14 0002C8C0 */  sll         $t9, $v0, 3
/* 01CB18 0041CB18 000550C0 */  sll         $t2, $a1, 3
/* 01CB1C 0041CB1C 01444021 */  addu        $t0, $t2, $a0
/* 01CB20 0041CB20 00991821 */  addu        $v1, $a0, $t9
/* 01CB24 0041CB24 3C0900FF */  lui         $t1, (0xFF0000 >> 16)
.L0041CB28:
/* 01CB28 0041CB28 8C620000 */  lw          $v0, 0x0($v1)
/* 01CB2C 0041CB2C 8C640004 */  lw          $a0, 0x4($v1)
/* 01CB30 0041CB30 0002C602 */  srl         $t8, $v0, 24
/* 01CB34 0041CB34 00026600 */  sll         $t4, $v0, 24
/* 01CB38 0041CB38 00025A00 */  sll         $t3, $v0, 8
/* 01CB3C 0041CB3C 01697024 */  and         $t6, $t3, $t1
/* 01CB40 0041CB40 030C6825 */  or          $t5, $t8, $t4
/* 01CB44 0041CB44 0002CA02 */  srl         $t9, $v0, 8
/* 01CB48 0041CB48 332AFF00 */  andi        $t2, $t9, 0xFF00
/* 01CB4C 0041CB4C 01AE7825 */  or          $t7, $t5, $t6
/* 01CB50 0041CB50 01EAC025 */  or          $t8, $t7, $t2
/* 01CB54 0041CB54 00047200 */  sll         $t6, $a0, 8
/* 01CB58 0041CB58 00046602 */  srl         $t4, $a0, 24
/* 01CB5C 0041CB5C 00045E00 */  sll         $t3, $a0, 24
/* 01CB60 0041CB60 8C660008 */  lw          $a2, 0x8($v1)
/* 01CB64 0041CB64 AC780000 */  sw          $t8, 0x0($v1)
/* 01CB68 0041CB68 018B6825 */  or          $t5, $t4, $t3
/* 01CB6C 0041CB6C 01C9C824 */  and         $t9, $t6, $t1
/* 01CB70 0041CB70 00045202 */  srl         $t2, $a0, 8
/* 01CB74 0041CB74 3158FF00 */  andi        $t8, $t2, 0xFF00
/* 01CB78 0041CB78 01B97825 */  or          $t7, $t5, $t9
/* 01CB7C 0041CB7C 01F86025 */  or          $t4, $t7, $t8
/* 01CB80 0041CB80 0006CA00 */  sll         $t9, $a2, 8
/* 01CB84 0041CB84 00067600 */  sll         $t6, $a2, 24
/* 01CB88 0041CB88 00065E02 */  srl         $t3, $a2, 24
/* 01CB8C 0041CB8C 8C67000C */  lw          $a3, 0xC($v1)
/* 01CB90 0041CB90 016E6825 */  or          $t5, $t3, $t6
/* 01CB94 0041CB94 03295024 */  and         $t2, $t9, $t1
/* 01CB98 0041CB98 AC6C0004 */  sw          $t4, 0x4($v1)
/* 01CB9C 0041CB9C 0006C202 */  srl         $t8, $a2, 8
/* 01CBA0 0041CBA0 330CFF00 */  andi        $t4, $t8, 0xFF00
/* 01CBA4 0041CBA4 01AA7825 */  or          $t7, $t5, $t2
/* 01CBA8 0041CBA8 01EC5825 */  or          $t3, $t7, $t4
/* 01CBAC 0041CBAC 00075200 */  sll         $t2, $a3, 8
/* 01CBB0 0041CBB0 0007CE00 */  sll         $t9, $a3, 24
/* 01CBB4 0041CBB4 00077602 */  srl         $t6, $a3, 24
/* 01CBB8 0041CBB8 01D96825 */  or          $t5, $t6, $t9
/* 01CBBC 0041CBBC 0149C024 */  and         $t8, $t2, $t1
/* 01CBC0 0041CBC0 AC6B0008 */  sw          $t3, 0x8($v1)
/* 01CBC4 0041CBC4 00076202 */  srl         $t4, $a3, 8
/* 01CBC8 0041CBC8 318BFF00 */  andi        $t3, $t4, 0xFF00
/* 01CBCC 0041CBCC 01B87825 */  or          $t7, $t5, $t8
/* 01CBD0 0041CBD0 01EB7025 */  or          $t6, $t7, $t3
/* 01CBD4 0041CBD4 24630010 */  addiu       $v1, $v1, 0x10
/* 01CBD8 0041CBD8 1468FFD3 */  bne         $v1, $t0, .L0041CB28
/* 01CBDC 0041CBDC AC6EFFFC */   sw         $t6, -0x4($v1)
.L0041CBE0:
/* 01CBE0 0041CBE0 03E00008 */  jr          $ra
/* 01CBE4 0041CBE4 00000000 */   nop
