.section .rodata
glabel STR_100061AC
/* 0251AC 100061AC */ .asciz "Conflicting definition of symbol %s"
                      .balign 4

glabel STR_100061D0
/* 0251D0 100061D0 */ .asciz "Conflicting definition of symbol %s"
                      .balign 4

glabel STR_100061F4
/* 0251F4 100061F4 */ .asciz "Conflicting definition of symbol %s"
                      .balign 4

glabel STR_10006218
/* 025218 10006218 */ .asciz "Cannot use .comm on previously defined symbol %s"
                      .balign 4

glabel STR_1000624C
/* 02524C 1000624C */ .asciz "Cannot use .lcomm on previously defined symbol %s"
                      .balign 4

glabel STR_10006280
/* 025280 10006280 */ .asciz ".globl must precede the definition of the symbol %s"
                      .balign 4

glabel STR_100062B4
/* 0252B4 100062B4 */ .asciz ".ent must precede the definition of the symbol %s"
                      .balign 4

glabel STR_100062E8
/* 0252E8 100062E8 */ .asciz "scNil to scNil"
                      .balign 4

glabel STR_100062F8
/* 0252F8 100062F8 */ .asciz "Internal: bad action in sym_define"
                      .balign 4

.section .late_rodata
glabel jtbl_10006320
/* 025320 10006320 F03FE64C */ .gpword .L0040F10C
/* 025324 10006324 F03FE0F4 */ .gpword .L0040EBB4
/* 025328 10006328 F03FE26C */ .gpword .L0040ED2C
/* 02532C 1000632C F03FE68C */ .gpword .L0040F14C
/* 025330 10006330 F03FE68C */ .gpword .L0040F14C
/* 025334 10006334 F03FE054 */ .gpword .L0040EB14
/* 025338 10006338 F03FE68C */ .gpword .L0040F14C
/* 02533C 1000633C F03FE68C */ .gpword .L0040F14C
/* 025340 10006340 F03FE68C */ .gpword .L0040F14C
/* 025344 10006344 F03FE68C */ .gpword .L0040F14C
/* 025348 10006348 F03FE68C */ .gpword .L0040F14C
/* 02534C 1000634C F03FE68C */ .gpword .L0040F14C
/* 025350 10006350 F03FE68C */ .gpword .L0040F14C
/* 025354 10006354 F03FE26C */ .gpword .L0040ED2C
/* 025358 10006358 F03FE68C */ .gpword .L0040F14C
/* 02535C 1000635C F03FE26C */ .gpword .L0040ED2C
/* 025360 10006360 F03FE68C */ .gpword .L0040F14C
/* 025364 10006364 F03FE338 */ .gpword .L0040EDF8
/* 025368 10006368 F03FE68C */ .gpword .L0040F14C
/* 02536C 1000636C F03FE68C */ .gpword .L0040F14C
/* 025370 10006370 F03FE68C */ .gpword .L0040F14C
/* 025374 10006374 F03FE68C */ .gpword .L0040F14C
/* 025378 10006378 F03FE68C */ .gpword .L0040F14C
/* 02537C 1000637C F03FE68C */ .gpword .L0040F14C
/* 025380 10006380 F03FE68C */ .gpword .L0040F14C
/* 025384 10006384 F03FE68C */ .gpword .L0040F14C
/* 025388 10006388 F03FE68C */ .gpword .L0040F14C
/* 02538C 1000638C F03FE68C */ .gpword .L0040F14C
/* 025390 10006390 F03FE68C */ .gpword .L0040F14C
/* 025394 10006394 F03FE68C */ .gpword .L0040F14C
/* 025398 10006398 F03FE68C */ .gpword .L0040F14C
/* 02539C 1000639C F03FE68C */ .gpword .L0040F14C
/* 0253A0 100063A0 F03FE68C */ .gpword .L0040F14C
/* 0253A4 100063A4 F03FE414 */ .gpword .L0040EED4
/* 0253A8 100063A8 F03FE4EC */ .gpword .L0040EFAC
/* 0253AC 100063AC F03FE5AC */ .gpword .L0040F06C


.section .text
/* Generated by spimdisasm 1.10.3 */

glabel sym_define # 95
# _gp_disp: 0xFC02028
.set noreorder; .cpload $t9; # .set reorder
/* 00EAA4 0040EAA4 27BDFFC0 */  addiu       $sp, $sp, -0x40
/* 00EAA8 0040EAA8 8F99822C */  lw          $t9, %call16(st_sym_idn)($gp)
/* 00EAAC 0040EAAC AFBF0024 */  sw          $ra, 0x24($sp)
/* 00EAB0 0040EAB0 AFA50044 */  sw          $a1, 0x44($sp)
/* 00EAB4 0040EAB4 AFA60048 */  sw          $a2, 0x48($sp)
/* 00EAB8 0040EAB8 27AE0030 */  addiu       $t6, $sp, 0x30
/* 00EABC 0040EABC AFBC0020 */  sw          $gp, 0x20($sp)
/* 00EAC0 0040EAC0 AFAE0010 */  sw          $t6, 0x10($sp)
/* 00EAC4 0040EAC4 27A60034 */  addiu       $a2, $sp, 0x34
/* 00EAC8 0040EAC8 27A50038 */  addiu       $a1, $sp, 0x38
/* 00EACC 0040EACC 27A7003C */  addiu       $a3, $sp, 0x3C
/* 00EAD0 0040EAD0 0320F809 */  jalr        $t9
/* 00EAD4 0040EAD4 AFA40040 */   sw         $a0, 0x40($sp)
/* 00EAD8 0040EAD8 8FA60044 */  lw          $a2, 0x44($sp)
/* 00EADC 0040EADC 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EAE0 0040EAE0 8FA40040 */  lw          $a0, 0x40($sp)
/* 00EAE4 0040EAE4 8FA70048 */  lw          $a3, 0x48($sp)
/* 00EAE8 0040EAE8 2CC10024 */  sltiu       $at, $a2, 0x24
/* 00EAEC 0040EAEC 10200197 */  beqz        $at, .L0040F14C
/* 00EAF0 0040EAF0 AFA2002C */   sw         $v0, 0x2C($sp)
/* 00EAF4 0040EAF4 8F818050 */  lw          $at, %got(jtbl_10006320)($gp)
/* 00EAF8 0040EAF8 00067880 */  sll         $t7, $a2, 2
/* 00EAFC 0040EAFC 002F0821 */  addu        $at, $at, $t7
/* 00EB00 0040EB00 8C2F6320 */  lw          $t7, %lo(jtbl_10006320)($at)
/* 00EB04 0040EB04 00000000 */  nop
/* 00EB08 0040EB08 01FC7821 */  addu        $t7, $t7, $gp
/* 00EB0C 0040EB0C 01E00008 */  jr          $t7
/* 00EB10 0040EB10 00000000 */   nop
.L0040EB14:
/* 00EB14 0040EB14 8FA20034 */  lw          $v0, 0x34($sp)
/* 00EB18 0040EB18 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EB1C 0040EB1C 1440000D */  bnez        $v0, .L0040EB54
/* 00EB20 0040EB20 24030001 */   addiu      $v1, $zero, 0x1
/* 00EB24 0040EB24 14A0000B */  bnez        $a1, .L0040EB54
/* 00EB28 0040EB28 24060005 */   addiu      $a2, $zero, 0x5
/* 00EB2C 0040EB2C 8F998018 */  lw          $t9, %got(func_0040E554)($gp)
/* 00EB30 0040EB30 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00EB34 0040EB34 24180001 */  addiu       $t8, $zero, 0x1
/* 00EB38 0040EB38 2739E554 */  addiu       $t9, $t9, %lo(func_0040E554)
/* 00EB3C 0040EB3C AFB80010 */  sw          $t8, 0x10($sp)
/* 00EB40 0040EB40 0320F809 */  jalr        $t9
/* 00EB44 0040EB44 24050002 */   addiu      $a1, $zero, 0x2
/* 00EB48 0040EB48 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EB4C 0040EB4C 10000188 */  b           .L0040F170
/* 00EB50 0040EB50 24020001 */   addiu      $v0, $zero, 0x1
.L0040EB54:
/* 00EB54 0040EB54 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EB58 0040EB58 1443000D */  bne         $v0, $v1, .L0040EB90
/* 00EB5C 0040EB5C 24060001 */   addiu      $a2, $zero, 0x1
/* 00EB60 0040EB60 14A0000B */  bnez        $a1, .L0040EB90
/* 00EB64 0040EB64 24190001 */   addiu      $t9, $zero, 0x1
/* 00EB68 0040EB68 AFB90010 */  sw          $t9, 0x10($sp)
/* 00EB6C 0040EB6C 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EB70 0040EB70 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00EB74 0040EB74 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EB78 0040EB78 24050001 */  addiu       $a1, $zero, 0x1
/* 00EB7C 0040EB7C 0320F809 */  jalr        $t9
/* 00EB80 0040EB80 24060005 */   addiu      $a2, $zero, 0x5
/* 00EB84 0040EB84 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EB88 0040EB88 10000179 */  b           .L0040F170
/* 00EB8C 0040EB8C 24020001 */   addiu      $v0, $zero, 0x1
.L0040EB90:
/* 00EB90 0040EB90 8F998018 */  lw          $t9, %got(func_0040E180)($gp)
/* 00EB94 0040EB94 8F848050 */  lw          $a0, %got(STR_100061AC)($gp)
/* 00EB98 0040EB98 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00EB9C 0040EB9C 2739E180 */  addiu       $t9, $t9, %lo(func_0040E180)
/* 00EBA0 0040EBA0 0320F809 */  jalr        $t9
/* 00EBA4 0040EBA4 248461AC */   addiu      $a0, $a0, %lo(STR_100061AC)
/* 00EBA8 0040EBA8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EBAC 0040EBAC 10000170 */  b           .L0040F170
/* 00EBB0 0040EBB0 00001025 */   move       $v0, $zero
.L0040EBB4:
/* 00EBB4 0040EBB4 8FA20034 */  lw          $v0, 0x34($sp)
/* 00EBB8 0040EBB8 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EBBC 0040EBBC 1440000C */  bnez        $v0, .L0040EBF0
/* 00EBC0 0040EBC0 2401000E */   addiu      $at, $zero, 0xE
/* 00EBC4 0040EBC4 14A0000A */  bnez        $a1, .L0040EBF0
/* 00EBC8 0040EBC8 24060001 */   addiu      $a2, $zero, 0x1
/* 00EBCC 0040EBCC 8F998018 */  lw          $t9, %got(func_0040E554)($gp)
/* 00EBD0 0040EBD0 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00EBD4 0040EBD4 2739E554 */  addiu       $t9, $t9, %lo(func_0040E554)
/* 00EBD8 0040EBD8 24050005 */  addiu       $a1, $zero, 0x5
/* 00EBDC 0040EBDC 0320F809 */  jalr        $t9
/* 00EBE0 0040EBE0 AFA00010 */   sw         $zero, 0x10($sp)
/* 00EBE4 0040EBE4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EBE8 0040EBE8 10000161 */  b           .L0040F170
/* 00EBEC 0040EBEC 24020001 */   addiu      $v0, $zero, 0x1
.L0040EBF0:
/* 00EBF0 0040EBF0 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EBF4 0040EBF4 1441001B */  bne         $v0, $at, .L0040EC64
/* 00EBF8 0040EBF8 24010006 */   addiu      $at, $zero, 0x6
/* 00EBFC 0040EBFC 14A00018 */  bnez        $a1, .L0040EC60
/* 00EC00 0040EC00 24060001 */   addiu      $a2, $zero, 0x1
/* 00EC04 0040EC04 8F998018 */  lw          $t9, %got(func_0040E554)($gp)
/* 00EC08 0040EC08 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00EC0C 0040EC0C 24080001 */  addiu       $t0, $zero, 0x1
/* 00EC10 0040EC10 2739E554 */  addiu       $t9, $t9, %lo(func_0040E554)
/* 00EC14 0040EC14 AFA80010 */  sw          $t0, 0x10($sp)
/* 00EC18 0040EC18 2405000E */  addiu       $a1, $zero, 0xE
/* 00EC1C 0040EC1C 0320F809 */  jalr        $t9
/* 00EC20 0040EC20 AFA40040 */   sw         $a0, 0x40($sp)
/* 00EC24 0040EC24 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EC28 0040EC28 8FA40040 */  lw          $a0, 0x40($sp)
/* 00EC2C 0040EC2C 8F998228 */  lw          $t9, %call16(st_procbegin)($gp)
/* 00EC30 0040EC30 00000000 */  nop
/* 00EC34 0040EC34 0320F809 */  jalr        $t9
/* 00EC38 0040EC38 00000000 */   nop
/* 00EC3C 0040EC3C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EC40 0040EC40 8FA40040 */  lw          $a0, 0x40($sp)
/* 00EC44 0040EC44 8F998234 */  lw          $t9, %call16(st_pdadd_idn)($gp)
/* 00EC48 0040EC48 00000000 */  nop
/* 00EC4C 0040EC4C 0320F809 */  jalr        $t9
/* 00EC50 0040EC50 00000000 */   nop
/* 00EC54 0040EC54 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EC58 0040EC58 10000145 */  b           .L0040F170
/* 00EC5C 0040EC5C 24020001 */   addiu      $v0, $zero, 0x1
.L0040EC60:
/* 00EC60 0040EC60 24010006 */  addiu       $at, $zero, 0x6
.L0040EC64:
/* 00EC64 0040EC64 1441001A */  bne         $v0, $at, .L0040ECD0
/* 00EC68 0040EC68 24030001 */   addiu      $v1, $zero, 0x1
/* 00EC6C 0040EC6C 14A00018 */  bnez        $a1, .L0040ECD0
/* 00EC70 0040EC70 00003025 */   move       $a2, $zero
/* 00EC74 0040EC74 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EC78 0040EC78 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00EC7C 0040EC7C 24090001 */  addiu       $t1, $zero, 0x1
/* 00EC80 0040EC80 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EC84 0040EC84 AFA90010 */  sw          $t1, 0x10($sp)
/* 00EC88 0040EC88 24050006 */  addiu       $a1, $zero, 0x6
/* 00EC8C 0040EC8C 0320F809 */  jalr        $t9
/* 00EC90 0040EC90 AFA40040 */   sw         $a0, 0x40($sp)
/* 00EC94 0040EC94 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EC98 0040EC98 8FA40040 */  lw          $a0, 0x40($sp)
/* 00EC9C 0040EC9C 8F998228 */  lw          $t9, %call16(st_procbegin)($gp)
/* 00ECA0 0040ECA0 00000000 */  nop
/* 00ECA4 0040ECA4 0320F809 */  jalr        $t9
/* 00ECA8 0040ECA8 00000000 */   nop
/* 00ECAC 0040ECAC 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00ECB0 0040ECB0 8FA40040 */  lw          $a0, 0x40($sp)
/* 00ECB4 0040ECB4 8F998234 */  lw          $t9, %call16(st_pdadd_idn)($gp)
/* 00ECB8 0040ECB8 00000000 */  nop
/* 00ECBC 0040ECBC 0320F809 */  jalr        $t9
/* 00ECC0 0040ECC0 00000000 */   nop
/* 00ECC4 0040ECC4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00ECC8 0040ECC8 10000129 */  b           .L0040F170
/* 00ECCC 0040ECCC 24020001 */   addiu      $v0, $zero, 0x1
.L0040ECD0:
/* 00ECD0 0040ECD0 1443000D */  bne         $v0, $v1, .L0040ED08
/* 00ECD4 0040ECD4 24060001 */   addiu      $a2, $zero, 0x1
/* 00ECD8 0040ECD8 14A0000B */  bnez        $a1, .L0040ED08
/* 00ECDC 0040ECDC 00000000 */   nop
/* 00ECE0 0040ECE0 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00ECE4 0040ECE4 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00ECE8 0040ECE8 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00ECEC 0040ECEC 24050005 */  addiu       $a1, $zero, 0x5
/* 00ECF0 0040ECF0 24060001 */  addiu       $a2, $zero, 0x1
/* 00ECF4 0040ECF4 0320F809 */  jalr        $t9
/* 00ECF8 0040ECF8 AFA00010 */   sw         $zero, 0x10($sp)
/* 00ECFC 0040ECFC 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00ED00 0040ED00 1000011B */  b           .L0040F170
/* 00ED04 0040ED04 24020001 */   addiu      $v0, $zero, 0x1
.L0040ED08:
/* 00ED08 0040ED08 8F998018 */  lw          $t9, %got(func_0040E180)($gp)
/* 00ED0C 0040ED0C 8F848050 */  lw          $a0, %got(STR_100061D0)($gp)
/* 00ED10 0040ED10 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00ED14 0040ED14 2739E180 */  addiu       $t9, $t9, %lo(func_0040E180)
/* 00ED18 0040ED18 0320F809 */  jalr        $t9
/* 00ED1C 0040ED1C 248461D0 */   addiu      $a0, $a0, %lo(STR_100061D0)
/* 00ED20 0040ED20 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00ED24 0040ED24 10000112 */  b           .L0040F170
/* 00ED28 0040ED28 00001025 */   move       $v0, $zero
.L0040ED2C:
/* 00ED2C 0040ED2C 8FA20034 */  lw          $v0, 0x34($sp)
/* 00ED30 0040ED30 8FA50038 */  lw          $a1, 0x38($sp)
/* 00ED34 0040ED34 1440000B */  bnez        $v0, .L0040ED64
/* 00ED38 0040ED38 24030001 */   addiu      $v1, $zero, 0x1
/* 00ED3C 0040ED3C 14A0000A */  bnez        $a1, .L0040ED68
/* 00ED40 0040ED40 8FA50038 */   lw         $a1, 0x38($sp)
/* 00ED44 0040ED44 8F998018 */  lw          $t9, %got(func_0040E3F0)($gp)
/* 00ED48 0040ED48 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00ED4C 0040ED4C 2739E3F0 */  addiu       $t9, $t9, %lo(func_0040E3F0)
/* 00ED50 0040ED50 0320F809 */  jalr        $t9
/* 00ED54 0040ED54 24050002 */   addiu      $a1, $zero, 0x2
/* 00ED58 0040ED58 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00ED5C 0040ED5C 10000104 */  b           .L0040F170
/* 00ED60 0040ED60 24020001 */   addiu      $v0, $zero, 0x1
.L0040ED64:
/* 00ED64 0040ED64 8FA50038 */  lw          $a1, 0x38($sp)
.L0040ED68:
/* 00ED68 0040ED68 1443000C */  bne         $v0, $v1, .L0040ED9C
/* 00ED6C 0040ED6C 00000000 */   nop
/* 00ED70 0040ED70 14A0000A */  bnez        $a1, .L0040ED9C
/* 00ED74 0040ED74 240A0001 */   addiu      $t2, $zero, 0x1
/* 00ED78 0040ED78 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00ED7C 0040ED7C 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00ED80 0040ED80 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00ED84 0040ED84 24050001 */  addiu       $a1, $zero, 0x1
/* 00ED88 0040ED88 0320F809 */  jalr        $t9
/* 00ED8C 0040ED8C AFAA0010 */   sw         $t2, 0x10($sp)
/* 00ED90 0040ED90 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00ED94 0040ED94 100000F6 */  b           .L0040F170
/* 00ED98 0040ED98 24020001 */   addiu      $v0, $zero, 0x1
.L0040ED9C:
/* 00ED9C 0040ED9C 1443000C */  bne         $v0, $v1, .L0040EDD0
/* 00EDA0 0040EDA0 24010011 */   addiu      $at, $zero, 0x11
/* 00EDA4 0040EDA4 14A1000A */  bne         $a1, $at, .L0040EDD0
/* 00EDA8 0040EDA8 240B0001 */   addiu      $t3, $zero, 0x1
/* 00EDAC 0040EDAC 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EDB0 0040EDB0 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00EDB4 0040EDB4 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EDB8 0040EDB8 24050001 */  addiu       $a1, $zero, 0x1
/* 00EDBC 0040EDBC 0320F809 */  jalr        $t9
/* 00EDC0 0040EDC0 AFAB0010 */   sw         $t3, 0x10($sp)
/* 00EDC4 0040EDC4 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EDC8 0040EDC8 100000E9 */  b           .L0040F170
/* 00EDCC 0040EDCC 24020001 */   addiu      $v0, $zero, 0x1
.L0040EDD0:
/* 00EDD0 0040EDD0 8F998018 */  lw          $t9, %got(func_0040E180)($gp)
/* 00EDD4 0040EDD4 8F848050 */  lw          $a0, %got(STR_100061F4)($gp)
/* 00EDD8 0040EDD8 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00EDDC 0040EDDC 2739E180 */  addiu       $t9, $t9, %lo(func_0040E180)
/* 00EDE0 0040EDE0 24060001 */  addiu       $a2, $zero, 0x1
/* 00EDE4 0040EDE4 0320F809 */  jalr        $t9
/* 00EDE8 0040EDE8 248461F4 */   addiu      $a0, $a0, %lo(STR_100061F4)
/* 00EDEC 0040EDEC 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EDF0 0040EDF0 100000DF */  b           .L0040F170
/* 00EDF4 0040EDF4 00001025 */   move       $v0, $zero
.L0040EDF8:
/* 00EDF8 0040EDF8 8FA20034 */  lw          $v0, 0x34($sp)
/* 00EDFC 0040EDFC 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EE00 0040EE00 1440000C */  bnez        $v0, .L0040EE34
/* 00EE04 0040EE04 24030001 */   addiu      $v1, $zero, 0x1
/* 00EE08 0040EE08 14A0000A */  bnez        $a1, .L0040EE34
/* 00EE0C 0040EE0C 24060011 */   addiu      $a2, $zero, 0x11
/* 00EE10 0040EE10 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EE14 0040EE14 240C0001 */  addiu       $t4, $zero, 0x1
/* 00EE18 0040EE18 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EE1C 0040EE1C AFAC0010 */  sw          $t4, 0x10($sp)
/* 00EE20 0040EE20 0320F809 */  jalr        $t9
/* 00EE24 0040EE24 24050001 */   addiu      $a1, $zero, 0x1
/* 00EE28 0040EE28 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EE2C 0040EE2C 100000D0 */  b           .L0040F170
/* 00EE30 0040EE30 24020001 */   addiu      $v0, $zero, 0x1
.L0040EE34:
/* 00EE34 0040EE34 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EE38 0040EE38 1443000C */  bne         $v0, $v1, .L0040EE6C
/* 00EE3C 0040EE3C 00000000 */   nop
/* 00EE40 0040EE40 14A0000A */  bnez        $a1, .L0040EE6C
/* 00EE44 0040EE44 24060011 */   addiu      $a2, $zero, 0x11
/* 00EE48 0040EE48 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EE4C 0040EE4C 240D0001 */  addiu       $t5, $zero, 0x1
/* 00EE50 0040EE50 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EE54 0040EE54 AFAD0010 */  sw          $t5, 0x10($sp)
/* 00EE58 0040EE58 0320F809 */  jalr        $t9
/* 00EE5C 0040EE5C 24050001 */   addiu      $a1, $zero, 0x1
/* 00EE60 0040EE60 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EE64 0040EE64 100000C2 */  b           .L0040F170
/* 00EE68 0040EE68 24020001 */   addiu      $v0, $zero, 0x1
.L0040EE6C:
/* 00EE6C 0040EE6C 1443000F */  bne         $v0, $v1, .L0040EEAC
/* 00EE70 0040EE70 24010011 */   addiu      $at, $zero, 0x11
/* 00EE74 0040EE74 14A1000D */  bne         $a1, $at, .L0040EEAC
/* 00EE78 0040EE78 24060011 */   addiu      $a2, $zero, 0x11
/* 00EE7C 0040EE7C 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EE80 0040EE80 8F818060 */  lw          $at, %got(D_10000020)($gp)
/* 00EE84 0040EE84 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EE88 0040EE88 00602825 */  move        $a1, $v1
/* 00EE8C 0040EE8C AFA30010 */  sw          $v1, 0x10($sp)
/* 00EE90 0040EE90 0320F809 */  jalr        $t9
/* 00EE94 0040EE94 AC230020 */   sw         $v1, %lo(D_10000020)($at)
/* 00EE98 0040EE98 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EE9C 0040EE9C 00000000 */  nop
/* 00EEA0 0040EEA0 8F818060 */  lw          $at, %got(D_10000020)($gp)
/* 00EEA4 0040EEA4 100000B1 */  b           .L0040F16C
/* 00EEA8 0040EEA8 AC200020 */   sw         $zero, %lo(D_10000020)($at)
.L0040EEAC:
/* 00EEAC 0040EEAC 8F998018 */  lw          $t9, %got(func_0040E180)($gp)
/* 00EEB0 0040EEB0 8F848050 */  lw          $a0, %got(STR_10006218)($gp)
/* 00EEB4 0040EEB4 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00EEB8 0040EEB8 2739E180 */  addiu       $t9, $t9, %lo(func_0040E180)
/* 00EEBC 0040EEBC 24060001 */  addiu       $a2, $zero, 0x1
/* 00EEC0 0040EEC0 0320F809 */  jalr        $t9
/* 00EEC4 0040EEC4 24846218 */   addiu      $a0, $a0, %lo(STR_10006218)
/* 00EEC8 0040EEC8 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EECC 0040EECC 100000A8 */  b           .L0040F170
/* 00EED0 0040EED0 00001025 */   move       $v0, $zero
.L0040EED4:
/* 00EED4 0040EED4 8FA20034 */  lw          $v0, 0x34($sp)
/* 00EED8 0040EED8 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EEDC 0040EEDC 1440000B */  bnez        $v0, .L0040EF0C
/* 00EEE0 0040EEE0 24030001 */   addiu      $v1, $zero, 0x1
/* 00EEE4 0040EEE4 14A0000A */  bnez        $a1, .L0040EF10
/* 00EEE8 0040EEE8 8FA50038 */   lw         $a1, 0x38($sp)
/* 00EEEC 0040EEEC 8F998018 */  lw          $t9, %got(func_0040E3F0)($gp)
/* 00EEF0 0040EEF0 24050002 */  addiu       $a1, $zero, 0x2
/* 00EEF4 0040EEF4 2739E3F0 */  addiu       $t9, $t9, %lo(func_0040E3F0)
/* 00EEF8 0040EEF8 0320F809 */  jalr        $t9
/* 00EEFC 0040EEFC 24060011 */   addiu      $a2, $zero, 0x11
/* 00EF00 0040EF00 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EF04 0040EF04 1000009A */  b           .L0040F170
/* 00EF08 0040EF08 24020001 */   addiu      $v0, $zero, 0x1
.L0040EF0C:
/* 00EF0C 0040EF0C 8FA50038 */  lw          $a1, 0x38($sp)
.L0040EF10:
/* 00EF10 0040EF10 1443000C */  bne         $v0, $v1, .L0040EF44
/* 00EF14 0040EF14 00000000 */   nop
/* 00EF18 0040EF18 14A0000A */  bnez        $a1, .L0040EF44
/* 00EF1C 0040EF1C 24060003 */   addiu      $a2, $zero, 0x3
/* 00EF20 0040EF20 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EF24 0040EF24 240E0001 */  addiu       $t6, $zero, 0x1
/* 00EF28 0040EF28 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EF2C 0040EF2C AFAE0010 */  sw          $t6, 0x10($sp)
/* 00EF30 0040EF30 0320F809 */  jalr        $t9
/* 00EF34 0040EF34 24050001 */   addiu      $a1, $zero, 0x1
/* 00EF38 0040EF38 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EF3C 0040EF3C 1000008C */  b           .L0040F170
/* 00EF40 0040EF40 24020001 */   addiu      $v0, $zero, 0x1
.L0040EF44:
/* 00EF44 0040EF44 1443000F */  bne         $v0, $v1, .L0040EF84
/* 00EF48 0040EF48 24010003 */   addiu      $at, $zero, 0x3
/* 00EF4C 0040EF4C 14A1000D */  bne         $a1, $at, .L0040EF84
/* 00EF50 0040EF50 24060003 */   addiu      $a2, $zero, 0x3
/* 00EF54 0040EF54 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EF58 0040EF58 8F818060 */  lw          $at, %got(D_10000020)($gp)
/* 00EF5C 0040EF5C 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EF60 0040EF60 00602825 */  move        $a1, $v1
/* 00EF64 0040EF64 AFA30010 */  sw          $v1, 0x10($sp)
/* 00EF68 0040EF68 0320F809 */  jalr        $t9
/* 00EF6C 0040EF6C AC230020 */   sw         $v1, %lo(D_10000020)($at)
/* 00EF70 0040EF70 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EF74 0040EF74 00000000 */  nop
/* 00EF78 0040EF78 8F818060 */  lw          $at, %got(D_10000020)($gp)
/* 00EF7C 0040EF7C 1000007B */  b           .L0040F16C
/* 00EF80 0040EF80 AC200020 */   sw         $zero, %lo(D_10000020)($at)
.L0040EF84:
/* 00EF84 0040EF84 8F998018 */  lw          $t9, %got(func_0040E180)($gp)
/* 00EF88 0040EF88 8F848050 */  lw          $a0, %got(STR_1000624C)($gp)
/* 00EF8C 0040EF8C 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00EF90 0040EF90 2739E180 */  addiu       $t9, $t9, %lo(func_0040E180)
/* 00EF94 0040EF94 24060001 */  addiu       $a2, $zero, 0x1
/* 00EF98 0040EF98 0320F809 */  jalr        $t9
/* 00EF9C 0040EF9C 2484624C */   addiu      $a0, $a0, %lo(STR_1000624C)
/* 00EFA0 0040EFA0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EFA4 0040EFA4 10000072 */  b           .L0040F170
/* 00EFA8 0040EFA8 00001025 */   move       $v0, $zero
.L0040EFAC:
/* 00EFAC 0040EFAC 8FA20034 */  lw          $v0, 0x34($sp)
/* 00EFB0 0040EFB0 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EFB4 0040EFB4 1440000D */  bnez        $v0, .L0040EFEC
/* 00EFB8 0040EFB8 24030001 */   addiu      $v1, $zero, 0x1
/* 00EFBC 0040EFBC 14A0000B */  bnez        $a1, .L0040EFEC
/* 00EFC0 0040EFC0 00003025 */   move       $a2, $zero
/* 00EFC4 0040EFC4 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00EFC8 0040EFC8 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00EFCC 0040EFCC 240F0001 */  addiu       $t7, $zero, 0x1
/* 00EFD0 0040EFD0 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00EFD4 0040EFD4 AFAF0010 */  sw          $t7, 0x10($sp)
/* 00EFD8 0040EFD8 0320F809 */  jalr        $t9
/* 00EFDC 0040EFDC 24050001 */   addiu      $a1, $zero, 0x1
/* 00EFE0 0040EFE0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00EFE4 0040EFE4 10000062 */  b           .L0040F170
/* 00EFE8 0040EFE8 24020001 */   addiu      $v0, $zero, 0x1
.L0040EFEC:
/* 00EFEC 0040EFEC 8FA50038 */  lw          $a1, 0x38($sp)
/* 00EFF0 0040EFF0 14430003 */  bne         $v0, $v1, .L0040F000
/* 00EFF4 0040EFF4 00000000 */   nop
/* 00EFF8 0040EFF8 10A0005C */  beqz        $a1, .L0040F16C
/* 00EFFC 0040EFFC 00000000 */   nop
.L0040F000:
/* 00F000 0040F000 14430002 */  bne         $v0, $v1, .L0040F00C
/* 00F004 0040F004 24010011 */   addiu      $at, $zero, 0x11
/* 00F008 0040F008 10A10058 */  beq         $a1, $at, .L0040F16C
.L0040F00C:
/* 00F00C 0040F00C 2401000E */   addiu      $at, $zero, 0xE
/* 00F010 0040F010 1441000D */  bne         $v0, $at, .L0040F048
/* 00F014 0040F014 24060001 */   addiu      $a2, $zero, 0x1
/* 00F018 0040F018 14A0000B */  bnez        $a1, .L0040F048
/* 00F01C 0040F01C 24180001 */   addiu      $t8, $zero, 0x1
/* 00F020 0040F020 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00F024 0040F024 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00F028 0040F028 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00F02C 0040F02C 24050006 */  addiu       $a1, $zero, 0x6
/* 00F030 0040F030 00003025 */  move        $a2, $zero
/* 00F034 0040F034 0320F809 */  jalr        $t9
/* 00F038 0040F038 AFB80010 */   sw         $t8, 0x10($sp)
/* 00F03C 0040F03C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00F040 0040F040 1000004B */  b           .L0040F170
/* 00F044 0040F044 24020001 */   addiu      $v0, $zero, 0x1
.L0040F048:
/* 00F048 0040F048 8F998018 */  lw          $t9, %got(func_0040E180)($gp)
/* 00F04C 0040F04C 8F848050 */  lw          $a0, %got(STR_10006280)($gp)
/* 00F050 0040F050 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00F054 0040F054 2739E180 */  addiu       $t9, $t9, %lo(func_0040E180)
/* 00F058 0040F058 0320F809 */  jalr        $t9
/* 00F05C 0040F05C 24846280 */   addiu      $a0, $a0, %lo(STR_10006280)
/* 00F060 0040F060 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00F064 0040F064 10000042 */  b           .L0040F170
/* 00F068 0040F068 00001025 */   move       $v0, $zero
.L0040F06C:
/* 00F06C 0040F06C 8FA20034 */  lw          $v0, 0x34($sp)
/* 00F070 0040F070 8FA50038 */  lw          $a1, 0x38($sp)
/* 00F074 0040F074 1440000D */  bnez        $v0, .L0040F0AC
/* 00F078 0040F078 24030001 */   addiu      $v1, $zero, 0x1
/* 00F07C 0040F07C 14A0000B */  bnez        $a1, .L0040F0AC
/* 00F080 0040F080 00003025 */   move       $a2, $zero
/* 00F084 0040F084 24190001 */  addiu       $t9, $zero, 0x1
/* 00F088 0040F088 AFB90010 */  sw          $t9, 0x10($sp)
/* 00F08C 0040F08C 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00F090 0040F090 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00F094 0040F094 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00F098 0040F098 0320F809 */  jalr        $t9
/* 00F09C 0040F09C 2405000E */   addiu      $a1, $zero, 0xE
/* 00F0A0 0040F0A0 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00F0A4 0040F0A4 10000032 */  b           .L0040F170
/* 00F0A8 0040F0A8 24020001 */   addiu      $v0, $zero, 0x1
.L0040F0AC:
/* 00F0AC 0040F0AC 8FA50038 */  lw          $a1, 0x38($sp)
/* 00F0B0 0040F0B0 1443000D */  bne         $v0, $v1, .L0040F0E8
/* 00F0B4 0040F0B4 24060001 */   addiu      $a2, $zero, 0x1
/* 00F0B8 0040F0B8 14A0000B */  bnez        $a1, .L0040F0E8
/* 00F0BC 0040F0BC 24080001 */   addiu      $t0, $zero, 0x1
/* 00F0C0 0040F0C0 8F998018 */  lw          $t9, %got(func_0040E230)($gp)
/* 00F0C4 0040F0C4 8FA7003C */  lw          $a3, 0x3C($sp)
/* 00F0C8 0040F0C8 2739E230 */  addiu       $t9, $t9, %lo(func_0040E230)
/* 00F0CC 0040F0CC 24050006 */  addiu       $a1, $zero, 0x6
/* 00F0D0 0040F0D0 00003025 */  move        $a2, $zero
/* 00F0D4 0040F0D4 0320F809 */  jalr        $t9
/* 00F0D8 0040F0D8 AFA80010 */   sw         $t0, 0x10($sp)
/* 00F0DC 0040F0DC 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00F0E0 0040F0E0 10000023 */  b           .L0040F170
/* 00F0E4 0040F0E4 24020001 */   addiu      $v0, $zero, 0x1
.L0040F0E8:
/* 00F0E8 0040F0E8 8F998018 */  lw          $t9, %got(func_0040E180)($gp)
/* 00F0EC 0040F0EC 8F848050 */  lw          $a0, %got(STR_100062B4)($gp)
/* 00F0F0 0040F0F0 8FA5002C */  lw          $a1, 0x2C($sp)
/* 00F0F4 0040F0F4 2739E180 */  addiu       $t9, $t9, %lo(func_0040E180)
/* 00F0F8 0040F0F8 0320F809 */  jalr        $t9
/* 00F0FC 0040F0FC 248462B4 */   addiu      $a0, $a0, %lo(STR_100062B4)
/* 00F100 0040F100 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00F104 0040F104 1000001A */  b           .L0040F170
/* 00F108 0040F108 00001025 */   move       $v0, $zero
.L0040F10C:
/* 00F10C 0040F10C 8FA20034 */  lw          $v0, 0x34($sp)
/* 00F110 0040F110 8FA50038 */  lw          $a1, 0x38($sp)
/* 00F114 0040F114 14400005 */  bnez        $v0, .L0040F12C
/* 00F118 0040F118 00000000 */   nop
/* 00F11C 0040F11C 14A00003 */  bnez        $a1, .L0040F12C
/* 00F120 0040F120 00000000 */   nop
/* 00F124 0040F124 10000012 */  b           .L0040F170
/* 00F128 0040F128 24020001 */   addiu      $v0, $zero, 0x1
.L0040F12C:
/* 00F12C 0040F12C 8F848050 */  lw          $a0, %got(STR_100062E8)($gp)
/* 00F130 0040F130 8F9981CC */  lw          $t9, %call16(postcerror)($gp)
/* 00F134 0040F134 00002825 */  move        $a1, $zero
/* 00F138 0040F138 0320F809 */  jalr        $t9
/* 00F13C 0040F13C 248462E8 */   addiu      $a0, $a0, %lo(STR_100062E8)
/* 00F140 0040F140 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00F144 0040F144 1000000A */  b           .L0040F170
/* 00F148 0040F148 00001025 */   move       $v0, $zero
.L0040F14C:
/* 00F14C 0040F14C 8F848050 */  lw          $a0, %got(STR_100062F8)($gp)
/* 00F150 0040F150 8F9981CC */  lw          $t9, %call16(postcerror)($gp)
/* 00F154 0040F154 00002825 */  move        $a1, $zero
/* 00F158 0040F158 0320F809 */  jalr        $t9
/* 00F15C 0040F15C 248462F8 */   addiu      $a0, $a0, %lo(STR_100062F8)
/* 00F160 0040F160 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00F164 0040F164 10000002 */  b           .L0040F170
/* 00F168 0040F168 00001025 */   move       $v0, $zero
.L0040F16C:
/* 00F16C 0040F16C 24020001 */  addiu       $v0, $zero, 0x1
.L0040F170:
/* 00F170 0040F170 8FBF0024 */  lw          $ra, 0x24($sp)
/* 00F174 0040F174 27BD0040 */  addiu       $sp, $sp, 0x40
/* 00F178 0040F178 03E00008 */  jr          $ra
/* 00F17C 0040F17C 00000000 */   nop
