/* Generated by spimdisasm 1.10.3 */

glabel xrealloc # 271
# _gp_disp: 0xFBF281C
.set noreorder; .cpload $t9; # .set reorder
/* 01E2B0 0041E2B0 8F9982D8 */  lw          $t9, %call16(alloc_resize)($gp)
/* 01E2B4 0041E2B4 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 01E2B8 0041E2B8 AFBF0024 */  sw          $ra, 0x24($sp)
/* 01E2BC 0041E2BC 8F8683D4 */  lw          $a2, %got(malloc_scb)($gp)
/* 01E2C0 0041E2C0 0320F809 */  jalr        $t9
/* 01E2C4 0041E2C4 AFBC0020 */   sw         $gp, 0x20($sp)
/* 01E2C8 0041E2C8 8FBF0024 */  lw          $ra, 0x24($sp)
/* 01E2CC 0041E2CC 8FBC0020 */  lw          $gp, 0x20($sp)
/* 01E2D0 0041E2D0 03E00008 */  jr          $ra
/* 01E2D4 0041E2D4 27BD0028 */   addiu      $sp, $sp, 0x28
