/* Generated by spimdisasm 1.9.1 */

glabel __start # 2
/* 002D00 00402D00 03E04025 */  move        $t0, $ra
/* 002D04 00402D04 04110001 */  bal         .L00402D0C
/* 002D08 00402D08 00000000 */   nop
.L00402D0C:
# _gp_disp: 0xFC07B14
.set noreorder; .cpload $ra; # .set reorder
/* 002D18 00402D18 0100F825 */  move        $ra, $t0
/* 002D1C 00402D1C 8FA40000 */  lw          $a0, 0x0($sp)
/* 002D20 00402D20 3C010000 */  lui         $at, %got_hi(_environ)
/* 002D24 00402D24 27A50004 */  addiu       $a1, $sp, 0x4
/* 002D28 00402D28 003C0821 */  addu        $at, $at, $gp
/* 002D2C 00402D2C 8C218080 */  lw          $at, %got_lo(_environ)($at)
/* 002D30 00402D30 24A60004 */  addiu       $a2, $a1, 0x4
/* 002D34 00402D34 00041080 */  sll         $v0, $a0, 2
/* 002D38 00402D38 00C23021 */  addu        $a2, $a2, $v0
/* 002D3C 00402D3C AC260000 */  sw          $a2, 0x0($at)
/* 002D40 00402D40 3C010000 */  lui         $at, %got_hi(__Argc)
/* 002D44 00402D44 003C0821 */  addu        $at, $at, $gp
/* 002D48 00402D48 8C218300 */  lw          $at, %got_lo(__Argc)($at)
/* 002D4C 00402D4C 3C190000 */  lui         $t9, %call_hi(__istart)
/* 002D50 00402D50 AC240000 */  sw          $a0, 0x0($at)
/* 002D54 00402D54 3C010000 */  lui         $at, %got_hi(__Argv)
/* 002D58 00402D58 003C0821 */  addu        $at, $at, $gp
/* 002D5C 00402D5C 8C218304 */  lw          $at, %got_lo(__Argv)($at)
/* 002D60 00402D60 033CC821 */  addu        $t9, $t9, $gp
/* 002D64 00402D64 8F398288 */  lw          $t9, %call_lo(__istart)($t9)
/* 002D68 00402D68 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 002D6C 00402D6C AFBC0010 */  sw          $gp, 0x10($sp)
/* 002D70 00402D70 AFA00014 */  sw          $zero, 0x14($sp)
/* 002D74 00402D74 0000F025 */  move        $fp, $zero
/* 002D78 00402D78 0320F809 */  jalr        $t9
/* 002D7C 00402D7C AC250000 */   sw         $a1, 0x0($at)
/* 002D80 00402D80 8FBC0010 */  lw          $gp, 0x10($sp)
/* 002D84 00402D84 3C190000 */  lui         $t9, %call_hi(__readenv_sigfpe)
/* 002D88 00402D88 033CC821 */  addu        $t9, $t9, $gp
/* 002D8C 00402D8C 8F39810C */  lw          $t9, %call_lo(__readenv_sigfpe)($t9)
/* 002D90 00402D90 00000000 */  nop
/* 002D94 00402D94 0320F809 */  jalr        $t9
/* 002D98 00402D98 00000000 */   nop
/* 002D9C 00402D9C 8FBC0010 */  lw          $gp, 0x10($sp)
/* 002DA0 00402DA0 3C040000 */  lui         $a0, %got_hi(__Argc)
/* 002DA4 00402DA4 3C050000 */  lui         $a1, %got_hi(__Argv)
/* 002DA8 00402DA8 3C060000 */  lui         $a2, %got_hi(_environ)
/* 002DAC 00402DAC 3C190000 */  lui         $t9, %call_hi(main)
/* 002DB0 00402DB0 009C2021 */  addu        $a0, $a0, $gp
/* 002DB4 00402DB4 00BC2821 */  addu        $a1, $a1, $gp
/* 002DB8 00402DB8 00DC3021 */  addu        $a2, $a2, $gp
/* 002DBC 00402DBC 8C848300 */  lw          $a0, %got_lo(__Argc)($a0)
/* 002DC0 00402DC0 8CA58304 */  lw          $a1, %got_lo(__Argv)($a1)
/* 002DC4 00402DC4 8CC68080 */  lw          $a2, %got_lo(_environ)($a2)
/* 002DC8 00402DC8 033CC821 */  addu        $t9, $t9, $gp
/* 002DCC 00402DCC 8F398150 */  lw          $t9, %call_lo(main)($t9)
/* 002DD0 00402DD0 8C840000 */  lw          $a0, 0x0($a0)
/* 002DD4 00402DD4 8CA50000 */  lw          $a1, 0x0($a1)
/* 002DD8 00402DD8 8CC60000 */  lw          $a2, 0x0($a2)
/* 002DDC 00402DDC 0320F809 */  jalr        $t9
/* 002DE0 00402DE0 00000000 */   nop
/* 002DE4 00402DE4 8FBC0010 */  lw          $gp, 0x10($sp)
/* 002DE8 00402DE8 3C190000 */  lui         $t9, %call_hi(exit)
/* 002DEC 00402DEC 033CC821 */  addu        $t9, $t9, $gp
/* 002DF0 00402DF0 8F398108 */  lw          $t9, %call_lo(exit)($t9)
/* 002DF4 00402DF4 00402025 */  move        $a0, $v0
/* 002DF8 00402DF8 0320F809 */  jalr        $t9
/* 002DFC 00402DFC 00000000 */   nop
/* 002E00 00402E00 8FBC0010 */  lw          $gp, 0x10($sp)
/* 002E04 00402E04 0000000D */  break       0
