.section .rodata
glabel STR_100014E4
/* 0134E4 100014E4 */ .asciz "#undef has no identifier (no macro name is present)"
                      .balign 4

glabel STR_10001518
/* 013518 10001518 */ .asciz "macro name in #undef starts with an inappropriate character"
                      .balign 4

glabel STR_10001554
/* 013554 10001554 */ .asciz "undefining `%s'"
                      .balign 4

glabel STR_10001564
/* 013564 10001564 */ .asciz "undef"
                      .balign 4

glabel STR_1000156C
/* 01356C 1000156C */ .asciz "text following #undef identifier  violates ANSI standard"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel do_undef # 24
# _gp_disp: 0xFC00B28
.set noreorder; .cpload $t9; # .set reorder
/* 009D04 00409D04 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* 009D08 00409D08 AFB20020 */  sw          $s2, 0x20($sp)
/* 009D0C 00409D0C AFBF002C */  sw          $ra, 0x2C($sp)
/* 009D10 00409D10 AFBC0028 */  sw          $gp, 0x28($sp)
/* 009D14 00409D14 AFB30024 */  sw          $s3, 0x24($sp)
/* 009D18 00409D18 AFB1001C */  sw          $s1, 0x1C($sp)
/* 009D1C 00409D1C AFB00018 */  sw          $s0, 0x18($sp)
/* 009D20 00409D20 AFA60038 */  sw          $a2, 0x38($sp)
/* 009D24 00409D24 AFA7003C */  sw          $a3, 0x3C($sp)
/* 009D28 00409D28 90820000 */  lbu         $v0, 0x0($a0)
/* 009D2C 00409D2C 8F928354 */  lw          $s2, %got(is_hor_space)($gp)
/* 009D30 00409D30 00808825 */  move        $s1, $a0
/* 009D34 00409D34 02427021 */  addu        $t6, $s2, $v0
/* 009D38 00409D38 91CF0000 */  lbu         $t7, 0x0($t6)
/* 009D3C 00409D3C 00A09825 */  move        $s3, $a1
/* 009D40 00409D40 11E00008 */  beqz        $t7, .L00409D64
/* 009D44 00409D44 00000000 */   nop
.L00409D48:
/* 009D48 00409D48 92220001 */  lbu         $v0, 0x1($s1)
/* 009D4C 00409D4C 26310001 */  addiu       $s1, $s1, 0x1
/* 009D50 00409D50 0242C021 */  addu        $t8, $s2, $v0
/* 009D54 00409D54 93190000 */  lbu         $t9, 0x0($t8)
/* 009D58 00409D58 00000000 */  nop
/* 009D5C 00409D5C 1720FFFA */  bnez        $t9, .L00409D48
/* 009D60 00409D60 00000000 */   nop
.L00409D64:
/* 009D64 00409D64 8F888350 */  lw          $t0, %got(is_idstart)($gp)
/* 009D68 00409D68 00000000 */  nop
/* 009D6C 00409D6C 00484821 */  addu        $t1, $v0, $t0
/* 009D70 00409D70 912A0000 */  lbu         $t2, 0x0($t1)
/* 009D74 00409D74 00000000 */  nop
/* 009D78 00409D78 1540001A */  bnez        $t2, .L00409DE4
/* 009D7C 00409D7C 00000000 */   nop
/* 009D80 00409D80 10400003 */  beqz        $v0, .L00409D90
/* 009D84 00409D84 2401000A */   addiu      $at, $zero, 0xA
/* 009D88 00409D88 14410009 */  bne         $v0, $at, .L00409DB0
/* 009D8C 00409D8C 00000000 */   nop
.L00409D90:
/* 009D90 00409D90 8F84804C */  lw          $a0, %got(STR_100014E4)($gp)
/* 009D94 00409D94 8F9981E4 */  lw          $t9, %call16(error)($gp)
/* 009D98 00409D98 248414E4 */  addiu       $a0, $a0, %lo(STR_100014E4)
/* 009D9C 00409D9C 0320F809 */  jalr        $t9
/* 009DA0 00409DA0 00000000 */   nop
/* 009DA4 00409DA4 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009DA8 00409DA8 1000000E */  b           .L00409DE4
/* 009DAC 00409DAC 00000000 */   nop
.L00409DB0:
/* 009DB0 00409DB0 8F8B8328 */  lw          $t3, %got(warnings_off)($gp)
/* 009DB4 00409DB4 00000000 */  nop
/* 009DB8 00409DB8 8D6B0000 */  lw          $t3, 0x0($t3)
/* 009DBC 00409DBC 00000000 */  nop
/* 009DC0 00409DC0 15600008 */  bnez        $t3, .L00409DE4
/* 009DC4 00409DC4 00000000 */   nop
/* 009DC8 00409DC8 8F84804C */  lw          $a0, %got(STR_10001518)($gp)
/* 009DCC 00409DCC 8F9981EC */  lw          $t9, %call16(warning)($gp)
/* 009DD0 00409DD0 24841518 */  addiu       $a0, $a0, %lo(STR_10001518)
/* 009DD4 00409DD4 0320F809 */  jalr        $t9
/* 009DD8 00409DD8 00000000 */   nop
/* 009DDC 00409DDC 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009DE0 00409DE0 00000000 */  nop
.L00409DE4:
/* 009DE4 00409DE4 8F998200 */  lw          $t9, %call16(lookup)($gp)
/* 009DE8 00409DE8 02202025 */  move        $a0, $s1
/* 009DEC 00409DEC 2405FFFF */  addiu       $a1, $zero, -0x1
/* 009DF0 00409DF0 0320F809 */  jalr        $t9
/* 009DF4 00409DF4 2406FFFF */   addiu      $a2, $zero, -0x1
/* 009DF8 00409DF8 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009DFC 00409DFC 10400019 */  beqz        $v0, .L00409E64
/* 009E00 00409E00 00408025 */   move       $s0, $v0
.L00409E04:
/* 009E04 00409E04 8C4C000C */  lw          $t4, 0xC($v0)
/* 009E08 00409E08 24010017 */  addiu       $at, $zero, 0x17
/* 009E0C 00409E0C 11810008 */  beq         $t4, $at, .L00409E30
/* 009E10 00409E10 00000000 */   nop
/* 009E14 00409E14 8F84804C */  lw          $a0, %got(STR_10001554)($gp)
/* 009E18 00409E18 8F9981E4 */  lw          $t9, %call16(error)($gp)
/* 009E1C 00409E1C 8E050014 */  lw          $a1, 0x14($s0)
/* 009E20 00409E20 0320F809 */  jalr        $t9
/* 009E24 00409E24 24841554 */   addiu      $a0, $a0, %lo(STR_10001554)
/* 009E28 00409E28 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009E2C 00409E2C 00000000 */  nop
.L00409E30:
/* 009E30 00409E30 8F998204 */  lw          $t9, %call16(delete_macro)($gp)
/* 009E34 00409E34 02002025 */  move        $a0, $s0
/* 009E38 00409E38 0320F809 */  jalr        $t9
/* 009E3C 00409E3C 00000000 */   nop
/* 009E40 00409E40 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009E44 00409E44 02202025 */  move        $a0, $s1
/* 009E48 00409E48 8F998200 */  lw          $t9, %call16(lookup)($gp)
/* 009E4C 00409E4C 2405FFFF */  addiu       $a1, $zero, -0x1
/* 009E50 00409E50 0320F809 */  jalr        $t9
/* 009E54 00409E54 2406FFFF */   addiu      $a2, $zero, -0x1
/* 009E58 00409E58 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009E5C 00409E5C 1440FFE9 */  bnez        $v0, .L00409E04
/* 009E60 00409E60 00408025 */   move       $s0, $v0
.L00409E64:
/* 009E64 00409E64 8F82834C */  lw          $v0, %got(is_idchar)($gp)
/* 009E68 00409E68 922D0000 */  lbu         $t5, 0x0($s1)
/* 009E6C 00409E6C 8FA40038 */  lw          $a0, 0x38($sp)
/* 009E70 00409E70 004D7021 */  addu        $t6, $v0, $t5
/* 009E74 00409E74 91CF0000 */  lbu         $t7, 0x0($t6)
/* 009E78 00409E78 02203025 */  move        $a2, $s1
/* 009E7C 00409E7C 11E0000C */  beqz        $t7, .L00409EB0
/* 009E80 00409E80 0233082B */   sltu       $at, $s1, $s3
/* 009E84 00409E84 1020000A */  beqz        $at, .L00409EB0
/* 009E88 00409E88 00000000 */   nop
.L00409E8C:
/* 009E8C 00409E8C 92380001 */  lbu         $t8, 0x1($s1)
/* 009E90 00409E90 26310001 */  addiu       $s1, $s1, 0x1
/* 009E94 00409E94 0058C821 */  addu        $t9, $v0, $t8
/* 009E98 00409E98 93280000 */  lbu         $t0, 0x0($t9)
/* 009E9C 00409E9C 0233082B */  sltu        $at, $s1, $s3
/* 009EA0 00409EA0 11000003 */  beqz        $t0, .L00409EB0
/* 009EA4 00409EA4 00000000 */   nop
/* 009EA8 00409EA8 1420FFF8 */  bnez        $at, .L00409E8C
/* 009EAC 00409EAC 00000000 */   nop
.L00409EB0:
/* 009EB0 00409EB0 8F89832C */  lw          $t1, %got(showdefines)($gp)
/* 009EB4 00409EB4 02263823 */  subu        $a3, $s1, $a2
/* 009EB8 00409EB8 8D290000 */  lw          $t1, 0x0($t1)
/* 009EBC 00409EBC 00000000 */  nop
/* 009EC0 00409EC0 11200008 */  beqz        $t1, .L00409EE4
/* 009EC4 00409EC4 00000000 */   nop
/* 009EC8 00409EC8 8F998014 */  lw          $t9, %got(func_00404734)($gp)
/* 009ECC 00409ECC 8F85804C */  lw          $a1, %got(STR_10001564)($gp)
/* 009ED0 00409ED0 27394734 */  addiu       $t9, $t9, %lo(func_00404734)
/* 009ED4 00409ED4 0320F809 */  jalr        $t9
/* 009ED8 00409ED8 24A51564 */   addiu      $a1, $a1, %lo(STR_10001564)
/* 009EDC 00409EDC 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009EE0 00409EE0 00000000 */  nop
.L00409EE4:
/* 009EE4 00409EE4 8F8A8324 */  lw          $t2, %got(pedantic)($gp)
/* 009EE8 00409EE8 00000000 */  nop
/* 009EEC 00409EEC 8D4A0000 */  lw          $t2, 0x0($t2)
/* 009EF0 00409EF0 00000000 */  nop
/* 009EF4 00409EF4 1140001F */  beqz        $t2, .L00409F74
/* 009EF8 00409EF8 8FBF002C */   lw         $ra, 0x2C($sp)
/* 009EFC 00409EFC 92220000 */  lbu         $v0, 0x0($s1)
/* 009F00 00409F00 00000000 */  nop
/* 009F04 00409F04 02425821 */  addu        $t3, $s2, $v0
/* 009F08 00409F08 916C0000 */  lbu         $t4, 0x0($t3)
/* 009F0C 00409F0C 00000000 */  nop
/* 009F10 00409F10 11800008 */  beqz        $t4, .L00409F34
/* 009F14 00409F14 00000000 */   nop
.L00409F18:
/* 009F18 00409F18 922D0001 */  lbu         $t5, 0x1($s1)
/* 009F1C 00409F1C 26310001 */  addiu       $s1, $s1, 0x1
/* 009F20 00409F20 024D7021 */  addu        $t6, $s2, $t5
/* 009F24 00409F24 91CF0000 */  lbu         $t7, 0x0($t6)
/* 009F28 00409F28 00000000 */  nop
/* 009F2C 00409F2C 15E0FFFA */  bnez        $t7, .L00409F18
/* 009F30 00409F30 00000000 */   nop
.L00409F34:
/* 009F34 00409F34 1233000F */  beq         $s1, $s3, .L00409F74
/* 009F38 00409F38 8FBF002C */   lw         $ra, 0x2C($sp)
/* 009F3C 00409F3C 8F988328 */  lw          $t8, %got(warnings_off)($gp)
/* 009F40 00409F40 00000000 */  nop
/* 009F44 00409F44 8F180000 */  lw          $t8, 0x0($t8)
/* 009F48 00409F48 00000000 */  nop
/* 009F4C 00409F4C 17000009 */  bnez        $t8, .L00409F74
/* 009F50 00409F50 8FBF002C */   lw         $ra, 0x2C($sp)
/* 009F54 00409F54 8F84804C */  lw          $a0, %got(STR_1000156C)($gp)
/* 009F58 00409F58 8F9981EC */  lw          $t9, %call16(warning)($gp)
/* 009F5C 00409F5C 2484156C */  addiu       $a0, $a0, %lo(STR_1000156C)
/* 009F60 00409F60 0320F809 */  jalr        $t9
/* 009F64 00409F64 00000000 */   nop
/* 009F68 00409F68 8FBC0028 */  lw          $gp, 0x28($sp)
/* 009F6C 00409F6C 00000000 */  nop
/* 009F70 00409F70 8FBF002C */  lw          $ra, 0x2C($sp)
.L00409F74:
/* 009F74 00409F74 8FB00018 */  lw          $s0, 0x18($sp)
/* 009F78 00409F78 8FB1001C */  lw          $s1, 0x1C($sp)
/* 009F7C 00409F7C 8FB20020 */  lw          $s2, 0x20($sp)
/* 009F80 00409F80 8FB30024 */  lw          $s3, 0x24($sp)
/* 009F84 00409F84 03E00008 */  jr          $ra
/* 009F88 00409F88 27BD0030 */   addiu      $sp, $sp, 0x30
