/* Generated by spimdisasm 1.9.1 */

glabel file_size_and_mode # 75
# _gp_disp: 0xFBFB764
.set noreorder; .cpload $t9; # .set reorder
/* 00F0C8 0040F0C8 27BDFF58 */  addiu       $sp, $sp, -0xA8
/* 00F0CC 0040F0CC 8F998140 */  lw          $t9, %call16(fstat)($gp)
/* 00F0D0 0040F0D0 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00F0D4 0040F0D4 AFA500AC */  sw          $a1, 0xAC($sp)
/* 00F0D8 0040F0D8 AFBC0018 */  sw          $gp, 0x18($sp)
/* 00F0DC 0040F0DC AFA600B0 */  sw          $a2, 0xB0($sp)
/* 00F0E0 0040F0E0 0320F809 */  jalr        $t9
/* 00F0E4 0040F0E4 27A50020 */   addiu      $a1, $sp, 0x20
/* 00F0E8 0040F0E8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F0EC 0040F0EC 8FA300AC */  lw          $v1, 0xAC($sp)
/* 00F0F0 0040F0F0 8FA400B0 */  lw          $a0, 0xB0($sp)
/* 00F0F4 0040F0F4 04410003 */  bgez        $v0, .L0040F104
/* 00F0F8 0040F0F8 00000000 */   nop
/* 00F0FC 0040F0FC 1000000B */  b           .L0040F12C
/* 00F100 0040F100 2402FFFF */   addiu      $v0, $zero, -0x1
.L0040F104:
/* 00F104 0040F104 10600004 */  beqz        $v1, .L0040F118
/* 00F108 0040F108 00001025 */   move       $v0, $zero
/* 00F10C 0040F10C 8FAE0034 */  lw          $t6, 0x34($sp)
/* 00F110 0040F110 00000000 */  nop
/* 00F114 0040F114 AC6E0000 */  sw          $t6, 0x0($v1)
.L0040F118:
/* 00F118 0040F118 10800004 */  beqz        $a0, .L0040F12C
/* 00F11C 0040F11C 00000000 */   nop
/* 00F120 0040F120 8FAF0050 */  lw          $t7, 0x50($sp)
/* 00F124 0040F124 00000000 */  nop
/* 00F128 0040F128 AC8F0000 */  sw          $t7, 0x0($a0)
.L0040F12C:
/* 00F12C 0040F12C 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00F130 0040F130 27BD00A8 */  addiu       $sp, $sp, 0xA8
/* 00F134 0040F134 03E00008 */  jr          $ra
/* 00F138 0040F138 00000000 */   nop
/* 00F13C 0040F13C 00000000 */  nop
/* 00F140 0040F140 00000000 */  nop
/* 00F144 0040F144 00000000 */  nop
