/* Generated by spimdisasm 1.9.1 */

glabel lookup # 53
# _gp_disp: 0xFBFC98C
.set noreorder; .cpload $t9; # .set reorder
/* 00DEA0 0040DEA0 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 00DEA4 0040DEA4 AFB2001C */  sw          $s2, 0x1C($sp)
/* 00DEA8 0040DEA8 AFB10018 */  sw          $s1, 0x18($sp)
/* 00DEAC 0040DEAC 00A08825 */  move        $s1, $a1
/* 00DEB0 0040DEB0 00809025 */  move        $s2, $a0
/* 00DEB4 0040DEB4 AFBF0024 */  sw          $ra, 0x24($sp)
/* 00DEB8 0040DEB8 AFBC0020 */  sw          $gp, 0x20($sp)
/* 00DEBC 0040DEBC 04A10011 */  bgez        $a1, .L0040DF04
/* 00DEC0 0040DEC0 AFB00014 */   sw         $s0, 0x14($sp)
/* 00DEC4 0040DEC4 8F83834C */  lw          $v1, %got(is_idchar)($gp)
/* 00DEC8 0040DEC8 908E0000 */  lbu         $t6, 0x0($a0)
/* 00DECC 0040DECC 00801025 */  move        $v0, $a0
/* 00DED0 0040DED0 006E7821 */  addu        $t7, $v1, $t6
/* 00DED4 0040DED4 91F80000 */  lbu         $t8, 0x0($t7)
/* 00DED8 0040DED8 00000000 */  nop
/* 00DEDC 0040DEDC 13000009 */  beqz        $t8, .L0040DF04
/* 00DEE0 0040DEE0 00528823 */   subu       $s1, $v0, $s2
.L0040DEE4:
/* 00DEE4 0040DEE4 90590001 */  lbu         $t9, 0x1($v0)
/* 00DEE8 0040DEE8 24420001 */  addiu       $v0, $v0, 0x1
/* 00DEEC 0040DEEC 00794021 */  addu        $t0, $v1, $t9
/* 00DEF0 0040DEF0 91090000 */  lbu         $t1, 0x0($t0)
/* 00DEF4 0040DEF4 00000000 */  nop
/* 00DEF8 0040DEF8 1520FFFA */  bnez        $t1, .L0040DEE4
/* 00DEFC 0040DEFC 00000000 */   nop
/* 00DF00 0040DF00 00528823 */  subu        $s1, $v0, $s2
.L0040DF04:
/* 00DF04 0040DF04 04C10007 */  bgez        $a2, .L0040DF24
/* 00DF08 0040DF08 02402025 */   move       $a0, $s2
/* 00DF0C 0040DF0C 8F998208 */  lw          $t9, %call16(hashf)($gp)
/* 00DF10 0040DF10 02202825 */  move        $a1, $s1
/* 00DF14 0040DF14 0320F809 */  jalr        $t9
/* 00DF18 0040DF18 2406057B */   addiu      $a2, $zero, 0x57B
/* 00DF1C 0040DF1C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DF20 0040DF20 00403025 */  move        $a2, $v0
.L0040DF24:
/* 00DF24 0040DF24 8F8B8348 */  lw          $t3, %got(hashtab)($gp)
/* 00DF28 0040DF28 00065080 */  sll         $t2, $a2, 2
/* 00DF2C 0040DF2C 014B6021 */  addu        $t4, $t2, $t3
/* 00DF30 0040DF30 8D900000 */  lw          $s0, 0x0($t4)
/* 00DF34 0040DF34 00000000 */  nop
/* 00DF38 0040DF38 12000013 */  beqz        $s0, .L0040DF88
/* 00DF3C 0040DF3C 00001025 */   move       $v0, $zero
.L0040DF40:
/* 00DF40 0040DF40 8E0D0010 */  lw          $t5, 0x10($s0)
/* 00DF44 0040DF44 02402825 */  move        $a1, $s2
/* 00DF48 0040DF48 162D000A */  bne         $s1, $t5, .L0040DF74
/* 00DF4C 0040DF4C 00000000 */   nop
/* 00DF50 0040DF50 8F998090 */  lw          $t9, %call16(strncmp)($gp)
/* 00DF54 0040DF54 8E040014 */  lw          $a0, 0x14($s0)
/* 00DF58 0040DF58 0320F809 */  jalr        $t9
/* 00DF5C 0040DF5C 02203025 */   move       $a2, $s1
/* 00DF60 0040DF60 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DF64 0040DF64 14400003 */  bnez        $v0, .L0040DF74
/* 00DF68 0040DF68 00000000 */   nop
/* 00DF6C 0040DF6C 10000006 */  b           .L0040DF88
/* 00DF70 0040DF70 02001025 */   move       $v0, $s0
.L0040DF74:
/* 00DF74 0040DF74 8E100000 */  lw          $s0, 0x0($s0)
/* 00DF78 0040DF78 00000000 */  nop
/* 00DF7C 0040DF7C 1600FFF0 */  bnez        $s0, .L0040DF40
/* 00DF80 0040DF80 00000000 */   nop
/* 00DF84 0040DF84 00001025 */  move        $v0, $zero
.L0040DF88:
/* 00DF88 0040DF88 8FBF0024 */  lw          $ra, 0x24($sp)
/* 00DF8C 0040DF8C 8FB00014 */  lw          $s0, 0x14($sp)
/* 00DF90 0040DF90 8FB10018 */  lw          $s1, 0x18($sp)
/* 00DF94 0040DF94 8FB2001C */  lw          $s2, 0x1C($sp)
/* 00DF98 0040DF98 03E00008 */  jr          $ra
/* 00DF9C 0040DF9C 27BD0028 */   addiu      $sp, $sp, 0x28
