.section .rodata
glabel STR_100018F4
/* 0138F4 100018F4 */ .asciz "unterminated macro call"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel macarg # 43
# _gp_disp: 0xFBFDDBC
.set noreorder; .cpload $t9; # .set reorder
/* 00CA70 0040CA70 27BDFF48 */  addiu       $sp, $sp, -0xB8
/* 00CA74 0040CA74 AFB60038 */  sw          $s6, 0x38($sp)
/* 00CA78 0040CA78 8F96829C */  lw          $s6, %got(indepth)($gp)
/* 00CA7C 0040CA7C 8F988340 */  lw          $t8, %got(instack)($gp)
/* 00CA80 0040CA80 8ECE0000 */  lw          $t6, 0x0($s6)
/* 00CA84 0040CA84 AFB40030 */  sw          $s4, 0x30($sp)
/* 00CA88 0040CA88 000E78C0 */  sll         $t7, $t6, 3
/* 00CA8C 0040CA8C 01EE7821 */  addu        $t7, $t7, $t6
/* 00CA90 0040CA90 000F7880 */  sll         $t7, $t7, 2
/* 00CA94 0040CA94 AFBF0044 */  sw          $ra, 0x44($sp)
/* 00CA98 0040CA98 AFBC0040 */  sw          $gp, 0x40($sp)
/* 00CA9C 0040CA9C AFB7003C */  sw          $s7, 0x3C($sp)
/* 00CAA0 0040CAA0 AFB50034 */  sw          $s5, 0x34($sp)
/* 00CAA4 0040CAA4 AFB3002C */  sw          $s3, 0x2C($sp)
/* 00CAA8 0040CAA8 AFB20028 */  sw          $s2, 0x28($sp)
/* 00CAAC 0040CAAC AFB10024 */  sw          $s1, 0x24($sp)
/* 00CAB0 0040CAB0 AFB00020 */  sw          $s0, 0x20($sp)
/* 00CAB4 0040CAB4 AFA000B0 */  sw          $zero, 0xB0($sp)
/* 00CAB8 0040CAB8 AFA000AC */  sw          $zero, 0xAC($sp)
/* 00CABC 0040CABC AFA000A8 */  sw          $zero, 0xA8($sp)
/* 00CAC0 0040CAC0 01F8A021 */  addu        $s4, $t7, $t8
/* 00CAC4 0040CAC4 8E990010 */  lw          $t9, 0x10($s4)
/* 00CAC8 0040CAC8 8E8B0008 */  lw          $t3, 0x8($s4)
/* 00CACC 0040CACC 0080B825 */  move        $s7, $a0
/* 00CAD0 0040CAD0 032B2821 */  addu        $a1, $t9, $t3
/* 00CAD4 0040CAD4 8F9981DC */  lw          $t9, %call16(macarg1)($gp)
/* 00CAD8 0040CAD8 8E840014 */  lw          $a0, 0x14($s4)
/* 00CADC 0040CADC 27AC00A8 */  addiu       $t4, $sp, 0xA8
/* 00CAE0 0040CAE0 AFAC0010 */  sw          $t4, 0x10($sp)
/* 00CAE4 0040CAE4 27A600B0 */  addiu       $a2, $sp, 0xB0
/* 00CAE8 0040CAE8 0320F809 */  jalr        $t9
/* 00CAEC 0040CAEC 27A700AC */   addiu      $a3, $sp, 0xAC
/* 00CAF0 0040CAF0 8E8D0000 */  lw          $t5, 0x0($s4)
/* 00CAF4 0040CAF4 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CAF8 0040CAF8 11A00007 */  beqz        $t5, .L0040CB18
/* 00CAFC 0040CAFC 00409025 */   move       $s2, $v0
/* 00CB00 0040CB00 8FAE00AC */  lw          $t6, 0xAC($sp)
/* 00CB04 0040CB04 8FAF00A8 */  lw          $t7, 0xA8($sp)
/* 00CB08 0040CB08 15C00014 */  bnez        $t6, .L0040CB5C
/* 00CB0C 0040CB0C 00000000 */   nop
/* 00CB10 0040CB10 15E00012 */  bnez        $t7, .L0040CB5C
/* 00CB14 0040CB14 00000000 */   nop
.L0040CB18:
/* 00CB18 0040CB18 8E980010 */  lw          $t8, 0x10($s4)
/* 00CB1C 0040CB1C 8E990008 */  lw          $t9, 0x8($s4)
/* 00CB20 0040CB20 00000000 */  nop
/* 00CB24 0040CB24 03195821 */  addu        $t3, $t8, $t9
/* 00CB28 0040CB28 104B000C */  beq         $v0, $t3, .L0040CB5C
/* 00CB2C 0040CB2C 00000000 */   nop
/* 00CB30 0040CB30 12E00008 */  beqz        $s7, .L0040CB54
/* 00CB34 0040CB34 00000000 */   nop
/* 00CB38 0040CB38 8E8C0014 */  lw          $t4, 0x14($s4)
/* 00CB3C 0040CB3C 00000000 */  nop
/* 00CB40 0040CB40 AEEC0000 */  sw          $t4, 0x0($s7)
/* 00CB44 0040CB44 8E8D0014 */  lw          $t5, 0x14($s4)
/* 00CB48 0040CB48 00000000 */  nop
/* 00CB4C 0040CB4C 004D7023 */  subu        $t6, $v0, $t5
/* 00CB50 0040CB50 AEEE0008 */  sw          $t6, 0x8($s7)
.L0040CB54:
/* 00CB54 0040CB54 1000009A */  b           .L0040CDC0
/* 00CB58 0040CB58 AE820014 */   sw         $v0, 0x14($s4)
.L0040CB5C:
/* 00CB5C 0040CB5C 8E8F0014 */  lw          $t7, 0x14($s4)
/* 00CB60 0040CB60 8FB300AC */  lw          $s3, 0xAC($sp)
/* 00CB64 0040CB64 8F998248 */  lw          $t9, %call16(xmalloc)($gp)
/* 00CB68 0040CB68 024F8823 */  subu        $s1, $s2, $t7
/* 00CB6C 0040CB6C 02332021 */  addu        $a0, $s1, $s3
/* 00CB70 0040CB70 0320F809 */  jalr        $t9
/* 00CB74 0040CB74 24840001 */   addiu      $a0, $a0, 0x1
/* 00CB78 0040CB78 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CB7C 0040CB7C AFA00094 */  sw          $zero, 0x94($sp)
/* 00CB80 0040CB80 8F998230 */  lw          $t9, %call16(bcopy)($gp)
/* 00CB84 0040CB84 8E840014 */  lw          $a0, 0x14($s4)
/* 00CB88 0040CB88 0040A825 */  move        $s5, $v0
/* 00CB8C 0040CB8C 00402825 */  move        $a1, $v0
/* 00CB90 0040CB90 0320F809 */  jalr        $t9
/* 00CB94 0040CB94 02203025 */   move       $a2, $s1
/* 00CB98 0040CB98 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CB9C 0040CB9C AE920014 */  sw          $s2, 0x14($s4)
/* 00CBA0 0040CBA0 8FAB00AC */  lw          $t3, 0xAC($sp)
/* 00CBA4 0040CBA4 8E990004 */  lw          $t9, 0x4($s4)
/* 00CBA8 0040CBA8 8E8D0010 */  lw          $t5, 0x10($s4)
/* 00CBAC 0040CBAC 8E8E0008 */  lw          $t6, 0x8($s4)
/* 00CBB0 0040CBB0 032B6021 */  addu        $t4, $t9, $t3
/* 00CBB4 0040CBB4 01AE7821 */  addu        $t7, $t5, $t6
/* 00CBB8 0040CBB8 164F0051 */  bne         $s2, $t7, .L0040CD00
/* 00CBBC 0040CBBC AE8C0004 */   sw         $t4, 0x4($s4)
.L0040CBC0:
/* 00CBC0 0040CBC0 8ED80000 */  lw          $t8, 0x0($s6)
/* 00CBC4 0040CBC4 8F8B8340 */  lw          $t3, %got(instack)($gp)
/* 00CBC8 0040CBC8 0018C8C0 */  sll         $t9, $t8, 3
/* 00CBCC 0040CBCC 0338C821 */  addu        $t9, $t9, $t8
/* 00CBD0 0040CBD0 0019C880 */  sll         $t9, $t9, 2
/* 00CBD4 0040CBD4 032B6021 */  addu        $t4, $t9, $t3
/* 00CBD8 0040CBD8 8D8D0018 */  lw          $t5, 0x18($t4)
/* 00CBDC 0040CBDC 00000000 */  nop
/* 00CBE0 0040CBE0 15A0000A */  bnez        $t5, .L0040CC0C
/* 00CBE4 0040CBE4 00000000 */   nop
/* 00CBE8 0040CBE8 8F99808C */  lw          $t9, %call16(free)($gp)
/* 00CBEC 0040CBEC 02A02025 */  move        $a0, $s5
/* 00CBF0 0040CBF0 0320F809 */  jalr        $t9
/* 00CBF4 0040CBF4 00000000 */   nop
/* 00CBF8 0040CBF8 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CBFC 0040CBFC 00000000 */  nop
/* 00CC00 0040CC00 8F82804C */  lw          $v0, %got(STR_100018F4)($gp)
/* 00CC04 0040CC04 100000F0 */  b           .L0040CFC8
/* 00CC08 0040CC08 244218F4 */   addiu      $v0, $v0, %lo(STR_100018F4)
.L0040CC0C:
/* 00CC0C 0040CC0C 8E8F0018 */  lw          $t7, 0x18($s4)
/* 00CC10 0040CC10 240E0017 */  addiu       $t6, $zero, 0x17
/* 00CC14 0040CC14 ADEE000C */  sw          $t6, 0xC($t7)
/* 00CC18 0040CC18 8F99808C */  lw          $t9, %call16(free)($gp)
/* 00CC1C 0040CC1C 8E840010 */  lw          $a0, 0x10($s4)
/* 00CC20 0040CC20 0320F809 */  jalr        $t9
/* 00CC24 0040CC24 00000000 */   nop
/* 00CC28 0040CC28 8EC30000 */  lw          $v1, 0x0($s6)
/* 00CC2C 0040CC2C 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CC30 0040CC30 2463FFFF */  addiu       $v1, $v1, -0x1
/* 00CC34 0040CC34 0003C0C0 */  sll         $t8, $v1, 3
/* 00CC38 0040CC38 8F998340 */  lw          $t9, %got(instack)($gp)
/* 00CC3C 0040CC3C 0303C021 */  addu        $t8, $t8, $v1
/* 00CC40 0040CC40 0018C080 */  sll         $t8, $t8, 2
/* 00CC44 0040CC44 03198021 */  addu        $s0, $t8, $t9
/* 00CC48 0040CC48 AEC30000 */  sw          $v1, 0x0($s6)
/* 00CC4C 0040CC4C 8E0B0010 */  lw          $t3, 0x10($s0)
/* 00CC50 0040CC50 8E0C0008 */  lw          $t4, 0x8($s0)
/* 00CC54 0040CC54 8F9981DC */  lw          $t9, %call16(macarg1)($gp)
/* 00CC58 0040CC58 8E040014 */  lw          $a0, 0x14($s0)
/* 00CC5C 0040CC5C 27AD00A8 */  addiu       $t5, $sp, 0xA8
/* 00CC60 0040CC60 0200A025 */  move        $s4, $s0
/* 00CC64 0040CC64 AFA000AC */  sw          $zero, 0xAC($sp)
/* 00CC68 0040CC68 AFA000A8 */  sw          $zero, 0xA8($sp)
/* 00CC6C 0040CC6C AFAD0010 */  sw          $t5, 0x10($sp)
/* 00CC70 0040CC70 27A600B0 */  addiu       $a2, $sp, 0xB0
/* 00CC74 0040CC74 27A700AC */  addiu       $a3, $sp, 0xAC
/* 00CC78 0040CC78 0320F809 */  jalr        $t9
/* 00CC7C 0040CC7C 016C2821 */   addu       $a1, $t3, $t4
/* 00CC80 0040CC80 8E0E0014 */  lw          $t6, 0x14($s0)
/* 00CC84 0040CC84 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CC88 0040CC88 8FB800AC */  lw          $t8, 0xAC($sp)
/* 00CC8C 0040CC8C AFB10094 */  sw          $s1, 0x94($sp)
/* 00CC90 0040CC90 004E7823 */  subu        $t7, $v0, $t6
/* 00CC94 0040CC94 8F99824C */  lw          $t9, %call16(xrealloc)($gp)
/* 00CC98 0040CC98 022F8821 */  addu        $s1, $s1, $t7
/* 00CC9C 0040CC9C 02789821 */  addu        $s3, $s3, $t8
/* 00CCA0 0040CCA0 02332821 */  addu        $a1, $s1, $s3
/* 00CCA4 0040CCA4 00409025 */  move        $s2, $v0
/* 00CCA8 0040CCA8 24A50001 */  addiu       $a1, $a1, 0x1
/* 00CCAC 0040CCAC 0320F809 */  jalr        $t9
/* 00CCB0 0040CCB0 02A02025 */   move       $a0, $s5
/* 00CCB4 0040CCB4 8E040014 */  lw          $a0, 0x14($s0)
/* 00CCB8 0040CCB8 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CCBC 0040CCBC 0051C821 */  addu        $t9, $v0, $s1
/* 00CCC0 0040CCC0 02443023 */  subu        $a2, $s2, $a0
/* 00CCC4 0040CCC4 03262823 */  subu        $a1, $t9, $a2
/* 00CCC8 0040CCC8 8F998230 */  lw          $t9, %call16(bcopy)($gp)
/* 00CCCC 0040CCCC 0040A825 */  move        $s5, $v0
/* 00CCD0 0040CCD0 0320F809 */  jalr        $t9
/* 00CCD4 0040CCD4 00000000 */   nop
/* 00CCD8 0040CCD8 8E0B0004 */  lw          $t3, 0x4($s0)
/* 00CCDC 0040CCDC 8FAC00AC */  lw          $t4, 0xAC($sp)
/* 00CCE0 0040CCE0 8E0E0010 */  lw          $t6, 0x10($s0)
/* 00CCE4 0040CCE4 8E0F0008 */  lw          $t7, 0x8($s0)
/* 00CCE8 0040CCE8 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CCEC 0040CCEC 016C6821 */  addu        $t5, $t3, $t4
/* 00CCF0 0040CCF0 01CFC021 */  addu        $t8, $t6, $t7
/* 00CCF4 0040CCF4 AE120014 */  sw          $s2, 0x14($s0)
/* 00CCF8 0040CCF8 1258FFB1 */  beq         $s2, $t8, .L0040CBC0
/* 00CCFC 0040CCFC AE0D0004 */   sw         $t5, 0x4($s0)
.L0040CD00:
/* 00CD00 0040CD00 12E0002F */  beqz        $s7, .L0040CDC0
/* 00CD04 0040CD04 00000000 */   nop
/* 00CD08 0040CD08 AEF50000 */  sw          $s5, 0x0($s7)
/* 00CD0C 0040CD0C AEF10008 */  sw          $s1, 0x8($s7)
/* 00CD10 0040CD10 AEF50014 */  sw          $s5, 0x14($s7)
/* 00CD14 0040CD14 8FB900AC */  lw          $t9, 0xAC($sp)
/* 00CD18 0040CD18 02338021 */  addu        $s0, $s1, $s3
/* 00CD1C 0040CD1C A2F9001C */  sb          $t9, 0x1C($s7)
/* 00CD20 0040CD20 8FAB00A8 */  lw          $t3, 0xA8($sp)
/* 00CD24 0040CD24 00000000 */  nop
/* 00CD28 0040CD28 A2EB001D */  sb          $t3, 0x1D($s7)
/* 00CD2C 0040CD2C 8FAC00AC */  lw          $t4, 0xAC($sp)
/* 00CD30 0040CD30 8FAD00A8 */  lw          $t5, 0xA8($sp)
/* 00CD34 0040CD34 15800003 */  bnez        $t4, .L0040CD44
/* 00CD38 0040CD38 00000000 */   nop
/* 00CD3C 0040CD3C 11A00010 */  beqz        $t5, .L0040CD80
/* 00CD40 0040CD40 00000000 */   nop
.L0040CD44:
/* 00CD44 0040CD44 8E8E0000 */  lw          $t6, 0x0($s4)
/* 00CD48 0040CD48 8FB80094 */  lw          $t8, 0x94($sp)
/* 00CD4C 0040CD4C 11C0000C */  beqz        $t6, .L0040CD80
/* 00CD50 0040CD50 00000000 */   nop
/* 00CD54 0040CD54 8EF90008 */  lw          $t9, 0x8($s7)
/* 00CD58 0040CD58 8EEF0000 */  lw          $t7, 0x0($s7)
/* 00CD5C 0040CD5C 03382823 */  subu        $a1, $t9, $t8
/* 00CD60 0040CD60 8F9981E0 */  lw          $t9, %call16(discard_comments)($gp)
/* 00CD64 0040CD64 8FA600AC */  lw          $a2, 0xAC($sp)
/* 00CD68 0040CD68 0320F809 */  jalr        $t9
/* 00CD6C 0040CD6C 01F82021 */   addu       $a0, $t7, $t8
/* 00CD70 0040CD70 8FAC0094 */  lw          $t4, 0x94($sp)
/* 00CD74 0040CD74 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CD78 0040CD78 004C6821 */  addu        $t5, $v0, $t4
/* 00CD7C 0040CD7C AEED0008 */  sw          $t5, 0x8($s7)
.L0040CD80:
/* 00CD80 0040CD80 8EEE0000 */  lw          $t6, 0x0($s7)
/* 00CD84 0040CD84 8EEF0008 */  lw          $t7, 0x8($s7)
/* 00CD88 0040CD88 00000000 */  nop
/* 00CD8C 0040CD8C 01CFC021 */  addu        $t8, $t6, $t7
/* 00CD90 0040CD90 A3000000 */  sb          $zero, 0x0($t8)
/* 00CD94 0040CD94 8EF90008 */  lw          $t9, 0x8($s7)
/* 00CD98 0040CD98 00000000 */  nop
/* 00CD9C 0040CD9C 0219082A */  slt         $at, $s0, $t9
/* 00CDA0 0040CDA0 10200007 */  beqz        $at, .L0040CDC0
/* 00CDA4 0040CDA4 00000000 */   nop
/* 00CDA8 0040CDA8 8F9980E0 */  lw          $t9, %call16(abort)($gp)
/* 00CDAC 0040CDAC 00000000 */  nop
/* 00CDB0 0040CDB0 0320F809 */  jalr        $t9
/* 00CDB4 0040CDB4 00000000 */   nop
/* 00CDB8 0040CDB8 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CDBC 0040CDBC 00000000 */  nop
.L0040CDC0:
/* 00CDC0 0040CDC0 12E00080 */  beqz        $s7, .L0040CFC4
/* 00CDC4 0040CDC4 00008825 */   move       $s1, $zero
/* 00CDC8 0040CDC8 8EE50000 */  lw          $a1, 0x0($s7)
/* 00CDCC 0040CDCC 8EEB0008 */  lw          $t3, 0x8($s7)
/* 00CDD0 0040CDD0 8F998164 */  lw          $t9, %call16(expand_to_temp_buffer)($gp)
/* 00CDD4 0040CDD4 00008025 */  move        $s0, $zero
/* 00CDD8 0040CDD8 27A40070 */  addiu       $a0, $sp, 0x70
/* 00CDDC 0040CDDC 24070001 */  addiu       $a3, $zero, 0x1
/* 00CDE0 0040CDE0 0320F809 */  jalr        $t9
/* 00CDE4 0040CDE4 00AB3021 */   addu       $a2, $a1, $t3
/* 00CDE8 0040CDE8 8FAC0080 */  lw          $t4, 0x80($sp)
/* 00CDEC 0040CDEC 8FBC0040 */  lw          $gp, 0x40($sp)
/* 00CDF0 0040CDF0 AEEC0004 */  sw          $t4, 0x4($s7)
/* 00CDF4 0040CDF4 8FAD0078 */  lw          $t5, 0x78($sp)
/* 00CDF8 0040CDF8 8EE30000 */  lw          $v1, 0x0($s7)
/* 00CDFC 0040CDFC 8EEF0008 */  lw          $t7, 0x8($s7)
/* 00CE00 0040CE00 AEED000C */  sw          $t5, 0xC($s7)
/* 00CE04 0040CE04 8FAE0080 */  lw          $t6, 0x80($sp)
/* 00CE08 0040CE08 01E33021 */  addu        $a2, $t7, $v1
/* 00CE0C 0040CE0C 10660013 */  beq         $v1, $a2, .L0040CE5C
/* 00CE10 0040CE10 AEEE0018 */   sw         $t6, 0x18($s7)
/* 00CE14 0040CE14 8F848358 */  lw          $a0, %got(is_space)($gp)
/* 00CE18 0040CE18 90780000 */  lbu         $t8, 0x0($v1)
/* 00CE1C 0040CE1C 00000000 */  nop
/* 00CE20 0040CE20 0098C821 */  addu        $t9, $a0, $t8
/* 00CE24 0040CE24 932B0000 */  lbu         $t3, 0x0($t9)
/* 00CE28 0040CE28 00000000 */  nop
/* 00CE2C 0040CE2C 1160000B */  beqz        $t3, .L0040CE5C
/* 00CE30 0040CE30 00000000 */   nop
.L0040CE34:
/* 00CE34 0040CE34 24630001 */  addiu       $v1, $v1, 0x1
/* 00CE38 0040CE38 10660008 */  beq         $v1, $a2, .L0040CE5C
/* 00CE3C 0040CE3C 00000000 */   nop
/* 00CE40 0040CE40 906C0000 */  lbu         $t4, 0x0($v1)
/* 00CE44 0040CE44 00000000 */  nop
/* 00CE48 0040CE48 008C6821 */  addu        $t5, $a0, $t4
/* 00CE4C 0040CE4C 91AE0000 */  lbu         $t6, 0x0($t5)
/* 00CE50 0040CE50 00000000 */  nop
/* 00CE54 0040CE54 15C0FFF7 */  bnez        $t6, .L0040CE34
/* 00CE58 0040CE58 00000000 */   nop
.L0040CE5C:
/* 00CE5C 0040CE5C 8F848358 */  lw          $a0, %got(is_space)($gp)
/* 00CE60 0040CE60 10660012 */  beq         $v1, $a2, .L0040CEAC
/* 00CE64 0040CE64 24050002 */   addiu      $a1, $zero, 0x2
/* 00CE68 0040CE68 90CFFFFF */  lbu         $t7, -0x1($a2)
/* 00CE6C 0040CE6C 00000000 */  nop
/* 00CE70 0040CE70 008FC021 */  addu        $t8, $a0, $t7
/* 00CE74 0040CE74 93190000 */  lbu         $t9, 0x0($t8)
/* 00CE78 0040CE78 00000000 */  nop
/* 00CE7C 0040CE7C 1320000B */  beqz        $t9, .L0040CEAC
/* 00CE80 0040CE80 00000000 */   nop
.L0040CE84:
/* 00CE84 0040CE84 24C6FFFF */  addiu       $a2, $a2, -0x1
/* 00CE88 0040CE88 10660008 */  beq         $v1, $a2, .L0040CEAC
/* 00CE8C 0040CE8C 00000000 */   nop
/* 00CE90 0040CE90 90CBFFFF */  lbu         $t3, -0x1($a2)
/* 00CE94 0040CE94 00000000 */  nop
/* 00CE98 0040CE98 008B6021 */  addu        $t4, $a0, $t3
/* 00CE9C 0040CE9C 918D0000 */  lbu         $t5, 0x0($t4)
/* 00CEA0 0040CEA0 00000000 */  nop
/* 00CEA4 0040CEA4 15A0FFF7 */  bnez        $t5, .L0040CE84
/* 00CEA8 0040CEA8 00000000 */   nop
.L0040CEAC:
/* 00CEAC 0040CEAC 8F8E8338 */  lw          $t6, %got(traditional)($gp)
/* 00CEB0 0040CEB0 240A0027 */  addiu       $t2, $zero, 0x27
/* 00CEB4 0040CEB4 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00CEB8 0040CEB8 2408005C */  addiu       $t0, $zero, 0x5C
/* 00CEBC 0040CEBC 11C00003 */  beqz        $t6, .L0040CECC
/* 00CEC0 0040CEC0 00000000 */   nop
/* 00CEC4 0040CEC4 10000001 */  b           .L0040CECC
/* 00CEC8 0040CEC8 00002825 */   move       $a1, $zero
.L0040CECC:
/* 00CECC 0040CECC 1066003C */  beq         $v1, $a2, .L0040CFC0
/* 00CED0 0040CED0 00000000 */   nop
/* 00CED4 0040CED4 8F898084 */  lw          $t1, %got(__ctype)($gp)
/* 00CED8 0040CED8 24070022 */  addiu       $a3, $zero, 0x22
.L0040CEDC:
/* 00CEDC 0040CEDC 90620000 */  lbu         $v0, 0x0($v1)
/* 00CEE0 0040CEE0 24630001 */  addiu       $v1, $v1, 0x1
/* 00CEE4 0040CEE4 12200003 */  beqz        $s1, .L0040CEF4
/* 00CEE8 0040CEE8 24A50001 */   addiu      $a1, $a1, 0x1
/* 00CEEC 0040CEEC 1000000F */  b           .L0040CF2C
/* 00CEF0 0040CEF0 00008825 */   move       $s1, $zero
.L0040CEF4:
/* 00CEF4 0040CEF4 14480002 */  bne         $v0, $t0, .L0040CF00
/* 00CEF8 0040CEF8 00000000 */   nop
/* 00CEFC 0040CEFC 24110001 */  addiu       $s1, $zero, 0x1
.L0040CF00:
/* 00CF00 0040CF00 12000005 */  beqz        $s0, .L0040CF18
/* 00CF04 0040CF04 00000000 */   nop
/* 00CF08 0040CF08 14500003 */  bne         $v0, $s0, .L0040CF18
/* 00CF0C 0040CF0C 00000000 */   nop
/* 00CF10 0040CF10 10000006 */  b           .L0040CF2C
/* 00CF14 0040CF14 00008025 */   move       $s0, $zero
.L0040CF18:
/* 00CF18 0040CF18 10470003 */  beq         $v0, $a3, .L0040CF28
/* 00CF1C 0040CF1C 00000000 */   nop
/* 00CF20 0040CF20 144A0003 */  bne         $v0, $t2, .L0040CF30
/* 00CF24 0040CF24 00827821 */   addu       $t7, $a0, $v0
.L0040CF28:
/* 00CF28 0040CF28 00408025 */  move        $s0, $v0
.L0040CF2C:
/* 00CF2C 0040CF2C 00827821 */  addu        $t7, $a0, $v0
.L0040CF30:
/* 00CF30 0040CF30 91F80000 */  lbu         $t8, 0x0($t7)
/* 00CF34 0040CF34 00000000 */  nop
/* 00CF38 0040CF38 13000013 */  beqz        $t8, .L0040CF88
/* 00CF3C 0040CF3C 00000000 */   nop
/* 00CF40 0040CF40 16000011 */  bnez        $s0, .L0040CF88
/* 00CF44 0040CF44 00000000 */   nop
/* 00CF48 0040CF48 90790000 */  lbu         $t9, 0x0($v1)
/* 00CF4C 0040CF4C 00000000 */  nop
/* 00CF50 0040CF50 00995821 */  addu        $t3, $a0, $t9
/* 00CF54 0040CF54 916C0000 */  lbu         $t4, 0x0($t3)
/* 00CF58 0040CF58 00000000 */  nop
/* 00CF5C 0040CF5C 11800016 */  beqz        $t4, .L0040CFB8
/* 00CF60 0040CF60 00000000 */   nop
.L0040CF64:
/* 00CF64 0040CF64 906D0001 */  lbu         $t5, 0x1($v1)
/* 00CF68 0040CF68 24630001 */  addiu       $v1, $v1, 0x1
/* 00CF6C 0040CF6C 008D7021 */  addu        $t6, $a0, $t5
/* 00CF70 0040CF70 91CF0000 */  lbu         $t7, 0x0($t6)
/* 00CF74 0040CF74 00000000 */  nop
/* 00CF78 0040CF78 15E0FFFA */  bnez        $t7, .L0040CF64
/* 00CF7C 0040CF7C 00000000 */   nop
/* 00CF80 0040CF80 1000000D */  b           .L0040CFB8
/* 00CF84 0040CF84 00000000 */   nop
.L0040CF88:
/* 00CF88 0040CF88 10470003 */  beq         $v0, $a3, .L0040CF98
/* 00CF8C 0040CF8C 00000000 */   nop
/* 00CF90 0040CF90 14480003 */  bne         $v0, $t0, .L0040CFA0
/* 00CF94 0040CF94 0122C021 */   addu       $t8, $t1, $v0
.L0040CF98:
/* 00CF98 0040CF98 10000007 */  b           .L0040CFB8
/* 00CF9C 0040CF9C 24A50001 */   addiu      $a1, $a1, 0x1
.L0040CFA0:
/* 00CFA0 0040CFA0 93190001 */  lbu         $t9, 0x1($t8)
/* 00CFA4 0040CFA4 00000000 */  nop
/* 00CFA8 0040CFA8 332B0057 */  andi        $t3, $t9, 0x57
/* 00CFAC 0040CFAC 15600002 */  bnez        $t3, .L0040CFB8
/* 00CFB0 0040CFB0 00000000 */   nop
/* 00CFB4 0040CFB4 24A50003 */  addiu       $a1, $a1, 0x3
.L0040CFB8:
/* 00CFB8 0040CFB8 1466FFC8 */  bne         $v1, $a2, .L0040CEDC
/* 00CFBC 0040CFBC 00000000 */   nop
.L0040CFC0:
/* 00CFC0 0040CFC0 AEE50010 */  sw          $a1, 0x10($s7)
.L0040CFC4:
/* 00CFC4 0040CFC4 00001025 */  move        $v0, $zero
.L0040CFC8:
/* 00CFC8 0040CFC8 8FBF0044 */  lw          $ra, 0x44($sp)
/* 00CFCC 0040CFCC 8FB00020 */  lw          $s0, 0x20($sp)
/* 00CFD0 0040CFD0 8FB10024 */  lw          $s1, 0x24($sp)
/* 00CFD4 0040CFD4 8FB20028 */  lw          $s2, 0x28($sp)
/* 00CFD8 0040CFD8 8FB3002C */  lw          $s3, 0x2C($sp)
/* 00CFDC 0040CFDC 8FB40030 */  lw          $s4, 0x30($sp)
/* 00CFE0 0040CFE0 8FB50034 */  lw          $s5, 0x34($sp)
/* 00CFE4 0040CFE4 8FB60038 */  lw          $s6, 0x38($sp)
/* 00CFE8 0040CFE8 8FB7003C */  lw          $s7, 0x3C($sp)
/* 00CFEC 0040CFEC 03E00008 */  jr          $ra
/* 00CFF0 0040CFF0 27BD00B8 */   addiu      $sp, $sp, 0xB8
