.section .rodata
glabel STR_10001A7C
/* 013A7C 10001A7C */ .asciz " 1"
                      .balign 4

glabel STR_10001A80
/* 013A80 10001A80 */ .asciz "*Initialization*"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel make_definition # 61
# _gp_disp: 0xFBFBF98
.set noreorder; .cpload $t9; # .set reorder
/* 00E894 0040E894 27BDFFC8 */  addiu       $sp, $sp, -0x38
/* 00E898 0040E898 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00E89C 0040E89C AFBC0018 */  sw          $gp, 0x18($sp)
/* 00E8A0 0040E8A0 AFB00014 */  sw          $s0, 0x14($sp)
/* 00E8A4 0040E8A4 8F83834C */  lw          $v1, %got(is_idchar)($gp)
/* 00E8A8 0040E8A8 908E0000 */  lbu         $t6, 0x0($a0)
/* 00E8AC 0040E8AC 00802825 */  move        $a1, $a0
/* 00E8B0 0040E8B0 006E7821 */  addu        $t7, $v1, $t6
/* 00E8B4 0040E8B4 91F80000 */  lbu         $t8, 0x0($t7)
/* 00E8B8 0040E8B8 00808025 */  move        $s0, $a0
/* 00E8BC 0040E8BC 13000008 */  beqz        $t8, .L0040E8E0
/* 00E8C0 0040E8C0 00801025 */   move       $v0, $a0
.L0040E8C4:
/* 00E8C4 0040E8C4 90590001 */  lbu         $t9, 0x1($v0)
/* 00E8C8 0040E8C8 24420001 */  addiu       $v0, $v0, 0x1
/* 00E8CC 0040E8CC 00794021 */  addu        $t0, $v1, $t9
/* 00E8D0 0040E8D0 91090000 */  lbu         $t1, 0x0($t0)
/* 00E8D4 0040E8D4 00000000 */  nop
/* 00E8D8 0040E8D8 1520FFFA */  bnez        $t1, .L0040E8C4
/* 00E8DC 0040E8DC 00000000 */   nop
.L0040E8E0:
/* 00E8E0 0040E8E0 904A0000 */  lbu         $t2, 0x0($v0)
/* 00E8E4 0040E8E4 00452023 */  subu        $a0, $v0, $a1
/* 00E8E8 0040E8E8 15400014 */  bnez        $t2, .L0040E93C
/* 00E8EC 0040E8EC 00000000 */   nop
/* 00E8F0 0040E8F0 8F998148 */  lw          $t9, %call16(alloca)($gp)
/* 00E8F4 0040E8F4 24840004 */  addiu       $a0, $a0, 0x4
/* 00E8F8 0040E8F8 0320F809 */  jalr        $t9
/* 00E8FC 0040E8FC AFA50038 */   sw         $a1, 0x38($sp)
/* 00E900 0040E900 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00E904 0040E904 8FA50038 */  lw          $a1, 0x38($sp)
/* 00E908 0040E908 8F9980C4 */  lw          $t9, %call16(strcpy)($gp)
/* 00E90C 0040E90C 00408025 */  move        $s0, $v0
/* 00E910 0040E910 0320F809 */  jalr        $t9
/* 00E914 0040E914 00402025 */   move       $a0, $v0
/* 00E918 0040E918 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00E91C 0040E91C 02002025 */  move        $a0, $s0
/* 00E920 0040E920 8F85804C */  lw          $a1, %got(STR_10001A7C)($gp)
/* 00E924 0040E924 8F9980C0 */  lw          $t9, %call16(strcat)($gp)
/* 00E928 0040E928 24A51A7C */  addiu       $a1, $a1, %lo(STR_10001A7C)
/* 00E92C 0040E92C 0320F809 */  jalr        $t9
/* 00E930 0040E930 00000000 */   nop
/* 00E934 0040E934 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00E938 0040E938 00000000 */  nop
.L0040E93C:
/* 00E93C 0040E93C 8F83829C */  lw          $v1, %got(indepth)($gp)
/* 00E940 0040E940 8F8C8340 */  lw          $t4, %got(instack)($gp)
/* 00E944 0040E944 8C620000 */  lw          $v0, 0x0($v1)
/* 00E948 0040E948 8F8D804C */  lw          $t5, %got(STR_10001A80)($gp)
/* 00E94C 0040E94C 24420001 */  addiu       $v0, $v0, 0x1
/* 00E950 0040E950 000258C0 */  sll         $t3, $v0, 3
/* 00E954 0040E954 01625821 */  addu        $t3, $t3, $v0
/* 00E958 0040E958 000B5880 */  sll         $t3, $t3, 2
/* 00E95C 0040E95C 016C2821 */  addu        $a1, $t3, $t4
/* 00E960 0040E960 25AD1A80 */  addiu       $t5, $t5, %lo(STR_10001A80)
/* 00E964 0040E964 ACAD0000 */  sw          $t5, 0x0($a1)
/* 00E968 0040E968 ACB00014 */  sw          $s0, 0x14($a1)
/* 00E96C 0040E96C ACB00010 */  sw          $s0, 0x10($a1)
/* 00E970 0040E970 AC620000 */  sw          $v0, 0x0($v1)
/* 00E974 0040E974 8F9980E4 */  lw          $t9, %call16(strlen)($gp)
/* 00E978 0040E978 AFA50020 */  sw          $a1, 0x20($sp)
/* 00E97C 0040E97C 0320F809 */  jalr        $t9
/* 00E980 0040E980 02002025 */   move       $a0, $s0
/* 00E984 0040E984 8FA50020 */  lw          $a1, 0x20($sp)
/* 00E988 0040E988 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00E98C 0040E98C 24030001 */  addiu       $v1, $zero, 0x1
/* 00E990 0040E990 8F8E82D0 */  lw          $t6, %got(if_stack)($gp)
/* 00E994 0040E994 ACA20008 */  sw          $v0, 0x8($a1)
/* 00E998 0040E998 ACA30004 */  sw          $v1, 0x4($a1)
/* 00E99C 0040E99C ACA00018 */  sw          $zero, 0x18($a1)
/* 00E9A0 0040E9A0 ACA00020 */  sw          $zero, 0x20($a1)
/* 00E9A4 0040E9A4 8DCE0000 */  lw          $t6, 0x0($t6)
/* 00E9A8 0040E9A8 8F8782C4 */  lw          $a3, %got(directive_table)($gp)
/* 00E9AC 0040E9AC ACAE001C */  sw          $t6, 0x1C($a1)
/* 00E9B0 0040E9B0 8CEF000C */  lw          $t7, 0xC($a3)
/* 00E9B4 0040E9B4 00000000 */  nop
/* 00E9B8 0040E9B8 106F0005 */  beq         $v1, $t7, .L0040E9D0
/* 00E9BC 0040E9BC 00000000 */   nop
.L0040E9C0:
/* 00E9C0 0040E9C0 8CF80020 */  lw          $t8, 0x20($a3)
/* 00E9C4 0040E9C4 24E70014 */  addiu       $a3, $a3, 0x14
/* 00E9C8 0040E9C8 1478FFFD */  bne         $v1, $t8, .L0040E9C0
/* 00E9CC 0040E9CC 00000000 */   nop
.L0040E9D0:
/* 00E9D0 0040E9D0 8F9980E4 */  lw          $t9, %call16(strlen)($gp)
/* 00E9D4 0040E9D4 02002025 */  move        $a0, $s0
/* 00E9D8 0040E9D8 0320F809 */  jalr        $t9
/* 00E9DC 0040E9DC AFA70030 */   sw         $a3, 0x30($sp)
/* 00E9E0 0040E9E0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00E9E4 0040E9E4 8FA70030 */  lw          $a3, 0x30($sp)
/* 00E9E8 0040E9E8 8F998178 */  lw          $t9, %call16(do_define)($gp)
/* 00E9EC 0040E9EC 02002025 */  move        $a0, $s0
/* 00E9F0 0040E9F0 00502821 */  addu        $a1, $v0, $s0
/* 00E9F4 0040E9F4 0320F809 */  jalr        $t9
/* 00E9F8 0040E9F8 00003025 */   move       $a2, $zero
/* 00E9FC 0040E9FC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00EA00 0040EA00 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00EA04 0040EA04 8F83829C */  lw          $v1, %got(indepth)($gp)
/* 00EA08 0040EA08 8FB00014 */  lw          $s0, 0x14($sp)
/* 00EA0C 0040EA0C 8C790000 */  lw          $t9, 0x0($v1)
/* 00EA10 0040EA10 27BD0038 */  addiu       $sp, $sp, 0x38
/* 00EA14 0040EA14 2728FFFF */  addiu       $t0, $t9, -0x1
/* 00EA18 0040EA18 03E00008 */  jr          $ra
/* 00EA1C 0040EA1C AC680000 */   sw         $t0, 0x0($v1)
