.section .rodata
glabel STR_100021F0
/* 0141F0 100021F0 */ .asciz "floating point numbers not allowed in #if expressions"
                      .balign 4

glabel STR_10002228
/* 014228 10002228 */ .asciz "0x"
                      .balign 4

glabel STR_1000222C
/* 01422C 1000222C */ .asciz "0X"
                      .balign 4

glabel STR_10002230
/* 014230 10002230 */ .asciz "Invalid number in #if expression"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel parse_number # 76
# _gp_disp: 0xFBFB6D8
.set noreorder; .cpload $t9; # .set reorder
/* 00F154 0040F154 27BDFFC8 */  addiu       $sp, $sp, -0x38
/* 00F158 0040F158 AFB00014 */  sw          $s0, 0x14($sp)
/* 00F15C 0040F15C 8F90805C */  lw          $s0, %got(B_10002CF0)($gp)
/* 00F160 0040F160 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00F164 0040F164 8E102CF0 */  lw          $s0, %lo(B_10002CF0)($s0)
/* 00F168 0040F168 AFBC0018 */  sw          $gp, 0x18($sp)
/* 00F16C 0040F16C AFA40038 */  sw          $a0, 0x38($sp)
/* 00F170 0040F170 00003825 */  move        $a3, $zero
/* 00F174 0040F174 2409000A */  addiu       $t1, $zero, 0xA
/* 00F178 0040F178 00804025 */  move        $t0, $a0
/* 00F17C 0040F17C 18800011 */  blez        $a0, .L0040F1C4
/* 00F180 0040F180 00001025 */   move       $v0, $zero
/* 00F184 0040F184 02001825 */  move        $v1, $s0
/* 00F188 0040F188 2404002E */  addiu       $a0, $zero, 0x2E
.L0040F18C:
/* 00F18C 0040F18C 906F0000 */  lbu         $t7, 0x0($v1)
/* 00F190 0040F190 24420001 */  addiu       $v0, $v0, 0x1
/* 00F194 0040F194 148F0009 */  bne         $a0, $t7, .L0040F1BC
/* 00F198 0040F198 0048082A */   slt        $at, $v0, $t0
/* 00F19C 0040F19C 8F84804C */  lw          $a0, %got(STR_100021F0)($gp)
/* 00F1A0 0040F1A0 8F998268 */  lw          $t9, %call16(yyerror)($gp)
/* 00F1A4 0040F1A4 248421F0 */  addiu       $a0, $a0, %lo(STR_100021F0)
/* 00F1A8 0040F1A8 0320F809 */  jalr        $t9
/* 00F1AC 0040F1AC 00000000 */   nop
/* 00F1B0 0040F1B0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F1B4 0040F1B4 10000078 */  b           .L0040F398
/* 00F1B8 0040F1B8 24020104 */   addiu      $v0, $zero, 0x104
.L0040F1BC:
/* 00F1BC 0040F1BC 1420FFF3 */  bnez        $at, .L0040F18C
/* 00F1C0 0040F1C0 24630001 */   addiu      $v1, $v1, 0x1
.L0040F1C4:
/* 00F1C4 0040F1C4 8FB80038 */  lw          $t8, 0x38($sp)
/* 00F1C8 0040F1C8 8F8A8374 */  lw          $t2, %got(yylval)($gp)
/* 00F1CC 0040F1CC 2B010003 */  slti        $at, $t8, 0x3
/* 00F1D0 0040F1D0 14200025 */  bnez        $at, .L0040F268
/* 00F1D4 0040F1D4 AD400004 */   sw         $zero, 0x4($t2)
/* 00F1D8 0040F1D8 8F85804C */  lw          $a1, %got(STR_10002228)($gp)
/* 00F1DC 0040F1DC 8F998090 */  lw          $t9, %call16(strncmp)($gp)
/* 00F1E0 0040F1E0 02002025 */  move        $a0, $s0
/* 00F1E4 0040F1E4 24060002 */  addiu       $a2, $zero, 0x2
/* 00F1E8 0040F1E8 AFA70030 */  sw          $a3, 0x30($sp)
/* 00F1EC 0040F1EC AFA80024 */  sw          $t0, 0x24($sp)
/* 00F1F0 0040F1F0 AFA90028 */  sw          $t1, 0x28($sp)
/* 00F1F4 0040F1F4 0320F809 */  jalr        $t9
/* 00F1F8 0040F1F8 24A52228 */   addiu      $a1, $a1, %lo(STR_10002228)
/* 00F1FC 0040F1FC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F200 0040F200 8FA70030 */  lw          $a3, 0x30($sp)
/* 00F204 0040F204 8FA80024 */  lw          $t0, 0x24($sp)
/* 00F208 0040F208 8FA90028 */  lw          $t1, 0x28($sp)
/* 00F20C 0040F20C 8F8A8374 */  lw          $t2, %got(yylval)($gp)
/* 00F210 0040F210 10400010 */  beqz        $v0, .L0040F254
/* 00F214 0040F214 02002025 */   move       $a0, $s0
/* 00F218 0040F218 8F85804C */  lw          $a1, %got(STR_1000222C)($gp)
/* 00F21C 0040F21C 8F998090 */  lw          $t9, %call16(strncmp)($gp)
/* 00F220 0040F220 24060002 */  addiu       $a2, $zero, 0x2
/* 00F224 0040F224 AFA70030 */  sw          $a3, 0x30($sp)
/* 00F228 0040F228 AFA80024 */  sw          $t0, 0x24($sp)
/* 00F22C 0040F22C AFA90028 */  sw          $t1, 0x28($sp)
/* 00F230 0040F230 0320F809 */  jalr        $t9
/* 00F234 0040F234 24A5222C */   addiu      $a1, $a1, %lo(STR_1000222C)
/* 00F238 0040F238 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F23C 0040F23C 8FA70030 */  lw          $a3, 0x30($sp)
/* 00F240 0040F240 8FA80024 */  lw          $t0, 0x24($sp)
/* 00F244 0040F244 8FA90028 */  lw          $t1, 0x28($sp)
/* 00F248 0040F248 8F8A8374 */  lw          $t2, %got(yylval)($gp)
/* 00F24C 0040F24C 14400006 */  bnez        $v0, .L0040F268
/* 00F250 0040F250 00000000 */   nop
.L0040F254:
/* 00F254 0040F254 8FA80038 */  lw          $t0, 0x38($sp)
/* 00F258 0040F258 26100002 */  addiu       $s0, $s0, 0x2
/* 00F25C 0040F25C 24090010 */  addiu       $t1, $zero, 0x10
/* 00F260 0040F260 10000006 */  b           .L0040F27C
/* 00F264 0040F264 2508FFFE */   addiu      $t0, $t0, -0x2
.L0040F268:
/* 00F268 0040F268 92190000 */  lbu         $t9, 0x0($s0)
/* 00F26C 0040F26C 24010030 */  addiu       $at, $zero, 0x30
/* 00F270 0040F270 17210002 */  bne         $t9, $at, .L0040F27C
/* 00F274 0040F274 00000000 */   nop
/* 00F278 0040F278 24090008 */  addiu       $t1, $zero, 0x8
.L0040F27C:
/* 00F27C 0040F27C 19000035 */  blez        $t0, .L0040F354
/* 00F280 0040F280 24030010 */   addiu      $v1, $zero, 0x10
.L0040F284:
/* 00F284 0040F284 92020000 */  lbu         $v0, 0x0($s0)
/* 00F288 0040F288 26100001 */  addiu       $s0, $s0, 0x1
/* 00F28C 0040F28C 28410041 */  slti        $at, $v0, 0x41
/* 00F290 0040F290 14200005 */  bnez        $at, .L0040F2A8
/* 00F294 0040F294 2508FFFF */   addiu      $t0, $t0, -0x1
/* 00F298 0040F298 2841005B */  slti        $at, $v0, 0x5B
/* 00F29C 0040F29C 10200003 */  beqz        $at, .L0040F2AC
/* 00F2A0 0040F2A0 28410030 */   slti       $at, $v0, 0x30
/* 00F2A4 0040F2A4 24420020 */  addiu       $v0, $v0, 0x20
.L0040F2A8:
/* 00F2A8 0040F2A8 28410030 */  slti        $at, $v0, 0x30
.L0040F2AC:
/* 00F2AC 0040F2AC 14200008 */  bnez        $at, .L0040F2D0
/* 00F2B0 0040F2B0 2841003A */   slti       $at, $v0, 0x3A
/* 00F2B4 0040F2B4 10200006 */  beqz        $at, .L0040F2D0
/* 00F2B8 0040F2B8 00000000 */   nop
/* 00F2BC 0040F2BC 00E90019 */  multu       $a3, $t1
/* 00F2C0 0040F2C0 00003812 */  mflo        $a3
/* 00F2C4 0040F2C4 00E23821 */  addu        $a3, $a3, $v0
/* 00F2C8 0040F2C8 10000020 */  b           .L0040F34C
/* 00F2CC 0040F2CC 24E7FFD0 */   addiu      $a3, $a3, -0x30
.L0040F2D0:
/* 00F2D0 0040F2D0 1523000A */  bne         $t1, $v1, .L0040F2FC
/* 00F2D4 0040F2D4 28410061 */   slti       $at, $v0, 0x61
/* 00F2D8 0040F2D8 14200008 */  bnez        $at, .L0040F2FC
/* 00F2DC 0040F2DC 28410067 */   slti       $at, $v0, 0x67
/* 00F2E0 0040F2E0 10200006 */  beqz        $at, .L0040F2FC
/* 00F2E4 0040F2E4 00000000 */   nop
/* 00F2E8 0040F2E8 00E90019 */  multu       $a3, $t1
/* 00F2EC 0040F2EC 00003812 */  mflo        $a3
/* 00F2F0 0040F2F0 00E23821 */  addu        $a3, $a3, $v0
/* 00F2F4 0040F2F4 10000015 */  b           .L0040F34C
/* 00F2F8 0040F2F8 24E7FFA9 */   addiu      $a3, $a3, -0x57
.L0040F2FC:
/* 00F2FC 0040F2FC 24090001 */  addiu       $t1, $zero, 0x1
/* 00F300 0040F300 24060055 */  addiu       $a2, $zero, 0x55
/* 00F304 0040F304 24050075 */  addiu       $a1, $zero, 0x75
/* 00F308 0040F308 2404004C */  addiu       $a0, $zero, 0x4C
/* 00F30C 0040F30C 2403006C */  addiu       $v1, $zero, 0x6C
.L0040F310:
/* 00F310 0040F310 10430008 */  beq         $v0, $v1, .L0040F334
/* 00F314 0040F314 00000000 */   nop
/* 00F318 0040F318 10440006 */  beq         $v0, $a0, .L0040F334
/* 00F31C 0040F31C 00000000 */   nop
/* 00F320 0040F320 10450003 */  beq         $v0, $a1, .L0040F330
/* 00F324 0040F324 00000000 */   nop
/* 00F328 0040F328 1446000A */  bne         $v0, $a2, .L0040F354
/* 00F32C 0040F32C 00000000 */   nop
.L0040F330:
/* 00F330 0040F330 AD490004 */  sw          $t1, 0x4($t2)
.L0040F334:
/* 00F334 0040F334 11000007 */  beqz        $t0, .L0040F354
/* 00F338 0040F338 00000000 */   nop
/* 00F33C 0040F33C 92020000 */  lbu         $v0, 0x0($s0)
/* 00F340 0040F340 26100001 */  addiu       $s0, $s0, 0x1
/* 00F344 0040F344 1000FFF2 */  b           .L0040F310
/* 00F348 0040F348 2508FFFF */   addiu      $t0, $t0, -0x1
.L0040F34C:
/* 00F34C 0040F34C 1D00FFCD */  bgtz        $t0, .L0040F284
/* 00F350 0040F350 00000000 */   nop
.L0040F354:
/* 00F354 0040F354 11000009 */  beqz        $t0, .L0040F37C
/* 00F358 0040F358 24090001 */   addiu      $t1, $zero, 0x1
/* 00F35C 0040F35C 8F84804C */  lw          $a0, %got(STR_10002230)($gp)
/* 00F360 0040F360 8F998268 */  lw          $t9, %call16(yyerror)($gp)
/* 00F364 0040F364 24842230 */  addiu       $a0, $a0, %lo(STR_10002230)
/* 00F368 0040F368 0320F809 */  jalr        $t9
/* 00F36C 0040F36C 00000000 */   nop
/* 00F370 0040F370 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F374 0040F374 10000008 */  b           .L0040F398
/* 00F378 0040F378 24020104 */   addiu      $v0, $zero, 0x104
.L0040F37C:
/* 00F37C 0040F37C 04E10002 */  bgez        $a3, .L0040F388
/* 00F380 0040F380 00000000 */   nop
/* 00F384 0040F384 AD490004 */  sw          $t1, 0x4($t2)
.L0040F388:
/* 00F388 0040F388 8F81805C */  lw          $at, %got(B_10002CF0)($gp)
/* 00F38C 0040F38C 24020101 */  addiu       $v0, $zero, 0x101
/* 00F390 0040F390 AC302CF0 */  sw          $s0, %lo(B_10002CF0)($at)
/* 00F394 0040F394 AD470000 */  sw          $a3, 0x0($t2)
.L0040F398:
/* 00F398 0040F398 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00F39C 0040F39C 8FB00014 */  lw          $s0, 0x14($sp)
/* 00F3A0 0040F3A0 03E00008 */  jr          $ra
/* 00F3A4 0040F3A4 27BD0038 */   addiu      $sp, $sp, 0x38
