.section .rodata
glabel STR_10002300
/* 014300 10002300 */ .asciz "octal character constant does not fit in a byte"
                      .balign 4

glabel STR_10002330
/* 014330 10002330 */ .asciz "hex character constant does not fit in a byte"
                      .balign 4

.section .late_rodata
glabel jtbl_10002580
/* 014580 10002580 F0405044 */ .gpword .L0040F864
/* 014584 10002584 F04051E0 */ .gpword .L0040FA00
/* 014588 10002588 F04051E0 */ .gpword .L0040FA00
/* 01458C 1000258C F0404FE8 */ .gpword .L0040F808
/* 014590 10002590 F0404FF0 */ .gpword .L0040F810
/* 014594 10002594 F04051E0 */ .gpword .L0040FA00
/* 014598 10002598 F04051E0 */ .gpword .L0040FA00
/* 01459C 1000259C F0404FF8 */ .gpword .L0040F818
/* 0145A0 100025A0 F0405000 */ .gpword .L0040F820
/* 0145A4 100025A4 F04051E0 */ .gpword .L0040FA00
/* 0145A8 100025A8 F04051E0 */ .gpword .L0040FA00
/* 0145AC 100025AC F04051E0 */ .gpword .L0040FA00
/* 0145B0 100025B0 F04051E0 */ .gpword .L0040FA00
/* 0145B4 100025B4 F04051E0 */ .gpword .L0040FA00
/* 0145B8 100025B8 F04051E0 */ .gpword .L0040FA00
/* 0145BC 100025BC F04051E0 */ .gpword .L0040FA00
/* 0145C0 100025C0 F0405008 */ .gpword .L0040F828
/* 0145C4 100025C4 F04051E0 */ .gpword .L0040FA00
/* 0145C8 100025C8 F04051E0 */ .gpword .L0040FA00
/* 0145CC 100025CC F04051E0 */ .gpword .L0040FA00
/* 0145D0 100025D0 F0405010 */ .gpword .L0040F830
/* 0145D4 100025D4 F04051E0 */ .gpword .L0040FA00
/* 0145D8 100025D8 F0405018 */ .gpword .L0040F838
/* 0145DC 100025DC F04051E0 */ .gpword .L0040FA00
/* 0145E0 100025E0 F0405020 */ .gpword .L0040F840
/* 0145E4 100025E4 F04051E0 */ .gpword .L0040FA00
/* 0145E8 100025E8 F0405128 */ .gpword .L0040F948

glabel jtbl_100025EC
/* 0145EC 100025EC F0405094 */ .gpword .L0040F8B4
/* 0145F0 100025F0 F0405094 */ .gpword .L0040F8B4
/* 0145F4 100025F4 F0405094 */ .gpword .L0040F8B4
/* 0145F8 100025F8 F0405094 */ .gpword .L0040F8B4
/* 0145FC 100025FC F0405094 */ .gpword .L0040F8B4
/* 014600 10002600 F0405094 */ .gpword .L0040F8B4
/* 014604 10002604 F0405094 */ .gpword .L0040F8B4
/* 014608 10002608 F0405094 */ .gpword .L0040F8B4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel parse_escape # 78
# _gp_disp: 0xFBFB0CC
.set noreorder; .cpload $t9; # .set reorder
/* 00F760 0040F760 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* 00F764 0040F764 AFBF001C */  sw          $ra, 0x1C($sp)
/* 00F768 0040F768 AFBC0018 */  sw          $gp, 0x18($sp)
/* 00F76C 0040F76C 8C820000 */  lw          $v0, 0x0($a0)
/* 00F770 0040F770 00803025 */  move        $a2, $a0
/* 00F774 0040F774 90430000 */  lbu         $v1, 0x0($v0)
/* 00F778 0040F778 244E0001 */  addiu       $t6, $v0, 0x1
/* 00F77C 0040F77C 2861000B */  slti        $at, $v1, 0xB
/* 00F780 0040F780 1420001B */  bnez        $at, .L0040F7F0
/* 00F784 0040F784 AC8E0000 */   sw         $t6, 0x0($a0)
/* 00F788 0040F788 28610038 */  slti        $at, $v1, 0x38
/* 00F78C 0040F78C 1420000D */  bnez        $at, .L0040F7C4
/* 00F790 0040F790 2478FFD0 */   addiu      $t8, $v1, -0x30
/* 00F794 0040F794 246FFFA2 */  addiu       $t7, $v1, -0x5E
/* 00F798 0040F798 2DE1001B */  sltiu       $at, $t7, 0x1B
/* 00F79C 0040F79C 10200099 */  beqz        $at, .L0040FA04
/* 00F7A0 0040F7A0 00601025 */   move       $v0, $v1
/* 00F7A4 0040F7A4 8F81804C */  lw          $at, %got(jtbl_10002580)($gp)
/* 00F7A8 0040F7A8 000F7880 */  sll         $t7, $t7, 2
/* 00F7AC 0040F7AC 002F0821 */  addu        $at, $at, $t7
/* 00F7B0 0040F7B0 8C2F2580 */  lw          $t7, %lo(jtbl_10002580)($at)
/* 00F7B4 0040F7B4 00000000 */  nop
/* 00F7B8 0040F7B8 01FC7821 */  addu        $t7, $t7, $gp
/* 00F7BC 0040F7BC 01E00008 */  jr          $t7
/* 00F7C0 0040F7C0 00000000 */   nop
.L0040F7C4:
/* 00F7C4 0040F7C4 2F010008 */  sltiu       $at, $t8, 0x8
/* 00F7C8 0040F7C8 1020008E */  beqz        $at, .L0040FA04
/* 00F7CC 0040F7CC 00601025 */   move       $v0, $v1
/* 00F7D0 0040F7D0 8F81804C */  lw          $at, %got(jtbl_100025EC)($gp)
/* 00F7D4 0040F7D4 0018C080 */  sll         $t8, $t8, 2
/* 00F7D8 0040F7D8 00380821 */  addu        $at, $at, $t8
/* 00F7DC 0040F7DC 8C3825EC */  lw          $t8, %lo(jtbl_100025EC)($at)
/* 00F7E0 0040F7E0 00000000 */  nop
/* 00F7E4 0040F7E4 031CC021 */  addu        $t8, $t8, $gp
/* 00F7E8 0040F7E8 03000008 */  jr          $t8
/* 00F7EC 0040F7EC 00000000 */   nop
.L0040F7F0:
/* 00F7F0 0040F7F0 10600017 */  beqz        $v1, .L0040F850
/* 00F7F4 0040F7F4 2401000A */   addiu      $at, $zero, 0xA
/* 00F7F8 0040F7F8 10610013 */  beq         $v1, $at, .L0040F848
/* 00F7FC 0040F7FC 00000000 */   nop
/* 00F800 0040F800 10000080 */  b           .L0040FA04
/* 00F804 0040F804 00601025 */   move       $v0, $v1
.L0040F808:
/* 00F808 0040F808 1000007E */  b           .L0040FA04
/* 00F80C 0040F80C 24020007 */   addiu      $v0, $zero, 0x7
.L0040F810:
/* 00F810 0040F810 1000007C */  b           .L0040FA04
/* 00F814 0040F814 24020008 */   addiu      $v0, $zero, 0x8
.L0040F818:
/* 00F818 0040F818 1000007A */  b           .L0040FA04
/* 00F81C 0040F81C 2402001B */   addiu      $v0, $zero, 0x1B
.L0040F820:
/* 00F820 0040F820 10000078 */  b           .L0040FA04
/* 00F824 0040F824 2402000C */   addiu      $v0, $zero, 0xC
.L0040F828:
/* 00F828 0040F828 10000076 */  b           .L0040FA04
/* 00F82C 0040F82C 2402000A */   addiu      $v0, $zero, 0xA
.L0040F830:
/* 00F830 0040F830 10000074 */  b           .L0040FA04
/* 00F834 0040F834 2402000D */   addiu      $v0, $zero, 0xD
.L0040F838:
/* 00F838 0040F838 10000072 */  b           .L0040FA04
/* 00F83C 0040F83C 24020009 */   addiu      $v0, $zero, 0x9
.L0040F840:
/* 00F840 0040F840 10000070 */  b           .L0040FA04
/* 00F844 0040F844 2402000B */   addiu      $v0, $zero, 0xB
.L0040F848:
/* 00F848 0040F848 1000006E */  b           .L0040FA04
/* 00F84C 0040F84C 2402FFFE */   addiu      $v0, $zero, -0x2
.L0040F850:
/* 00F850 0040F850 8CD90000 */  lw          $t9, 0x0($a2)
/* 00F854 0040F854 00001025 */  move        $v0, $zero
/* 00F858 0040F858 2728FFFF */  addiu       $t0, $t9, -0x1
/* 00F85C 0040F85C 10000069 */  b           .L0040FA04
/* 00F860 0040F860 ACC80000 */   sw         $t0, 0x0($a2)
.L0040F864:
/* 00F864 0040F864 8CC20000 */  lw          $v0, 0x0($a2)
/* 00F868 0040F868 2401005C */  addiu       $at, $zero, 0x5C
/* 00F86C 0040F86C 90430000 */  lbu         $v1, 0x0($v0)
/* 00F870 0040F870 24490001 */  addiu       $t1, $v0, 0x1
/* 00F874 0040F874 14610007 */  bne         $v1, $at, .L0040F894
/* 00F878 0040F878 ACC90000 */   sw         $t1, 0x0($a2)
/* 00F87C 0040F87C 8F998264 */  lw          $t9, %call16(parse_escape)($gp)
/* 00F880 0040F880 00C02025 */  move        $a0, $a2
/* 00F884 0040F884 0320F809 */  jalr        $t9
/* 00F888 0040F888 00000000 */   nop
/* 00F88C 0040F88C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F890 0040F890 00401825 */  move        $v1, $v0
.L0040F894:
/* 00F894 0040F894 2401003F */  addiu       $at, $zero, 0x3F
/* 00F898 0040F898 14610003 */  bne         $v1, $at, .L0040F8A8
/* 00F89C 0040F89C 306A0080 */   andi       $t2, $v1, 0x80
/* 00F8A0 0040F8A0 10000058 */  b           .L0040FA04
/* 00F8A4 0040F8A4 2402007F */   addiu      $v0, $zero, 0x7F
.L0040F8A8:
/* 00F8A8 0040F8A8 306B001F */  andi        $t3, $v1, 0x1F
/* 00F8AC 0040F8AC 10000055 */  b           .L0040FA04
/* 00F8B0 0040F8B0 014B1025 */   or         $v0, $t2, $t3
.L0040F8B4:
/* 00F8B4 0040F8B4 2465FFD0 */  addiu       $a1, $v1, -0x30
/* 00F8B8 0040F8B8 24040001 */  addiu       $a0, $zero, 0x1
/* 00F8BC 0040F8BC 24070003 */  addiu       $a3, $zero, 0x3
.L0040F8C0:
/* 00F8C0 0040F8C0 8CC20000 */  lw          $v0, 0x0($a2)
/* 00F8C4 0040F8C4 000568C0 */  sll         $t5, $a1, 3
/* 00F8C8 0040F8C8 90430000 */  lbu         $v1, 0x0($v0)
/* 00F8CC 0040F8CC 244C0001 */  addiu       $t4, $v0, 0x1
/* 00F8D0 0040F8D0 28610030 */  slti        $at, $v1, 0x30
/* 00F8D4 0040F8D4 14200007 */  bnez        $at, .L0040F8F4
/* 00F8D8 0040F8D8 ACCC0000 */   sw         $t4, 0x0($a2)
/* 00F8DC 0040F8DC 28610038 */  slti        $at, $v1, 0x38
/* 00F8E0 0040F8E0 10200004 */  beqz        $at, .L0040F8F4
/* 00F8E4 0040F8E4 24840001 */   addiu      $a0, $a0, 0x1
/* 00F8E8 0040F8E8 01A32821 */  addu        $a1, $t5, $v1
/* 00F8EC 0040F8EC 10000006 */  b           .L0040F908
/* 00F8F0 0040F8F0 24A5FFD0 */   addiu      $a1, $a1, -0x30
.L0040F8F4:
/* 00F8F4 0040F8F4 8CCE0000 */  lw          $t6, 0x0($a2)
/* 00F8F8 0040F8F8 00000000 */  nop
/* 00F8FC 0040F8FC 25CFFFFF */  addiu       $t7, $t6, -0x1
/* 00F900 0040F900 10000003 */  b           .L0040F910
/* 00F904 0040F904 ACCF0000 */   sw         $t7, 0x0($a2)
.L0040F908:
/* 00F908 0040F908 1487FFED */  bne         $a0, $a3, .L0040F8C0
/* 00F90C 0040F90C 00000000 */   nop
.L0040F910:
/* 00F910 0040F910 0005C202 */  srl         $t8, $a1, 8
/* 00F914 0040F914 1300000A */  beqz        $t8, .L0040F940
/* 00F918 0040F918 00000000 */   nop
/* 00F91C 0040F91C 30B900FF */  andi        $t9, $a1, 0xFF
/* 00F920 0040F920 AFB90028 */  sw          $t9, 0x28($sp)
/* 00F924 0040F924 8F9981EC */  lw          $t9, %call16(warning)($gp)
/* 00F928 0040F928 8F84804C */  lw          $a0, %got(STR_10002300)($gp)
/* 00F92C 0040F92C 0320F809 */  jalr        $t9
/* 00F930 0040F930 24842300 */   addiu      $a0, $a0, %lo(STR_10002300)
/* 00F934 0040F934 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F938 0040F938 8FA50028 */  lw          $a1, 0x28($sp)
/* 00F93C 0040F93C 00000000 */  nop
.L0040F940:
/* 00F940 0040F940 10000030 */  b           .L0040FA04
/* 00F944 0040F944 00A01025 */   move       $v0, $a1
.L0040F948:
/* 00F948 0040F948 00002825 */  move        $a1, $zero
.L0040F94C:
/* 00F94C 0040F94C 8CC20000 */  lw          $v0, 0x0($a2)
/* 00F950 0040F950 00055900 */  sll         $t3, $a1, 4
/* 00F954 0040F954 90430000 */  lbu         $v1, 0x0($v0)
/* 00F958 0040F958 24480001 */  addiu       $t0, $v0, 0x1
/* 00F95C 0040F95C 28610030 */  slti        $at, $v1, 0x30
/* 00F960 0040F960 14200007 */  bnez        $at, .L0040F980
/* 00F964 0040F964 ACC80000 */   sw         $t0, 0x0($a2)
/* 00F968 0040F968 2861003A */  slti        $at, $v1, 0x3A
/* 00F96C 0040F96C 10200004 */  beqz        $at, .L0040F980
/* 00F970 0040F970 00054900 */   sll        $t1, $a1, 4
/* 00F974 0040F974 01232821 */  addu        $a1, $t1, $v1
/* 00F978 0040F978 1000FFF4 */  b           .L0040F94C
/* 00F97C 0040F97C 24A5FFD0 */   addiu      $a1, $a1, -0x30
.L0040F980:
/* 00F980 0040F980 28610061 */  slti        $at, $v1, 0x61
/* 00F984 0040F984 14200006 */  bnez        $at, .L0040F9A0
/* 00F988 0040F988 28610067 */   slti       $at, $v1, 0x67
/* 00F98C 0040F98C 10200004 */  beqz        $at, .L0040F9A0
/* 00F990 0040F990 00055100 */   sll        $t2, $a1, 4
/* 00F994 0040F994 01432821 */  addu        $a1, $t2, $v1
/* 00F998 0040F998 1000FFEC */  b           .L0040F94C
/* 00F99C 0040F99C 24A5FFA9 */   addiu      $a1, $a1, -0x57
.L0040F9A0:
/* 00F9A0 0040F9A0 28610041 */  slti        $at, $v1, 0x41
/* 00F9A4 0040F9A4 14200006 */  bnez        $at, .L0040F9C0
/* 00F9A8 0040F9A8 28610047 */   slti       $at, $v1, 0x47
/* 00F9AC 0040F9AC 10200004 */  beqz        $at, .L0040F9C0
/* 00F9B0 0040F9B0 00000000 */   nop
/* 00F9B4 0040F9B4 01632821 */  addu        $a1, $t3, $v1
/* 00F9B8 0040F9B8 1000FFE4 */  b           .L0040F94C
/* 00F9BC 0040F9BC 24A5FFC9 */   addiu      $a1, $a1, -0x37
.L0040F9C0:
/* 00F9C0 0040F9C0 8CCC0000 */  lw          $t4, 0x0($a2)
/* 00F9C4 0040F9C4 00057202 */  srl         $t6, $a1, 8
/* 00F9C8 0040F9C8 258DFFFF */  addiu       $t5, $t4, -0x1
/* 00F9CC 0040F9CC 11C0000A */  beqz        $t6, .L0040F9F8
/* 00F9D0 0040F9D0 ACCD0000 */   sw         $t5, 0x0($a2)
/* 00F9D4 0040F9D4 8F84804C */  lw          $a0, %got(STR_10002330)($gp)
/* 00F9D8 0040F9D8 8F9981EC */  lw          $t9, %call16(warning)($gp)
/* 00F9DC 0040F9DC 30AF00FF */  andi        $t7, $a1, 0xFF
/* 00F9E0 0040F9E0 AFAF0020 */  sw          $t7, 0x20($sp)
/* 00F9E4 0040F9E4 0320F809 */  jalr        $t9
/* 00F9E8 0040F9E8 24842330 */   addiu      $a0, $a0, %lo(STR_10002330)
/* 00F9EC 0040F9EC 8FBC0018 */  lw          $gp, 0x18($sp)
/* 00F9F0 0040F9F0 8FA50020 */  lw          $a1, 0x20($sp)
/* 00F9F4 0040F9F4 00000000 */  nop
.L0040F9F8:
/* 00F9F8 0040F9F8 10000002 */  b           .L0040FA04
/* 00F9FC 0040F9FC 00A01025 */   move       $v0, $a1
.L0040FA00:
/* 00FA00 0040FA00 00601025 */  move        $v0, $v1
.L0040FA04:
/* 00FA04 0040FA04 8FBF001C */  lw          $ra, 0x1C($sp)
/* 00FA08 0040FA08 27BD0030 */  addiu       $sp, $sp, 0x30
/* 00FA0C 0040FA0C 03E00008 */  jr          $ra
/* 00FA10 0040FA10 00000000 */   nop
