.section .rodata
glabel STR_100019B4
/* 0139B4 100019B4 */ .asciz "%s:%d: "
                      .balign 4

glabel STR_100019BC
/* 0139BC 100019BC */ .asciz "warning: "
                      .balign 4

glabel STR_100019C8
/* 0139C8 100019C8 */ .asciz "\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.9.1 */

glabel warning # 48
# _gp_disp: 0xFBFCE98
.set noreorder; .cpload $t9; # .set reorder
/* 00D994 0040D994 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 00D998 0040D998 8F83829C */  lw          $v1, %got(indepth)($gp)
/* 00D99C 0040D99C AFBF0024 */  sw          $ra, 0x24($sp)
/* 00D9A0 0040D9A0 8C630000 */  lw          $v1, 0x0($v1)
/* 00D9A4 0040D9A4 AFBC0020 */  sw          $gp, 0x20($sp)
/* 00D9A8 0040D9A8 AFA40028 */  sw          $a0, 0x28($sp)
/* 00D9AC 0040D9AC AFA5002C */  sw          $a1, 0x2C($sp)
/* 00D9B0 0040D9B0 AFA60030 */  sw          $a2, 0x30($sp)
/* 00D9B4 0040D9B4 AFA70034 */  sw          $a3, 0x34($sp)
/* 00D9B8 0040D9B8 04600010 */  bltz        $v1, .L0040D9FC
/* 00D9BC 0040D9BC 00004025 */   move       $t0, $zero
/* 00D9C0 0040D9C0 000370C0 */  sll         $t6, $v1, 3
/* 00D9C4 0040D9C4 01C37021 */  addu        $t6, $t6, $v1
/* 00D9C8 0040D9C8 8F838340 */  lw          $v1, %got(instack)($gp)
/* 00D9CC 0040D9CC 000E7080 */  sll         $t6, $t6, 2
/* 00D9D0 0040D9D0 01C31021 */  addu        $v0, $t6, $v1
.L0040D9D4:
/* 00D9D4 0040D9D4 8C580000 */  lw          $t8, 0x0($v0)
/* 00D9D8 0040D9D8 00000000 */  nop
/* 00D9DC 0040D9DC 13000003 */  beqz        $t8, .L0040D9EC
/* 00D9E0 0040D9E0 00000000 */   nop
/* 00D9E4 0040D9E4 10000005 */  b           .L0040D9FC
/* 00D9E8 0040D9E8 00404025 */   move       $t0, $v0
.L0040D9EC:
/* 00D9EC 0040D9EC 2442FFDC */  addiu       $v0, $v0, -0x24
/* 00D9F0 0040D9F0 0043082B */  sltu        $at, $v0, $v1
/* 00D9F4 0040D9F4 1020FFF7 */  beqz        $at, .L0040D9D4
/* 00D9F8 0040D9F8 00000000 */   nop
.L0040D9FC:
/* 00D9FC 0040D9FC 1100000B */  beqz        $t0, .L0040DA2C
/* 00DA00 0040DA00 00000000 */   nop
/* 00DA04 0040DA04 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00DA08 0040DA08 8F85804C */  lw          $a1, %got(STR_100019B4)($gp)
/* 00DA0C 0040DA0C 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00DA10 0040DA10 8D060000 */  lw          $a2, 0x0($t0)
/* 00DA14 0040DA14 8D070004 */  lw          $a3, 0x4($t0)
/* 00DA18 0040DA18 24840020 */  addiu       $a0, $a0, 0x20
/* 00DA1C 0040DA1C 0320F809 */  jalr        $t9
/* 00DA20 0040DA20 24A519B4 */   addiu      $a1, $a1, %lo(STR_100019B4)
/* 00DA24 0040DA24 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DA28 0040DA28 00000000 */  nop
.L0040DA2C:
/* 00DA2C 0040DA2C 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00DA30 0040DA30 8F85804C */  lw          $a1, %got(STR_100019BC)($gp)
/* 00DA34 0040DA34 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00DA38 0040DA38 24840020 */  addiu       $a0, $a0, 0x20
/* 00DA3C 0040DA3C 0320F809 */  jalr        $t9
/* 00DA40 0040DA40 24A519BC */   addiu      $a1, $a1, %lo(STR_100019BC)
/* 00DA44 0040DA44 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DA48 0040DA48 8FB90034 */  lw          $t9, 0x34($sp)
/* 00DA4C 0040DA4C 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00DA50 0040DA50 AFB90010 */  sw          $t9, 0x10($sp)
/* 00DA54 0040DA54 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00DA58 0040DA58 8FA50028 */  lw          $a1, 0x28($sp)
/* 00DA5C 0040DA5C 8FA6002C */  lw          $a2, 0x2C($sp)
/* 00DA60 0040DA60 8FA70030 */  lw          $a3, 0x30($sp)
/* 00DA64 0040DA64 0320F809 */  jalr        $t9
/* 00DA68 0040DA68 24840020 */   addiu      $a0, $a0, 0x20
/* 00DA6C 0040DA6C 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DA70 0040DA70 00000000 */  nop
/* 00DA74 0040DA74 8F848074 */  lw          $a0, %got(__iob)($gp)
/* 00DA78 0040DA78 8F85804C */  lw          $a1, %got(STR_100019C8)($gp)
/* 00DA7C 0040DA7C 8F9980B4 */  lw          $t9, %call16(fprintf)($gp)
/* 00DA80 0040DA80 24840020 */  addiu       $a0, $a0, 0x20
/* 00DA84 0040DA84 0320F809 */  jalr        $t9
/* 00DA88 0040DA88 24A519C8 */   addiu      $a1, $a1, %lo(STR_100019C8)
/* 00DA8C 0040DA8C 8FBF0024 */  lw          $ra, 0x24($sp)
/* 00DA90 0040DA90 8FBC0020 */  lw          $gp, 0x20($sp)
/* 00DA94 0040DA94 27BD0028 */  addiu       $sp, $sp, 0x28
/* 00DA98 0040DA98 03E00008 */  jr          $ra
/* 00DA9C 0040DA9C 00001025 */   move       $v0, $zero
